Use EventArgs for KeyBindingContainer
ppy/osu-framework pull request #2601
Opened 2019-06-30 15:54 UTC by Aergwyn

solves https://github.com/ppy/osu-framework/issues/1697

I hope this is what was envisioned.

---
Changes the usage of `IKeyBindingHandler<T>` to pass "EventArgs" that allow adding more information such as e. g. `Repeat` in case of `OnPressed(KeyBindingPressEvent<T> e)`

```csharp
public bool OnPressed(Taction) { }
public bool OnReleased(Taction) { }
```
to
```csharp
public bool OnPressed(KeyBindingPressEvent<T> e) { }
public bool OnReleased(KeyBindingReleaseEvent<T> e) { }
```

2019-07-04 05:14 UTC, peppy submitted a review, later dismissed

2019-07-11 13:24 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        public void TriggerPressed(T pressed) => PropagatePressed(KeyBindingInputQueue, GetContainingInputManager()?.CurrentState ?? new InputState(), pressed);
I'm not a fan of this `GetContainingInputManager()` call. Is there a reason the inputstate from handleNewPressed/handleNewReleased can't be used?

2019-07-11 13:40 UTC, Aergwyn commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        public void TriggerPressed(T pressed) => PropagatePressed(KeyBindingInputQueue, GetContainingInputManager()?.CurrentState ?? new InputState(), pressed);
As far as I could understand what these are for it's for convenience for testing or automatic actions (replays in osu!) and nothing passes an `InputState` to them. For most of the uses I wouldn't know where to get an `InputState` either.

2019-07-11 13:43 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        public void TriggerPressed(T pressed) => PropagatePressed(KeyBindingInputQueue, GetContainingInputManager()?.CurrentState ?? new InputState(), pressed);
Ah I see 👍

2019-07-11 13:50 UTC, smoogipoo commented
Have you tested that this works with mouse position? Seems like target needs to be set on the event but it doesn't seem to be through the OnPressed/OnReleased actions.

2019-07-11 13:51 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                KeyBindingInputQueue.OfType<IKeyBindingHandler<T>>().ForEach(d => d.OnReleased(new KeyBindingReleaseEvent<T>(state, action)));
May be worth caching the event as you're doing for the press one, same for the other usage below.

2019-07-11 14:02 UTC, Aergwyn commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                KeyBindingInputQueue.OfType<IKeyBindingHandler<T>>().ForEach(d => d.OnReleased(new KeyBindingReleaseEvent<T>(state, action)));
As in going from that to
```csharp
foreach (var action in pressedActions)
{
    var releasedAction = new KeyBindingReleaseEvent<T>(state, action);
    KeyBindingInputQueue.OfType<IKeyBindingHandler<T>>().ForEach(d => d.OnReleased(releasedAction));
}
```
?

2019-07-11 14:08 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                KeyBindingInputQueue.OfType<IKeyBindingHandler<T>>().ForEach(d => d.OnReleased(new KeyBindingReleaseEvent<T>(state, action)));
Yeah

2021-07-23 16:39 UTC, smoogipoo commented
I feel like we should probably start looking to make this happen at some point soon... It's probably gonna be a breaking change but it's gotta be done sometime, and earlier is best.

2021-07-24 02:33 UTC, frenzibyte commented
I've bumped this all the way to latest master, resolved [remaining conversation](https://github.com/ppy/osu-framework/pull/2601#discussion_r302553962), and added xmldoc to the events for consistency with the rest of the classes.

I've also added `UIEvent` support for `IScrollBindingHandler<T>` while at it, saves another potential breaking change going forward.

2021-07-24 02:36 UTC, peppy commented
At very least this needs an update to the `KeyBindingGrid` test scene showing that repeat events are working. Properly automated test on a separate scene would also work fine. I had to add logging and check to actually know if the repeat flow was hooked up.

2021-07-24 03:28 UTC, frenzibyte commented
I've added test coverage as requested, found `TestSceneKeyBindingContainer` which seems mostly perfect for the job, so I added the test cases there.

2021-07-25 10:55 UTC, bdach reviewed
Looks mostly okay, some side notes.

2021-07-25 10:55 UTC, bdach commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        protected virtual Drawable PropagatePressed(IEnumerable<Drawable> drawables, InputState state, T pressed, float scrollAmount = 0, bool isPrecise = false, bool repeat = false)
This isn't all great, what with the optional parameter list having both scroll and key repeat info. Maybe something for later, I dunno.

2021-07-25 10:55 UTC, bdach commented on osu.Framework/Input/Events/KeyBindingPressEvent.cs
> +        public KeyBindingPressEvent(InputState state, T action, bool repeat)
`repeat` does not default to `false` contrary to `KeyDownEvent`. Maybe worth unifying?

(Same thing with `isPrecise` on scroll.)

2021-07-25 11:00 UTC, frenzibyte commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        protected virtual Drawable PropagatePressed(IEnumerable<Drawable> drawables, InputState state, T pressed, float scrollAmount = 0, bool isPrecise = false, bool repeat = false)
Yeah well, the fact that there is already `scrollAmount` and `isPrecise` on a "propagate pressed" method sounds not great already, and I didn't bother to touch it in this PR thinking it's suited for a follow-up or otherwise.

2021-07-26 06:29 UTC, peppy commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +        protected virtual Drawable PropagatePressed(IEnumerable<Drawable> drawables, InputState state, T pressed, float scrollAmount = 0, bool isPrecise = false, bool repeat = false)
Based on the other parameters already being there, I think this is fine for an initial implementation.

2021-07-26 06:31 UTC, peppy commented on osu.Framework/Input/Events/KeyBindingPressEvent.cs
> +        public readonly bool Repeat;
Probably should add xmldoc here just to be in line with all the other documented events.

2021-07-26 06:33 UTC, frenzibyte commented on osu.Framework/Input/Events/KeyBindingPressEvent.cs
> +        public readonly bool Repeat;
```suggestion
        /// <summary>
        /// Whether this is a repeated event resulted from a held keyboard key.
        /// </summary>
        public readonly bool Repeat;
```
Does this read fine?

2021-07-26 06:51 UTC, peppy commented on osu.Framework/Input/Events/KeyBindingPressEvent.cs
> +        public readonly bool Repeat;
Seems fine.

2021-07-26 07:49 UTC, smoogipoo requested changes
The rest looks fine

2021-07-26 07:49 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                    throw new ArgumentOutOfRangeException(nameof(e));
```suggestion
                    throw new ArgumentException("Invalid event type.", nameof(e));
```

2021-07-26 07:49 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            e.Target = (Drawable)drawable;
Not sure how I feel about this bypassing `Drawable.TriggerEvent()`, but I don't have a simple solution for the time being. Reflection can obviously be used but I'd want to benchmark that.

2021-07-26 07:50 UTC, frenzibyte commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            e.Target = (Drawable)drawable;
And have the key binding handling code in `Drawable.TriggerEvent()` instead?

2021-07-26 07:51 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            e.Target = (Drawable)drawable;
That's the idea, yes. Don't attempt this without making a benchmark first, if you're going to use reflection.

2021-07-26 07:57 UTC, frenzibyte commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            e.Target = (Drawable)drawable;
Ah right it's a generic event, I wasn't sure why you were stating to use reflection. I'll give it a benchmark and see how things go.

2021-07-26 08:13 UTC, smoogipoo commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            e.Target = (Drawable)drawable;
I think it's fine to leave it as it is for the time being. You're going to encounter problems such as the default invocation of `Handle()` which all other input methods do and all that...

2021-07-31 15:44 UTC, bdach approved these changes

2021-08-02 04:47 UTC, peppy commented
@smoogipoo shall we get this in the next framework bump?

2021-08-02 04:48 UTC, peppy submitted a review, later dismissed

2021-08-10 05:27 UTC, peppy approved these changes

2021-09-16 08:29 UTC, smoogipoo approved these changes

2021-09-16 08:39 UTC, merged