Add interface for leased bindables
ppy/osu-framework pull request #3353
Opened 2020-03-11 03:01 UTC by iiSaLMaN

Allows for spotting leased bindable instances without needing to know its value type. (e.g. `bindable is ILeasedBindable`)

Also intentionally didn't add a generic version of the interface because it's pretty much unnecessary and `LeasedBindable<T>` can take its place.

2020-03-11 07:00 UTC, peppy submitted a review, later dismissed

2021-01-02 21:27 UTC, bdach requested changes

2021-01-02 21:27 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +        private ILeasedBindable<T> leasedBindable;
not sure there is much point to this change given it's a private reference... maybe would make more sense if this was `protected internal`, but as-is, it's pretty useless. would revert for now.

in fact this probably *should* be protected, because if you want to add leasing to `BindableNumber`, then this will be essentially a dead unused field just taking up stack space in that class, and you'll have another one duplicating this one in `BindableNumber` itself. that's in scope of the dependent PR, though.

2021-01-02 21:27 UTC, bdach commented on osu.Framework/Bindables/ILeasedBindable.cs
> +    /// An interface that represents a read-only leased bindable.
would probably drop the "read-only" qualifier from this xmldoc. if you want a read-only bindable, you might as well scope up to `IBindable`. the leased part (and, being able to return, as a consequence) is the important part.

2021-01-02 21:36 UTC, frenzibyte commented on osu.Framework/Bindables/Bindable.cs
> +        private ILeasedBindable<T> leasedBindable;
I've done support for `BindableNumber` this way:
https://github.com/ppy/osu-framework/blob/cb98257fdf4dd2c1b8027166e702daea86d841ef/osu.Framework/Bindables/Bindable.cs#L435-L445
https://github.com/ppy/osu-framework/blob/cb98257fdf4dd2c1b8027166e702daea86d841ef/osu.Framework/Bindables/BindableNumber.cs#L444

So this is required as-is (`LeasedBindableNumber<T>` doesn't inherit `LeasedBindable<T>`), unless you want me to move it to the dependent PR, can do.

2021-01-02 21:38 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +        private ILeasedBindable<T> leasedBindable;
as I said above, this change does not make much sense or stand on its own in this PR, so I'd move it back where it does make sense.

2021-01-02 21:39 UTC, frenzibyte commented on osu.Framework/Bindables/Bindable.cs
> +        private ILeasedBindable<T> leasedBindable;
Ah, that's what you meant, alright.

2021-01-04 20:44 UTC, bdach approved these changes
looks inoffensive enough to me

2021-01-05 07:27 UTC, peppy commented on osu.Framework.Tests/Bindables/BindableLeasingTest.cs
> +            Assert.Throws<InvalidOperationException>(() => original.EndLease(new Bindable<int>().BeginLease(true)));
what's the reasoning behind this change?

2021-01-05 07:29 UTC, frenzibyte commented on osu.Framework.Tests/Bindables/BindableLeasingTest.cs
> +            Assert.Throws<InvalidOperationException>(() => original.EndLease(new Bindable<int>().BeginLease(true)));
EndLease now only accepts `ILeasedBindable<T>` as an argument, so had to make another leased instance for this.

2021-01-05 07:31 UTC, peppy approved these changes

2021-01-05 07:31 UTC, peppy commented on osu.Framework.Tests/Bindables/BindableLeasingTest.cs
> +            Assert.Throws<InvalidOperationException>(() => original.EndLease(new Bindable<int>().BeginLease(true)));
Completely missed that. Seems fine.

2021-01-05 07:48 UTC, merged