Fix setting GridContainer content by index
ppy/osu-framework pull request #3692
Opened 2020-07-06 13:44 UTC by UselessToucan

resolves #3657 

The problem is that an array does not notify about changing its elements.
This PR adds a `GridContainerContent` class which wraps a jagged array and provides notifications for its elements changes.

2020-07-06 13:48 UTC, smoogipoo commented
Awesome, but this is a pretty large breaking change. Is it possible to have an implicit operator conversion from `Drawable[][]` to `GridContainerContent`?

2020-07-06 13:53 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +        public ArrayWrapper<ArrayWrapper<Drawable>> _ { get; }
This is not a convention we have used anywhere else, please don't use `_` as a non-discard variable name.

2020-07-06 19:23 UTC, UselessToucan commented
> Is it possible to have an implicit operator conversion from `Drawable[][]` to `GridContainerContent`?

AFAIK it is not possible to convert an array to a custom object.  However, I can write an extension method in order to make code a little cleaner.

> Vice-versa would also be good to have (`GridContainerContent` -> `Drawable[][]`, even if it requires allocs).

We can expose the original array via method or property. See https://github.com/UselessToucan/osu-framework/commit/f5b3f9205a8beaa847e392563fc4342703eb2e3d.

2020-07-06 19:31 UTC, bdach commented
> AFAIK it is not possible to convert an array to a custom object. However, I can write an extension method in order to make code a little cleaner.

I think the suggestion was to add operators like

```csharp
public static implicit operator Drawable[][](GridContainerContent content);
public static implicit operator GridContainerContent(Drawable[][] drawables);
```

and it seems to at least not throw syntax errors and build? This way the changes to `Content` should no longer be breaking, or am I missing something?

2020-07-06 23:37 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent
This needs member ordering, I get lost reading this, move fields, properties and indexer above the ctor

2020-07-06 23:48 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +        public ArrayWrapper<ArrayWrapper<Drawable>> WrappedArray { get; }
Why is this `publicly` exposed, the whole array wrapper class should be `private`, only collection interfaces should be exposed to lead to the `ArrayWrapper`'s indexer.

2020-07-06 23:50 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +                    ArrayElementChanged?.Invoke();
No equality check

2020-07-06 23:52 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent
Should probably inherit some collection interfaces for LINQ extensions

2020-07-06 23:53 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent
Useful internally, only.
```suggestion
    internal class GridContainerContent
```

2020-07-07 08:34 UTC, UselessToucan commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent
This means that `GridContainer.Content` have to be internal which is not possible since it is used in some game classes.
![image](https://user-images.githubusercontent.com/22450664/86749229-bfb7ed80-c045-11ea-8ec9-924403b1a733.png)

2020-07-07 08:35 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent
`public` class with a `private` or `internal` ctor works (i.e. always use the implicit operator).

2020-07-07 20:42 UTC, bdach commented
Unfortunately this is still a breaking change, albeit a slightly less breaking one - game-side there's [this usage](https://github.com/ppy/osu/blob/c21b1e358c55a03f74e7e02a74042ec7a25e2712/osu.Game.Rulesets.Osu/Statistics/AccuracyHeatmap.cs#L195) that needs adjusting for.

2020-07-07 21:16 UTC, UselessToucan commented on osu.Framework/Graphics/Containers/GridContainer.cs
> +            int requiredColumns = requiredRows == 0 ? 0 : Content?.Max(c => c?.WrappedArray.Length ?? 0) ?? 0;
Here is the `Count` method implementation:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Count.cs#L12

As you can see on the [line 29](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Count.cs#L29), it is using `ICollection.Count` property which [is implemented](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Array.CoreCLR.cs#L16) in arrays.

2020-07-07 21:18 UTC, bdach commented on osu.Framework/Graphics/Containers/GridContainer.cs
> +            int requiredColumns = requiredRows == 0 ? 0 : Content?.Max(c => c?.WrappedArray.Length ?? 0) ?? 0;
Yes, that's what I meant by proposing to *not* change this to `Count()`.

2020-07-08 01:07 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +        public class ArrayWrapper<T> : IEnumerable<T>
I'm also talking about this to not be exposed, implement `IReadOnlyList<T>` and map all properties directly to the `WrappedArray`, now you don't need to expose this *internal* class.

2020-07-08 01:14 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +    public class GridContainerContent : IEnumerable<GridContainerContent.ArrayWrapper<Drawable>>
This should also use `IReadOnlyList<T>` instead to get to a very similar implementation to the `Content`'s original type.

2020-07-08 01:23 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainer.cs
>                  if (content == value)
This is not correct now, one array can instantiate more than one `GridContainerContent`, use `IEquatable<T>` instead.

2020-07-09 02:02 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +        public class ArrayWrapper<T> : IEnumerable<T>
In response to the confusion reaction above (guess I suck at being concise), `ArrayWrapper` should not be exposed to `public` as it is very internal and should not be used anywhere outside the `GridContainerContent` class.

Note: my bad on picking `IReadOnlyList<T>`, misunderstood the interface, turns out it doesn't have a setter indexer, please replace that with `IList<T>` instead.

So, I'm suggesting to implement `IList<T>` such that the indexer implemented here can be called from the interface without exposing the whole class (picked `IList<T>` as there's no direct interface for arrays):
```csharp
public class GridContainerContent : IList< IList<Drawable>>
{
    private readonly ArrayWrapper<ArrayWrapper<string>> sourceWrapper;

    public IList<string> this[int index]
    {
        get => sourceWrapper[index];
        set => sourceWrapper[index] = new ArrayWrapper(list); // maybe change the wrapped list instead, saving immediate construction (e.g. sourceWrapper[index].ChangeWrappedArray(list))
    }

    private class ArrayWrapper<T> : IList<T>
    {
        public T this[int index]
        {
            get => wrappedList[index];
            set
            {
                  // check equality.

                  wrappedList[index] = value;
                  // Invoke event
             }
        }
    }
}

2020-07-12 11:07 UTC, bdach commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +            }
while I can understand mutating operations from `IList<T>` throwing exceptions for simplicity, however inelegant that might be, I don't understand why these non-mutating methods also throw while they could delegate to the inner array instead.

on another note, you could also probably implement all of these if you leveraged `BindableList`'s `CollectionChanged` events, although that would probably be fairly complex and possibly not worth the effort.

2020-09-01 09:12 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
>              }
I think it's fine. There's only one such usage in osu!, so I don't think it's a common thing.

2020-09-01 09:25 UTC, smoogipoo submitted a review, later dismissed
@peppy would like your quick check on this

2020-09-01 11:13 UTC, frenzibyte-alt requested changes
One thing that has been missed to push from my suggestion and must be fixed before merging, and a minor suggestion.

2020-09-01 11:13 UTC, frenzibyte-alt commented on osu.Framework/Graphics/Containers/GridContainerContent.cs
> +                    observableArray.ArrayElementChanged += OnArrayElementChanged;
this should not be here, but inside `ObservableArray` as I have shown in my suggestion commit:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/70440919/91841566-4579a300-ec5b-11ea-9bc0-3938398fe589.png">
[source](https://github.com/ppy/osu-framework/commit/472f144d2d01b65688bb6fbe7f94c3ce74f6dde9#diff-a777f284af1e2a423ca3ed3a4b4590e6R32-R38)

because on the case where you do `Content[i] = new[] { ... }`, the `ArrayElementChanged` event of the `ObservableArray` created implicitly from inside will not be propagated to the main one at here, thus elements of the created array will not be observable to `GridContainer`.

should probably add test case covering this scenario to ensure it doesn't regress next time.

(also that `INotifyElementChanged` interface is meant to be `private` and only used privately, not to clash out with the existing System.Collections.Specialized.INotifyCollectionChanged`)

2020-09-01 11:13 UTC, frenzibyte-alt commented on osu.Framework/Graphics/Containers/GridContainer.cs
> +                if (content?.Equals(value) ?? false)
nit: what if both values are null? probably minor and not affecting currently, but worth fixing rather than staying silent and potentially hitting a bug at some point, and that's why I added a `==` operator in my suggestion commit:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/70440919/91842259-68588700-ec5c-11ea-87ce-727f75d7a174.png">
[source](https://github.com/ppy/osu-framework/commit/472f144d2d01b65688bb6fbe7f94c3ce74f6dde9#diff-a777f284af1e2a423ca3ed3a4b4590e6R74-R87)

though probably worth coupling `Equals(ObservableArray<T>)` to `==`:
```csharp
public bool Equals(ObservableArray<T> other) => this == other;
```

2020-09-02 02:58 UTC, peppy submitted a review, later dismissed
i think this looks okay apart from the minor code quality issue pointed out. haven't tested thoroughly though.

2020-09-02 02:58 UTC, peppy commented on osu.Framework/Graphics/Containers/GridContainer.cs
> +                if (content?.Equals(value) ?? false)
```suggestion
                if (content?.Equals(value) == true)
```

reads better imho and is how we do this elsewhere.

2020-09-07 05:43 UTC, smoogipoo requested changes

2020-09-07 05:43 UTC, smoogipoo commented on osu.Framework/Lists/INotifyArrayChanged.cs
> +    internal interface INotifyArrayChanged
Please make this `public` and xmldoc it. You can move the xmldoc of `ArrayElementChanged` from `ObservableArray<T>`.

2020-09-07 08:37 UTC, smoogipoo approved these changes

2020-09-07 10:54 UTC, merged