Fix transforms for the nth time
ppy/osu-framework pull request #3842
Opened 2020-08-18 11:14 UTC by peppy

- Closes https://github.com/ppy/osu-framework/issues/3837.

Best understood by going through commits one by one and looking at test failures in `TestSceneTransformRewinding` in visual tests, but basically:

- We don't want to be applying transforms in the rewind code. This is iterating in the wrong direction through the transforms list and will not lead to correct application order between overlapping TargetMembers.
- With the removal of the application just mentioned, a regression shows up when adding a transform in the past which will immediately complete in the next frame – rewind logic will not be run to reset `AppliedToEnd` so the end value may not be updated correctly. This is resolved by marking as *not* `AppliedToEnd` in `AddTransform` when required.

2020-08-18 12:03 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +        /// <param name="targetMember">An optional target member. If null, the highest common last application is returned.</param>
```suggestion
        /// <param name="targetMember">An optional target member. If null, the lowest common last application is returned.</param>
```

2020-08-18 12:36 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                    // To avoid this, we ensure all transforms before the insertion point on next update.
accidentally a word, I think

```suggestion
                    // To avoid this, we ensure all transforms before the insertion point run on next update.
```

2020-08-18 12:39 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                else if (i > insertionIndex && t.TargetMember == transform.TargetMember)
While this seems correct something's off here. I checked out 6159b332 (so the commit before this change) and got no test fails across the framework test suite. Which one is supposed to fail?

2020-08-18 15:02 UTC, peppy commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                else if (i > insertionIndex && t.TargetMember == transform.TargetMember)
I believe `AddPastTransformFromFuture` should fail..

2020-08-18 15:04 UTC, peppy commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                else if (i > insertionIndex && t.TargetMember == transform.TargetMember)
The logic being "transforms in the past were removed because of this new transform being added. the transforms before the ones that were removed need to replay their final states so the new transform we added (also in the past but will be run to completion) gets the correct starting state".

How are you checking for test failure? nunit?

2020-08-18 15:27 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                else if (i > insertionIndex && t.TargetMember == transform.TargetMember)
Both nunit and test scene. I've tried multiple times to make it fail but it doesn't seem to...

2020-08-18 16:23 UTC, peppy commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                else if (i > insertionIndex && t.TargetMember == transform.TargetMember)
Reverted this commit for now.

2020-08-19 11:50 UTC, smoogipoo commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> -                                t.Apply(t.EndTime);
So this is removed because of "We don't want to be applying transforms in the rewind code", but what about the code in the `else` block just below? Is that fine? How is correct ordering enforced there?

2020-08-19 11:51 UTC, smoogipoo requested changes

2020-08-19 11:51 UTC, smoogipoo commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +        private readonly Dictionary<string, int> lastAppliedIndex = new Dictionary<string, int>();
This is unused, either remove this dictionary or the one below. Probably the one below since it's an `int?` where it doesn't seem necessary to be.

2020-08-19 12:00 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> -                                t.Apply(t.EndTime);
I think the difference is that in the case of transforms that are in progress while the rewind runs, there is no need to apply them as the forward pass will apply them (and in correct order, too). Transforms yet to play need to be eagerly rewound to their start time as they won't be processed below. Removing the application in the `else` branch fails a test (`TestMultipleTransformTargets`) that seeks to `double.MinValue`.

2020-08-19 12:04 UTC, peppy commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +        private readonly Dictionary<string, int> lastAppliedIndex = new Dictionary<string, int>();
good catch

2020-08-19 12:05 UTC, peppy commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> -                                t.Apply(t.EndTime);
For what it's worth, I haven't considered the else case. I'm looking to bring things back to a known state. There may still be remaining issues but those issues were present before any of these optimisations, and we can deal with them when they come up.

2020-08-19 12:11 UTC, smoogipoo approved these changes

2020-08-19 12:20 UTC, bdach approved these changes

2020-08-19 12:29 UTC, merged