Add origin detection and compensation for joystick axes
ppy/osu-framework pull request #3844
Opened 2020-08-19 19:19 UTC by Jeremiidesu

Fixes #3802, possibly (resolves) #2854 

The selected origin depends on the initial axis values, as explained on this diagram:
![image](https://user-images.githubusercontent.com/20820425/90677238-5985d380-e25d-11ea-8c39-1d359db82f14.png)

Deadzone detection is then adjusted accordingly be measured around the detected origin rather than around the `0` mark.

2020-08-19 22:32 UTC, frenzibyte requested changes
Not entirely sure about this, code suggestions aside. I think it's fine to have given that it'll fix the whole issue with axis triggers having different origins (@GSculerlor please check if this fixes your aforementioned Xbox 360 controller issue).

2020-08-19 22:32 UTC, frenzibyte commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
> +                            Logger.Log("No origin value was somehow determined", level: LogLevel.Important);
that's never the case?

2020-08-19 22:32 UTC, frenzibyte commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
>                      var deadzone = MathF.Max(device.DefaultDeadzones?[i] ?? 0, Precision.FLOAT_EPSILON);
Sounds like the axis value retrieval logic (from line 109 till 124) should be moved to its own private method `getAxisValue(JoystickDevice device, int axis)`.

2020-08-19 22:38 UTC, Jeremiidesu commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
> +                            Logger.Log("No origin value was somehow determined", level: LogLevel.Important);
Oh - my mistake, I intended to remove it before pushing but seems like I forgot. Thanks for pointing it out!

2020-08-19 22:40 UTC, Jeremiidesu commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
>                      var deadzone = MathF.Max(device.DefaultDeadzones?[i] ?? 0, Precision.FLOAT_EPSILON);
Not too sure if it's worth moving to a separate method given that it's the only place where that logic is used, and isn't too long either - as far as I can tell, the adjusted value is used everywhere else.

2020-08-19 22:45 UTC, frenzibyte commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
>                      var deadzone = MathF.Max(device.DefaultDeadzones?[i] ?? 0, Precision.FLOAT_EPSILON);
`getHatButtons()` already exists and is even shorter than this; when you read the whole logic as "save current values to state", which is what it is doing in general:
![image](https://user-images.githubusercontent.com/22781491/90697223-91554100-e286-11ea-94d2-eb278d246893.png) 

it would make more sense to put this in its own method instead.

2020-08-19 22:47 UTC, Jeremiidesu commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
>                      var deadzone = MathF.Max(device.DefaultDeadzones?[i] ?? 0, Precision.FLOAT_EPSILON);
Ah, fair. I'll do that then.

2020-09-05 16:12 UTC, peppy requested changes

2020-09-05 16:12 UTC, peppy commented on osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
> +                if (Precision.AlmostEquals(value, 0, deadzone))
this should be removed (see https://github.com/ppy/osu-framework/pull/3869)

2020-09-05 16:17 UTC, peppy commented
I really don't know if this is the correct direction. Sure it may work for gamepads, but it's not a universal solution and is adding more local assumptions.

If we are to do this, though, it 100% needs tests written since the math logic here is hard to parse, and is not enough to let me know the assumptions and expectations of this change. I'd hope unit tests (not visual tests) can cover each case, showing what the raw readouts should be giving for each of the three origin decisions.

Also, we should probably rename this from "raw" to "normalised" or "transposed" and also expose the raw values for consumers that don't want this post-processing.

2020-09-05 16:32 UTC, Jeremiidesu commented
Another idea I had would have been to implement per-controller-type joystick handler but there doesn't seem to be a way to accurately detect what controller has been connected across OSes.

Currently, the first 8 characters of the GUID are vendor and product code concatenated, so that should help, but as far as I can remember, at least for the Dualshock 4, that part of the GUID is different between Windows and Manjaro Linux, and I don't believe that a lot of specific handlers is something that would be accepted. 

That could separate some of the assumptions this PR makes as it is a valid concern (might close and start from scratch depending on where this ends up going).

2020-09-05 16:36 UTC, peppy commented
Honestly I would prefer to keep things simple where possible. If this change is going to cover the average cases in a way joysticks can be consumed in the way you/other framework consumers need I think it's fine.

But we do need test coverage.

2020-10-24 04:50 UTC, peppy commented
Replaced by #3844 for the time being. We can reconsider this if the need comes up in the future.

2020-10-24 04:50 UTC, closed without merging