Allow all types of steps to be considered setup steps
ppy/osu-framework pull request #3896
Opened 2020-09-24 06:37 UTC by peppy

Previously, the ability to mark steps as setup was tied to the `SetUpStepButton` class. This meant that `UntilStep`s were not considered setup steps even when contained within `[SetUpSteps]`, causing the visual test browser to not automatically run them.

Fixes the most annoying case on osu!-side with "exit all screens" would be run and not run any of the actual test code.

This also removes the public `AddSetupStep` method because we aren't using it (and I don't think anyone should be, anyway).

Tested to not regress any osu!-side tests.

2020-09-24 10:31 UTC, smoogipoo requested changes

2020-09-24 10:31 UTC, smoogipoo commented on osu.Framework/Testing/TestScene.cs
> -        public StepButton AddSetupStep(string description, Action action)
Maybe keep this an obsolete it? Seems like there's at least a few usages: https://github.com/search?l=C%23&q=AddSetupStep&type=Code

2020-09-24 11:20 UTC, peppy commented on osu.Framework/Testing/TestScene.cs
> -        public StepButton AddSetupStep(string description, Action action)
only one of those is valid. if you really insist i'll do it but just seems unnecessary

2020-09-25 03:04 UTC, peppy commented on osu.Framework/Testing/TestScene.cs
> -        public StepButton AddSetupStep(string description, Action action)
Added back

2020-09-25 04:25 UTC, smoogipoo approved these changes

2020-09-25 05:04 UTC, merged