SDL Joystick Handling
ppy/osu-framework pull request #3900
Opened 2020-09-27 07:34 UTC by swoolcock

Implements joystick handling with the SDL window backend.  Buttons and axes are mapped as close to osuTK as possible.

This PR is primarily for parity with osuTK.  In the future we will want to identify individual controllers, and potentially identify buttons based on logical meaning rather than button number (for example, show `Button1` as `X` if an Xbox controller is connected, or `Square` if a DualShock is connected).

Differences to osuTK:
* Triggers range from 0 to 1 rather than -1 to 1.  This is how SDL reports it, and I see the -1 to 1 range as a design flaw in osuTK.
* Unmapped button presses will be ignored.  This is to avoid problems with controllers that send multiple button events for a single press, or use buttons as flags.  For example, the Xbox Elite Series 2 sends two different button indices with each of the ABXY buttons, and it uses buttons 35 and 36 to indicate the current profile selection and whether the trigger locks are enabled.  The downside is that extra buttons (such as the Xbox Elite paddles or the DualShock touch pad) cannot be used.

2020-09-27 09:09 UTC, peppy requested changes

2020-09-27 09:09 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
according to the PR description, should this one 0..1?

2020-09-27 09:09 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                    axisDirectionButtons[instanceID] = new JoystickButton[(int)JoystickAxisSource.AxisCount];
i'm confused why there's three dictionaries here. if it's all related data, why not make a class for it?

2020-09-27 09:09 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var value = Math.Abs(clamped) < deadzone_threshold ? 0 : Math.Sign(clamped) * (Math.Abs(clamped) - deadzone_threshold) / (1f - deadzone_threshold);
is this doing a mapping to -1..1? i can't see where this would be happening, am i missing something?

2020-09-27 09:14 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
SDL reports an axis value between 0 and 32767 for triggers, so it doesn't matter.

2020-09-27 09:16 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                    axisDirectionButtons[instanceID] = new JoystickButton[(int)JoystickAxisSource.AxisCount];
I can do that.

2020-09-27 09:18 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var value = Math.Abs(clamped) < deadzone_threshold ? 0 : Math.Sign(clamped) * (Math.Abs(clamped) - deadzone_threshold) / (1f - deadzone_threshold);
This does similar to osuTK, where the `deadzone_threshold` is used as the new zero, rather than just dropping any values less than the threshold.

2020-09-27 09:38 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
i'm confused.  is there a reason to have it clamp between -1..1 if it never goes below 0?

2020-09-27 09:44 UTC, bdach commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
[From `SDL_GameControllerGetAxis`](https://wiki.libsdl.org/SDL_GameControllerGetAxis):

> The state is a value ranging from -32768 to 32767. Triggers, however, range from 0 to 32767 (they never return a negative value). 

So it sounds like actual positional axes still go -1..1, but "button-like" axes (triggers, etc.) go 0..1.

2020-09-27 09:52 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
If `axisValue` is -32768, `(float)axisValue / short.MaxValue` will be less than -1.

2020-09-27 12:02 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
Aha, that's what I was missing. I'm just trying to figure out how to see this 0..1 thing now.

2020-09-27 12:07 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
Tested with switch pro controller, xbox one and joystick with 64 buttons 3 hats 6 axes. all work as expected  👍 .

2020-09-27 12:12 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
Note that Xbox Elite Series 2 does not 100% work (on macOS, at least), as SDL does not have correct mappings for it.  This is fixed in a PR I made to the SDL_GameControllerDB project, so it's something we may want to look at later.

2020-09-27 12:14 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
As already discussed, we shouldn't need to provide support for proprietary stuff. As long as generic HID works there's no issue.

2020-09-27 12:16 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
The problem is that SDL *does* detect it as a "controller", but as an Elite Series 1.  The mapping is therefore incorrect.
I think we can safely assume it will be fixed as the SDL team adds more controller mappings.

2020-09-27 12:19 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var clamped = Math.Clamp((float)axisValue / short.MaxValue, -1f, 1f);
The point is we're trying to get SDL implemented. Not add support for one controller that likely only you care about.

2020-09-27 14:02 UTC, peppy requested changes

2020-09-27 14:02 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var directionButton = state.AxisDirectionButtons[(int)axisSource];
split `(int)axisSource` out into a local `int index`, it's used 5+ times

2020-09-27 14:02 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            if (value == 0 && directionButton != 0 || value < 0 && directionButton == positiveButton || value > 0 && directionButton == negativeButton)
this is basically impossible to read

2020-09-27 14:02 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            if (value < 0 && directionButton != negativeButton)
as above, can't really follow this logic

2020-09-29 18:43 UTC, bdach commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            public readonly int InstanceID;
This seems to be never read - was there intent behind it? Also not sure if this was intended to be public API, but maybe not too relevant for now.

2020-09-29 18:43 UTC, bdach commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            public SDL.SDL_GameControllerButton GetButtonForIndex(byte index)
also unused, unsure of purpose

2020-09-29 23:39 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var value = Math.Abs(clamped) < deadzone_threshold ? 0 : Math.Sign(clamped) * (Math.Abs(clamped) - deadzone_threshold) / (1f - deadzone_threshold);
I disagree with pulling a single line of code out into its own method when it’s used exactly once.  Maybe just a one line comment explaining what the code does?

2020-09-29 23:41 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var expectedButton = value < 0 ? negativeButton : value > 0 ? positiveButton : 0;
As above, I think this could just be clarified with a one line comment rather than making a short “only used once” helper method.

2020-09-29 23:47 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            public readonly int InstanceID;
This is SDL’s internal ID for joystick.  It’s what’s used as the key for the dictionary.  Technically this could be removed, but only because we (currently) already have the instance ID at the places we need to use it.

2020-09-29 23:50 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            public SDL.SDL_GameControllerButton GetButtonForIndex(byte index)
Originally used in the same fashion as `GetAxisForIndex`, currently unused due to the second note in the PR description regarding “flag” button presses being detected.  In retrospect, I’m thinking it may be better to detect those too (using this method) which will be equivalent to osuTK.

2020-09-30 01:35 UTC, peppy requested changes

2020-09-30 01:36 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var expectedButton = value < 0 ? negativeButton : value > 0 ? positiveButton : 0;
what's the reasoning against splitting out into a method? i agree it would make the code more legible.

2020-09-30 01:47 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var expectedButton = value < 0 ? negativeButton : value > 0 ? positiveButton : 0;
I can change it to a helper method then, no problem.

2020-09-30 02:41 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            public SDL.SDL_GameControllerButton GetButtonForIndex(byte index)
Changed to no longer drop unmapped buttons (as such, this method is now used).

2020-09-30 02:42 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +            var value = Math.Abs(clamped) < deadzone_threshold ? 0 : Math.Sign(clamped) * (Math.Abs(clamped) - deadzone_threshold) / (1f - deadzone_threshold);
Changed, as below.

2020-09-30 06:33 UTC, peppy requested changes

2020-09-30 06:33 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +        protected class ControllerState
should be in its own file

2020-09-30 06:33 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +        private const float deadzone_threshold = 0.075f;
I don't know where to start with reviewing this class.

All joystick / controller logic should be moved either into another class. If making a new class for this is too hard to manage, then make it a partial class `Sdl2WindowBackend_Joystick` or something.

2020-10-05 00:51 UTC, swoolcock commented
Note: Currently blocked by #3911 as it will make it easier to centralise the joystick logic.

2020-10-12 21:16 UTC, bdach commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                        break;
Out of curiosity, is there a reason why the joystick function calls have guards for double open/close but the controller ones don't? I can't see anything in the docs about that.

2020-10-12 21:16 UTC, bdach commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +        private JoystickButton joystickButtonFromGameController(SDL.SDL_GameControllerButton button)
Maybe move these mappings out to an extension method or something? Might keep the class a little leaner (already nearing on 1k lines as is).

2020-10-12 22:21 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                        break;
SDL will only fire controller events if the joystick is recognised as a mapped controller. It will fire joystick events in both cases, so we need to make sure it doesn’t handle the events twice.

2020-10-12 22:22 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +        private JoystickButton joystickButtonFromGameController(SDL.SDL_GameControllerButton button)
I had thought of moving this to `Sdl2Extensions`, actually. Will do so today.

2020-10-14 06:55 UTC, peppy commented
Code looks sane. Will do a final check with my army of controllers tonight and merge pending success.

2020-10-18 17:32 UTC, peppy commented
I've noticed a couple of issues which need further investigation before this is merged:

- Starting the game with a non-zeroed axis causes the deadzone to become insanely huge. This is an issue for controllers which don't reset to zero when not interacted with (ie. throttles)

![2020-10-19_02-29-32](https://user-images.githubusercontent.com/191335/96375286-08d61c80-11b3-11eb-8bd5-f437e55725db.gif)

- Positive axis maxes at 0.9999835 for me. Need to confirm whether this is an issue with this PR or the controller's output:

![2020-10-19_02-31-49](https://user-images.githubusercontent.com/191335/96375311-3fac3280-11b3-11eb-98a2-285ba8624ee1.gif)

Note how negative values always reach -1 as expected, but positive never do.

2020-10-18 17:44 UTC, bdach commented
For what it's worth I can hit +/-1 on axes (testing on ubuntu, with an xbox 360 gamepad). Can't seem to get any funny thing to happen with the deadzones, either, but that controller has no stationary axes - tried to emulate by holding down trigger during game open but it also looks correct as far as I can tell.

2020-10-19 00:26 UTC, swoolcock commented
@peppy which controller are you testing with?  I'm guessing it's one that doesn't show up in SDL's controller mappings, thus it will be handled solely by the joystick API.  It's likely that the deadzone/positive axis problems are sourced directly from SDL, so I might need to put some debug-mode logging for the raw values in the SDL_JoyAxisEvent.

2020-10-19 02:04 UTC, peppy commented
Okay never mind, I forgot the SDL switch. Now I'm getting hard crashes.

```csharp
Unhandled exception. System.NullReferenceException: Object reference not set to
an instance of an object.
   at osu.Framework.Platform.Sdl.Sdl2ControllerBindings.GetAxisForIndex(Byte ind
ex) in C:\Users\Dean\Projects\osu-framework\osu.Framework\Platform\Sdl\Sdl2Contr
ollerBindings.cs:line 64
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend.handleJoyAxisEvent(SDL_JoyAxi
sEvent evtJaxis) in C:\Users\Dean\Projects\osu-framework\osu.Framework\Platform\
Sdl\Sdl2WindowBackend.cs:line 723
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend.processEvents() in C:\Users\D
ean\Projects\osu-framework\osu.Framework\Platform\Sdl\Sdl2WindowBackend.cs:line
552
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend.Run() in C:\Users\Dean\Projec
ts\osu-framework\osu.Framework\Platform\Sdl\Sdl2WindowBackend.cs:line 447
   at osu.Framework.Platform.Window.Run() in C:\Users\Dean\Projects\osu-framewor
k\osu.Framework\Platform\Window.cs:line 321
```

2020-10-19 02:05 UTC, peppy commented
![image](https://user-images.githubusercontent.com/191335/96393721-ef58c300-11fa-11eb-8aea-e0c5f8e92d68.png)

2020-10-24 04:32 UTC, peppy approved these changes

2020-10-24 04:46 UTC, merged