Extract numeric type check to utils class from BindableNumber
ppy/osu-framework pull request #3901
Opened 2020-09-27 19:12 UTC by frenzibyte

Required in another PR involving arithmetic operation between generic types, therefore I need to use this method there to shorten stuff and not copy-paste.

2020-09-27 19:36 UTC, bdach requested changes

2020-09-27 19:36 UTC, bdach commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
why?

look at:

* the method name
* the method implementation

and rethink whether this xmldoc is necessary

2020-09-27 19:40 UTC, frenzibyte commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
the class is public for framework users, therefore xmldocs must be 100% filled I believe, and mostly for the part that there are types not in the check like `decimal` for example, better show it to the user by just hovering on the method instead of making them disassemble the framework package or otherwise.

2020-09-27 19:43 UTC, bdach commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
then maybe list the exception instead of literally *everything else*, making the xmldoc longer than the method implementation itself?

2020-09-27 19:44 UTC, frenzibyte commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
sure I guess

2020-09-27 19:50 UTC, bdach commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
also this should probably *not* be public, while we're at it

2020-09-27 19:51 UTC, frenzibyte commented on osu.Framework/Utils/Validation.cs
> +        /// </summary>
yeah got concerned right after I said it, alright will make it `internal`.

2020-09-28 03:41 UTC, frenzibyte commented
No longer needed.

2020-09-28 03:41 UTC, closed without merging