Fix offset-based position transform not respecting previous transforms
ppy/osu-framework pull request #3902
Opened 2020-09-27 19:12 UTC by frenzibyte

Closes #3821 

- [ ] Depends on #3901

Basically `MoveToOffset` previously calculates the end value based off the current `Position` value **when the transform is first added** (i.e. when `MoveToOffset(...)` call is first executed), which is quite incorrect for cases mentioned in the linked issue (which is added to the test).

Therefore I fixed it by introducing a `TransformOffset` class that calculates the end value by the start value **when the start time of the transform has reached**.

2020-09-27 19:21 UTC, frenzibyte commented
Looks like this will be a breaking change for whoever implements the `Transform` class, can't figure out any way to avoid it...

2020-09-28 03:01 UTC, smoogipoo commented
This is completely overengineered to the point where I don't know where to start. Why not make a custom transform for this single purpose? Derive `Transform` and set `Position = StartValue + offset` without all the other changes in this PR. Remove the whole `MakeOffsetTransform` thing. Remove the `sum()` thing.

2020-09-28 03:01 UTC, smoogipoo requested changes
As mentioned

2020-09-28 03:22 UTC, peppy commented
That is what I suggested in discord, for what it's worth..

2020-09-28 03:40 UTC, frenzibyte commented
The point of all these changes is about adding `MakeOffsetTransform`, as I thought it would be worth it to allow adding offset transforms to any property / field I want, but actually looking back now, not so sure that it would be a graspable change anymore with the `sum()` method hanging around like this...

Alright will supersede this PR with a local custom position offset transform.

2020-09-28 03:40 UTC, closed without merging

2020-09-28 03:44 UTC, smoogipoo commented
Offsetting is not a common thing in general. If it's needed somewhere it can be implemented locally, it's maybe 10 LOC.