Fix LoadComponentAsync enumerating input enumerable multiple times
ppy/osu-framework pull request #3929
Opened 2020-10-12 08:59 UTC by peppy

This is a huge oversight: calling `LoadComponentAsync` with a live `IEnumerable` will result in the provided drawable(s) being constructed multiple times. The final returned values are also not the loaded once, but fresh instances.

I've confirmed the test I added behaves per expectations on master / this branch, but I've somehow broken exceptions and reference retention with this change. PRing for feedback.

2020-10-12 10:59 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +                if (!loaded.Result.Any())
At least one of the issues is going to be caused by this - accessing `Result` will throw if the task has faulted.

This could be moved out to just after `components.ToArray()` above - I don't believe there was a reason for this being here other than to prevent multiple evaluation.

The other failures are DLUW - for some reason references aren't being lost there, but I'm not yet sure on the reason.

2020-10-12 16:29 UTC, peppy commented
Should be good to go now

2020-10-12 18:27 UTC, bdach approved these changes
As a change this seems correct from what I can tell. Shame about the few extra allocs but I think I prefer the usage safety. If it's deemed a problem then we can scope down the param type to an array if need be.

2020-10-12 21:21 UTC, peppy commented
Yeah, not sure performance/allocs is a huge deal for this flow as loading drawables should be a *relatively* rare operation. Can be fixed if/when it becomes an issue for a specific usage.

2020-10-13 03:00 UTC, smoogipoo requested changes
Rest seems fine

2020-10-13 03:00 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            // ReSharper disable once IteratorMethodResultIsIgnored (we don't care about the results here).
I don't get it, what iterator? Is this an out of date comment? I don't get a warning here.

2020-10-13 03:01 UTC, peppy commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            // ReSharper disable once IteratorMethodResultIsIgnored (we don't care about the results here).
out of date comment, yes.

2020-10-13 03:56 UTC, smoogipoo approved these changes

2020-10-13 03:56 UTC, merged