Improve robustness of DLW/DLUW logic
ppy/osu-framework pull request #3936
Opened 2020-10-14 21:16 UTC by bdach

This aims to let ppy/osu#10493 be merged. I am PRing this just to have this out/visible/editable by someone other than me, so that me looking at this is not a blocker.

There are three distinct issues this PR aims to fix. As they touch the same places I don't really want to split this into three PRs as it'd probably significantly harm readability.

# Possibility of multiple loads starting

As I outlined in the PR thread already, DLW has two flags that determine whether the content needs to be loaded: `DelayedLoadTriggered` and `DelayedLoadCompleted`. On current `master`, the first is a shorthand for `loadTask != null`, and the second is a shorthand for `InternalChildren.Count > 0`.

Because the addition of `Content` is scheduled in DLW, there is a one-frame window of opportunity in which `DelayedLoadTriggered` becomes `false` (as the load has concluded) while `DelayedLoadCompleted` does not yet become `true`.

See the following log excerpt for an example (this is taken from game-side `TestScenePlaySongSelect.TestExternalBeatmapChangeWhileFiltered`):

```
[frame 0]
Update()        | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: load started in Update at thread GameThread.Update (id 16, is pool thread = False). Time = 177366,6666666725
                | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: BeginDelayedLoad started at thread GameThread.Update (id 16, is pool thread = False). Time = 177366,6666666725

[frame 1]
game scheduler  | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: loadTask cleared via load end at thread GameThread.Update (id 16, is pool thread = False). Time = 177400,00000000585
                | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: loadTask cleared by task cancellation at thread GameThread.Update (id 16, is pool thread = False). Time = 177400,00000000585
Update()        | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: load started in Update at thread GameThread.Update (id 16, is pool thread = False). Time = 177400,00000000585
                | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: BeginDelayedLoad started at thread GameThread.Update (id 16, is pool thread = False). Time = 177400,00000000585

[frame 2]
game scheduler  | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: loadTask cleared via load end at thread GameThread.Update (id 16, is pool thread = False). Time = 177433,3333333392
                | [runtime] 2020-10-14 16:20:11 [verbose]: DLUW #20420726: adding scheduled unload check at thread GameThread.Update (id 16, is pool thread = False). Time = 177433,3333333392
local scheduler | [runtime] 2020-10-14 16:20:11 [verbose]: DLW #20420726: content added at thread GameThread.Update (id 16, is pool thread = False). Time = 177433,3333333392

[frame 3]
game scheduler  | [runtime] 2020-10-14 16:20:11 [verbose]: DLUW #20420726: adding scheduled unload check at thread GameThread.Update (id 16, is pool thread = False). Time = 177466,66666667254
                | [runtime] 2020-10-14 16:20:11 [error]: An unhandled error has occurred.
                | [runtime] 2020-10-14 16:20:11 [error]: NUnit.Framework.AssertionException: :
```

The failing assert is [this one](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs#L79). This PR includes a test that will trip this same assertion on `master`.

The resolution proposal for this is to track load trigger/completion state by setting the flags manually instead of delegating.

# Cancelling DLW/DLUW's load does not really cancel load

While DLW has a local reference to a `loadTask` which performs the drawable load, it doesn't actually cancel the task if need be. [There is no cancellation token passed in](https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs#L91) and [the task is just set to `null` if task cancellation is requested](https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs#L116).

Similarly, DLUW [schedules a schedule](https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs#L76-L88) (sic) that tracks whether the inner drawable needs to be unloaded. The outer schedule itself is not tracked, so if the loading is cancelled in the middle, `checkForUnload` will get scheduled on the game scheduler every frame anyway, potentially [tripping over other assertions](https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs#L113).

Both resolved by adding more cancellations.

# DLUW can attempt to clean up its already-disposed `Content`

`checkForUnload()` can fail on one of these operations:

https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs#L126-L129

as there is a possibility that `Content` has been disposed from under it. Resolve by adding another guard.

I don't know how this can happen yet. It's inconsistent and best visible game-side on `TestScenePlaySongSelect.     TestGroupedDifficultyIconSelecting`. My best explanation for this right now is *(handwaving about async disposal queue)*.

Perhaps the operation ordering is slightly wrong, too, as the children are disposed before the parent, and `UnbindAllBindables()` (which triggers `CancelTasks()` for DLW/DLUW) is called after drawable disposal, but I don't really get why that would be the issue given that `checkForUnload()` is scheduled onto the game scheduler and as such it shouldn't be possible for operation order to influence that.

---

DLW/DLUW logic overall is very difficult for me to navigate. I'm not sure if I'm just tired out of my mind these past few days but the amount of scheduling involved makes it very hard to track what goes where. That's why I'm very unconfident of these changes, but I'm less confident I have the time or the skills to try and rewrite.

I've tested this by stressing game-side `TestScenePlaySongSelect` for a bit (each test 50 times). Looks green, for whatever that's worth.

2020-10-15 10:05 UTC, smoogipoo requested changes
I'm generally pretty OK with the PR at a visual inspection. But the issue I pointed out puts a big questionmark over my head as to whether this is the correct path to go down fixing this issue.

Would this test have failed prior to https://github.com/ppy/osu-framework/pull/3926?

2020-10-15 10:14 UTC, smoogipoo commented
One of the things I was going to point out in the original PR though I'd convinced myself it was fine, was the assumption that UnbindAllBindables was always run synchronously. This isn't always the case, so I'm also concerned that the original memory leak wasn't really fixed either.

2020-10-15 10:17 UTC, peppy commented
Are you suggesting `UnbindAllBindables` can be run asynchronously in a non-finalizer context? How does that occur?

2020-10-15 10:21 UTC, smoogipoo commented
Finalizer is the case I was thinking about.

2020-10-15 10:28 UTC, smoogipoo commented
On second thought the finalizer case should be safe as long as there's one upwards reference, which is `Parent`.

2020-10-15 10:32 UTC, peppy commented
so...

```csharp

this.Add(drawable) // schedules to game

this.Remove(drawable) // doesn't dispose

// all references to drawable gone

// finalizer runs

game.Update() -> game.Scheduler.Update() -> runs checkForUnload
```

might be an issue still? i mean the chances are next to zero and there's a `Debug.Assert` to guard, but we may want to change the assertion to a `CancelTasks(); return;` ...

2020-10-15 10:34 UTC, peppy commented
No, that should still cancel fine...

2020-10-15 10:40 UTC, smoogipoo commented
I was thinking of the case:
```
- Composite
    - DLUW
        - Content

this.Remove(Composite)
```

Where DLUW is still referenced by the game and will receive scheduled callbacks, but Composite isn't so it's a candidate for finalization. That would've been fine but `Parent` is the saving grace and the reference graph becomes `Game -> DLUW -> Composite+Content`.

So I think I can convince myself it's safe again.

2020-10-15 12:01 UTC, peppy commented on osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
> +            if (!Content.IsDisposed)
For clarity, in this scenario, what is the "ClearInternal failure" you mention?

2020-10-15 12:07 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
> +            if (!Content.IsDisposed)
![image](https://user-images.githubusercontent.com/1329837/96121034-715e9880-0f2a-11eb-98d3-eea5c49afcec.png)

2020-10-15 13:38 UTC, peppy commented
I've gone through every scenario I can think of (including the one I was trying to explain above) and can't repro a failure logically or via test runs.

The changes in this PR are adding some extra protections and I think leave things in a better state than we have had until now (the load cancellation was actually something that came up as a TODO when working on song select improvements - could see this occurring).

Getting my approval. Not going to merge without @smoogipoo's double confirm though.

2020-10-15 13:39 UTC, peppy submitted a review, later dismissed

2020-10-15 13:50 UTC, smoogipoo commented
My concern still remains as to why that `Content.IsDisposed` check is required. I don't want to leave this in a half-not-known-why-working state, because I think we've already convinced ourselves it shouldn't be possible to reach that scenario. If it is possible, then relying on this variable that's set in an async context, from a sync context, without any locking between them, is guaranteed to cause issues.

2020-10-15 14:26 UTC, bdach commented
I will attempt to confirm and isolate the double-disposal on clear then. Fingers crossed I can figure out what's happening relatively quickly...

2020-10-15 14:35 UTC, peppy commented
My question is why does that logic need to do a ClearInternal?
why not

```csharp
if (Content.Parent == null)
    Content.Dispose()
```

2020-10-15 22:02 UTC, bdach commented
After an inordinately long dig I think I know what the failure case is. Long and short of it is:

1. Game-side song select [removes some off-screen items](https://github.com/ppy/osu/blob/583fdc3a95cad81db3819c797c3f1cbf8ae554ff/osu.Game/Screens/Select/BeatmapCarousel.cs#L564-L565).
2. Normally removing prevents the component from doing anything, but recall that DLUW registers `checkForUnload()` onto the *game scheduler*, and it executes *every frame*, therefore being a glorified hidden `Update()` that runs before all of the scene graph. Due to that the unload timer runs, even despite the drawable not being in the hierarchy. [There's even a fallback to the game clock if nothing else can be found](https://github.com/ppy/osu-framework/blob/7b594edd61d2747dc47a9756dcb4fdd0f0ec7b33/osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs#L109).
3. The `DrawableCarouselBeatmap` gets enqueued for disposal asynchronously on a pooled thread. (I don't know 100% where this happens, but I don't think it matters.)
4. The unload timer from step (2) completes and triggers unloading of the DLUW, calling `ClearInternal()` and disposing `Content`.
5. The async disposal dies either by enumerating over the `InternalChildren` modified by (4) or by setting null `Parent` on `Content`, after (4) has already disposed it.

I'm not sure if I can figure out a fix within the next hour that I can spare on this, but I'll try. It's probably best not to increment the timer while the DLUW is outside of the hierarchy? Not sure.

2020-10-16 00:02 UTC, peppy commented
Well discovered. The old song select logic is super dodgy, but we still need to protect against this.

`Remove(false)` calls are very dangerous which is what I was worried about above.

2020-10-16 06:41 UTC, smoogipoo commented
That all to me sounds like:
1. The unload callback needs to have the disposal check because UnbindAllBindables is not guaranteed to be called synchronously.
2. The game scheduler callback should check the disposal state before scheduling the unload delegate.

Would either of you be against reverting https://github.com/ppy/osu-framework/pull/3926 and doing (2) from the above?

2020-10-16 06:55 UTC, bdach commented
Seems like that could work as long as `Dispose()` will attempt to call `cancelTasks` (to prevent the leak from resurfacing if the game scheduler check wins the race against async disposal). The complexity is not ideal but I'm not seeing a way to avoid it.

2020-10-16 07:00 UTC, smoogipoo commented
The fix is basically as in the last commit of this PR: https://github.com/smoogipoo/osu-framework/tree/fix-dluw-disposal

How did you replicate your failure cases?

2020-10-16 07:18 UTC, bdach commented
Easiest replication is running `TestScenePlaySongSelect. TestGroupedDifficultyIconSelecting` multiple times - 50 repeats should easily be enough to trigger.

I'm not sure the `checkForUnload` callback should be allowed to spin after disposal, though... I'd imagine it could be canceled outright on disposal.

2020-10-16 07:22 UTC, bdach commented
Never mind, missed the fact that the task cancel is fired in DLW and DLUW delegates to base. Looks OK.

2020-10-16 07:47 UTC, peppy commented
I'll leave this in your hands, fine with reverting as long as it works. Async disposal is a mistake, but we'll address that in a future.

2020-10-16 11:22 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
> +                DelayedLoadCompleted = true;
This can be removed, right? It's set by the scheduled callback in `DLW.EndDelayedLoad()`, which is on the local scheduler and is guaranteed to be hit before this schedule (because the schedule above was added from a callback from the game scheduler).

The call graph looks like:
```
LoadComponentAsync(...)

... { some delay until the load completes }

Game.Scheduler.Update()
EndDelayedLoad()
s1: Schedule()
s2: Game.Schedule()

... { rest of frame }

DLW.Scheduler.Update()
s1()

... { end of frame }
... { new frame }

s2()
```

2020-10-16 11:36 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
> +                DelayedLoadCompleted = true;
This is incorrect in the case that the DLUW is hidden for the rest of the frame.

2020-10-16 12:04 UTC, smoogipoo commented
I've pushed what I think are the final changes required to make DLUW as thread safe as possible. Please be highly critical and make sure the things I commented are adequately substantiated.

2020-10-17 15:19 UTC, bdach commented
I've read through the changes, followed the flow again and I can't really see any feasible way in which this could fail now ([see notes if curious](https://gist.github.com/bdach/3f69fcff2e27a5f3a8499def8e54d026)), so yeah, I'm on board with this version.

2020-10-17 16:22 UTC, bdach commented
Game-side tests look green, so should be good to go.

2020-10-17 16:42 UTC, peppy approved these changes

2020-10-17 16:43 UTC, merged