Improve transform allocation overhead (with focus on AutoSize)
ppy/osu-framework pull request #3942
Opened 2020-10-18 04:03 UTC by peppy

A collection of a few low-effort allocation optimisations. Most applicable to the edge case where `AutoSizeDuration > 0` and size is updated every frame. This happens at the osu! menu.

I think a more permanent solution would be using a Lerp call in place of this, but we will need to obsolete / remove `AutoSizeEasing` (not sure we want this - it can give correct results in the case autosize is only changed once in a while... but maybe it's just not worth supporting?).

before

|                       Method |       Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-----------:|--------:|--------:|------:|------:|------:|----------:|
|                     RunFrame |   739.0 us | 5.82 us | 4.86 us |     - |     - |     - |       1 B |
|         RunFrameWithAutoSize | 1,321.7 us | 6.70 us | 6.27 us |     - |     - |     - |     124 B |
| RunFrameWithAutoSizeDuration | 1,102.9 us | 5.52 us | 4.61 us |     - |     - |     - |     828 B |

after (enumeration reduction https://github.com/ppy/osu-framework/commit/246502b3becbac03fb810b3dab533f4a8b842819)

|                       Method |       Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-----------:|--------:|--------:|------:|------:|------:|----------:|
|                     RunFrame |   721.0 us | 4.81 us | 4.26 us |     - |     - |     - |      10 B |
|         RunFrameWithAutoSize | 1,319.9 us | 5.05 us | 4.22 us |     - |     - |     - |       1 B |
| RunFrameWithAutoSizeDuration | 1,107.1 us | 7.04 us | 6.59 us |     - |     - |     - |     524 B |

after (list -> queue https://github.com/ppy/osu-framework/commit/dcaabb1a42ac60f5deee89b81ef9ddcd37f2b179)

|                       Method |       Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-----------:|---------:|---------:|------:|------:|------:|----------:|
|                     RunFrame |   713.9 us |  3.07 us |  2.87 us |     - |     - |     - |      10 B |
|         RunFrameWithAutoSize | 1,319.8 us |  6.13 us |  5.73 us |     - |     - |     - |       1 B |
| RunFrameWithAutoSizeDuration | 1,113.2 us | 19.86 us | 17.61 us |     - |     - |     - |     492 B |

after (start list at size 1 https://github.com/ppy/osu-framework/commit/9de51768387e37a48d895728c91dbd6954311ed5)

|                       Method |       Mean |   Error |  StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-----------:|--------:|--------:|------:|------:|------:|----------:|
|                     RunFrame |   712.6 us | 2.01 us | 1.78 us |     - |     - |     - |       1 B |
|         RunFrameWithAutoSize | 1,309.5 us | 4.96 us | 4.64 us |     - |     - |     - |       1 B |
| RunFrameWithAutoSizeDuration | 1,103.3 us | 8.26 us | 6.89 us |     - |     - |     - |     449 B |

2020-10-18 11:58 UTC, bdach submitted a review, later dismissed
These all seem reasonable to me, but not 100% confident in merging myself.

2020-10-19 06:03 UTC, smoogipoo requested changes
Rest seems fine

2020-10-19 06:05 UTC, peppy commented on osu.Framework/Graphics/Transforms/Transformable.cs
> +        internal IEnumerable<Transform> TransformsForTargetMember(string targetMember) =>
No reason, change and add documentation if you think that's a valid use case.

As an aside, there's still an (unavoidable?) enumerator alloc in this call due to the return as `IEnumerable`. In an earlier version i was returning the `SortedList` directly to avoid that, and thus the `internal`.

2020-10-19 06:18 UTC, smoogipoo commented on osu.Framework/Graphics/Transforms/Transformable.cs
> +        internal IEnumerable<Transform> TransformsForTargetMember(string targetMember) =>
At least for the case of `FirstOrDefault()`, the allocation can be avoided by making `SortedList` implement `IList<T>`. Not trivial to do however, as that interface defines `Insert()`.

List stuff is really badly interfaced in .NET...

2020-10-19 06:34 UTC, smoogipoo approved these changes

2020-10-19 06:50 UTC, merged