SDL raw input
ppy/osu-framework pull request #3960
Opened 2020-11-01 03:59 UTC by swoolcock

Implements raw input with the SDL backend.  Should work fine on Windows (tested) and Linux (untested), but macOS is non-trivial and thus a future task.

There were some gotchas that made this take longer than it should have, specifically that events were being invoked in batches rather than sequentially.  The call to `SDL_SetRelativeMouseMode` purges all pending SDL mouse motion events, but it's possible that they have already been polled and added to `eventScheduler`.  I have thus changed the event loop to only handle a single SDL event at a time.  This means that any event invocations can be sure to immediately execute SDL commands before the next invocation.  Note that it is still using the scheduler, so that subclasses can inject events if required (such as with `MacOSWindowBackend`).

While the "raw" part of macOS is not implemented by SDL, the "relative" part is.  This means that the sensitivity slider and map absolute options can be used, but for now the mouse still includes OS acceleration.

"Map Absolute" scales the relative movement based on a window with a long edge of 1024 pixels.  This is somewhat of a guess, since it was hard to match against osuTK's implementation.

Needs testing on Linux, and verification on the implementation's "correctness" based on the user's expectation of the functionality.

Should hopefully resolve all or most of #2860, #2814, #2247, #2077, #1378

Requires a change to osu! to correctly select the raw input mouse handler when running SDL.

2020-11-01 09:05 UTC, peppy commented on osu.Framework/Platform/IWindow.cs
> +        /// Enables or disables relative mouse mode.
Why is this a bool though? The flow of all this is very confusing to me.

On windows, raw input comes in as either absolute or relative depending on the device. Are you saying that this gets switched depending on the source? The way it's implemented it looks like something we/a consumer is switching

2020-11-01 09:05 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                var relativeMargin = relativeEnabled ? -10 : 10;
They're arbitrary values I found worked well after testing.

2020-11-01 09:05 UTC, swoolcock commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                ScheduleEvent(() => OnMouseMoveRelative(new Vector2(evtMotion.xrel, evtMotion.yrel)));
Not necessary, since the delta is coming directly from the device and not in screen space.

2020-11-01 09:08 UTC, swoolcock commented on osu.Framework/Platform/DesktopWindow.cs
> +            config.BindWith(FrameworkSetting.MapAbsoluteInputToWindow, MapAbsoluteInputToWindow);
It's exposed to `RawMouseHandler` in a similar fashion to how `DesktopGameWindow.MapAbsoluteInputToWindow` is exposed to `OsuTKRawMouseHandler`.  I suppose the config could be resolved in the handler instead.

2020-11-01 09:09 UTC, swoolcock commented on osu.Framework/Platform/Window.cs
> +        /// The <see cref="Vector2"/> provided is the number of pixels the cursor has moved since the previous
If you think it's worth using integers instead, we should probably change both `MouseMove` and `MouseMoveRelative` to use `Point`, then.

2020-11-01 09:10 UTC, peppy commented
Initial issues noticed on windows (can only test mouse at the moment, need to find cables for tablet):

- When window if not focused, input events aren't handled fast enough. This happens with raw input on and off https://youtu.be/szf3riM-wSE
- Map absolute to window seems to be incorrectly applying to mouse movement. It should only apply to absolute pointer devices.
- Toggling raw input while absolute to window is enabled causes jumps on toggle of 5-10 pixels

2020-11-01 09:17 UTC, swoolcock commented on osu.Framework/Platform/IWindow.cs
> +        /// Enables or disables relative mouse mode.
The only way to access "raw input" through SDL is by enabling relative mode, which reports unaccelerated deltas from the mouse rather than absolute positions.  If this is not the way we want to implement raw input, then we cannot do it with SDL alone.

2020-11-01 09:18 UTC, peppy commented on osu.Framework/Platform/IWindow.cs
> +        /// Enables or disables relative mouse mode.
i'll have to test with a tablet, but this definitely does not sound what we want. and if that's the case, why not rename "relative" bools to "rawInput", since apparently that's what they are doing?

2020-11-01 09:31 UTC, peppy commented
mapAbsoluteToScreen is fine to work on mice if it actually does what it says btw. It should make the mouse move from one side of the window to the other over the same physical distance regardless of window size. We'll need this to make cursor sensitivity portable.

2020-11-01 09:45 UTC, peppy requested changes

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/IWindow.cs
> +        /// Enables or disables relative mouse mode.
what *is* relative mouse mode?

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/IWindowBackend.cs
> +        /// While relative mouse mode is disabled, <see cref="MouseMove"/> events will be fired.
this doesn't explain when/why i'd want either.

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                var relativeMargin = relativeEnabled ? -10 : 10;
where do these numbers come from?

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
> +                ScheduleEvent(() => OnMouseMoveRelative(new Vector2(evtMotion.xrel, evtMotion.yrel)));
what's the reason for not multiplying in scale here? is it actually not necessary?

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/Window.cs
> +        /// The <see cref="Vector2"/> provided is the number of pixels the cursor has moved since the previous
pixels in what space? also pixels are not floating point, so may want to rewrite this to refer to the "distance the mouse has moved" or something if it's actually floating point data.

2020-11-01 09:45 UTC, peppy commented on osu.Framework/Platform/DesktopWindow.cs
> +            config.BindWith(FrameworkSetting.MapAbsoluteInputToWindow, MapAbsoluteInputToWindow);
no value changed action? what's the point of this bindable?

2020-11-01 10:21 UTC, bdach commented
It does indeed seem that the SDL mouse API is insufficient for some of the requirements listed above. After some digging I have some good news and some bad news. SDL's tip branch does seem to have a touch input API, which is supposed to also support tablets - see [this readme document](https://hg.libsdl.org/SDL/file/2b1cce20e59b/docs/README-touch.md).

Bad news is (provided the README is even up to date):

> Linux:
> (...) Currently only Wacom tablets are supported.
> (...)
> Windows:
> Unfortunately there is no windows support as of yet. Support for Windows 7 is planned, but we currently have no way to test. (...)

We're kind of going into device driver territory here. Windows can provide raw input via WM_INPUT, and it seems that linux should also be able to via the input subsystem, as long as drivers are written properly ([link](https://www.kernel.org/doc/html/v4.12/input/event-codes.html#guidelines)). I can't see a .NET wrapper over the latter, though...

2020-11-01 11:41 UTC, bdach commented
I've tested the current code on linux.

* Can also reproduce the warp on raw input toggle - seems like the raw input handler is not marshaling back its last cursor position to the OS correctly for it to be able to resume where raw input left off.
* I'm also getting very weird behaviour if a framework window with raw input off is behind a normal window. Within the confines of the normal window the cursor works fine, but if you move to the framework window, the OS mouse pointer will show and be locked in place at the center of the framework window, while the game pointer will very choppily attempt to move as requested by the user.

2020-11-03 07:04 UTC, swoolcock commented
Looking more at how SDL and various other windowing toolkits handle raw input of pointing devices, it seems that honestly OpenTK's implementation is closest to what we actually want.  It exposes both absolute and relative values from attached pointing devices via `Mouse.GetStates()`, while also calling `MouseMove` based on the OS cursor position.

Both SDL and GLFW can only handle absolute OR relative motion for a single device via the event loop, and the developer needs to select which type of input they want at the time.  GLFW has a similar implementation.

It may be worth just copy-pasting a lot of the platform-specific mouse implementation from osuTK and repurposing it for our requirements.  We know it currently works, and it shouldn't be too much effort.

2021-03-09 11:52 UTC, closed without merging