WIP: Make DevicePeriod configurable
ppy/osu-framework pull request #4008
Opened 2020-11-18 12:41 UTC by ArniDagur

Result of discussion from https://github.com/ppy/osu-framework/pull/3832

2020-11-18 13:06 UTC, peppy requested changes

2020-11-18 13:12 UTC, ArniDagur commented on osu.Framework/Audio/AudioManager.cs
> +            MaxValue = 240
Probably not. Anything above 100 or so for me is unplayable. I think I'll change the max to 60 or so later.

2020-11-18 17:28 UTC, bdach commented
@ArniDagur please avoid force-pushing in general if you can avoid it.

2020-11-20 22:56 UTC, peppy requested changes

2020-11-20 22:56 UTC, peppy commented on osu.Framework/Audio/AudioManager.cs
> +        };
shouldn't be added

2022-04-13 07:18 UTC, smoogipoo commented
Closing due to inactivity. Still need to discuss how to do this since we all have different ideas/expectations.

2022-04-13 07:18 UTC, closed without merging