Target .NET 5 instead of .NET Core 3
ppy/osu-framework pull request #4012
Opened 2020-11-20 11:50 UTC by UselessToucan

2020-11-21 12:22 UTC, bdach requested changes

2020-11-21 12:22 UTC, bdach commented on osu.Framework/Extensions/ExtensionMethods.cs
> +                return e.Types;
not sure about this

![2020-11-21-130730_1077x116_scrot](https://user-images.githubusercontent.com/20418176/99876928-8e0d8080-2bfa-11eb-9e60-6e247e285a0d.png)

2020-11-21 12:22 UTC, bdach commented on osu.Framework/Graphics/Drawable.cs
> +                    var property = type?.GetProperty(inputProperty);
this nullcheck seems suspect. where's that coming from? only call is from `get(Drawable, ConcurrentDictionary<Type, bool>, bool)`, which passes `drawable.GetType()` as the type. that should never be null I'd hope.

this looks like an analyser bug, but if we want to shut it up for now, this should be a `type != null` assert at the top of the method as a precondition.

2020-11-21 12:22 UTC, bdach commented on osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
> +#if NET5_0
FYI rider 2020.2.4 is (seemingly wrongly) showing this code as dead.

2020-11-21 12:26 UTC, bdach commented
aside from the above, i'm seeing the following build warnings:

```
osu-framework/osu.Framework/IO/Network/WebRequest.cs(394,47): warning CA2016: Forward the 'cancellationToken' parameter to the 'ReadAsStreamAsync' method or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token [/home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/osu.Framework.csproj]
osu-framework/osu.Framework/Statistics/BackgroundStackTraceCollector.cs(184,72): warning CA1837: Use 'Environment.ProcessId' instead of 'Process.GetCurrentProcess().Id' [/home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/osu.Framework.csproj]
osu-framework/osu.Framework/Platform/Windows/WindowsGameHost.cs(24,49): warning CA1416: 'Console.CapsLock.get' is supported on 'windows' [/home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/osu.Framework.csproj]
```

and dynamic compilation seems to be failing with the following:

```
[runtime] 2020-11-21 12:19:53 [error]: Error with dynamic compilation!
[runtime] 2020-11-21 12:19:53 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.ProjectModel, Version=5.8.0.6930, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
[runtime] 2020-11-21 12:19:53 [error]: 
[runtime] 2020-11-21 12:19:53 [error]: File name: 'NuGet.ProjectModel, Version=5.8.0.6930, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[runtime] 2020-11-21 12:19:53 [error]: at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
[runtime] 2020-11-21 12:19:53 [error]: at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
[runtime] 2020-11-21 12:19:53 [error]: at System.RuntimeType.get_DeclaringType()
[runtime] 2020-11-21 12:19:53 [error]: at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
[runtime] 2020-11-21 12:19:53 [error]: at System.RuntimeType.get_Namespace()
[runtime] 2020-11-21 12:19:53 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.<>c.<GetReferencedAssemblies>b__13_4(Type t) in /home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/Testing/RoslynTypeReferenceBuilder.cs:line 93
```

2020-11-23 01:37 UTC, turbedi commented
My benchmark numbers for anyone interested (OS=Windows 10.0.19042 Intel Core i5-4590):

<details>
  <summary>BenchmarkBindableList</summary>
This PR:

|    Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|------:|------:|------:|----------:|
| Enumerate | 2.828 μs | 0.0224 μs | 0.0187 μs |     - |     - |     - |         - |


Master:
|    Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|------:|------:|------:|----------:|
| Enumerate | 2.709 μs | 0.0138 μs | 0.0129 μs |     - |     - |     - |         - |

</details>

<details>
  <summary>BenchmarkButtonInput</summary>
This PR:

|        Method | count |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------- |------ |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|         **Apply** |     **?** |   **790.7 ns** |  **3.18 ns** |  **2.65 ns** | **0.7849** |     **-** |     **-** |    **2464 B** |
| **FromTwoStates** |     **1** |   **231.6 ns** |  **3.90 ns** |  **3.65 ns** | **0.2244** |     **-** |     **-** |     **704 B** |
| **FromTwoStates** |     **5** |   **583.5 ns** |  **3.40 ns** |  **2.84 ns** | **0.3977** |     **-** |     **-** |    **1248 B** |
| **FromTwoStates** |    **10** | **1,011.6 ns** |  **3.12 ns** |  **2.76 ns** | **0.6981** |     **-** |     **-** |    **2192 B** |
| **FromTwoStates** |    **50** | **3,956.2 ns** | **11.23 ns** | **10.50 ns** | **2.6321** |     **-** |     **-** |    **8272 B** |

Master:

|        Method | count |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------- |------ |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|         **Apply** |     **?** |   **916.5 ns** |  **2.00 ns** |  **1.67 ns** | **0.7696** |     **-** |     **-** |    **2416 B** |
| **FromTwoStates** |     **1** |   **249.1 ns** |  **1.32 ns** |  **1.17 ns** | **0.2189** |     **-** |     **-** |     **688 B** |
| **FromTwoStates** |     **5** |   **726.4 ns** |  **3.08 ns** |  **2.57 ns** | **0.3920** |     **-** |     **-** |    **1232 B** |
| **FromTwoStates** |    **10** | **1,315.3 ns** |  **4.11 ns** |  **3.65 ns** | **0.6924** |     **-** |     **-** |    **2176 B** |
| **FromTwoStates** |    **50** | **5,562.2 ns** | **21.43 ns** | **17.90 ns** | **2.6245** |     **-** |     **-** |    **8256 B** |

</details>

<details>
  <summary>BenchmarkButtonStates</summary>
This PR:

|                    Method | count |        Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------ |------------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
|                 **CreateNew** |     **?** |    **16.08 ns** | **0.080 ns** | **0.070 ns** |  **1.00** |    **0.00** | **0.0306** |     **-** |     **-** |      **96 B** |
|                SetPressed |     ? |    50.84 ns | 0.246 ns | 0.218 ns |  3.16 |    0.02 | 0.0637 |     - |     - |     200 B |
| EnumerateEmptyDifferences |     ? |    34.07 ns | 0.167 ns | 0.148 ns |  2.12 |    0.01 | 0.0612 |     - |     - |     192 B |
|                           |       |             |          |          |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |     **1** |   **184.62 ns** | **0.464 ns** | **0.411 ns** |     **?** |       **?** | **0.1938** |     **-** |     **-** |     **608 B** |
|                           |       |             |          |          |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |     **5** |   **516.20 ns** | **2.870 ns** | **2.241 ns** |     **?** |       **?** | **0.3462** |     **-** |     **-** |    **1088 B** |
|                           |       |             |          |          |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |    **10** |   **925.85 ns** | **3.645 ns** | **3.232 ns** |     **?** |       **?** | **0.6218** |     **-** |     **-** |    **1952 B** |
|                           |       |             |          |          |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |    **50** | **3,669.54 ns** | **5.487 ns** | **5.132 ns** |     **?** |       **?** | **2.3537** |     **-** |     **-** |    **7392 B** |

Master:

|                    Method | count |        Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |------ |------------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
|                 **CreateNew** |     **?** |    **15.21 ns** |  **0.126 ns** |  **0.105 ns** |  **1.00** |    **0.00** | **0.0280** |     **-** |     **-** |      **88 B** |
|                SetPressed |     ? |    47.92 ns |  0.830 ns |  0.776 ns |  3.15 |    0.06 | 0.0612 |     - |     - |     192 B |
| EnumerateEmptyDifferences |     ? |    37.37 ns |  0.284 ns |  0.237 ns |  2.46 |    0.02 | 0.0561 |     - |     - |     176 B |
|                           |       |             |           |           |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |     **1** |   **221.07 ns** |  **0.730 ns** |  **0.610 ns** |     **?** |       **?** | **0.1886** |     **-** |     **-** |     **592 B** |
|                           |       |             |           |           |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |     **5** |   **672.93 ns** |  **2.347 ns** |  **1.959 ns** |     **?** |       **?** | **0.3414** |     **-** |     **-** |    **1072 B** |
|                           |       |             |           |           |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |    **10** | **1,262.29 ns** |  **4.862 ns** |  **4.310 ns** |     **?** |       **?** | **0.6161** |     **-** |     **-** |    **1936 B** |
|                           |       |             |           |           |       |         |        |       |       |           |
|  **EnumerateBothDifferences** |    **50** | **5,283.73 ns** | **21.381 ns** | **20.000 ns** |     **?** |       **?** | **2.3499** |     **-** |     **-** |    **7376 B** |

</details>

<details>
  <summary>BenchmarkCompositeDrawableAllocations</summary>
This PR:

|              Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------------------- |----------:|----------:|----------:|-------:|-------:|------:|----------:|
|   TestEmptyGameLoop |  5.642 μs | 0.0164 μs | 0.0137 μs |      - |      - |     - |         - |
|  TestAllocContainer |  7.656 μs | 0.0479 μs | 0.0424 μs | 0.5493 | 0.2747 |     - |    1750 B |
| TestLoadedContainer | 13.605 μs | 0.0633 μs | 0.0529 μs | 0.6714 | 0.3052 |     - |    2205 B |
|     TestAllocSprite |  7.494 μs | 0.0237 μs | 0.0210 μs | 0.4654 | 0.2289 |     - |    1472 B |
|    TestLoadedSprite | 10.616 μs | 0.0468 μs | 0.0415 μs | 0.5493 | 0.2747 |     - |    1751 B |

Master:

|              Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------------------- |----------:|----------:|----------:|-------:|-------:|------:|----------:|
|   TestEmptyGameLoop |  6.395 μs | 0.0268 μs | 0.0237 μs |      - |      - |     - |         - |
|  TestAllocContainer |  8.851 μs | 0.0489 μs | 0.0458 μs | 0.5493 | 0.2747 |     - |    1750 B |
| TestLoadedContainer | 15.891 μs | 0.1068 μs | 0.0999 μs | 0.7019 | 0.3357 |     - |    2208 B |
|     TestAllocSprite |  8.346 μs | 0.0821 μs | 0.0728 μs | 0.4578 | 0.2289 |     - |    1471 B |
|    TestLoadedSprite | 12.651 μs | 0.0701 μs | 0.0621 μs | 0.5493 | 0.2747 |     - |    1752 B |

</details>

<details>
  <summary>BenchmarkDependencyContainer</summary>
This PR:

|       Method |      Mean |    Error |   StdDev  [...]

2020-11-24 06:31 UTC, smoogipoo commented on osu.Framework/osu.Framework.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
I think netstandard is dead with net5?

2020-11-24 15:03 UTC, UselessToucan commented on osu.Framework/osu.Framework.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
No, it is not dead yet. Xamarin projects can't reference `net5.0` libraries.

2020-11-24 15:04 UTC, smoogipoo commented on osu.Framework/osu.Framework.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
Wouldn't the xamarin projects use net5.0-ios + net5.0-android? https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

2020-11-24 15:42 UTC, peppy commented on osu.Framework/osu.Framework.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
Last I heard they are still some way off (a couple of weeks ago, can't find the thread immediately).

2020-11-30 19:52 UTC, bdach commented
I've looked a little bit into resolving the build warnings and 2 of them are not easy to get rid of without first ditching `netstandard2.1`:

* For the `Console.CapsLock` warning, the intended way to fix via the [`SupportedOSPlatform` attribute](https://docs.microsoft.com/pl-pl/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-5.0) is held back by .NET Standard as the attribute was (is) internal there.
* Similarly [`Environment.ProcessId` is not a thing](https://docs.microsoft.com/pl-pl/dotnet/api/system.environment.processid?view=net-5.0) in Standard.

Therefore this might get delayed for a longer while, unless we accept the warnings for the time being.

As for dynamic compilation failures, they seem to be resolved with installing [the package in the error message](https://www.nuget.org/packages/NuGet.ProjectModel), although I'm not sure that's 100% the correct thing to do.

2020-11-30 20:43 UTC, turbedi commented
I'm pretty sure that the `Environment.ProcessId` warning can be safely ignored for now. It was only added because it is more performant and easier to use. [Here is the issue thread for the API](https://github.com/dotnet/runtime/issues/38388).

2020-11-30 20:47 UTC, bdach commented
well, i'm of the opinion that this bump to .NET 5 is the best possible time to address that warning if it can happen.

2020-12-01 02:04 UTC, peppy commented
I'm pretty sure @smoogipoo was proposing we drop netstandard along with this change?

2020-12-01 10:20 UTC, UselessToucan commented
Actually `Console.CapsLock` and `Environment.ProcessId` warnings can be easily fixed with conditional compilation. Hovewer, this solution is ugly and uncomfortable to maintain.

see https://github.com/UselessToucan/osu-framework/commit/f8fdc7b38bb9cdd30d46419ddb780fad3cba9d3d

2021-01-14 10:29 UTC, peppy commented on osu.Framework/osu.Framework.csproj
> +    <TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
These are not usable yet (apparently net6.0 may bring them in) so we need to leave `netstandard2.1` for now.

2021-01-14 10:30 UTC, smoogipoo requested changes

2021-01-14 10:30 UTC, smoogipoo commented on osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
> +                if (!force && loadedTypes.Any(t => t?.Namespace == jetbrains_annotations_namespace))
Actually I specifically remember `e.Types` being `null` in some case, so I'm not sure about this change. Also the one above in https://github.com/ppy/osu-framework/pull/4012/files#r528188947 as a result (not sure why it was marked as resolved).

2021-01-14 10:30 UTC, smoogipoo commented on osu.Framework/IO/Network/WebRequest.cs
> +                            // ReSharper disable once MethodSupportsCancellation
Why not conditional to `NET5_0` like elsewhere and pass `linkedToken.Token`?

2021-01-14 10:32 UTC, smoogipoo commented on osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
> +                Debug.Assert(entry?.State == LifetimeEntryState.Future);
This is very suspicious... Is this nullcheck really required here?

2021-01-14 10:33 UTC, smoogipoo commented
@peppy why did you mark several of the above comments as resolved? I've unresolved them.

https://github.com/ppy/osu-framework/pull/4012#discussion_r528188947
https://github.com/ppy/osu-framework/pull/4012#discussion_r528189164

2021-01-14 10:35 UTC, peppy commented
I am about to commit changes. Trying to fix broken branch.

2021-01-14 10:44 UTC, peppy commented on osu.Framework/Extensions/ExtensionMethods.cs
> +                return e.Types;
This has been resolved via https://github.com/ppy/osu-framework/pull/4143

2021-01-14 10:45 UTC, peppy commented on osu.Framework/Graphics/Drawable.cs
> +                    var property = type?.GetProperty(inputProperty);
This doesn't even trigger an analyser issue.

2021-01-14 10:47 UTC, peppy commented on osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
> +                Debug.Assert(entry?.State == LifetimeEntryState.Future);
Has been reverted, was not required.

2021-01-14 11:09 UTC, peppy commented on osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
> +                if (!force && loadedTypes.Any(t => t?.Namespace == jetbrains_annotations_namespace))
it can be null in the exception case directly above.

2021-01-14 11:20 UTC, peppy commented
I've tested on iOS and there are no issues with this change, so let's go ahead and see where it takes us. @smoogipoo requesting a double-check from your end.

2021-01-14 11:20 UTC, peppy approved these changes

2021-01-14 11:33 UTC, smoogipoo submitted a review, later dismissed

2021-01-14 17:38 UTC, bdach commented
The reason for CI failures is dual-targeting .NET 5.0 along with .NET Standard 2.1, again. All of the CI errors occur in spots where net5.0 runtime/libs add nullability annotations which are not present on netstandard, therefore leading to ambiguous analysis errors - and it seems that while rider won't show *either* error when dual-targeting in that case, inspectcode will show *every possible* error.

Looking into ways to choose one of the two via configuring the `jb` tool right now.

2021-01-14 18:29 UTC, bdach commented
Pushed in a couple of commits that should hopefully get CI to pass.

2021-01-14 18:34 UTC, bdach reviewed
explanations for the changes:

2021-01-14 18:34 UTC, bdach commented on osu.Framework/Graphics/Drawable.cs
> +            private static bool compute([NotNull] Type type, bool positional)
This is a curious one - it's likely due to a jetbrains bug. The issue lies in the `IsAssignableFrom()` call that's inside of this method. `net5.0` adds a conditional nullability annotation:

![2021-01-14-191419_778x134_scrot](https://user-images.githubusercontent.com/20418176/104633207-1eb68900-569f-11eb-95c7-240cdac5521f.png)

Some control flow analysis seems to be borked by this. As the loop over `inputInterfaces` early-returns if `IsAssignableFrom` ever returns `true` on one of the items, something seems to misinterpret the value of `false` - instead of interpreting it as "`type` is possibly null still" it seems to infer that "`type` is definitely null" without much reason to do so.

2021-01-14 18:34 UTC, bdach commented on osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
> +                var entry = futureEntries.Min.AsNonNull(); // guaranteed by the .Count > 0 guard.
`SortedSet.{Min,Max}` were changed to `T?` in net5.0.

2021-01-14 18:36 UTC, bdach approved these changes

2021-01-15 02:05 UTC, peppy approved these changes

2021-01-15 03:59 UTC, smoogipoo approved these changes

2021-01-15 04:01 UTC, merged