Rewrite GLWrapper's scheduled disposal logic to avoid delegate allocations
ppy/osu-framework pull request #4013
Opened 2020-11-20 12:54 UTC by peppy

Needs sanity testing

2020-11-21 14:31 UTC, bdach commented
I've briefly read the source (seemed sane) and resolved the CI inspection but done no further testing than that. Would need to run windows to benchmark this but might fire it up tomorrow.

2020-11-21 20:43 UTC, peppy commented
Centipede single run:

![image](https://user-images.githubusercontent.com/191335/99887186-86df8480-2c85-11eb-8b3e-f9c31a518159.jpeg)

I tried to add a headless benchmark, but GLWrapper.Initialize is kind of not run in headless contexts and therefore it's not easy to make work.

2020-12-01 08:36 UTC, smoogipoo requested changes

2020-12-01 08:36 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/GLWrapper.cs
> +                        pending_disposal_actions.Remove(item);
Use `RemoveAt(i)` to avoid an internal `IndexOf()`, though I don't think that would be much because: I think it would also be instructive to add a `Debug.Assert(i == 0)`.

2020-12-01 08:36 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/GLWrapper.cs
> +            host.UpdateThread.Scheduler.AddDelayed(checkPendingDisposals, 0, true);
This is incorrect. The initial scheduling was done from the update thread (for whatever reason, I don't remember, need to blame), but the actual disposal (`item.Action()`) should be run on the `reset_scheduler` (draw thread).

2020-12-03 12:11 UTC, smoogipoo approved these changes

2020-12-03 12:11 UTC, merged