No longer targeting properties in UnbindAllBindables
ppy/osu-framework pull request #4015
Opened 2020-11-20 14:30 UTC by OliBomby

closes #4014

As mentioned in the issue, unbinding external bindables is pretty dodgy. I updated the unbinding code and changed the test to test for the opposite behaviour.

2020-11-21 12:56 UTC, bdach commented
I've expanded test coverage to ensure auto-properties (not delegating ones) are indeed auto-unbound and added a clarifying comment where the property unbound code used to be. Seems good to me otherwise.

2020-11-21 12:56 UTC, bdach approved these changes

2020-11-23 04:19 UTC, peppy submitted a review, later dismissed

2020-11-23 04:57 UTC, smoogipoo requested changes

2020-11-23 04:57 UTC, smoogipoo commented on osu.Framework.Tests/Bindables/BindableBindingTest.cs
> +            Assert.IsTrue(valueChanged, "bound correctly");
valueChanged needs to be reset before the SetValue, otherwise assert can pass incorrectly.

2020-11-24 04:48 UTC, smoogipoo approved these changes
lgtm

2020-11-24 04:48 UTC, merged