Implementation of hexagons with masking
ppy/osu-framework pull request #4016
Opened 2020-11-23 05:48 UTC by harshavb

Thanks to Poyo for all the help. Optimally uses 4 triangles per hexagon.

2020-11-23 05:58 UTC, bdach commented
Do you have permission from @Poyo-SSB to PR this back upstream? Kind of dodgy that you're taking authorship credit on the commits, too.

For the record, original implementation was made in https://github.com/harshavb/piously/pull/13 and https://github.com/harshavb/piously/pull/21.

2020-11-23 06:01 UTC, harshavb commented
Fair enough. Will re-open if granted permission.

2020-11-23 18:45 UTC, Poyo-SSB commented
Permission granted. I can make adjustments and do rewrites as necessary.

2020-11-23 19:02 UTC, bdach commented
reopening for review then, I guess.

@Poyo-SSB would you like (co-)authorship credit on the existing commits? probably one of the rare cases we could allow for a force-push.

2020-11-23 19:16 UTC, Poyo-SSB commented
I don't mind either way. @harshavb can take care of that, probably.

2020-11-23 19:39 UTC, harshavb commented
Poyo should take full authorship credit, as all the code here is written by her.

2020-11-23 19:40 UTC, bdach requested changes

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Containers/HexagonalContainer.cs
> +        where T : Drawable
is this generic all that necessary? why not just stick with `HexagonalContainer`?

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Containers/HexagonalContainer.cs
> +        private static readonly float sin_pi_over_3 = (float)Math.Sin(Math.PI / 3);
fancy way of writing `0.5f`, but sure

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Containers/HexagonalContainer.cs
> +        public static readonly float HEXAGON_INRADIUS = sin_pi_over_3;
unused

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Containers/HexagonalContainer.cs
> +            norm = new Vector2(norm.X / ScreenSpaceDrawQuad.Width, norm.Y / ScreenSpaceDrawQuad.Height); // apparently we can't divide Vector2s?
it is actually possible, just not via operator overload

```suggestion
            norm = Vector2.Divide(norm, ScreenSpaceDrawQuad.Size);
```

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Containers/HexagonalContainer.cs
> +                    hexagonShader.GetUniform<float>("g_Resolution").UpdateValue(ref resolution);
what's with this comment?

2020-11-23 19:40 UTC, bdach commented on osu.Framework/Graphics/Shapes/Hexagon.cs
> +                    new Vector2(InflationAmount.X / DrawRectangle.Width, InflationAmount.Y / DrawRectangle.Height), TextureCoords);
can these be a method at least or something? duplicated 8 times across 2 methods, only differing with the triangle involved.

2020-11-23 19:42 UTC, bdach commented
oh, and this PR should also include the test scene.

2020-11-23 20:27 UTC, Poyo-SSB commented
`HexagonalContainer` is generic for the same reason that other Containers are generic—for ease of access to single-type children, yes? I don't know if there are any performance optimizations that come with that or anything.

As for the comment, I'm unsure if passing in the resolution as a uniform is the canonical method of having screenspace-aware shaders. I wasn't able to find the way that CompositeDrawable does this.

2020-11-23 20:29 UTC, bdach commented
re: generic - i mean sure, i get that, it's just that it's generating quite a few CI inspections so i was wondering if it can be removed entirely. i guess it can stay for convenience though, the static fields can be moved to the non-generic base as protected.

not sure about the screenspace awareness. would have to poke `CompositeDrawable` myself.

2020-11-24 00:56 UTC, peppy commented
I'd remove generics for simplicity. `Container` is an exception since it is such a commonly used class. this is not.

2020-11-24 22:37 UTC, bdach commented
@harshavb did you happen to uncheck the "Allow edits from maintainers" checkbox on this PR? i have a batch of changes that are supposed to resolve my reviews, fix up style somewhat and reattribute previous commits, but i cannot push to this PR.

that said it might also be due to this being PRed from `master`, which is never a good idea.

2020-11-25 14:25 UTC, harshavb commented
@bdach It's likely because it's PRed from master, since it's not unchecked.

2020-12-12 00:19 UTC, harshavb commented
Moved to #4091

2020-12-12 00:19 UTC, closed without merging