Fix window position getting updated from config while in maximised state
ppy/osu-framework pull request #4076
Opened 2020-12-05 22:43 UTC by frenzibyte

Closes #4070

The issue is coming from the window implementation setting `WindowState` to `Normal` regardless of whether it is maximised or not, which causes the window to potentially have its position changed according to the config while being in maximised state.

This also adds `SDL_RestoreWindow(handle)` to normal state for correct window state updating, as, previously, switching from maximised/minimised state to normal state via `WindowState` property would do absolutely nothing.

---

I've tried to look for more elegant ways to solve this, but this is the least inelegant solution I came up with. 

Another way could be to just not change position if the window is in maximised state (inside `WindowState.Normal` switch case), which would win to the current solution in terms of [not having to stay for a whole frame stuck in `Fullscreen`/`FullscreenBorderless` state while `WindowMode` is already set to `Windowed`](https://github.com/ppy/osu-framework/commit/98627a0b6096d460fd52d7a8a5af6e8492b1b9fe#diff-802f1281748362cec8a6ce40039ebf6ae50bd82897f7d4c0699df24234b7a5e3R1099-R1100), but would **break** switching from maximised state to normal state via `WindowState` property (as, with this PR, switching to normal state would be restoring the window from maximised/minimised state).

Would appreciate feedback on whether the current pushed solution or the other given solution would work out best here.

2020-12-07 05:30 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        ScheduleCommand(() =>
How did you find this method? I'd like to think that someone else has run into this problem in the past and there is some documentation we can link to? Don't really want to invent our own solutions where possible..

2020-12-07 08:13 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        ScheduleCommand(() =>
More like it was getting incorrectly handled previously, by setting `WindowState to `Normal`, and attempting to change its position according to the config, while it is actually in maximized mode.

2020-12-07 20:54 UTC, bdach commented
I think the "not change position if the window is in maximised state" variant sounds like a saner thing to do seeing whatever that fullscreen workaround is doing, but I'm not sure I'm understanding what the caveat about setting `WindowState` with that variant would be - would you mind to elaborate what the problem is there?

2020-12-08 07:36 UTC, frenzibyte commented
`WindowState` already has a `Maximised` enum state, and would expect `Normal` to be that the window should be in unmaximised state, in which the window can be moved around the display with no issues.

Choosing the other variant would mean breaking one case of `WindowState` switching via property setter, as I've already mentioned in the description:
> but would break switching from maximised state to normal state via `WindowState` property (as, with this PR, switching to normal state would be restoring the window from maximised/minimised state).

2020-12-08 07:43 UTC, bdach commented
Quoting the OP again does not answer my question. I was asking since I don't understand the reasoning provided there to begin with.

2020-12-08 09:12 UTC, frenzibyte commented
Ah, my bad, I got driven by my words without looking back at them. using the other variant would cause switching into `Windowed` mode always makes the window unmaximised regardless of what state it was in, as I've added `SDL_RestoreWindow(handle)` there for fixing switching from `Maximised`/`Minimised` into `Normal` not causing any effects.

2020-12-09 00:07 UTC, bdach commented
Just as a loose idea, maybe storing info about whether or not the window was maximised previously could be of help? Hesitant to suggest that as the windowing code is close to reaching critical density again, but maybe there is a way to store and use that info in a legible manner...

2020-12-09 00:13 UTC, frenzibyte commented
Hmm, I've tried doing that by window event IDs, and failed to work for me (couldn't tell if an `SDL_WINDOWEVENT_RESTORED` means from maximised state or from minimised state), but I think I can do this by checking the flags every window event (basically inside the `updateWindowSpecifics` method), it may not look that good but would 100% be better for getting rid of the "unsynced window state with mode" issue that is present in the pushed solution. Good suggestion, I'll look into doing it tomorrow.

2020-12-10 01:14 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        ScheduleCommand(() =>
@peppy I've updated the PR by using an alternative solution suggested by @bdach, please check if it looks more saner now.

2020-12-10 04:00 UTC, peppy requested changes

2020-12-10 04:00 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                windowMaximised = currentState == WindowState.Maximised;
can this just be made into a method (`updateMaximisedState`) and used in both locations? seems like this is basically doing the same thing as your code in the `switch` statement below, but this version is more concise and doesn't need to be split over different `case`s.

hopefully it could then just be called after the full `switch` execution.

2020-12-10 04:20 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        private void updateMaximisedState(WindowState windowState)
does this really need a parameter passed in..? it's a field in this class already.

2020-12-10 04:20 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateMaximisedState(currentState);
just move this below the switch and remove the parameter right?

2020-12-10 04:24 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        private void updateMaximisedState(WindowState windowState)
I've done it that way because `OnWindowStateChanged(...)` could potentially change window mode while maximised state not updated. but actually, nevermind, the event is scheduled anyway.

2020-12-10 04:26 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateMaximisedState(currentState);
I'm not sure what you mean, but this should be placed both here (for catching external window state changes), and in `updateWindowStateAndSize()` (for catching internal window state changes, i.e. via changing `WindowState` property)

2020-12-10 04:46 UTC, peppy approved these changes

2020-12-10 05:17 UTC, merged