Improve support for disabled dropdowns
ppy/osu-framework pull request #4077
Opened 2020-12-06 15:10 UTC by bdach

Follow-up on https://github.com/ppy/osu/pull/11101 and the issues with disabling dropdowns I found there.

In general, the existing support for disabled dropdowns was lacking. They were fully interactable, but trying to click on dropdown items just did nothing. This pull aims to achieve the following effects:

- Disabled dropdowns are no longer interactable. Clicking on them does not expand the dropdown, and hovering on them does not change their background colour.
- Disabled dropdowns now have a visual indication of their visual state, by being partially faded out. This is done by adding a `DisabledColour` to `DropdownHeader`.
- Disabled dropdowns no longer handle changing value via keyboard. They would previously attempt to do so, and promptly crash due to `Current` being disabled.
- If an actively opened dropdown becomes disabled, its dropdown is closed immediately.

This includes a test case for the new behaviours, and some slight refactorings of the test scene (first three commits) as I didn't particularly like the way it was written (and needed to re-use some helpers that were already there).

2020-12-06 17:39 UTC, frenzibyte requested changes
Otherwise, this looks to be and feels very good 👍🏼

2020-12-06 17:39 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/DropdownHeader.cs
> +        public Bindable<bool> Disabled { get; } = new BindableBool();
`DropdownHeader` already exposes an `Enabled` property (by inheriting `ClickableContainer`), which would make this component expose publicly both an `Enabled` property and `Disabled` property.

2020-12-06 17:44 UTC, bdach commented on osu.Framework/Graphics/UserInterface/DropdownHeader.cs
> +        public Bindable<bool> Disabled { get; } = new BindableBool();
good point

2020-12-06 17:54 UTC, frenzibyte approved these changes

2020-12-07 05:04 UTC, peppy approved these changes
Looks solid

2020-12-07 05:04 UTC, merged