Save maximised window state for use in next startup
ppy/osu-framework pull request #4089
Opened 2020-12-10 18:56 UTC by frenzibyte

- [ ] Depends on #4085 (fixing bugs encounterable here)

Saves maximised window state internally to framework config for use in next startups, this PR also has several changes required for "start-up in maximised state" to work correctly:
#### https://github.com/ppy/osu-framework/commit/5c16fa6464f8081358e373a931294e9ec64de64f
To make restoring the window from initial maximised state work properly, as now the window would switch to maximised state while its already positioned and sized to config values, unlike previously where it would switch to maximised state while its position is 0 and size is `default_width,default_height` (1366x768).

---

#### https://github.com/ppy/osu-framework/commit/c5d916e5f0e3b32e60d76f173f06ed778c16b7d5
Methods such as `SDL_MaximizeWindow()` or `SDL_RestoreWindow()` would display the window (if it gives effect) regardless of whether it was hidden previously or not. 

This fixes the issue by re-applying the current visibility state after finishing from propagating all required SDL actions.

2020-12-10 19:36 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
Quoting the OP:

> the window would switch to maximised state while its already positioned and sized to config values, unlike previously where it would switch to maximised state while its position is 0 and size is `default_width,default_height` (1366x768)

What difference does it make if it's maximised anyway? Does it matter on multi-display setups? I'm really confused by these sets.

2020-12-10 19:36 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
>              if (windowState == WindowState.Normal || windowState == WindowState.Maximised)
Not 100% related as this was here already, but I'm super confused by this guard. Does it need to exist?

2020-12-10 20:12 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
Sorry if I wasn't clear, I meant that when the window is restored from initial maximised state by user, it'll restore back to the config values set.

2020-12-10 20:15 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
>              if (windowState == WindowState.Normal || windowState == WindowState.Maximised)
Yes, the `maximised` field should not be overwritten on irrelevant window states, since that field is supposed to save whether the window was maximised in windowed mode or not.

2020-12-10 20:22 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
But if the window is restored, `updateWindowStateAndSize` should surely fire? Why restore on window init if that code is also supposed to do that?

2020-12-10 20:22 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
>              if (windowState == WindowState.Normal || windowState == WindowState.Maximised)
I kinda feel I'd prefer this to be written as

```csharp
switch (windowState)
{
	case WindowState.Normal:
		windowMaximised.Value = false;
		break;

	case WindowState.Maximised;
		windowMaximised.Value = true;
		break;

	// other window states should not be modifying the maximised flag state
}
```

2020-12-11 07:28 UTC, peppy requested changes

2020-12-11 07:28 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
does this not cause a flicker where the window is temporarily visible?

2020-12-11 07:32 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
As expected, this does cause a flicker:

![2020-12-11 16 31 12](https://user-images.githubusercontent.com/191335/101875691-6ba1ce00-3bce-11eb-954c-48b6b48d717d.gif)

2020-12-11 11:15 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
No, the restore is performed externally, not internally where we would have to rely on `updateWindowStateAndSize()`, I'll look through removing the actions invoked there if possible as looks like they misled you.

2020-12-11 11:19 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
I'm not sure I follow. Are you saying that SDL does not currently listen to maximise/restore events? If so why isn't that done to fix this? That sounds like a shortcoming.

Also why do you want to remove anything from `updateWindowPositionAndSize`? Hopefully you're not suggesting that that function should no longer update position and size?

2020-12-12 02:58 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
Looks like I got tricked into thinking that it doesn't flicker (*thanks windows.*)

Unfortunately, I couldn't get to completely get rid of the "initial white flash" issue, but I've limited its duration of occurrence to a number of milliseconds, that's the best I could do. (doesn't look noticeable on a booted windows, and shows for an average of 90ms on VM).

Not sure about the naming of `IGraphicsBackend.ResetBuffer` and the existence of `IWindow.MaxSize` though, only added for helping achieve proper results. Thoughts?

2020-12-12 03:25 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            Size = sizeWindowed.Value;
> Also why do you want to remove anything from updateWindowPositionAndSize? Hopefully you're not suggesting that that function should no longer update position and size?

Yeah, as `SDL_RestoreWindow` should take care of that, but scratch that since we have borderless mode changing the window position and size for doing the 1px hack.

> I'm not sure I follow. Are you saying that SDL does not currently listen to maximise/restore events? If so why isn't that done to fix this? That sounds like a shortcoming.
>
> If the issue is that there is no event to respond to on launch, then I'd be fine with calling the aforementioned function manually at window creation, too, so long as that logic is in one place and not two.

OK so, in the current implementation of SDL window handling, we handle two types of changes:
1. External changes: which could be done by the user resizing the window manually, or maximizing the window by the "maximize" button, or minimizing it, for example. 
 These are handled through windows events by updating our current states with them (check `updateWindowSpecifics()` and the switch cases), as we're not aware of them, and would allow us to handle internal changes properly without being desynced from the window's current state.
2. Internal/programmatic changes: which are done by the consumer/framework changing `WindowState` for example.
 These are handled by performing the required SDL actions for them (`updateWindowStateAndSize()` for the above case).

In the highlighted lines above, the window must be positioned and sized according to the config, such that when the user restores the window (**externally**, not programmatic via `updateWindowStateAndSize()`), they would be restored to the position and size they should be.

I've gone with the way we currently handle SDL window changes here, listening to restore events and changing the window's position and size according to the config by them doesn't sound correct (and would not be easy to handle as an `SDL_WINDOWEVENT_SIZE_CHANGED` event would be sent before the `SDL_WINDOWEVENT_RESTORED` event, also no event on launch)

Hope that clears up everything. (and I hope I haven't misunderstood anything)

2020-12-12 04:23 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
>              if (windowState == WindowState.Normal || windowState == WindowState.Maximised)
Feel free to open a PR on that.

2020-12-13 15:57 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
is it not possible to check whether the window is visible *before* attempting to restore maximised state from config? or otherwise delay the restoration until the window has been made visible?

2020-12-13 20:05 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
The issue here is that `SDL_MaximizeWindow()` makes the window visible regardless of whether it was hidden, therefore bringing back the "initial white content flash" issue.

For some reason even after performing a `glClear()` to the black colour and swapping buffers both before and after the `SDL_MaximizeWindow()` call (doing it after made no changes at all), there's a slight duration (around 100ms) where the window would show all white, not sure if it's because I'm running this in VM though, but I would consider this issue fixed on our side, as both https://github.com/ppy/osu-framework/pull/4089/commits/56b6b729b8a64b67b1bc144b0bebe74b3a3c64f0 and https://github.com/ppy/osu-framework/pull/4089/commits/515f4e2325f5331458cd3cd1563a2b567dbdbcad is all that can be done here.

2020-12-13 20:08 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
i got that part. what i tried to say is, we can check whether the window is hidden, and not try to maximise the window if it is, to prevent the flicker from ever happening in the first place, instead of applying weird hacks to work around that.

2020-12-13 20:09 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
when would the window be maximised then?

2020-12-13 20:21 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
there are events fired on the window showing/hiding (`SDL_WINDOWEVENT_SHOWN`/`SDL_WINDOWEVENT_HIDDEN`). those could maybe work, no?

i don't think using a magic 9999x9999 size (sounds potentially dangerous from a memory standpoint) and exposing a new method to be able to jam in said magic size to "clear to black" does not "a proper way" make.

2020-12-13 23:34 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
> also from the gif attached above, it doesn't even look like it's the actual window contents flickering, but the titlebar of the windiw.

that is from https://github.com/ppy/osu-framework/pull/4089/commits/c5d916e5f0e3b32e60d76f173f06ed778c16b7d5 hiding the window after becoming visible, therefore causing a flicker on startup. I've fixed that by reverting it and looking for an alternative way to do it.

> there are events fired on the window showing/hiding (`SDL_WINDOWEVENT_SHOWN`/`SDL_WINDOWEVENT_HIDDEN`). those could maybe work, no?

this will make the window switch into maximised state, after it has became visible from the first draw, not sure if that's something fine to be staying as-is.

> I think using a magic 9999x9999 size (sounds potentially dangerous from a memory standpoint) and exposing a new method to be able to jam in said magic size to "clear to black" does not "a proper way" make.

oh right, didn't realize that dangerous downside of the 9999x9999 magic..., my bad. I'll experiment more on alternative ways to revert https://github.com/ppy/osu-framework/pull/4089/commits/515f4e2325f5331458cd3cd1563a2b567dbdbcad with.

2020-12-14 01:21 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            updateWindowVisibility(Visible);
It's the whole window appearing for a frame. the gif doesn't capture because it's too low fps wise.

2020-12-19 00:30 UTC, frenzibyte commented
Closing this PR for now as it needs more work and apparently is broken on macOS.

2020-12-19 00:30 UTC, closed without merging