Fix continous resize events no longer handled
ppy/osu-framework pull request #4093
Opened 2020-12-12 16:19 UTC by frenzibyte

Regressed in https://github.com/ppy/osu-framework/pull/4085

The aforementioned PR (by me..) removed the case handling the `RESIZED` event thinking that it gets fired before the SDL has processed it, while it actually gets sent after the `SIZE_CHANGED` event, [as noted there](https://github.com/ppy/osu-framework/pull/4085#issuecomment-742707285).

Turns out that there was an event filter set to listen for it to handle continuous resize events (as `SDL_PollEvent` blocks those), and since the `SDL_WINDOWEVENT_RESIZED` case was removed, these events are no longer handled, causing the window to not update the client size while resizing:
<img src="https://user-images.githubusercontent.com/22781491/101988963-2bb21800-3cae-11eb-89e1-8bf9b3a383a8.gif" width=500/>

This fixes it by updating the client size on those continuous resize events, **but** without saving the new size to config, as we don't know what state the window would end up in once finishing from the external change (i.e. switching to maximised mode, which https://github.com/ppy/osu-framework/pull/4085 was there to fix it).

2020-12-13 15:15 UTC, bdach requested changes

2020-12-13 15:15 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        private void updateWindowSize(bool saveToConfig = true)
Given that this method has only two usages I'm opposed to having this default param. Would propose to split saving to config to a separate method, which the normal event loop will call but the event filter won't.

2020-12-14 06:24 UTC, peppy approved these changes

2020-12-14 07:05 UTC, peppy approved these changes

2020-12-14 07:05 UTC, merged

2020-12-15 04:27 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        storeWindowSizeToConfig();
this breaks switching from borderless to window.