Allow parsing same-type bindables
ppy/osu-framework pull request #4110
Opened 2020-12-26 23:52 UTC by frenzibyte

Fixes a case osu!-side in testing where invoking `ToMod()` on a non-deserialized (manually constructed) `APIMod` instance would attempt to parse a `Bindable`. Upon discussing, parsing `Bindable`s sounds OK to do.

2020-12-26 23:53 UTC, bdach commented
Needs test coverage.

2020-12-27 00:26 UTC, frenzibyte commented
Added, that actually made me realize there's no direct check for different-type bindables. 😄

2020-12-27 00:32 UTC, bdach requested changes

2020-12-27 00:32 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +                        throw new ArgumentException($"Attempting to parse {input.GetType()}, which has differnet value type from {typeof(T)}", nameof(input));
has typo, but in general i'd recommend writing this as

```suggestion
                        throw new ArgumentException($"Expected bindable of type {nameof(IBindable)}<{typeof(T)}>, got {input.GetType()}", nameof(input));
```

2020-12-27 00:32 UTC, bdach commented on osu.Framework.Tests/Bindables/BindableTest.cs
> +            bindable3.Parse(new BindableBool(true));
should also cover not-exactly-same-but-convertible types (`Bindable<int>` and `BindableInt`, etc.), and also things like `Bindable<string>`

2020-12-27 10:16 UTC, frenzibyte commented on osu.Framework.Tests/Bindables/BindableTest.cs
> +            bindable3.Parse(new BindableBool(true));
Does this fulfill what you're suggesting? https://github.com/ppy/osu-framework/pull/4110/commits/1314d13a749de26db437288dec60fe6f96ada6f5

2020-12-27 12:11 UTC, bdach approved these changes
looks fine to me

2020-12-27 17:28 UTC, peppy approved these changes
logical

2020-12-27 17:58 UTC, merged