Fix slider bar crashing upon binding to disabled current
ppy/osu-framework pull request #4118
Opened 2021-01-01 04:58 UTC by frenzibyte

Another issue of https://github.com/ppy/osu-framework/issues/3218, added test step to ensure `SliderBar` never crashes on disabled current again.

Also updates that outdated `instantaneous.Default = current.Default` line into a `current.DefaultChanged += e => instantaneous.Default = e.NewValue`.

2021-01-01 10:24 UTC, bdach commented
In the future, if you're submitting a fix to an issue without explaining how the fix works in the description but providing a test case instead, it would be nice if the commit that has the test case was first in the series, so I can check it out myself and step through the error without having to cherrypick the test onto `master`.

2021-01-01 10:39 UTC, bdach requested changes

2021-01-01 10:39 UTC, bdach commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
Why are these changed? Again, `current` and `currentNumberInstantaneous` should either both be disabled or both enabled, but the former was not used once in this method, and now reads confusingly (`current` is checked for disable but `currentNumberInstantaneous` is actually the bindable that's being changed).

2021-01-01 10:39 UTC, bdach commented on osu.Framework/Bindables/BindableNumberWithCurrent.cs
> +                Disabled = false;
If we're doing this (which I'm not sure if we should be), `BindableWithCurrent` should probably get a similar thing.

2021-01-01 12:11 UTC, frenzibyte commented on osu.Framework/Bindables/BindableNumberWithCurrent.cs
> +                Disabled = false;
good catch, didn't know that existed.

2021-01-01 12:13 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
`currentNumberInstantaneous` has to always be enabled to allow receiving value changes from disabled current without actually falling to a disabled exception, maybe providing an inline comment would help

2021-01-01 12:13 UTC, frenzibyte commented
> In the future, if you're submitting a fix to an issue without explaining how the fix works in the description but providing a test case instead, it would be nice if the commit that has the test case was first in the series, so I can check it out myself and step through the error without having to cherrypick the test onto `master`.

Gotcha.

2021-01-01 12:18 UTC, bdach commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
sounds like a lease might be what's desired here.

2021-01-01 12:21 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
thought about doing so but it seems that `LeasedBindableNumber<T>` is not a thing yet, guess I have to make one?

2021-01-01 12:24 UTC, bdach commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
i guess, but this entire chain of changes is quickly spiraling out of control in regards to the number of actual changes required. this might take weeks to merge.

2021-01-01 12:26 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
yeah..., if there's any way to help in that, then I'll do

2021-01-01 12:42 UTC, peppy requested changes

2021-01-01 12:42 UTC, peppy commented on osu.Framework/Bindables/BindableNumberWithCurrent.cs
> +                // must be re-enabled before binding below, see https://github.com/ppy/osu-framework/issues/3218.
what happens after binding? is it re-disabled?

2021-01-01 12:42 UTC, peppy commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> -                currentNumberInstantaneous.Default = current.Default;
is there any test coverage checking this change works as expected?

2021-01-01 12:42 UTC, peppy commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            // intentionally not updating disabled state to "currentNumberInstantaneous" to handle value changes from disabled current.
this explodes my head. needs rewriting

2021-01-01 12:42 UTC, peppy commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
so what's the reasoning behind this? `currentNumberInstantaneous` is no longer disabled ever?

2021-01-01 12:57 UTC, peppy commented
What crash does this fix? Where was the crash experienced? I'm having trouble following the path of documentation / reasoning here.

2021-01-01 12:57 UTC, bdach commented
Test case added in df011b2 crashes if cherry-picked onto `master`.

2021-01-01 13:03 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> -                currentNumberInstantaneous.Default = current.Default;
well, i've made it do like the others do `DefaultChanged += instantaneous.Default = value`, so thought no test coverage is really needed.

I believe that line was as-is because of no such thing as `DefaultChanged` back when this was implemented.

2021-01-01 14:14 UTC, frenzibyte commented on osu.Framework/Bindables/BindableNumberWithCurrent.cs
> +                // must be re-enabled before binding below, see https://github.com/ppy/osu-framework/issues/3218.
yeah this is basically working around that https://github.com/ppy/osu-framework/issues/3218 issue, will see if I can properly fix the underlying issue or not (https://github.com/ppy/osu-framework/pull/4039 PR'd but tests broken)

2021-01-01 14:15 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            // intentionally not updating disabled state to "currentNumberInstantaneous" to handle value changes from disabled current.
will just remove altogether with a leased `currentNumberInstantaneous` instead.

2021-01-01 14:15 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/SliderBar.cs
> +            if (current.Disabled)
will revert as well.

2021-07-07 14:24 UTC, frenzibyte commented
Closing this PR as the history got pretty dirty and there seems to be multiple different changes fixing separate things without clear explaination...

I'll look back into this and explain it more sanely.

2021-07-07 14:24 UTC, closed without merging