Fix playing back SampleChannels ending previous playbacks
ppy/osu-framework pull request #4139
Opened 2021-01-07 09:18 UTC by peppy

Reverts changes made in #3792. As mentioned in my comment there, cleanup of previous samples is a non-issue since that is handled by bass. The case that PR was fixing (hard to even know without reading the conversation thoroughly) looks to be looping samples, where `Play` is called twice and the previous channel ends up in a permanently playing state. I've added a case to fix that specifically, while allowing standard flow otherwise.

There is an expectation everywhere in the framework that sample playback is limited to provided `SAMPLE_CONCURRENCY`. I believe this expectation should carry through for a single instance of `SampleChannel`, where a new playback should be initialised for each call to play.

This has come up multiple times, but the class `SampleChannel` is named quite badly, since it tries to represent what BASS refers to as a channel, but internally fetches a new channel each playback. We'll probably have to address this at some point. Open to feedback (maybe we can obsolete the `Play` method and add a `bool` specific to whether a new channel should be used or not).

Apart from fixing concurrency, this also fixes weird clipping artifacts when a previous channel is stopped and immediately restarted.

2021-01-07 21:14 UTC, bdach requested changes

2021-01-07 21:14 UTC, bdach commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +        /// Note that this will not stop previous playbacks unless <see cref="Looping"/> is true (but concurrency will be limited by the source <see cref="ISampleStore.PlaybackConcurrency"/>.
This has me confused. If I'm reading correctly, `SampleChannelBass`'s implementation does not have these semantics. If the sample is already playing, it will not start a new playback of the sample at all, but preserve the old playback, correct? (see early-return if `currentChannelPlaying && !restart`)

Is that an oversight with the implementation, or is this xmldoc inaccurate?

2021-01-07 21:16 UTC, bdach commented
If I recall correctly what the original PR intended to fix was looping samples being allowed to play out until the end of the sample if they were stopped mid-loop. This was apparent in the pause overlay; having checked this PR with a framework checkout it looks that case has not regressed with this change (as I expected from reading the diff).

2021-01-08 00:09 UTC, peppy commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +        /// Note that this will not stop previous playbacks unless <see cref="Looping"/> is true (but concurrency will be limited by the source <see cref="ISampleStore.PlaybackConcurrency"/>.
The coded behaviour is correct. I'm open to changes to the xmldoc if you think you can make it read better.

For the record, we use the `restart` parameter nowhere. Removing would be another option. It's actually pretty useless because for it to work, we also need to expose `Bass_ChannelPause`. The `Stop()` method we currently have *always* resets position.

2021-01-08 02:20 UTC, peppy commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +using osu.Framework.Audio.Track;
Seems to be `ISampleStore`. Will move it, but I guess it's a minor breaking change for consumers.

2021-01-08 17:48 UTC, bdach commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +        /// Note that this will not stop previous playbacks unless <see cref="Looping"/> is true (but concurrency will be limited by the source <see cref="ISampleStore.PlaybackConcurrency"/>.
Yeah I don't know if there actually is a way to describe the current behaviour elegantly. It's all weird, because a `Play()` will play the sample, unless it's already playing, in which case it won't do anything and ignore `restart`, unless it's looping, in which case it'll *continue* playing but take `restart` into consideration. Super wonky.

I'm actually not sure if that special weird looping case is even relevant anymore now that we have `ISamplePlaybackDisabler` game-side. In fact I'm going to check that right now. Maybe we can just nuke it and do the sane thing of "play if not playing, restart if restart requested". Maybe `Restart()` should be a separate method even.

2021-01-12 04:27 UTC, peppy commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +        /// Note that this will not stop previous playbacks unless <see cref="Looping"/> is true (but concurrency will be limited by the source <see cref="ISampleStore.PlaybackConcurrency"/>.
I don't think your description here is totally correct: in the case `Play()` is called and the sample is already playing, it *will* play a second time (and doesn't ignore `restart` - it takes it into account and avoids restarting the sample if set to `false`).

2021-01-12 15:53 UTC, bdach commented on osu.Framework/Audio/Sample/ISampleChannel.cs
> +        /// Note that this will not stop previous playbacks unless <see cref="Looping"/> is true (but concurrency will be limited by the source <see cref="ISampleStore.PlaybackConcurrency"/>.
Oh never mind, looks like I misread that conditional in there, you're right.

2021-01-14 04:40 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (!restart)
So if I understand this code correctly, if restarting and not looping then samples will be layered? I don't think a single `SampleChannel` should allow layering itself - a hitcircle playing the same hit `SampleChannel` twice in a row should not play two samples.

2021-01-14 04:42 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (!restart)
Okay, so how would you expect the flow to work for the 99% case, where you expect concurrency as exposed by the sample manager / game?

2021-01-14 04:44 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (!restart)
So, with hover effects as the main example? I'd say you need a new sample channel at that point.

2021-01-14 04:45 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (!restart)
Which means a complete restructure and not using bass concurrency management.

2021-01-14 09:56 UTC, smoogipoo approved these changes
Lgtm, requesting a review from @bdach to see if he agrees with the direction.

2021-01-15 22:10 UTC, bdach commented
Just as a heads up: I don't have an issue with this diff but before I approve I want to suggest improvements to #4148, just to make sure all game-side use cases are taken care of properly. I have queued that up for this weekend.

2021-01-16 00:48 UTC, peppy commented
@bdach do your changes involve changing this PR? if not i think it's fine to get this in on its own (it fixes a separate issue).

2021-01-16 16:56 UTC, bdach commented
I'm not sure what it is but this diff confuses me greatly every time I read it - but I would agree that this is independent from the pull I mentioned and it *seems* like it should be correct. It would be good to have this tested, but that seems infeasible, so I guess I'll just approve and merge for now...

2021-01-16 16:57 UTC, bdach approved these changes

2021-01-16 17:33 UTC, merged