Add IKeyBinding interface type for flexibility in key bindings
ppy/osu-framework pull request #4144
Opened 2021-01-12 04:50 UTC by peppy

This is a prerequisite for my realm `KeyBindingStore` implementation.

When working with realm, it is beneficial to have interfacing defining the underlying model types due to the restrictions on inheritance. I think in general having interfaces for model types like this is a good step forward, regardless.

Probably resulting in a breaking change for rulesets, but not sure that is avoidable (or an issue at this point in development).

2021-01-12 05:15 UTC, frenzibyte commented
Could make `PlatformKeyBindings` also use `IKeyBinding` type as well while at it.

2021-01-12 05:21 UTC, peppy commented
Not sure I can see a reason for doing so. Can you imagine a platform which is specifying key bindings which aren't of a known type? Not really sure such a change should be made without reason.

2021-01-12 05:24 UTC, frenzibyte commented
Was thinking about it from a consistency point of view, but I guess that's a valid reason not to do it, nevermind.

2021-01-12 20:59 UTC, bdach requested changes

2021-01-12 20:59 UTC, bdach commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                newlyPressed = newlyPressed.Where(b => b.KeyCombination.Keys.All(KeyCombination.IsModifierKey));
won't this change to a method group cause per-call allocations, as per the preceding comment? may be the case that we don't care, but if we don't, then the comment should be trimmed.

2021-01-13 00:43 UTC, peppy commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                newlyPressed = newlyPressed.Where(b => b.KeyCombination.Keys.All(KeyCombination.IsModifierKey));
Good catch. Not sure why this got changed, I think somewhere along the way it became a warning somehow..

2021-01-13 05:30 UTC, bdach approved these changes

2021-01-14 03:43 UTC, smoogipoo approved these changes

2021-01-14 04:06 UTC, merged