Add a method of retrieving sample channels which can layer multiple playbacks
ppy/osu-framework pull request #4148
Opened 2021-01-14 05:46 UTC by peppy

2021-01-14 05:53 UTC, smoogipoo requested changes

2021-01-14 05:53 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (PlayStopsPreviousPlayback)
I think this should wrap the entire thing, such that if `playing && !restart` then it also plays a new channel.

2021-01-14 05:53 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +        internal bool PlayStopsPreviousPlayback;
Name/value is inversed, which results in the conditions also appearing inversed.

2021-01-14 05:53 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (PlayStopsPreviousPlayback && Looping)
I'd add this check to `Looping.set` instead and seal the override.

2021-01-14 05:56 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (PlayStopsPreviousPlayback)
throw instead maybe?

2021-01-14 05:57 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (PlayStopsPreviousPlayback && Looping)
I'll leave it here as well, just as a safety measure.

2021-01-14 05:59 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    if (PlayStopsPreviousPlayback)
if `restart = false`? Yeah I think that's probably fine since it's not the default parameter.

2021-01-14 10:16 UTC, smoogipoo requested changes

2021-01-14 10:16 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (!PlayStopsPreviousPlayback)
The inverted condition here in combination with the field name is particularly hard to read.

I suggest renaming the field to:
```csharp
/// <summary>
/// Whether each invocation of <see cref="Play"/> results in a new (potentially concurrent) playback.
/// </summary>
internal bool ConcurrentPlayback;
```
And inverting conditions like this.

2021-01-14 10:16 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (!IsDisposed && PlayStopsPreviousPlayback)
This is very unfortunate...

2021-01-14 10:16 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleBass.cs
> +        internal volatile int SampleId;
```suggestion
        internal int SampleId { get; private set; }
```

2021-01-14 10:23 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (!IsDisposed && PlayStopsPreviousPlayback)
well it's not going to work as expected either way. you'd hope it stopped *all* playbacks in a layered context, right? not sure we want to go that deep though.

if we just want to avoid this conditional, could make a protected stop implementation and bypass the exceptions.

2021-01-14 10:25 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (!PlayStopsPreviousPlayback)
Yep, got halfway through doing this, will change.

2021-01-14 10:25 UTC, peppy commented on osu.Framework/Audio/Sample/SampleBass.cs
> +        internal volatile int SampleId;
are we okay with dropping the volatile here?

2021-01-14 10:52 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleBass.cs
> +        internal volatile int SampleId;
It shouldn't make a difference because the only external multi-threaded use-case is via `IsLoaded` which shouldn't care about a read being reordered before the first write, otherwise it would have other problems like trying to make sure the audio thread is running completely synchronously. Means at the worst case it'll read `IsLoaded = false` slightly before `IsLoaded = true`.

Something to note which I also just noticed, we're not setting this to 0 in `Dispose()`. Probably want to do that so `IsLoaded` becomes `false` if disposed...

2021-01-14 11:21 UTC, peppy commented on osu.Framework/Audio/Sample/SampleBass.cs
> +        internal volatile int SampleId;
Have applied both, seems logical.

2021-01-14 11:36 UTC, smoogipoo approved these changes

2021-01-14 11:36 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            if (!IsDisposed && PlayStopsPreviousPlayback)
Correct, I'd expect it to stop all playbacks in a layered context, but as you said that's quite a large level of complexity. I think the use of layered playbacks is small enough that this shouldn't be much of an issue...

2021-01-14 16:29 UTC, bdach commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            }
So I'm not sure where to add comments with this entire pull chain going on because it's really one huge blob at this point and everything affects everything, but I guess this is the most apt place. I personally very much don't like this API. `ConcurrentPlayback` getting set to `true` pretty much forces these two other flags' values and callers have to be unreasonably careful to not upset this at runtime. Similarly the throw in `Stop()` is suspect to me, for the same reason.

If you ask me - I'm fine with having `Get()` and `GetLayerable()` in concept, number of usages be damned - as they really *do* have different semantics. The first is expecting a more "track-like" behaviour, wherein the sample has duration and you want to make sure you are able to loop it, not double-play it, etc. etc., and what this PR is aiming to add is a more "sample-like", fire-and-forget... sample? Which is totally fine by me and probably even correct I'd say.

But I very much don't like the way this is written right now, because now the two share common API without actually *having* a sane common API, and you have to be immediately very careful what you're calling on what instead of just *not being able to call it*, because the code won't compile otherwise. If we do go down this path, I really think there really ought to be a `LayeredSampleChannel` or something, that's fully separated out of this, and has only declared operations/flags that are actually valid for it.

2021-01-17 16:54 UTC, bdach commented on osu.Framework/Audio/Sample/SampleChannel.cs
> +            }
To put some money where my mouth is, here's a commit that feels like a slight improvement to me in this regard: https://github.com/ppy/osu-framework/commit/0e23f8fd25e633732558a4018e03c508ceca5132

It's not perfect, unfortunately. A few throws are still left in `SampleChannelBass` - would have to split that into two too to get rid - but it's not intended for direct usage so maybe fine...?

2021-01-18 10:57 UTC, smoogipoo commented
It becomes a bit of a mess. I took a stab at it myself, and while I've gotten the osu!framework-side to look like the following:
```csharp
sample = store.Get(name); // SampleChannel (or an ISampleChannel)
sample.Play(); // Compiles
sample.Play(false); // Does not compile
sample.Stop(); // Does not compile
sample.Looping = value; // Does not compile

//

sample = store.GetNonConcurrent(name); // INonConcurrentSampleChannel
sample.Play(); // Compiles (=> Play(true))
sample.Play(false); // Compiles
sample.Stop(); // Compiles
sample.Looping = value; // Compiles

// Note: I took the non-concurrent route in the hopes to reduce the changes in https://github.com/ppy/osu/pull/11482. It _should_ be invertible.
```
... the osu!-side changes look very, very, exceedingly bad. To the point where the same "NonConcurrent" moniker has to be applied to SkinnableSound, PoolableSkinnableSample, ISkin/Skin (including transformers, all derived types, skin providing container, and skinmanager), and many other miscellaneous tests.

There are ways you can probably clean things up a bit - like for example exposing `GetNonConcurrent()` as an extension method that returns a wrapped `SampleChannel` providing the extra methods and could clean up the store implementations, but that doesn't help with any of the usages of `SampleChannel`s that I've mentioned above.

I can't think of a way to make the fully-separate route pretty, however nice that sounds from an OOP sense. I'm even starting to consider removing the `GetLayerable` method and having it be part of the `SampleChannel` in the first place. Furthermore, I'd probably accept `ConcurrentPlayback = true` by default to reduce the changes seen osu!-side.

2021-02-15 09:17 UTC, closed without merging