Non concurrent sample playback
ppy/osu-framework pull request #4161
Opened 2021-01-19 09:35 UTC by smoogipoo

Alternative to / closes https://github.com/ppy/osu-framework/pull/4148.

PRing for visibility in-case anyone wants to early review. It's ready to go except for:
1. Documentation.
2. Adding a `.With()` method to `SampleChannel`.
3. Making `AudioComponent.Looping` protected OR moving it out of `AudioComponent` (it's very weirdly placed).
4. Some testing.

* `SampleStore` contains a set of `SampleBassFactory`s, a unique factory for each sample name.
* `SampleBassFactory` holds the sample ID and provides the `CreateSample()` method. This object is hidden from the user.
* `Sample`, the return value of `SampleBassFactory.CreateSample()`, is what is returned to the user by `SampleStore.Get()`.
  * This is a pretty dumb object by itself, containing only a `Play()` method.
 * `SampleChannel` is the return value of `Sample.Play()`, representing a single playback of the sample in a dedicated BASS channel.
   * This is the object which now provides functionality to `Stop()`, or set `Looping`.
```
  (public)        (internal)       (public)    (public)

                                 |> Sample |> SampleChannel
            |> SampleBassFactory |
            |                    |> Sample
            |
            |> SampleBassFactory |> Sample |> SampleChannel
            |                              |> SampleChannel
            |                              |> SampleChannel
SampleStore |                              |> SampleChannel
            |
            |> SampleBassFactory |> Sample
            |
            |                    |> Sample
            |> SampleBassFactory |> Sample |> SampleChannel
                                 |> Sample
```
Example:
```csharp
var sample = samples.Get("name");

// Play a looping channel.
var channel = sample.Play();
channel1.Looping = true;

// Play a normal channel concurrently.
// A new channel is returned, but playback will only be heard concurrently up to SampleStore.PlaybackConcurrency times.
var channel2 = sample.Play();

// Affects all channels from the sample.
sample.Volume.Value = 0.5;

// Stop channel 2, but keep channel 1 playing.
channel2.Stop();

// Apply an independent volume adjustment to channel 2
// The final value will be 0.5 (sample) * 0.5 (channel) = 0.25;
channel1.Volume.Value = 0.5;

// Disposes the sample and all channels, halting playback.
sample.Dispose();
```

A big tossup I had was whether each call to `SampleStore.Get()` should return a new `Sample` instance. This is the case in the end. The common member of all `Sample`s is the internal `SampleBassFactory` that owns the sample ID. There's a few reasons for this.

If `Sample` owns the sample ID, then it should follow that `Sample` should be the one to clean it up on disposal, but `Sample.Dispose()` is unsafe from a consumer as it will permanently break that `Sample` for any further and existing usages. A contributing factor to this is that `SampleStore` would have to cache the `Sample` instances in order to achieve this, and would need additional provisions to allow "refreshing" the cache on disposal, however other usages of the sample would still remain broken.

The second reason is that having `Sample` inherit from `AdjustableAudioComponent` is useful so that it can be used as a parameter to `DrawableAudioWrapper` (from `DrawableSample`). It's possible to work around this by adding `DrawableSampleChannels` internally to the `DrawableSample` every `Play()`, but it gets very messy to do so.  

Finally, I see `Sample` being adjustable itself potentially reducing the amount of state handling that needs to be done by the user, for example in cases where samples are layered and e.g. balance is updated every update frame.

2021-01-19 22:37 UTC, bdach commented
I couldn't find enough time in the day today to look at this properly, but I've scrolled through the description and some usage code, and I'm still definitely on board with this. Will have a proper look through in the coming days, hopefully, if the overall traffic is merciful.

2021-01-20 04:35 UTC, smoogipoo commented
This PR is now ready, I've updated the PR description.

2021-01-20 13:22 UTC, frenzibyte commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Bass.SampleSetInfo(SampleId, sampleInfo);
Have dug through this, and finally found the reason. :p

Firstly checked to ensure that it doesn't happen on a simple C project, and it indeed doesn't happen there and works perfectly fine.

Then I started fiddling around with an isolated version of this in C#, until I found out that `ManagedBass` is likely to be at fault, as using [radio42's `Bass.NET` wrapper](http://bass.radio42.com/) and calling `SampleGetInfo` works correctly in there.

After checking through `ManagedBass`'s way of doing so: 
![image](https://user-images.githubusercontent.com/22781491/105178348-f0222d80-5b38-11eb-8cf6-ff35cc527d50.png)

and looking back at the native code's declaration:
![image](https://user-images.githubusercontent.com/22781491/105180228-5445f100-5b3b-11eb-80b2-fc7f3cee6148.png)


According to my knowledge, and [the docs with their near-equivalent sample](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-classes-structures-and-unions#systime-sample), `ManagedBass`'s method prototype is incorrectly declared, reference types are already pointers by themselves, what it should've been is:
```csharp
public static extern bool SampleGetInfo(int Handle, [In, Out] SampleInfo info);
```

(out attribute for indicating that changes to sample info by unmanaged code are expected)

Tested it and it indeed works now, I'll open a PR for that on their side, not sure how active they are these days but we'll see.

2021-01-20 13:29 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Bass.SampleSetInfo(SampleId, sampleInfo);
Good stuff. They're pretty active, but we're still yet to update to ManagedBass 3.0.0 due to lack of testing / it not working on mobile platforms due to the removal of dllmap.

2021-01-21 04:21 UTC, peppy commented
What happens if a sample finishes before `.Looping = true` is run? It's a pretty edge case, but seems like a potential oversight.

A more common one may be setting the volume on a playback, but the sample begins playing at full volume for a brief moment before the change has propagated.

2021-01-21 05:33 UTC, smoogipoo commented
Both are very good points... I'm not entirely sure how to address those issues at the moment, so I need to mull over it a bit.

I'd like to avoid having `.Play()` on `SampleChannel` or in any place where it can be called multiple times and be required to throw an exception the second time around (e.g., was also considering exposing `CreateChannel()` which you could `.Play()` at the right time).

I'm thinking something along the lines of a `PlayWith(bool? looping, ...)` method. Would like for the process to be `.Play().With(looping: true)` but I don't know if that's possible...

2021-01-21 05:35 UTC, peppy commented
What about the case where you want to play a channel a second time? Or when you stop a looping channel but want to start it again?

2021-01-21 05:37 UTC, smoogipoo commented
Are you referring to pausing and continuing of channels? That can't happen, it makes no sense in terms of concurrency. If you want that then we can't use BASS concurrency at all.

2021-01-21 05:50 UTC, smoogipoo commented
I suppose it can work... So you're imagining the usage being:

```
var sample = sampleStore.Get(...);
var channel = sample.GetChannel();
channel.Play();
channel.Stop();
channel.Play(); // Resumes the channel from the last position, or restarts if it's at the end.
```

2021-01-21 05:51 UTC, peppy commented
I am, yeah. This was previously supported by our API, and no longer is.

There's one usage of precisely this (stopping the spinner looping sound and resuming from the point it was stopped).

2021-01-21 05:52 UTC, peppy commented
Is there a reason for not making the restart optional, like we have on `master`?

2021-01-21 05:55 UTC, smoogipoo commented
No reason, I'll see how the changes feel.

2021-01-22 01:20 UTC, smoogipoo commented
Also noticed one more issue with this which is that it's likely very leaky as `Sample`s are added to the collection but never removed.

2021-02-12 10:04 UTC, smoogipoo commented
I think I've covered all issues mentioned above now, and updated the PR description.

`TestTogglePlaying` is audibly broken on master regardless of `restart = false` - it will always restart the sample since `Stop()` frees the sample. It doesn't fail the test, but making it fail the test is quite a lot of trouble. This is fixed in this PR.

However I need feedback on a particular edge-case. When the sample reaches the end, a call to `Play()` will restart the sample. There's no special handling for this - I'm just calling `Bass.ChannelPlay()` and it's just how BASS works internally. `TrackBass` has custom logic for stopping the restart in this case, so if that's the more desirable option, I can add similar logic here.

As for setting `Looping`,`Volume`, etc - now that the `GetChannel()` method exists I think it's reasonable for the user to expect that a sample could have stopped playing between a .`Play` and `.Looping` adjustment, or could have started playing between a `.Play()` and `.Volume` adjustment.
Such properties can be set via the `GetChannel()` method, prior to `.Play()`.

2021-02-14 14:28 UTC, bdach commented
I think not allowing a completed sample playback to play again is the better option, for two reasons:

* Consistency with `TrackBass`
* Given now we have proper sample channels, which are single-use "playback objects", then a single use of a non-looping sample implies it should not be possible to start it again

The various adjustments (looping/volume) seem fine to be potentially racey to me. The API should be clear enough that the user should be expecting to set these before firing a playback.

2021-02-14 14:30 UTC, bdach commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
For what it's worth upstream has merged this now, but no release yet.

2021-02-15 05:44 UTC, smoogipoo commented
> I think not allowing a completed sample playback to play again is the better option

I can't disagree with any of the reasons provided, so I've done it. The only weirdness is it can't use the same process as `TrackBass` because `ChannelSetSync()` seems to not be applicable to sample channels (only streams, rather confusingly).

2021-02-15 08:30 UTC, peppy commented on osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
> +                channel.Frequency.Value = 1 + Y / notes;
isn't this wrong? the sample will potentially start with the wrong frequency?

2021-02-15 08:33 UTC, peppy commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
so while this is broken, what behaviour do we actually get? is it using some global value still? or is this going to regress playback?

2021-02-15 08:37 UTC, peppy commented on osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
> +                channel.Frequency.Value = 1 + Y / notes;
I think this can be resolved by changing it to

```csharp
                var channel = sample.GetChannel();
                channel.Frequency.Value = 1 + Y / notes;
                channel.Play();
```

2021-02-15 08:52 UTC, peppy requested changes

2021-02-15 08:52 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +            // If the the audio thread were to update and see the channel not playing, it would reset the playing state and remove the channel from the audio thread's visibility.
```suggestion
            // If the audio thread were to update and see the channel not playing, it would reset the playing state and remove the channel from the audio thread's visibility.
```

2021-02-15 08:52 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +            // Notify to Sample/SampleBassFactory that this channel has come alive.
```suggestion
            // Notifies Sample/SampleBassFactory that this channel has come alive.
```

2021-02-15 08:52 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    case PlaybackState.Paused when userRequestedPlay:
if you're going to use `when` here (would probably prefer not doing so) why not combine with the above case?

2021-02-15 09:00 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    case PlaybackState.Paused when userRequestedPlay:
> if you're going to use `when` here

Personally I find the switch statement easier to read, and this is as simple as the condition is going to get without explicitly mentioning the stalled case:
![image](https://user-images.githubusercontent.com/1329837/107925356-ae5d9900-6fb7-11eb-8c63-64cde17bc45d.png)

2021-02-15 09:06 UTC, peppy commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    case PlaybackState.Paused when userRequestedPlay:
yeah, that's what i was proposing. i think that sits better than splitting them out?

2021-02-15 09:07 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleChannelBass.cs
> +                    case PlaybackState.Paused when userRequestedPlay:
I've already done that in the latest commit, the comment above was only directed towards the use of `when`.

2021-02-15 09:07 UTC, peppy approved these changes
There's a lot of threading logic changes here but it looks to be pretty good (at least the API is something I can get behind now). Let's get this out in a release for testing further.

2021-02-15 09:17 UTC, merged

2021-02-15 09:18 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
it's just not going to support per-`Sample` playback concurrency. the `ISampleStore` one will always be used at the point when the sample is initialised, like on current master.

2021-02-15 09:19 UTC, peppy commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
Think it's worth adding a note on the property until this is fixed? Maybe not considering it's a new API and likely used by noone.

2021-02-15 09:20 UTC, smoogipoo commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
Will do

2021-02-15 09:20 UTC, peppy commented on osu.Framework/Audio/Sample/SampleBassFactory.cs
> +                // Broken in ManagedBass (https://github.com/ManagedBass/ManagedBass/pull/85).
or just note expose it until it's working?