Fix key combination ordering
ppy/osu-framework pull request #4165
Opened 2021-01-22 08:18 UTC by vinaqq

Fixes #4153
 
- Introduce OrderAttribute from osu.Game
- To avoid adding an order to all `InputKeys`,  an `AllowPartialOrdering` flag was added on the `HasOrderedElements` to allow for only certain member to define a custom order as the current implementation of `GetValuesInOrder` would throw an exception.
- Added simple tests to verify correct ordering of KeyCombination

2021-01-23 13:30 UTC, bdach requested changes

2021-01-23 13:30 UTC, bdach commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +            Keys = keys?.Any() == true ? OrderAttributeUtils.GetValuesInOrder(keys.Distinct()).ToImmutableArray() : none;
I don't think this is a good spot to put this sort in, for several reasons:

* The `OrderAttribute` sorting logic heavily uses reflection, so I don't know that it is a good idea from a performance standpoint to be calling that logic every time a key combination is constructed.
* Moreover, `KeyCombination.FromInputState()`, which is mentioned in the xmldoc to this method (and is the optimised path), now sorts in a different way to this. Seeing that `KeyCombination.Equals()` uses sequence equality, I imagine this breaks things.

If you ask me this sort should *only* be done locally for display purposes in `ToString()`/`ReadableString()`.

2021-01-23 13:30 UTC, bdach commented on osu.Framework/Utils/OrderAttribute.cs
> +                throw new InvalidOperationException("T must be an enum");
I know it was like this game-side, but it was arguably unhelpful/wrong - comments to this file are just fixes that we might as well go ahead with while we're moving things around

```suggestion
                throw new InvalidOperationException($"{typeof(T)} must be an enum");
```

2021-01-23 13:30 UTC, bdach commented on osu.Framework/Utils/OrderAttribute.cs
> +                throw new InvalidOperationException("T must be an enum");
```suggestion
            if (!type.IsEnum)
                throw new InvalidOperationException($"{typeof(T)} must be an enum");
```

2021-01-23 13:30 UTC, bdach commented on osu.Framework/Utils/OrderAttribute.cs
> +                throw new ArgumentException($"Not all values of {nameof(T)} have {nameof(OrderAttribute)} specified.");
```suggestion
                throw new ArgumentException($"Not all values of {typeof(T)} have {nameof(OrderAttribute)} specified.");
```

`nameof` is compile-time and does not work with generics

2021-01-23 13:30 UTC, bdach commented on osu.Framework/Utils/OrderAttribute.cs
> +        /// </summary>
```suggestion
        /// <summary>
        /// Allow for partially ordering <see cref="Enum"/> members.
        /// Members without an <see cref="OrderAttribute"/> will default to their value as ordering key.
        /// </summary>
```

2021-01-23 17:11 UTC, bdach commented
Oh and needless to say, if this goes in, the game-side class should be removed.

2021-01-23 23:19 UTC, vinaqq commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +            Keys = keys?.Any() == true ? OrderAttributeUtils.GetValuesInOrder(keys.Distinct()).ToImmutableArray() : none;
Thank you for the feedback @bdach. 
As you suggested I moved the sorting to ToString() and ReadableString().

2021-01-24 14:37 UTC, bdach commented
I made a mistake in suggesting that the sort should be applied to `ToString()` - that would be a breaking change. It should only be in `ReadableString()`; I'll fix that now.

(I'll also fix the tests since they aren't really asserting that this change works, more like asserting that the keys were sorted. Therefore I'm pretty sure that test as written would also pass on `master`.)

2021-01-24 15:13 UTC, bdach submitted a review, later dismissed

2021-01-24 15:35 UTC, peppy commented on osu.Framework/Extensions/EnumExtensions/OrderedEnumExtensions.cs
> +namespace osu.Framework.Extensions.EnumExtensions
Is there a reason we put these in their own namespace (this isn't the only case)? Seems pointless when most are single file implementations.

2021-01-24 15:37 UTC, peppy requested changes

2021-01-24 15:37 UTC, peppy commented on osu.Framework/Extensions/EnumExtensions/OrderedEnumExtensions.cs
> +    public static class OrderedEnumExtensions
Shouldn't this just be `EnumExtensions`? I think that's generally the standard naming schema for extension methods.

2021-01-24 15:37 UTC, peppy commented on osu.Framework/Utils/OrderAttribute.cs
> +    public class OrderAttribute : Attribute
probably deserves xmldoc. i know that `Order` attributes exist in at *least* one other place in database abstractions (or dotnet itself?) so it would be good to know why we have our own (and when it should be used).

2021-01-24 15:51 UTC, bdach commented on osu.Framework/Extensions/EnumExtensions/OrderedEnumExtensions.cs
> +namespace osu.Framework.Extensions.EnumExtensions
I don't know, I mostly did this to follow precedent.

2021-01-25 06:47 UTC, peppy approved these changes

2021-01-25 06:47 UTC, merged