Fix ModelBackedDrawable not applying transforms on reloaded wrapper
ppy/osu-framework pull request #4167
Opened 2021-01-23 16:57 UTC by frenzibyte

Closes #3318

Previously if `finishLoad(wrapper)` is called in the case of a DLUW reload, the method will early-return without applying fade in transforms to the wrapper. 

This PR changes it to do so, now it'll always hide and apply show transforms when a drawable is loaded/reloaded, and if there is a previous displayed drawable different from the new one, then hide and expire it.

Also added proper test coverage for unloading MBDs, along with a [failing test case which this PR fixes](https://github.com/ppy/osu-framework/blob/7ec51b3486d306f362e5011d8b1eb6108fe0819d/osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs#L72-L85).

---

I was initially going to inject test coverage into `TestSceneModelBackedDrawable` but realized it's actually completely unfriendly with drawable unloading and reloading (each created `TestModel` provides a drawable, instead of the other direction).

Was gonna attempt to refactor that test scene into being friendly but I realized it's just a waste of time instead of writing a new fresh test scene with DLUW in mind.

2021-01-23 17:06 UTC, bdach commented on osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
> -            // In this case, we do not want to transform/expire the wrapper
By the comment it looks as if this was explicitly stated as intended. This PR has no explanation as to why you would need to change this and whether removing this special case doesn't break some existing use cases.

2021-01-23 17:28 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
> -            // In this case, we do not want to transform/expire the wrapper
Thought it was unnecessary given that really this PR is just applying a show transform to a drawable, but that's fair I suppose.

The second line of that comment indicated to me that the wrapper which is currently displayed shouldn't get hidden and expire in the case of a DLUW reload, but seems it's bad of me not to discuss it. 

@smoogipoo as you're the writer of this comment (in https://github.com/ppy/osu-framework/pull/2467), did you intend that drawables reloaded via DLUW must not have show transforms applied to them?

As for existing use cases, there is really one use case that is suffering from this issue `UpateableBeatmapBackgroundSprite`, there's another MBD+DLUW usage but for some reason it's applying the transform from inside the content drawable, ignoring MBD's feature of doing so.

2021-01-25 12:13 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
> -            // In this case, we do not want to transform/expire the wrapper
I don't remember the case that led to my comment there. It's possible that the internals of DLUW have changed so much over time that the comment can be invalidated.

2021-05-10 10:30 UTC, smoogipoo requested changes

2021-05-10 10:30 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
> -            // In this case, we do not want to transform/expire the wrapper
Well the reason for this is MBD + DLUW inside scrolling containers. But I think this makes sense - all usages of raw DLUW already have a `d.OnLoadComplete += d => d.FadeInFromZero(X)`.

2021-05-10 10:30 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
> +            if (displayedWrapper != null && displayedWrapper != wrapper)
Please add the comment back here, regarding expiry.

2021-05-10 20:21 UTC, bdach commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +            AddWaitStep("wait for potential load", 5);
On its own maybe it wouldn't be so weird, but mixed with the wait steps it sort of implies that there's a link or dependency when reading the test, while in fact there is none.

2021-05-10 20:22 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +            AddWaitStep("wait for potential load", 5);
Aha, I see.

2021-05-16 13:09 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +            AddWaitStep("wait for potential load", 5);
Should be better now, check it out.

2021-05-17 07:36 UTC, smoogipoo submitted a review, later dismissed
This looks fine imo. @peppy will await your review.

2021-05-17 07:53 UTC, peppy commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +    [System.ComponentModel.Description("MBD behaviour with unloading wrapper")]
i really dislike using these arbitrary acronyms in code/comments.

2021-05-17 08:04 UTC, smoogipoo approved these changes

2021-05-17 08:06 UTC, peppy approved these changes

2021-05-17 08:09 UTC, bdach commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +    [System.ComponentModel.Description("MBD behaviour with unloading wrapper")]
I'd go a step further and say that these sorts of descriptions say about as much as the class names, if not less - so at that point you might as well make do without.

2021-05-17 08:13 UTC, peppy commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +    [System.ComponentModel.Description("MBD behaviour with unloading wrapper")]
already gone :)

2021-05-17 08:38 UTC, merged

2021-05-17 08:53 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +    [System.ComponentModel.Description("MBD behaviour with unloading wrapper")]
We may want to do the same everywhere across the codebase, to avoid this from happening again later on. (as I wasn't going to use acronyms until I noticed they're already used in the project)

2021-05-17 08:54 UTC, peppy commented on osu.Framework.Tests/Visual/Drawables/TestSceneUnloadingModelBackedDrawable.cs
> +    [System.ComponentModel.Description("MBD behaviour with unloading wrapper")]
Go for it. The only other I could find immediately was DLUW, which i also disagree with.