Fix TextureStore and ResourceStore locks being held globally across all lookups
ppy/osu-framework pull request #4197
Opened 2021-02-16 13:23 UTC by peppy

- [ ] Add test coverage

PRing this for feedback. I believe the code could be further simplified by using `Task.Run` instead of `TaskCompletionSource`, but in an effort to not add more new unknowns I went with this to avoid TPL usage.

Closes ppy/osu#11141.

2021-02-16 19:56 UTC, bdach requested changes
Other than the one comment (the other is more of an observation) I don't believe I see much wrong with the code. Tests would definitely be a plus, however.

2021-02-16 19:56 UTC, bdach commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +                    retrievalCompletionSources[name] = (tcs = new TaskCompletionSource<Texture>()).Task;
I don't believe using `name` (as opposed to `key`) is entirely correct. The same asset with a different wrap mode results in a slightly different texture on the atlas, after all.

Using `name` could lead to erroneous reads from task completion sources that request the same asset with a different wrap mode.

2021-02-16 19:56 UTC, bdach commented on osu.Framework/IO/Stores/ResourceStore.cs
> +            lock (stores) return stores.ToArray();
A loose thought about these allocs - I'm not sure it'll matter much, but a way to reduce these might be to have `{Add,Remove}Store` take the allocs by creating a copy of `stores` inside, having them mutate the copy to their hearts' contents, and then storing back the list reference atomically.

Most likely not a huge deal, but adding/removing stores should be an even rarer operation than querying for resources.

2021-02-17 02:22 UTC, peppy commented on osu.Framework/IO/Stores/ResourceStore.cs
> +            lock (stores) return stores.ToArray();
Yeah, that might be a good direction, although you would hope that retrievals from stores are seldom enough that the alloc overhead is non-important. Given it only happens right now in cache failures (ie. there's always a store in front of a resource store to cache things) I'm on the fence whether we should change this now. @smoogipoo thoughts?

2021-02-17 05:02 UTC, smoogipoo commented on osu.Framework/IO/Stores/ResourceStore.cs
> +            lock (stores) return stores.ToArray();
Hmm... I was going to say it's fine given the rarity of resourcestore ever holding more than 1-2 nested stores, but then I realised that FontStore is a thing, which in the case of osu! has 13 nested stores. It's still at worst only ~100kb per second at 1000FPS but it's probably worthwhile to optimise the retrieval path as suggested.

2021-02-17 05:03 UTC, peppy commented on osu.Framework/IO/Stores/ResourceStore.cs
> +            lock (stores) return stores.ToArray();
when doing what though? retrieving hundreds of new glyphs constantly every frame without any caching? is this actually a valid use case?

2021-02-17 05:05 UTC, peppy commented
Turns out this new flow actually breaks `LargeTextureStore`, due to the texture being returns via the task result rather than being fetched via `TryGetCached` each time. Will need to revert the `Task`s to non-generic versions.

2021-02-17 05:08 UTC, smoogipoo commented on osu.Framework/IO/Stores/ResourceStore.cs
> +            lock (stores) return stores.ToArray();
True, I missed that it's backed by a TextureStore. I think this is fine as is then.

2021-02-17 18:17 UTC, bdach submitted a review, later dismissed

2021-02-18 11:07 UTC, smoogipoo requested changes

2021-02-18 11:07 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +            lock (retrievalCompletionSources)
I can imagine a scenario where two threads reach this, one passes through, completes the entire rest of this method, completes the `finally`, removes the key from `retrievalCompletionSources`, and only then does the second one take the exclusive lock, which proceeds to fall through to the uncached path.

I believe this needs a `TryGetCached()` call inside it? Perhaps by moving the one above this block inside it.

2021-02-18 12:11 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +            lock (retrievalCompletionSources)
Sounds fair.

The original code had the initial lookup outside the lock, do you think it's worth maintaining that? Or just presuming this lock is going to be pretty low contention and moving it inside.

2021-02-18 12:26 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +            lock (retrievalCompletionSources)
It should be low enough contention  that it doesn’t matter.

2021-02-19 01:26 UTC, smoogipoo approved these changes
lgtm now

2021-02-19 01:28 UTC, merged