Fix text builder not invalidating on indirect relative size changes
ppy/osu-framework pull request #4249
Opened 2021-03-02 20:41 UTC by bdach

Resolves https://github.com/ppy/osu-framework/issues/4248.

As it turns out this was covered by framework tests, but only visually. I've hacked up something not-overly-pretty that will fail a test if this breaks again.

Not entirely sure I did this 100% correctly. It seems to work at least, but `DrawSize` might not be enough? I'm always confused by those flags.

Also this will technically invalidate `DrawSize` twice when setting `Width`/`Height` (once via base, once via the manual `invalidate(true, true);` call), but I wasn't sure if I should trim it and explain with a comment, and it shouldn't have any performance impact anyways.

Figured I'd open this for the test, at the very least.

2021-03-03 02:55 UTC, peppy submitted a review, later dismissed

2021-03-03 03:29 UTC, smoogipoo requested changes

2021-03-03 03:29 UTC, smoogipoo commented on osu.Framework/Graphics/Sprites/SpriteText.cs
> +        private readonly LayoutValue<TextBuilder> textBuilderCache = new LayoutValue<TextBuilder>(Invalidation.DrawSize);
I think this will trigger a second time for autosized texts? Probably needs `InvalidationSource.Parent`

2021-03-03 04:01 UTC, bdach commented on osu.Framework/Graphics/Sprites/SpriteText.cs
> +        private readonly LayoutValue<TextBuilder> textBuilderCache = new LayoutValue<TextBuilder>(Invalidation.DrawSize);
Good point. I'll add test coverage for it and check, but I'm pretty sure you're right.

2021-03-03 19:21 UTC, bdach commented on osu.Framework/Graphics/Sprites/SpriteText.cs
> +        private readonly LayoutValue<TextBuilder> textBuilderCache = new LayoutValue<TextBuilder>(Invalidation.DrawSize);
I wasn't able to come up with a test that would indeed trigger this twice, but I did see several reasons for making this change, namely:

* the obvious - less invalidations = better
* it passes the new test
* `Width` and `Height` invalidate manually anyway
* other `LayoutValues` in this class also combine `DrawSize` with `Parent`
* judging by `Drawable.invalidateParentSizeDependencies()` it does seem to make sense to ignore invalidations from self, if I'm understanding it correctly

So I've just made the change. If it plays up in some other edge case I guess we'll revisit.

2021-03-04 01:20 UTC, smoogipoo approved these changes
Makes sense to me

2021-03-04 01:24 UTC, smoogipoo commented on osu.Framework/Graphics/Sprites/SpriteText.cs
> +        private readonly LayoutValue<TextBuilder> textBuilderCache = new LayoutValue<TextBuilder>(Invalidation.DrawSize);
Yeah it's pretty hard to test layout, and your reasoning is sound. `Drawable.invalidateParentSizeDependencies()` is only an optimisation for `BypassAutoSizeAxes` though.

2021-03-04 03:28 UTC, merged