Remove the majority of osuTK support
ppy/osu-framework pull request #4267
Opened 2021-03-09 11:22 UTC by peppy

Still remaining in some places for mobile platforms, which will continue to use it into the future.

Tested on iOS to work as expected. Pending android confirmation.

- [ ] Loosely depends on #4264, but for no reason apart from the order in which this should probably be merged (as to not reduce input functionality).

2021-03-09 11:51 UTC, frenzibyte commented
Android does work as expected, testing with the sample game and osu!framework tests.

2021-03-11 00:51 UTC, peppy commented on osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
> -    public class TestSceneBorderless : FrameworkTestScene
it cast the window at the beginning of all of its code. decided too much effort to bring it across.

2021-03-11 04:34 UTC, peppy commented on osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
> -    public class TestSceneBorderless : FrameworkTestScene
It's actually quite a useful test to have around, so I'm going to update it to work again.

2021-03-11 04:38 UTC, peppy commented on osu.Framework/Host.cs
> -                    return new MacOSGameHost(gameName, bindIPC, toolkitOptions, portableInstallation, useOsuTK);
Missed these, have removed.

2021-03-11 05:45 UTC, smoogipoo requested changes

2021-03-11 05:45 UTC, smoogipoo commented on osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
> -                AddAssert("check window location", () => window.Location == display.Bounds.Location, desc1);
Maybe add back this assert to fix the CI error?

2021-03-11 05:56 UTC, peppy commented on osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
> -                AddAssert("check window location", () => window.Location == display.Bounds.Location, desc1);
The assert itself can't exit because the window location is not currently valid except in windowed mode (added this to the xmldoc https://github.com/ppy/osu-framework/pull/4267/commits/6b7d2816ce964015b20348135d062b6a8c196053).

Will remove the unused variable instead.

2021-03-11 06:04 UTC, smoogipoo approved these changes

2021-03-11 06:25 UTC, merged