Add new configuration store for InputHandlers
ppy/osu-framework pull request #4271
Opened 2021-03-11 12:19 UTC by peppy

This paves a path forward to allow individual `InputHandlers` to specify their own settings. Intended to be consumed via reflection (portions of that may arrive at the framework in a future PR).

Using `json` as the storage format will allow, as an example, per-device configurations in `TabletHandler` without further implementation from our end.

2021-03-13 18:10 UTC, bdach commented on osu.Framework/Configuration/InputConfigManager.cs
> +        protected override bool PerformSave()
A little weirded out that `PerformSave()` does not check errors and despite returning a `bool` it only ever returns `true`, while `PerformLoad()` checks the errors, but does not return anything, and logs the errors instead.

Worse yet, if `PerformSave()` fails on I/O (probably about the only place where it can fail), it'll throw while a lock is held in `ConfigManager`, which sounds like trouble.

Then again I'm not exactly sure what the intention for those methods was, since they don't have xmldoc.

2021-03-13 18:29 UTC, peppy commented on osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
> +#pragma warning restore 618
I think it might in a follow-up PR already

2021-03-14 14:21 UTC, peppy commented on osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
> +#pragma warning restore 618
Seems like it's not, will change it here.

2021-03-15 05:22 UTC, smoogipoo requested changes

2021-03-15 05:22 UTC, smoogipoo commented on osu.Framework.Tests/Configuration/InputConfigManagerTest.cs
> +            using (var host = new TestHeadlessGameHost(@"input-config-host"))
I don't know about this being a common name across all test gamehosts. Unlike `CleanRunHeadlessGameHost`, this has the possibility of conflicting storage dirs.

2021-03-15 05:22 UTC, smoogipoo commented on osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
> +        private MouseHandler getMousehHandler()
Typo (`getMouse**h**Handler`)

2021-03-15 05:22 UTC, smoogipoo commented on osu.Framework/Configuration/ConfigManager.cs
> +                Save();
What do you mean by finaliser-safe in this context?

2021-03-15 05:22 UTC, smoogipoo commented on osu.Framework/Configuration/InputConfigManager.cs
> +        protected override bool PerformSave()
I think the bool return was supposed to be used for retry (as `CollectionManager` does in its own similar implementation).

It should definitely have a try-catch though.

2021-03-15 05:55 UTC, bdach commented on osu.Framework/Configuration/ConfigManager.cs
> +                Save();
There are pretty much no guarantees of the consistency of an object's state in the finaliser. [It may well be called on partially constructed objects](https://ericlippert.com/2015/05/21/when-everything-you-know-is-wrong-part-two/) (see the "Myth: An object being finalized was fully constructed." section)

2021-03-15 06:41 UTC, smoogipoo commented on osu.Framework/Configuration/ConfigManager.cs
> +                Save();
Ah sure, was wondering if there was something else deeper that I was somehow missing. This isn't changing logic though so it's fine imo.

2021-03-15 06:48 UTC, peppy commented on osu.Framework/Configuration/ConfigManager.cs
> +                Save();
Confirm that a change isn't required here?

2021-03-15 06:48 UTC, smoogipoo commented on osu.Framework/Configuration/ConfigManager.cs
> +                Save();
No change required.

2021-03-15 07:16 UTC, smoogipoo approved these changes
seems good

2021-03-15 07:16 UTC, merged

2021-03-22 16:33 UTC, Thomzzz commented
Hi, I am a regular lazer player (using a tablet) and I noticed something weird just now. 
My cursor flickers and when I hover over a button it "spams" the selection sound. Maps are unplayable. I suspect the cursor jumps between some location and the correct pen location. Mouse works fine.
Restarting osu, PC or tablet doesn't fix it.

I looked at the change, because last thursday it worked just fine, and saw something about input, so here I am.

(I'm not a developer on this project so I don't know if this is the best place to notify you)

2021-03-22 17:11 UTC, bdach commented
@Thomzzz we're aware of such issues, and this merged PR thread is not the correct place to report them. please disable the tablet handler for now while we fix the tablet issues. they may well be fixed already in the next release.