Prepare InputHandlers for configuration via bindables and reflection
ppy/osu-framework pull request #4272
Opened 2021-03-11 12:22 UTC by peppy

This is some initial tidy-up to get things into a working state. There will likely be more changes required going forward, but wanted to get this out to make sure the direction feels good.
----------------------- >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

Requesting a pull to ppy:master from peppy:input-handler-settings

Write a message for this pull request. The first block
of text is the title and the rest is the description.

Changes:

48bc6bb95 (Dean Herbert, 6 hours ago)
   Expose UseRelativeMode as a bindable and reorder bindables

489a6b3ca (Dean Herbert, 6 hours ago)
   Rename MidiInputHandler to MidiHandler to be in line with other handler
   classes

f8e35aa85 (Dean Herbert, 2 days ago)
   Add default description creation behaviour

   Seems to work well as a sane default.

5b2dc1164 (Dean Herbert, 2 days ago)
   Add descriptions to each input handler

9581022f0 (Dean Herbert, 2 days ago)
   Expose bindables as properties, not fields

2021-03-12 09:41 UTC, peppy commented
Note that I've gone in a bit of a different direction that doesn't necessarily require these changes to go in, but I think they all count as code quality improvements. You be the judge.

2021-03-13 17:18 UTC, bdach requested changes

2021-03-13 17:18 UTC, bdach commented on osu.Framework/Input/Handlers/Midi/MidiHandler.cs
> +    public class MidiHandler : InputHandler
Bit of a nitpick, but might want to override `Description` here (from what I gather it'll read `Midi` via the automatic implementation in `InputHandler`, instead of `MIDI`).

2021-03-13 17:18 UTC, bdach commented on osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
> +        public BindableBool UseRelativeMode { get; set; } = new BindableBool(true)
```suggestion
        public BindableBool UseRelativeMode { get; } = new BindableBool(true)
```

2021-03-13 17:18 UTC, bdach commented on osu.Framework/Platform/MacOS/MacOSGameHost.cs
> +                h.UseRelativeMode.Value = false;
Would also probably want to disable this bindable, too.

2021-03-13 17:18 UTC, bdach commented
Generally I don't see this diff as necessarily hugely worse or better, just a bit different and maybe more consistent. So aside from the above I have no objections.

2021-03-13 17:24 UTC, peppy commented on osu.Framework/Platform/MacOS/MacOSGameHost.cs
> +                h.UseRelativeMode.Value = false;
Intentionally didn't want to do this, so the user can decide for themselves.

2021-03-13 17:36 UTC, bdach approved these changes

2021-03-14 13:57 UTC, bdach submitted a review, later dismissed

2021-03-16 03:14 UTC, smoogipoo approved these changes

2021-03-16 03:30 UTC, merged