Fix resetting input handlers via IgnoredInputHandlers causing reinitialisation
ppy/osu-framework pull request #4274
Opened 2021-03-12 07:03 UTC by peppy

Until now, it was possible to "reset" all input handlers by specifying an empty string for `IgnoredInputHandlers`. This is used at osu! end to reset raw input / sensitivity in the case a user gets into a bad state.

Going forward, since we want to allow binding to configuration `Bindable`s exposed by `InputHandlers`, this process needs to be removed. I don't think there was much reason to allow the full `Dispose` -> `Initialise` process to occur (and it was done in a very haphazard way, via the empty string setting) so I've converted this into a method exposed by `GameHost` which only resets `Enabled` stated and sensitivity values to defaults.

In the future we may want to consider resetting all settings to defaults via reflection, but we'll see where things lead us first.

This will require a change osu!-sidem but that should be implied as raw input toggle handling has also completely changed.

2021-03-13 17:20 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            ignoredInputHandlers.TriggerChange();
Yeah, that should be removed.

2021-03-13 17:21 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.BindTo(cursorSensitivity);
It saves tracking and binding when they are potentially enabled in the future.

2021-03-13 17:22 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            ignoredInputHandlers.TriggerChange();
The intention is to reapply the config values (ie. what the framework consumer expects to be the same default). This method is called, for instance, by the "reset input" hotkey in osu! to turn off raw input, via this config variable.

2021-03-13 17:24 UTC, bdach commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.BindTo(cursorSensitivity);
I was under the impression that that should never happen, going off this xmldoc:

https://github.com/ppy/osu-framework/blob/0638d441b57e9d276e2b1a593ee3005f42262f85/osu.Framework/Input/Handlers/InputHandler.cs#L15-L19

But again, not a huge deal.

2021-03-13 17:26 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.BindTo(cursorSensitivity);
I think the may be a logic error here. The important piece to note is that `Initialise` isn't called if `Enabled` is disabled. It should be called after the first time enabled becomes true, I guess.

2021-03-15 05:23 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.BindTo(cursorSensitivity);
I've reworked this so that `Initialize` is always called. Potentially slightly higher startup overhead if some handlers were disabled, but I think it's fine for now.

2021-03-15 07:30 UTC, smoogipoo requested changes

2021-03-15 07:30 UTC, smoogipoo commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.SetDefault();
Surely we want to expose a method on `InputHandler` for this, I'm not sure why it's tied to `IHasCursorSensitify` and not something like `InputHandler.Reset()`.

2021-03-15 07:30 UTC, smoogipoo commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.BindTo(cursorSensitivity);
I think this still needs to be moved inside the InputHandlers? I'm just considering how a package like https://www.nuget.org/packages/osu.Framework.Microphone/ would implement this and it seems like that's what it would do, so I'd like a little bit of consistency here? This and my comment on `ResetInputHandlers` together.

2021-03-15 07:32 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +                (handler as IHasCursorSensitivity)?.Sensitivity.SetDefault();
Sounds good.

2021-03-15 07:33 UTC, peppy commented
You're fine with adding binding to the (obsolete) config via the `Host` in `Initialize` for the existing handlers?

2021-03-15 07:37 UTC, smoogipoo commented
Ah, that's the only reason it's done this way? And it can be removed in 6mo along with the deprecation added previously? If so then it's fine to leave as is - still think the `.Reset()` method needs to happen though, even if there's a case for the sensitivity where it currently is.

Needs conflict resolution too.

2021-03-15 07:39 UTC, peppy commented
Nah, we also want a reset flow as you describe, so i'll make that happen here

2021-03-15 08:03 UTC, smoogipoo approved these changes
lgtm

2021-03-15 08:05 UTC, smoogipoo submitted a review, later dismissed

2021-03-15 13:10 UTC, merged