Fix CursorInWindow not updating as expected
ppy/osu-framework pull request #4277
Opened 2021-03-12 10:40 UTC by peppy

It turns out with the introduction of relative mouse support in `MouseHandler`, we were toggling the state far more often than necessary. It was feasible that feedback loops when at the edge of the window could cause the state to flip-flop multiple times, causing what seems to be race conditions inside SDL or winapi. This is likely also the reason for https://github.com/libsdl-org/SDL/issues/4165 occurring (this change does greatly reduce the chance of this triggering, to the point I don't think users will ever encounter the issue).

FWIW, the underlying issue here is that the `SDL_WINDOWEVENT_ENTER` / `LEAVE` events stop arriving altogether.

@smoogipoo this resolves the issue you pointed out where the framework test cursor gets stuck at the edge of the window.

- [ ] Depends on https://github.com/ppy/osu-framework/pull/4276 (because toggling raw input before this is a bit... weird).

2021-03-15 19:34 UTC, bdach approved these changes
off the source alone, seems like a reasonable resolution

2021-03-16 03:18 UTC, smoogipoo requested changes

2021-03-16 03:18 UTC, smoogipoo commented on osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
> +            cursorInWindow.BindValueChanged(_ => updateRelativeMode());
Can this bindable be removed, or is an implementation missing here?

2021-03-16 03:18 UTC, smoogipoo commented on osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
> +            cursorInWindow.BindValueChanged(_ => updateRelativeMode());
Nevermind, I missed the line I was commenting on...

2021-03-16 03:34 UTC, smoogipoo submitted a review, later dismissed

2021-03-16 03:35 UTC, smoogipoo approved these changes

2021-03-16 03:50 UTC, merged