Add Resizable property in SDLWindow
ppy/osu-framework pull request #4279
Opened 2021-03-13 10:42 UTC by LeNitrous

Adds `Resizable` property in `SDLWindow`. Makes use of `SDL.SDL_SetWindowResizable(IntPtr, bool)`. This simply removes the ability of the window to be dragged in its frames to be resized so that consumers can programmatically control the window dimensions.

2021-03-13 10:58 UTC, peppy submitted a review, later dismissed

2021-03-13 10:58 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        private bool resizable;
isn't this going to be the wrong value at startup? probably needs to be read along with other window attributes.

2021-03-13 10:58 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                resizable = value;
missing early return, see implementation of other properties in this class for reference.

2021-03-13 14:16 UTC, bdach commented
This should have test coverage, at least manual, given we're not likely to be using this much on the game side.

2021-03-13 14:20 UTC, bdach requested changes

2021-03-13 14:20 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        public bool Resizable
[As stated in the SDL docs](https://wiki.libsdl.org/SDL_SetWindowResizable), setting this is invalid if fullscreen:

> Note: You can't change the resizable state of a fullscreen window.

This will therefore silently fail (sets the field successfully, but then doesn't actually do anything on the SDL side and reverts to the actual value on the next `updateWindowSpecifics()`). I'm not sure it should be allowed to call this without some kind of error in that case. Either that, or it should be ensured that any potential sets of this property aren't lost (and the appropriate commands are executed the next time the window changes state to windowed).

2021-03-14 02:00 UTC, LeNitrous commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        public bool Resizable
I can just set the default value for this as `true` since its guaranteed that we will always have a resizable window on startup. Unless we choose to expose this to the user as a framework config variable.

https://github.com/ppy/osu-framework/blob/4b4dc843aff09dc71b92dbb4cc6606a74eafb94f/osu.Framework/Platform/SDL2DesktopWindow.cs#L411-L417

To ensure that `Resizable` is still the correct value, I can just call `SDL.SDL_SetWindowResizable` again after the window state has been changed to `Normal`.

2021-03-14 02:02 UTC, LeNitrous commented
Should this be a config variable in `framework.ini`? Or should we just leave it hidden to the end user?

2021-03-14 02:03 UTC, peppy commented
should not be exposed

2021-03-14 06:01 UTC, LeNitrous commented
I'm rather unsure of what you mean by "manual". Would a test scene that has steps on toggling the resizable state be enough?

2021-03-14 06:39 UTC, bdach commented
A test scene with a manual toggle is good enough for me, yes.

2021-03-14 06:57 UTC, LeNitrous commented
Added the test scene. Something to note on Windows, The Minimize/Maximize button gets greyed out once `Resizable = false`.

2021-03-14 12:37 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        public bool Resizable
> I can just set the default value for this as true since its guaranteed that we will always have a resizable window on startup.

That's kind of unrelated to what I was asking about...?

> To ensure that `Resizable` is still the correct value, I can just call `SDL.SDL_SetWindowResizable` again after the window state has been changed to `Normal`.

That would be one of the ways I proposed to fix this, yes. Note that this would mean that the semantics of `Resizable` we expose would now differ from SDL's (in fullscreen, SDL says that the window is *not* resizable - so it's a byproduct of `SetWindowResizable` calls and the window mode, while ours would be an internal state variable, that doesn't change value with window mode changes, but is only valid in windowed). It should be documented as such.

2021-03-14 12:38 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneResizableWindow.cs
> +            AddToggleStep("toggle resizable", (state) => ((SDL2DesktopWindow)host.Window).Resizable = state);
see CI failure
```suggestion
            AddToggleStep("toggle resizable", state => ((SDL2DesktopWindow)host.Window).Resizable = state);
```

2021-03-15 02:16 UTC, LeNitrous commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        public bool Resizable
> That's kind of unrelated to what I was asking about...?

Pardon me. I was referring to removing this:

https://github.com/ppy/osu-framework/blob/4b4dc843aff09dc71b92dbb4cc6606a74eafb94f/osu.Framework/Platform/SDL2DesktopWindow.cs#L993

Because inside `SDLDesktopWindow.Create()`, one of the flags set when creating the window is `SDL_WindowFlags.SDL_WINDOW_RESIZABLE`. From that, I can naively assume that we have a resizable window from the start.

In other things, I have updated the xmldocs for the property to note this behavior.

2021-03-15 05:55 UTC, peppy commented on osu.Framework.Tests/Visual/Platform/TestSceneResizableWindow.cs
> +            if (host.Window == null)
You're looking for `[HeadlessTest]` as an attribute on this class.

2021-03-15 07:45 UTC, smoogipoo commented on osu.Framework.Tests/Visual/Platform/TestSceneResizableWindow.cs
> +            if (host.Window == null)
It's the other way around, this class requires a window.

2021-03-15 07:51 UTC, smoogipoo approved these changes
lgtm

2021-03-15 07:53 UTC, smoogipoo submitted a review, later dismissed

2021-03-15 19:03 UTC, bdach approved these changes
seems ok

2021-03-16 03:02 UTC, smoogipoo commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                ScheduleCommand(() => SDL.SDL_SetWindowResizable(SDLWindowHandle, value ? SDL.SDL_bool.SDL_TRUE : SDL.SDL_bool.SDL_FALSE));
What happens if the window is already fullscreen? Is this just a no-op? Perhaps this should check the window state?

2021-03-16 03:08 UTC, peppy commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                ScheduleCommand(() => SDL.SDL_SetWindowResizable(SDLWindowHandle, value ? SDL.SDL_bool.SDL_TRUE : SDL.SDL_bool.SDL_FALSE));
Should be safe enough:

![20210316 120844 (iTerm2)](https://user-images.githubusercontent.com/191335/111250259-5feff880-8650-11eb-8b75-48363837b5c2.png)

2021-03-16 03:09 UTC, smoogipoo approved these changes

2021-03-16 03:11 UTC, merged