Avoid using DI for audio component adjustment lookup to better support pooling
ppy/osu-framework pull request #4303
Opened 2021-03-22 08:41 UTC by peppy

This is a second attempt at https://github.com/ppy/osu-framework/pull/4212, minus the breakage.

The only part of this I'm not 100% sure about is the logic added to ensure no self-references. An alternative to this is to fix each occurrence that uses interface delegation (see https://github.com/ppy/osu/compare/master...peppy:audio-interafce-delegation-fixes?expand=1). In theory this looks like a better approach, until you realise that to make it works, `PoolableSkinnableSample` needs to have similar code to this framework-side change in order to get the parent adjustments (since it is pretending to be a wrapper without actually being one).

Tested to work well osu! side. Not sure if it's worth adding test coverage for this.

2021-03-22 10:17 UTC, smoogipoo requested changes

2021-03-22 10:17 UTC, smoogipoo commented on osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
> +            // in the majority of cases the traversal should be quite short. may require later attention if a use case comes up which this is not true for.
Sure, there's just two things that concern me.

1. `Drawable` receives a `Parent` invalidation basically immediately as its added to the parenting composite, for better or worse.
2. `CompositeDrawable` sets a parent after the child's parent is set (`loadChild(c1) -> loadChild(c2) -> loadChild(c3) -> c3.SetParent() -> c2.SetParent() -> c1.SetParent()`).

Since `Parent` is one of the special invalidation types that always propagates to children, it means a simple load where no parents change causes 3 lookups here which can get pretty rough. There's no xmldoc for this (https://github.com/ppy/osu-framework/pull/4304).

As for fixing, I think this needs a debounce (`Update` + backed by `LayoutValue`). However before going down that path, what do you think about just referencing `Parent.Dependencies` directly?

2021-03-22 10:18 UTC, peppy commented on osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
> +            // in the majority of cases the traversal should be quite short. may require later attention if a use case comes up which this is not true for.
i'm fine with trying `Parent.Dependencies`. At worst it will give us reason to not do it in other scenarios if we run into failure cases.

2021-03-23 02:39 UTC, peppy commented on osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
> +            // in the majority of cases the traversal should be quite short. may require later attention if a use case comes up which this is not true for.
As discussed in discord, using `Parent.Dependencies` doesn't work as expected due to the feedback-loop avoidance part, where we potentially skip a portion of traversal. I've gone with the debounce-via-`LayoutValue` part though.

2021-03-23 04:25 UTC, smoogipoo requested changes

2021-03-23 04:25 UTC, smoogipoo commented on osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
> +                refreshAdjustments();
needs a `parentAdjustmentLayout.Validate()`

2021-03-23 04:29 UTC, peppy commented on osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
> +                refreshAdjustments();
Added and re-tested with osu! to make sure it still works.

2021-03-23 05:19 UTC, smoogipoo approved these changes
Let's see how this goes. I'm still concerned about performance, especially as it's going to manifest as a single-time event rather than a global reduction in frametime, but I don't have a better solution immediately.

2021-03-23 05:36 UTC, merged