Ensure disposal of drawables within DrawablePool
ppy/osu-framework pull request #4305
Opened 2021-03-22 19:03 UTC by LumpBloom7

After the removal of finalizers from `Drawables` in #4242, disposals must be invoked manually.

`Drawables` within the draw hierarchy do get properly disposed since the disposal of a parent drawable would also trigger a disposal on their children. 
https://github.com/peppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L299

However, in `DrawablePool`, a stack is used to store `PoolableDrawable`s, which means that they aren't within the drawable hierarchy, so the pool's contents aren't disposed properly. 

This PR adds a change that ensures that the pool's contents are disposed.

<sub>This is something I've noticed when pooling drawables within another pooled drawable in my ruleset, and the failure to properly dispose drawables within the pool led to the nested pool's statistic entry not being removed from the global statistics panel. The actual pool is properly disposed though.

(`DrawablePool<DrawableHitObject>` > `DHO` > [`Piece` > `DrawablePool<Drawable>`](https://github.com/LumpBloom7/sentakki/blob/master/osu.Game.Rulesets.Sentakki/Objects/Drawables/Pieces/SlideVisual.cs#L62))
[Image showing potential problem caused by this fault](https://user-images.githubusercontent.com/12001167/112043372-e1f88980-8b48-11eb-9827-58173e3b4b80.png)</sub>

2021-03-22 19:12 UTC, bdach commented on osu.Framework/Graphics/Pooling/DrawablePool.cs
> +                x.Dispose();
Could also clear the stack (and the references within) to allow refcounts to be decremented? Not sure. Should be fine either way, I think.

Also this is a bit awkwardly placed, given it's delineating the removal of `statistic` from it being cleared. I'd either move fully before or fully after both.

2021-03-23 01:26 UTC, peppy requested changes

2021-03-23 01:26 UTC, peppy commented on osu.Framework/Graphics/Pooling/DrawablePool.cs
> +            foreach (var x in pool)
We generally don't call variables `x`. I'd go with `d` for drawable or `p` for pooable (probably the second).

2021-03-23 02:37 UTC, peppy approved these changes

2021-03-23 03:43 UTC, smoogipoo approved these changes

2021-03-23 03:44 UTC, merged