Change `IsDragged` state before triggering end event
ppy/osu-framework pull request #4401
Opened 2021-04-25 06:48 UTC by frenzibyte

Matches behaviour as hover lose and focus lose, where the property would have its state changed before triggering the event.

# vNext

## `Drawable.IsDragged` now changes its state before triggering event

Unlike the other way around, now `Drawable.IsDragged` changes state before the `DragEndEvent` is triggered, matching other similar events like hover and focus.

2021-04-25 12:36 UTC, bdach requested changes

2021-04-25 12:36 UTC, bdach commented on osu.Framework/Input/MouseButtonEventManager.cs
>              DraggedDrawable = null;
This should also be unset before the event is propagated. Compare focus, which stores the previous `FocusedDrawable` to a local and only then triggers the event. Hover does similar.

This should also be included in the breaking changes note.

2021-04-25 16:09 UTC, frenzibyte commented on osu.Framework/Input/MouseButtonEventManager.cs
>              DraggedDrawable = null;
Ah, missed to notice that.

2021-04-25 16:16 UTC, bdach commented on osu.Framework/Input/MouseButtonEventManager.cs
> -            if (DraggedDrawable == null) return;
not sure why this guard went away. something like the following reads much better and has no nesting/null checks:

```csharp
if (DraggedDrawable == null) return;

var previousDragged = DraggedDrawable;
previousDragged.IsDragged = false;
DraggedDrawable = null;

PropagateButtonEvent(new[] { DraggedDrawable }, new DragEndEvent(state, Button, MouseDownPosition));
```

but i guess this variant also works...

2021-04-25 16:19 UTC, frenzibyte commented on osu.Framework/Input/MouseButtonEventManager.cs
> -            if (DraggedDrawable == null) return;
Went with the same way focus lose logic does it, felt good to me at first, but I think yours sound much better.

2021-04-25 16:41 UTC, bdach approved these changes

2021-04-26 10:24 UTC, smoogipoo approved these changes
Makes sense

2021-04-26 11:24 UTC, peppy approved these changes

2021-04-26 11:24 UTC, merged