Abstractify bindable number constraints logic and use for `BindableSize`
ppy/osu-framework pull request #4404
Opened 2021-04-26 00:11 UTC by frenzibyte

Resolves #4307 

Rather than copying logic from `BindableNumber` over to `BindableSize`, I've abstracted the constraints logic into a `ConstrainedBindable` and let `BindableSize` inherit it and override the required properties.

For test cases, I've moved the constraints test cases from `BindableNumberTest` to a `ConstrainedBindableTest` test class and currently instantiate `BindableNumber`s as a sample for testing constraints propagation, not sure if also instantiating and testing a `BindableSize` is worth it, if one breaks on that aspect the other should also break.

Also made sure to document that `BindableSize` constraints are component-wise, to avoid any confusion.

2021-04-26 01:43 UTC, ekrctb commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
I don't think the new code is right either. For example, it is both `(0, 1) < (1, 0)` and `(1, 0) < (0, 1)`.

Can't we just use the lexicographic ordering?
```csharp
if (x.Width != y.Width) return x.Width.CompareTo(y.Width);
return x.Height.CompareTo(y.Height);
```

2021-04-26 02:11 UTC, frenzibyte commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
hmm, this would allow `MinValue` to be `(0, 1)` and `MaxValue` to be `(1, 0)`, which is not valid.. not sure how to handle these cases, maybe override and throw undefined exception on that case instead?

2021-04-26 02:42 UTC, ekrctb commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
I missed that the comparison is for comparison between min/max values.
As the ordering required for the size clamping is not a total ordering, but only a partial ordering, `Compare` cannot always return one of the `-1, 0, 1` values for each comparison, but it has to return a separate "unordered" case.
Perhaps the return type of `Compare` should just be `bool`, and return `true` if LHS is less than or equals to RHS. If the ordering between LHS and RHS is undefined (unordered), it returns `false`.
For `Size`, it is `Compare(x, y) => x.Width <= y.Width && x.Height <= y.Height`.

2021-04-26 03:17 UTC, ekrctb commented on osu.Framework/Bindables/ConstrainedBindable.cs
> +    public abstract class ConstrainedBindable<T> : Bindable<T>
As this class implement a special kind of constraint (clamping), more specific can be used, like `RangeConstrainedBindable`?

2021-04-26 04:05 UTC, bdach commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
`BindableSize` should not implement `IComparable`, period. There is no sane way to declare a full ordering on it as stated above. Where is the requirement of implementing it coming from?

2021-04-26 04:06 UTC, frenzibyte commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
doesn't implement `IComparable`, simply using the method for comparing `MinValue` and `MaxValue` to avoid non-overlapping ranges.

2021-04-26 04:13 UTC, bdach commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
then this abstraction is wrong. declare a bound-checking method that returns a `bool` in `ConstrainedBindable` instead of that `CompareTo()`.

2021-04-26 04:15 UTC, frenzibyte commented on osu.Framework/Bindables/BindableSize.cs
> +                return -1;
hmm, you have a point. as it isn't used anywhere else.

2021-05-01 13:55 UTC, bdach commented
@frenzibyte Tests are failing and there are unresolved reviews. Is this going to get fixed?

2021-05-01 21:27 UTC, frenzibyte commented
Yeah, I'll get to it when I have the chance to.

2021-05-05 21:41 UTC, bdach requested changes

2021-05-05 21:41 UTC, bdach commented on osu.Framework.Tests/Bindables/ConstrainedBindableTest.cs
> +    public class ConstrainedBindableTest
test class name does not match tested class's name anymore (should be `RangeConstrainedBindableTest`)

2021-05-05 21:41 UTC, bdach commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +        protected abstract bool IsOverlappingRange(T min, T max);
would rename to `IsValidRange` or something along these lines ("overlapping range" sounds like it's *not* a correct range).

2021-05-05 21:41 UTC, bdach commented on osu.Framework/Bindables/BindableNumber.cs
> +        protected override bool IsOverlappingRange(T min, T max) => min.CompareTo(max) <= 0;
would probably seal these overrides

2021-05-05 21:41 UTC, bdach commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +                Value = base.Value;
stuff like `Value = base.Value;` doing business logic and having silent side effects makes me extremely scared - preferred the previous `SetValue(Value)` thing `BindableNumber` had

2021-05-05 21:41 UTC, bdach commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +                }
this exception message direly needs updating ("weld" and not "bind"? bindable "longs"?).

as an aside it's interesting that this is only checked *after* already having transferred the value, not before - would probably check before, to avoid leaving this bindable in a potentially corrupted state.

2021-05-05 21:58 UTC, frenzibyte commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +        protected abstract bool IsOverlappingRange(T min, T max);
yeah, thought it was just me not understanding the term `overlapping` properly.

2021-05-05 21:58 UTC, frenzibyte commented on osu.Framework/Bindables/BindableNumber.cs
> +        protected override bool IsOverlappingRange(T min, T max) => min.CompareTo(max) <= 0;
and at `BindableSize` too? or is there a special reason into this one?

2021-05-05 22:01 UTC, frenzibyte commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +                Value = base.Value;
right, the way I have it looks really bad and I haven't even noticed.

2021-05-05 22:06 UTC, frenzibyte commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +                }
right, the exception message itself is broken since both `MinValue` and `other.MinValue` are gonna be the same if thrown after, will update.

2021-05-05 22:10 UTC, bdach commented on osu.Framework/Bindables/BindableNumber.cs
> +        protected override bool IsOverlappingRange(T min, T max) => min.CompareTo(max) <= 0;
I suppose you could do both. This one is a *bit* special because of the generics, but neither should hurt really.

2021-05-06 21:26 UTC, bdach approved these changes
i can live with this now

2021-05-06 21:26 UTC, bdach commented on osu.Framework/Bindables/RangeConstrainedBindable.cs
> +                }
note that sets to `{Min,Max}Value` should really be checking range validity as well, but that is not a regression as the old code also didn't do that, so i'm purposefully looking away from that issue to not enlarge the diff any further

2021-05-07 03:39 UTC, peppy approved these changes

2021-05-07 03:39 UTC, merged