Migrate osu!framework to GitHub Actions
ppy/osu-framework pull request #4412
Opened 2021-04-27 14:49 UTC by sr229

Similar vein to GH-4407, but in a feature-complete state.

### Changes

- CI has a richer integration with NUnit using the NUnit Logger with the NUnit Reporter Action.

2021-04-27 15:50 UTC, smoogipoo requested changes

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +on: [push, pull_request, release]
I don't think we need `release`.

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +     needs: test
Any reason for this? Can run concurrently.

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
Are you absolutely sure you need this on `ubuntu-latest`? I'm able to run inspectcode locally on arch perfectly fine, but I do get errors on my windows VM.

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +            done
I suppose this is fine for now, but please add a todo that this functionality should be added to CFS itself.

Also, have you tested that this actually fails the CI process?

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
Have you tested this also fails the CI process? Nvika's quite old (came before gh-actions) so I'd be surprised if it does (also: https://github.com/laedit/vika/issues/224).

```suggestion
            dotnet nvika parsereport $(pwd)/inspectcodereport.xml --treatwarningsaserrors
```

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +  pack-n-publish:
`pack-and-publish`

Also, this shouldn't be publishing to nuget immediately. That's done manually on a pushed tag, and needs to be in another workflow.
All that this should be doing is uploading the artifacts. Though really, I'm not sure that this is required for the time being, since I don't believe any of us have been used the appveyor feed the last year (@peppy?), so it's probably fine to skip this altogether.

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +                  dotnet-version: '3.1.x'
I don't understand - they use the Xamarin SDK which is neither .NET 3.1 nor 5. It's xamarin+msbuild.

They probably shouldn't even be compiled on windows in the first place, see: https://github.com/saamerm/Xamarin-GitHubActions-DevOps/blob/master/.github/workflows/main.yml

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true /p:NoDefaultExcludes=tru
Wrong project

2021-04-27 15:50 UTC, smoogipoo commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
Shouldn't be in this workflow.

2021-04-27 15:52 UTC, peppy commented on .github/workflows/ci.yml
> +  pack-n-publish:
I think there's not much harm in upload artifacts (assuming github has a sane retention policy - i'd be against having them stored permanently for every build as that is a waste of resources).

2021-04-27 15:54 UTC, smoogipoo commented on .github/workflows/ci.yml
> +  pack-n-publish:
Seems like the retention policy can be adjusted: https://docs.github.com/en/github/administering-a-repository/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-repository

2021-04-27 15:58 UTC, sr229 commented on .github/workflows/ci.yml
> +                  dotnet-version: '3.1.x'
Using `setup-dotnet` overrides the active .NET installation on `PATH` so I had to install 3.1 LTS libraries for the builds to actually compile.

2021-04-27 15:59 UTC, peppy commented on .github/workflows/ci.yml
> +  pack-n-publish:
90 days sounds fine, or lower. That said, if it's adding a performance overhead switching off is also a feasible path.

2021-04-27 16:01 UTC, sr229 commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
Any reasoning why this shouldn't be in this workflow? I closely followed the structure from Cake so I wasn't aware how you want the CI done.

2021-04-27 16:02 UTC, smoogipoo commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
There is a completely separate appveyor workspace for publishing the native libs: https://github.com/ppy/osu-framework/blob/master/appveyor_native_deploy.yml

This is done manually. Otherwise we're uploading hundreds of MBs of packages with every o!f release.

2021-04-27 16:02 UTC, sr229 commented on .github/workflows/ci.yml
> +  pack-n-publish:
There should be no overhead in uploading the artifacts since they're there for testing purposes. The workflow only executes publish on a specific GitHub Event (which I assume is `tag`?) so this gets skipped altogether anyways.

2021-04-27 16:04 UTC, sr229 commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
Haven't introduced a bad change to test things out, but Actions is designed to error if the said workflow sends a non-zero exit code (which is fairly standard for most analyzers).

2021-04-27 16:04 UTC, sr229 commented on .github/workflows/ci.yml
> +            done
It only sends a warning, but it doesn't fail it, which is something we have to introduce in CFS either way.

2021-04-27 16:06 UTC, sr229 commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
Inspect Code Workflow steps uses Bash syntax, and since I already have this structured it's no harm to use the Linux environment for Code Analysis.

2021-04-27 16:06 UTC, sr229 commented on .github/workflows/ci.yml
> +     needs: test
Got it, we'll make this non-linear in the next rev

2021-04-27 16:08 UTC, sr229 commented on .github/workflows/ci.yml
> +                  dotnet-version: '3.1.x'
> They probably shouldn't even be compiled on windows in the first place, see: https://github.com/saamerm/Xamarin-GitHubActions-DevOps/blob/master/.github/workflows/main.yml

Regarding this, we could use `macos-latest`, but I wasn't certain if I should do that so I left it in a state that was close to what was on Cake. Sorry about that.

2021-04-27 16:10 UTC, smoogipoo commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
Yeah I know that about analyzers exiting on non-zero, wasn't sure whether nvika did that. Seems like it does:
```
[smgi@smgi osu-framework]$ dotnet jb inspectcode osu-framework.Desktop.slnf --output="build/inspectcodereport.xml" --verbosity=WARN && dotnet nvika parsereport build/inspectcodereport.xml --treatwarningsaserrors

...

[Fatal] Issues with severity error was found: the build will fail

[smgi@smgi osu-framework]$ $?
-bash: 5: command not found
```

We also can't just have it error and have the user fish for it in plain text. The inspectcode command already dumps thousands of lines of output (one for each file).

How does it look when it fails, can you provide a screenshot?

2021-04-27 16:10 UTC, sr229 commented on .github/workflows/ci.yml
> +on: [push, pull_request, release]
Hmm, there isn't any alternative to listening to Git tags, so `release` was the closest thing.

2021-04-27 16:11 UTC, smoogipoo commented on .github/workflows/ci.yml
> +                  dotnet-version: '3.1.x'
Just to clarify, you could also just make a separate job for msbuild for the iOS/Android projects (windows-latest). There's no need to keep everything in one like this.

2021-04-27 16:12 UTC, peppy commented on .github/workflows/ci.yml
> +on: [push, pull_request, release]
It doesn't need to run on releases or tags. Tags are based on a commit on `master` which has inherently already passed CI.

2021-04-27 16:13 UTC, smoogipoo commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
What? I mean you shouldn't need to install LTS tools to run the dotnet tools.

I think the only one that's broken is dotnet-format, but that needs a lot of fixing up anyway, and it's fine to leave broken for now.

2021-04-27 16:14 UTC, sr229 commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
Ah, I'll make it a seperate workflow soon.

2021-04-27 16:18 UTC, sr229 commented on .github/workflows/ci.yml
> +                  dotnet-version: '3.1.x'
> Just to clarify, you could also just make a separate job just for the iOS/Android projects (`windows-latest`). There's no need to keep everything in one like this.

Got it, sorry if this was too monolithic, I mostly followed Cake with no afterthought of redesigning it again. Will do that in the next rev.

2021-04-27 16:23 UTC, sr229 commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
> We also can't just have it error and have the user fish for it in plain text. The inspectcode command already dumps thousands of lines of output (one for each file).

Hmm, since InspectCode is also a GitHub Action, I think it'll be much safer to use that instead? [I think this is pretty close but I doubt this is what we want.](https://github.com/glassechidna/resharper-action)

2021-04-27 16:25 UTC, sr229 commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
CFS Relies on 2.1 LTS which I thought should *just work* but it threw an error during development which led to this stopgap.

![image](https://user-images.githubusercontent.com/14976516/116277610-3c27e280-a7b8-11eb-98e1-f4d472674bba.png)

2021-04-27 16:28 UTC, sr229 commented on .github/workflows/ci.yml
> +on: [push, pull_request, release]
Got it, I'll just run it against PRs and Pushes. As for releases I assume [Repository Dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) should be enough to cover the expected use case?

2021-04-27 16:30 UTC, smoogipoo commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
It's slightly out of date but you may be able to use the xml option (rather than solution):
```
with:
    report: $(pwd)/inspectcodereport.xml
```

2021-04-27 16:35 UTC, smoogipoo commented on .github/workflows/ci.yml
> +on: [push, pull_request, release]
See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

You can run on tags.

2021-04-27 16:40 UTC, smoogipoo commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
Uh, well firstly CFS 15.0.0 is wrong, but I understand that it's because that's how it was in the cake file. It should be 0.0.36 which is targetted towards 3.1, and may be runnable by the NET5 runtime.

2021-04-28 00:56 UTC, sr229 commented
As per review, tasks are more parallelized now. they've also been given unique artifact identifiers during upload which is close to what we have at appveyor.

2021-04-28 01:21 UTC, sr229 commented on .github/workflows/ci.yml
> +            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors
This should be resolved now by using the ReSharper Action.

2021-04-28 01:23 UTC, sr229 commented on .github/workflows/ci.yml
> +            done
TODO added here, I'll see what I can do on the CFS side post-merge.

2021-04-28 02:40 UTC, peppy commented
Please consider fixing your editor up: get a yaml linter to show indentation issues, turn on whitespace cleaning on save. maybe turn on auto-format on save.

2021-04-28 03:10 UTC, sr229 commented
> Please consider fixing your editor up: get a yaml linter to show indentation issues, turn on whitespace cleaning on save. maybe turn on auto-format on save.

I have the YAML linter installed on my editor but it seems not to catch stray whitespaces, I'll work on that later.

2021-04-28 03:27 UTC, sr229 commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
> Ah, I'll make it a seperate workflow soon.

Just a follow-up on this: Would this workflow listen to pushes like the rest, or it will be triggered manually? (we can use `workflow_dispatch` if the latter.)

2021-04-28 15:02 UTC, sr229 commented on .github/workflows/ci.yml
> +             dotnet-version: '3.1.x'
This should be fixed but Actions is not firing for some reason, I'll get to fix that to see if moving versions worked.

2021-04-29 00:22 UTC, sr229 commented on .github/workflows/ci.yml
> +              run: dotnet pack -c Release osu.Framework.NativeLibs /p:Configuration=Release /p:Version=${{steps.deployment.outputs.version}} /p:GenerateDocumentationFile=true -o ${{steps.artifactsPat
Added this as a seperate Dispatch workflow. Feel free to review that if there's something that doesn't seem to fit the bill.

2021-04-29 00:50 UTC, sr229 commented
The workflows are pretty much done at this point as it's pretty close to the AppVeyor CI, however, I'm requesting another review before this gets merged (just to prevent some show-stoppers).

![image](https://user-images.githubusercontent.com/14976516/116489545-d296f980-a8c7-11eb-92f1-da27a21bd955.png)

As for NativeLibs, I won't be able to test that since it needs to be in `master` to be tested, but this uses the same workflow code used in the main CI so I'm confident it'll work here as well.

2021-04-29 01:20 UTC, peppy commented
Re-reviews are implicit if you commit anything since last review, no need to ask.

Curious why you can't test NativeLibs on your fork's master though?

2021-04-29 01:28 UTC, sr229 commented
> Curious why you can't test NativeLibs on your fork's master though?

Was planning to keep `master` clean as much as possible since it's used for syncing to ppy tree, though this PR might be an exception.

2021-04-29 01:44 UTC, sr229 commented
Decided to merge this on the fork master, after some changes, NativeLibs is ready to go as well.

![image](https://user-images.githubusercontent.com/14976516/116492675-71732400-a8cf-11eb-886d-419b17071772.png)

2021-04-29 02:53 UTC, peppy commented
> > Curious why you can't test NativeLibs on your fork's master though?
> 
> Was planning to keep `master` clean as much as possible since it's used for syncing to ppy tree, though this PR might be an exception.

You can force push your own master as much as you want. Or you can just create a second fork for testing if you see that as an issue.

2021-04-29 03:10 UTC, ekrctb commented on .github/workflows/ci.yml
> +             if [ $(echo $line| grep -q "./osu.Framework.Templates/"; echo $?) == 1 ]; then
```suggestion
             if [[ "$line" != *"/osu.Framework.Templates/"* ]]; then
```

No need to create a process each line.

2021-04-29 03:17 UTC, sr229 commented on .github/workflows/ci.yml
> +             if [ $(echo $line| grep -q "./osu.Framework.Templates/"; echo $?) == 1 ]; then
Not really a fan of Bash-conditionals, as much as possible, I use POSIX.

2021-04-29 09:08 UTC, peppy commented on .github/workflows/ci.yml
> +             if [ $(echo $line| grep -q "./osu.Framework.Templates/"; echo $?) == 1 ]; then
Personally I think the proposal reads better.

2021-04-29 09:10 UTC, peppy commented on .github/workflows/ci.yml
> +  pack-framework:
why is this whole thing in the `ci.yml`? should it not be its own workflow completely?

2021-04-29 09:12 UTC, peppy requested changes

2021-04-29 09:12 UTC, peppy commented on osu.Framework.Tests/osu.Framework.Tests.csproj
> +    <PackageReference Include="NunitXml.TestLogger" Version="3.0.97" />
What is this used for?

2021-04-29 09:12 UTC, peppy commented on .github/workflows/ci.yml
> +  check-if-tag:
likewise, this tag getting stuff feels super out of place here. it should be inside a deploy yaml which is only run on release/tag in the first place.

2021-04-29 09:15 UTC, peppy commented on .github/workflows/ci.yml
> +        if: ${{ always() }}
is this even required?

2021-04-29 12:43 UTC, sr229 commented on osu.Framework.Tests/osu.Framework.Tests.csproj
> +    <PackageReference Include="NunitXml.TestLogger" Version="3.0.97" />
This replaces the AppVeyor Test Logger, it reports all the NUnit errors in Test Summary, it looks like this.

![image](https://user-images.githubusercontent.com/14976516/116552405-8e3d4500-a92b-11eb-8d81-582a35813405.png)

2021-04-29 12:43 UTC, sr229 commented on .github/workflows/ci.yml
> +        if: ${{ always() }}
Refer to my response [here](https://github.com/ppy/osu-framework/pull/4412#discussion_r623015171).

2021-04-29 12:47 UTC, sr229 commented on .github/workflows/ci.yml
> +  check-if-tag:
I consolidated the release pipeline on the CI workflow since it'll be redundant anyways. The main idea here is it only makes a release for you if `github.ref` matches `refs/tags/x.y.z`, otherwise, it just uploads the artifacts.

2021-04-29 12:50 UTC, sr229 commented on .github/workflows/ci.yml
> +  pack-framework:
Different workflows cannot share jobs IIRC, so if you want a workflow to require task A but it's on a different workflow, you can't do so. Besides this will show up as a different CI check so it's a non issue if you're worried that it'll show up as one big workflow.

2021-04-29 12:54 UTC, sr229 commented on .github/workflows/ci.yml
> +             if [ $(echo $line| grep -q "./osu.Framework.Templates/"; echo $?) == 1 ]; then
tested it and it works just as well, thanks for the suggestion. Though I'd prefer this would be using POSIX conditionals for consistency but this will do for now.

2021-04-29 12:57 UTC, sr229 commented on .github/workflows/ci.yml
> +  check-if-tag:
Also the reason I made the tag step was because of duplication, I decided to share the same logic for all workflows to be more consistent, it keeps the workflow cleaner as well.

2021-04-29 13:04 UTC, sr229 commented on .github/workflows/ci.yml
> +  check-if-tag:
Opted to change the terminology instead from workflow that it's main intent is to set Package version. Should resolve this properly.

2021-04-29 13:07 UTC, peppy commented on osu.Framework.Tests/osu.Framework.Tests.csproj
> +    <PackageReference Include="NunitXml.TestLogger" Version="3.0.97" />
Just curious where/how this interacts with the tests project itself. There are no usages of this within the project so it's going to be listed as a dependency which can be removed.

May be worthwhile adding a comment inline explaining why it's there so we don't do that by accident.

2021-04-30 11:38 UTC, peppy approved these changes

2021-04-30 11:39 UTC, peppy commented
Rather than dwelling on this for too long, I think this is in a fine state to get live so we can test how things work in our workflow (while also leaving appveyor running as the primary point of truth into the future, until we are confident with the change).

2021-04-30 13:33 UTC, smoogipoo approved these changes
looks fine now

2021-04-30 13:33 UTC, merged