Run Test Job as Matrix
ppy/osu-framework pull request #4430
Opened 2021-05-04 14:12 UTC by sr229

Closes #4426. This will run the `test` job against all supported platform runners in GitHub Actions on SingleThread and MultiThread mode.

Currently tests are flaky so I'm not sure how to fix this.

2021-05-04 14:15 UTC, sr229 commented
I would like to remark Test Reporting will be broken since this PR includes the proper fixes.

2021-05-04 14:52 UTC, LittleEndu commented on .github/workflows/ci.yml
> +        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --settings $pwd/build/vstestconfig.runsettings --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}.trx"
Isn't this missing the threading side of the matrix? Only 3 out of 6 test results are uploaded

2021-05-04 14:56 UTC, bdach requested changes

2021-05-04 14:56 UTC, bdach commented on .github/workflows/ci.yml
> +      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
not sure what this comment is trying to convey by "let's fix that", but if you mean as a todo in the future, then i'd link the actual issue instead (https://github.com/ppy/osu-framework/issues/4349)

2021-05-04 14:56 UTC, bdach commented on .github/workflows/ci.yml
> +        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --settings $pwd/build/vstestconfig.runsettings --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}.trx"
yeah, seems like artifacts from one OS will overwrite each other in non-deterministic fashion because of how they're named.

2021-05-04 15:03 UTC, sr229 commented on .github/workflows/ci.yml
> +        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --settings $pwd/build/vstestconfig.runsettings --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}.trx"
I should fix that later on, good catch.

2021-05-04 15:03 UTC, sr229 commented on .github/workflows/ci.yml
> +      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
Thanks for the issue link, but this will be removed anyways since I opened a [issue](https://github.com/actions/virtual-environments/issues/3306) to include the dependency inside ubuntu-latest.

2021-05-04 18:32 UTC, bdach commented
Aside from the culture test failures, which are to be addressed by the PR above, I am also locally seeing failures at:

- [ ] `GameHostSuspendTest.TestPauseResume`
- [ ] `TestSceneSampleLooping.TestZeroFrequencyOnStart`

Probably best addressed before proceeding with this merge.

2021-05-05 16:10 UTC, smoogipoo approved these changes

2021-05-05 16:14 UTC, bdach approved these changes

2021-05-05 16:18 UTC, merged