Split Pack Tasks Entirely
ppy/osu-framework pull request #4438
Opened 2021-05-05 17:14 UTC by sr229

This removes the Pack Tasks away from the main CI, and calls them via a dispatch flow instead during a tagged commit. While it's possible to call them manually [you're limited to branches in UI.](https://github.community/t/workflow-dispatch-from-a-tag-in-actions-tab/130561)

![image](https://user-images.githubusercontent.com/14976516/117181904-4e350100-ae08-11eb-8d3b-f5f3af88fc5f.png)

![image](https://user-images.githubusercontent.com/14976516/117181946-5856ff80-ae08-11eb-9708-4affe5b75b8b.png)

2021-05-05 17:19 UTC, smoogipoo commented
I was reading about this earlier - doesn't this do what's necessary?: https://stackoverflow.com/a/59349906 (read the comment too)

So something like:
```yml
on:
  push:
    tags:
      - '*'
```

2021-05-05 17:22 UTC, sr229 commented
> I was reading about this earlier - doesn't this do what's necessary?: https://stackoverflow.com/a/59349906 (read the comment too)
> 
> So something like:
> 
> ```yaml
> on:
>   push:
>     tags:
>       - '*'
> ```

IIRC this needed to be done manually, so `workflow_dispatch` was used. I can switch it out right now if so.

2021-05-05 17:24 UTC, smoogipoo commented
Ah right, my bad. Automatic wouldn't make much sense anyway given nativelibs...

2021-05-05 17:30 UTC, smoogipoo commented on .github/workflows/ci.yml
> +  dispatch-release:
So I'm a little confused how this entire process works.

The nativelibs and pack workflows have a separate button to run their workflow, via `workflow_dispatch`: 
![image](https://user-images.githubusercontent.com/1329837/117183707-d4564500-ae12-11eb-8010-6348cbe4decf.png)

But the workflow is _also_ being dispatched from the main CI here. Am I right in understanding that this is intending to dispatch on a tag? Because if so, and this should all be manual, then this should not be here.

2021-05-05 17:32 UTC, smoogipoo commented on .github/workflows/ci.yml
> +  dispatch-release:
Ah, this is because you can't select a tag? With the comments in the other .yml files?

2021-05-05 17:32 UTC, sr229 commented on .github/workflows/ci.yml
> +  dispatch-release:
My main worry is that the UI limitations would make this dispatch impossible, since running this by tags is API-facing only. I can remove it now.

2021-05-05 17:40 UTC, smoogipoo commented on .github/workflows/ci.yml
> +  dispatch-release:
Have you considered just calling `git describe --tags --exact-match`?

2021-05-05 17:43 UTC, bdach commented on .github/workflows/ci.yml
> +     if: ${{ ${{ github.event != 'pull_request' && contains(github.ref, 'refs/heads/')  != true }} || github.event == 'pull_request' }}
What is happening here?

What's with the `(a && b) || a` check? What's `refs/heads/`? And shouldn't this dispatch on new tags only? As in, run on [`create`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create) events?

2021-05-05 17:43 UTC, bdach commented on .github/workflows/ci.yml
> +     if: ${{ github.event != 'pull_request' && contains(github.ref, 'refs/heads/')  != true || github.event == 'pull_request' }}
What is happening here?

What's with the `(a && b) || !a` check? Surely you mean `!a || b`? What's `refs/heads/`? And shouldn't this dispatch on new tags only? As in, run on [`create`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create) events, not on everything?

2021-05-05 17:43 UTC, bdach commented on .github/workflows/ci.yml
> +           token: ${{ secrets.GITHUB_TOKEN }}
So am I to understand that each framework release will be accompanied by a nativelibs release? Bit extravagant, and not how things were usually done up to now. How do you bump nativelibs and then use that bumped version in an actual framework release with this flow?

2021-05-05 19:38 UTC, bdach requested changes

2021-05-05 19:38 UTC, bdach commented on .github/workflows/deploy-pack.yml
> +name: Continuous Integration - Pack
this still says CI; should be
```suggestion
name: Deployment - Pack
```
probably?

2021-05-05 19:38 UTC, bdach commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
this seems bogus? any string contains an empty string, does it not? should this not be just

```suggestion
    if: ${{ needs.check-if-tag.outputs.version != '' }}
```

also see same conditional in `deploy-pack.yml`

2021-05-05 19:45 UTC, sr229 commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
Tried the following before and it'll still execute the step either way, which was the main reason I took too long on finalizing the logic because the evaluation is not working as it should.

2021-05-05 21:27 UTC, bdach commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
...and what you have *doesn't* always execute? something is *very* broken on github's side if this is really the case, then

2021-05-06 00:36 UTC, sr229 commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
Decided to make Package Version job fail entirely if HEAD has no tag which is probably what we want anyways 

![image](https://user-images.githubusercontent.com/14976516/117225973-2c5a6f00-ae46-11eb-9145-90c57a6b1cd3.png)

2021-05-06 04:02 UTC, peppy commented
Please refrain from mindlessly merging master into your PRs. We will do this when necessary.

2021-05-06 20:37 UTC, bdach requested changes

2021-05-06 20:37 UTC, bdach commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
this check was not deleted properly in 1f2e59f596b0b1f15d0bbc2d7568ca40953e6920. please fix it, because when i tried to do so myself, i ended up pushing a branch to this repository rather than pushing a commit to your fork.

and i don't know how you've managed to break maintainer pushing to PRs, but please, for the love of anything holy sort out this remote situation so that we can fix things for you and speed up this already gruesomely long process. because in fact [i believe this is the *second* time in two days that the same fiasco happens](https://discord.com/channels/188630481301012481/589331078574112768/839492356704436272), caused by us assuming that things work normally. it might be that "codespaces" thing again. if it is, i would actually recommend *not* using it as it looks to be terminally broken and not fit for actual development.

2021-05-06 23:23 UTC, sr229 commented on .github/workflows/deploy-nativelibs.yml
> +    if: ${{ contains(needs.check-if-tag.outputs.version, '')  == false }}
I'll remove the check now, seems a small oversight from me, whoops. As for broken pushes, I have no idea what happened, but that's something I may have to report to GitHub. I'll refrain using this while making PRs from now on until I clear this up.

2021-05-07 03:23 UTC, peppy approved these changes

2021-05-07 03:23 UTC, merged