Add HSV colour picker component
ppy/osu-framework pull request #4489
Opened 2021-06-06 11:49 UTC by bdach

First step towards resolving #3134.

https://user-images.githubusercontent.com/20418176/120922773-4f897000-c6cb-11eb-8ca3-a5efe7757ee9.mp4

An implementation of such a component was given in #3138, but it had several shortcomings that made it easier to just rewrite, the key ones being:

* The structure of that PR did not really yield to customisation much, or match the rest of the framework controls (which use an abstract base control and a `Basic` control that uses the framework design language), while with the structure here I will - eventually, at the end of the series of changes I have queued - be able to achieve the following game-side in less than 200 LOC:

![2021-06-06-130347_441x611_scrot](https://user-images.githubusercontent.com/20418176/120922863-d8081080-c6cb-11eb-8b58-bf24e42dab73.png)

* The hue slider looked wrong/incorrect. The method used in that PR - splicing piece-wise gradients for each of the 6 primary hues - does not look as expected, because linear interpolation in RGB space is not linear interpolation in HSV space across hue. This is resolved in this version via a custom specific-use shader, which is a first in framework, so I'm not sure whether it'll be accepted. Other implementations I've seen [use custom texture generation](https://github.com/Flutterish/Hitokori/blob/d876be5dbf84a0fd342ac82ec22540c9d3b30b41/Hitokori/UI/ColorPickerControl.HuePicker.cs#L34), which to me seems pretty much just like a shader, but slower.

There are unfortunately some gotchas in the bindable flow and layout code that needed inline commentary, but I don't think any of it looks *that* bad.

The hex part, as well as the combined component, will be coming in subsequent PRs. I split this since both the HSV and the hex part have their own behaviours that need separate consideration. And this diff is over 600 lines already.

2021-06-06 12:49 UTC, gagahpangeran commented
I get this flicker in saturation selector and can reproduce it consistently.

https://user-images.githubusercontent.com/4964985/120924900-36e77d00-c700-11eb-869b-f94f28a3d51c.mp4

2021-06-06 13:24 UTC, bdach commented
That looks like hue wrapping around back to 0 when it hits 360... I'll see if I can manage to special-case it somehow, probably similarly to the saturation hack. Disappointing that it happens but alas, with the way colours are stored in floats this sort of thing is bound to pop up.

2021-06-06 15:43 UTC, bdach commented
I believe the case mentioned above should be fixed now. Part of it was indeed the particular kink of HSV that a hue of 0 and a hue of 1 are functionally equivalent (and so adding that check still makes sense, e.g. in the case that `Current` is externally mutated, since `.ToHSV()` would basically have to guess whether to return 0 or 1 otherwise), but a part of it was that I was allowing the following circular bindable updates:

```
saturation/value changed -> current changed -> hue changed
```

so I fixed both things. The 0/1 hue check suffices to fix, but I figured I'd want to reduce circular updates anyway as an optimisation anyway.

2021-06-08 07:42 UTC, peppy commented
One scenario I can think of which this doesn't currently lend well to is showing a preview of the colour adjacent to the hue selector. The layout is very "locked-in" with the non-basic implementation.

![20210608 164134 (Adobe Photoshop 2021)](https://user-images.githubusercontent.com/191335/121143812-67522700-c878-11eb-8110-7d349df3ce3b.png)

I can imagine we want to show a box like this, and the obvious place for it to go would be next to the hue selector (making the hue selector less wide). But I guess we could put it beside the whole control like photoshop does if that's preferred? Main concern being the preview in the saturation selector is so small it's hard to even tell if you're getting a preview of the colour or if it's just transparent and showing the saturation gradient from the selector.

2021-06-08 08:02 UTC, peppy requested changes
Just some minor code quality changes.

2021-06-08 08:02 UTC, peppy commented on osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
> +                Hue.Value = value;
```suggestion
                Hue.Value = localSpacePosition.X / DrawWidth;
```

2021-06-08 08:02 UTC, peppy commented on osu.Framework/Resources/Shaders/sh_Utils.h
> +}
Not sure if it matters, but probably best to add a newline here to match other shaders. Never know what platforms this might break >_>.

2021-06-08 08:04 UTC, bdach commented on osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
> +                background = new Box
Sure, I'll also nix `BackgroundColour` then as it will no longer be necessary.

2021-06-08 08:05 UTC, bdach commented on osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
> +        public abstract class SaturationValueSelector : CompositeDrawable
Yeah it was a tough one. I didn't necessarily want to pollute the namespace with several color picker-specific subcomponents since I already split the HSV and hex parts. I'm fine with splitting - maybe to a separate sub-namespace? That doesn't make much sense though does it...

2021-06-08 08:08 UTC, peppy commented on osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
> +                background = new Box
Oh I didn't see that that was already a thing. Probably better to just expose the background box though, yeah.

2021-06-08 08:37 UTC, bdach commented on osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
> +        public abstract class SaturationValueSelector : CompositeDrawable
Tried the partial class way for both the hue and SV selectors and ended up liking it, so that's in this pull now.

2021-06-08 08:46 UTC, peppy approved these changes
Seems fine

2021-06-10 08:02 UTC, merged