Add hex colour picker
ppy/osu-framework pull request #4506
Opened 2021-06-11 22:06 UTC by bdach

Another part of #3134. The last part will be combining the two, which is basically a glorified way of saying "two `.BindTo()` calls with extra steps".

https://user-images.githubusercontent.com/20418176/121752419-60454600-cb10-11eb-9b87-dfba104a5b07.mp4

A note on the UX of this: Signaling input errors better than just discarding the value input by the user - by flashing the text box or otherwise - would definitely make this feel better, but the issue is that the structure of `TextBox` does not support that very well. What I mean by that is that both the things that control the appearance of it, and the things that control its behaviour wrt input validity (`NotifyInputError()`, `CanAddCharacter(char)`) are driven by virtual members.

So I cannot really define just the latter without the former, because that would require either multiple inheritance (impossible in this language, at least right now), or reimplementation of either the appearance or the validation logic by consumers.

If it is deemed necessary, I'll take the detour and try to fix the state of `TextBox` to decouple inherited validation logic from inherited appearance, but it'll end up being a fair few breaking changes I imagine.

However, if it's some consolation, from my experience image editing software (photoshop, GIMP) hex colour entry controls seem to work in an extremely similar manner to this.

2021-06-11 22:20 UTC, frenzibyte commented
Yeah I think the current UX of the textbox is fair enough.

2021-06-14 04:33 UTC, peppy requested changes
Looks good otherwise.

2021-06-14 04:33 UTC, peppy commented on osu.Framework/Graphics/UserInterface/BasicHexColourPicker.cs
> +                Current.BindValueChanged(_ => updatePreview());
I think this needs a `true` argument here? Looks like there a potential the initial colour display could be forgotten based on operation order. I think with the way you have the decoupled bindable setup right now it's likely fine, but also no harm in making sure.

2021-06-15 00:42 UTC, peppy approved these changes

2021-06-15 00:50 UTC, merged