Expose an event from `GameHost` before update thread changes native threads
ppy/osu-framework pull request #4533
Opened 2021-06-22 09:10 UTC by peppy

PRing for comment. Intended to be used as a way for realm to clean up after itself.

Not sure if we want to instead expose somewhere in `GameThread` itself.

2021-06-22 10:44 UTC, smoogipoo requested changes
Seems fine otherwise.

2021-06-22 10:44 UTC, smoogipoo commented on osu.Framework/Platform/GameHost.cs
> +                if (ExecutionState >= ExecutionState.Running)
Nit: Perhaps `> ExecutionState.Stopped` instead? Should throw if it's stopping but not yet stopped.

2021-06-22 10:46 UTC, peppy commented
I've added a bit of discussion on discord that means this function will likely have to change. Basically, it turns out that `Update` frames can run on the old update thread even after this event is called. So the API will either need to be a set of two events exposed (`UpdateThreadChanging` -> `UpdateThreadChanged`) or some other equivalent that guaranteed states...

2021-06-22 10:48 UTC, smoogipoo commented
I was originally going to ask why this wasn't done in `ThreadRunner` itself. An event that's run at the end of `ensureCorrectExecutionMode` - doesn't matter if it's run on update or whatever (have the binder decide where to schedule it).

It could be re-exposed through `GameHost` but the idea is the original event comes from `ThreadRunner`.

2021-06-22 10:49 UTC, peppy commented
Yeah, that sounds better. I'll take a look at updating to do so.

2021-06-22 17:50 UTC, bdach commented on osu.Framework/Threading/GameThread.cs
> +            ThreadPausing?.Invoke();
While this works, how about making this method private non-virtual (and making the draw thread subscribe itself to the event to release the GL context)? Would remove a bit of complexity in this setup and ensure there can be no funny business wrt something overriding `OnPause()` and accidentally breaking contract of `ThreadPausing` by suppressing a base call or something.

Maybe a bit of a paranoid one but the GL context release regression made me a bit paranoid about this sort of pattern of side effects via overrides as `GameThread`s have a lot of those and it feels a bit like walking a minefield at times...

2021-06-23 00:03 UTC, peppy commented on osu.Framework/Threading/GameThread.cs
> +            ThreadPausing?.Invoke();
i figured it was seldom modified code so should not be an issue, but can change that i guess. self subscription is a weird pattern to me so i tend to avoid it when writing code.

2021-06-23 03:39 UTC, bdach commented on osu.Framework/Threading/GameThread.cs
> +            ThreadPausing?.Invoke();
Fair call. I'm not insisting on this change, it can stay as is. Hopefully it shouldn't ever matter.

2021-06-23 08:52 UTC, smoogipoo approved these changes

2021-06-23 08:53 UTC, merged