Add shader disposal support
ppy/osu-framework pull request #4539
Opened 2021-06-23 09:26 UTC by frenzibyte

Closes #4534 

Follows the existing pattern for GL disposal, if a `Shader`/`ShaderPart` gets finalised, the 3-frame delay will be applied, but if it's explicitly disposed, then there won't be any delay from the class itself, it would come from whatever's disposing of it internally (the `ShaderManager` in this case).

Also added a simple test case ensuring `Shader` references aren't leaked after disposing of `ShaderManager` (which heavily depended on doing https://github.com/ppy/osu-framework/commit/cd36ea3b8608aaa305603c0763c142a2ffd063f9 for testing without GL context, kinda ugly but needed).

2021-06-23 19:29 UTC, bdach requested changes
Not overly familiar with this area but I'll have a go...

2021-06-23 19:29 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +        protected virtual void DeleteProgram(int id)
Not too sure about exposing these for the tests so widely. Maybe these should be `private protected`. Nothing outside the framework assembly/a subclass should be overriding these.

2021-06-23 19:29 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                DeleteProgram(this);
I think these are missing a `id != 1` check, which is now a case that has to be potentially handled as this is possibly being called from the finaliser and therefore there are no more guarantees about object state anymore. Not to mention the program might not even have been compiled yet.

2021-06-23 19:29 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> -        private IUniform[] uniformsArray;
I was skeptical about this removal (clearly this had some purpose), so I checked blame and found https://github.com/ppy/osu-framework/commit/9a3f310f75cbf8d4a6a0723cd908752f0a9515b9. So it looks like this should be benchmarked to check whether using the value collection isn't causing a performance regression, if not outright reverted.

I'm not sure what this change has to do with the rest of this pull anyway.

2021-06-23 19:29 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +        }
Because `Compile()` bails if the shader is disposed, `EnsureLoaded()` does not in fact ensure that the shader is loaded. I imagine this may be a problem in all call sites that expect that to be the case.

2021-06-23 21:24 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                DeleteProgram(this);
It's actually checked inside of the method but that looks weird reading it again, will change.

2021-06-23 21:25 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +        protected virtual void DeleteProgram(int id)
That's the one I was looking for.

2021-06-23 21:26 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> -        private IUniform[] uniformsArray;
Good find, thought it isn't necessary compared to just `Uniforms.Values` but it appears I'm wrong. Wondering if enumerating on `Uniforms` then `kvp.Value.Update()` would also not be good?

2021-06-23 21:29 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +        }
Seems like it should throw in here as well, `EnsureLoaded` must not be called if the shader has already been disposed of.

2021-06-24 01:00 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> -        private IUniform[] uniformsArray;
```
|                            Method | ItemCount |       Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------------------- |---------- |-----------:|----------:|----------:|------:|------:|------:|----------:|
|         EnumerateDictionaryValues |      1000 | 3,769.5 ns | 151.16 ns | 443.33 ns |     - |     - |     - |         - |
| EnumerateDictionaryAndAccessValue |      1000 | 4,721.2 ns | 133.93 ns | 386.43 ns |     - |     - |     - |         - |
|                    EnumerateArray |      1000 |   551.7 ns |  11.08 ns |  31.25 ns |     - |     - |     - |         - |
```

Ok that shocked me... TIL.

2021-06-24 02:34 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +        }
I've refactored that area a bit as I didn't actually intend `Compile()` to silently bail when the shader is disposed of, should be in a good state now.

2021-06-24 23:15 UTC, frenzibyte commented
Blocking momentarily while I figure out what's causing `Shader` references to still remain even though the manager is disposed of, scary enough that it happens on a real `Shader`, not a `TestShader` (even though the abstraction was meant in a way that doesn't result in differentiation between both classes).

2021-06-25 01:08 UTC, frenzibyte commented
Turns out it was due to the test scene stupidly forces a silent `Shader` compile before the `GLWrapper` scheduled one, resulting in compiling twice and registering to `GlobalPropertyManager` twice.

I have solved that in multiple ways, by:
 - Guarding in `Shader.Compile` to never recompile again, 
 - Guarding in `GlobalPropertyManager` to not add shader twice (not sure if `all_shaders` should actually exist in the first place, GC purposes?), 
 - And privatizing `Shader.Compile`, to be replaced with using `EnsureShaderCompiled` instead (all internally).

2021-07-03 16:12 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                throw new InvalidOperationException("Attempting to compile already compiled shader.");
```suggestion
                throw new InvalidOperationException("Attempting to compile an already-compiled shader.");
```

2021-07-03 16:12 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +            parts.RemoveAll(p => p == null);
What is this?

2021-07-03 16:12 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                shaderCompileDelegate.RunTask();
This looks dodgy/racey at first glance (even if the internal logic of `ScheduledDelegate` ensures that this won't do the wrong thing on accident). Should probably use `State` of the delegate directly.

2021-07-03 16:14 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +            parts.RemoveAll(p => p == null);
Dunno, another pre-existing thing, can remove if it's deemed redundant (I believe it to be so).

2021-07-03 16:25 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +            parts.RemoveAll(p => p == null);
I didn't notice that it was there before, fair enough. Probably not going to insist on having it removed since it's been there since the first commit of framework...

2021-07-04 12:56 UTC, frenzibyte commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                shaderCompileDelegate.RunTask();
`State == Waiting` you mean? otherwise, I don't follow.

2021-07-04 12:59 UTC, bdach commented on osu.Framework/Graphics/Shaders/Shader.cs
> +                shaderCompileDelegate.RunTask();
Correct.

2021-07-05 05:38 UTC, smoogipoo approved these changes
I'm not a super big fan of the `private protected virtual` stuff, but let's go with this for now.

2021-07-05 05:54 UTC, merged

2021-07-05 07:01 UTC, frenzibyte commented
> I'm not a super big fan of the `private protected virtual` stuff, but let's go with this for now.

Yeah without doubts, I'm not really sure what's the reason behind making all of them internal, but sounds like they should be separated in some better way, something like `Texture` and `TextureGL` maybe, needs investigation at some point.