Expose virtual method in `MarkdownImage`
ppy/osu-framework pull request #4547
Opened 2021-06-28 09:31 UTC by gagahpangeran

In order to resolve https://github.com/ppy/osu/issues/13418, need these method so I can override some parts in `MarkdownImage`

I don't have the solution for the actual issue yet, still figuring out about it.

2021-06-28 09:43 UTC, peppy commented
Will wait to see how these are used before merging. You are aware of how to use a local framework checkout yeah?

2021-06-28 09:44 UTC, gagahpangeran commented
Yeah, PR-ing this for visibility now.

2021-06-28 09:46 UTC, frenzibyte commented
Probably worth getting a working implementation first, then start PR'ing the required parts for discussing it. (since either way, the usage of these changes is probably required for considering this and whether it should be abstracted this way etc.)

2021-06-29 06:11 UTC, smoogipoo requested changes

2021-06-29 06:11 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/Markdown/MarkdownImage.cs
> +            protected virtual Sprite CreateSpriteImage() => new Sprite();
I think `CreateImageSprite()` makes more sense.

2021-06-30 10:02 UTC, smoogipoo approved these changes

2021-06-30 11:33 UTC, merged