Add support for localising `IFormattable` objects
ppy/osu-framework pull request #4550
Opened 2021-06-29 10:57 UTC by frenzibyte

Introduces a `LocalisableFormattable` class, containing the `IFormattable` object and the format string, and a method for formatting the `IFormattable` with the provided format provider.

Allowing for localising any `IFormattable` object (integers, floats, `DateTime`s, etc...) with the currently selected locale, like in [here](https://github.com/ppy/osu/commit/feb67bee58f071c0cfddba75dccdaf648275a0e5) for example.

2021-06-29 11:40 UTC, smoogipoo requested changes

2021-06-29 11:40 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +                        break;
I don't want to see another case being added here, or anywhere in the other places it's been added.

- There needs to be an `ILocalisableStringData` interface which these "data" classes implement.
- `LocalisableString` needs to have a ctor or static method to convert from an `ILocalisableStringData` type.
- The data types need to have implicit operators to convert to `LocalisableString` via said ctor/static method.
- The interface needs to have methods for doing the localisation. No more `.GetPreferred()`/`.Format()`/`.ToString()` - just one method common to the data type interface.

2021-06-29 11:40 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
> +                    break;
I believe all of this code is actually completely pointless, and could just be `hashCode.Add(obj.GetHashCode())`.

Need to run through `BenchmarkLocalisableString`, and add more cases to the benchmark for different types.

2021-06-29 11:40 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
>              return false;
This should really fall back to `object.Equals(...)` with a `#pragma warning disable` around it.

2021-06-29 11:42 UTC, smoogipoo commented
Honestly, I quite liked the original version using delegates because it could also be humanised. Which may have made the changes I proposed less important but still favourable to have.

2021-06-29 11:49 UTC, frenzibyte commented
Where's the original version you're talking about, for reference?

2021-06-29 11:52 UTC, smoogipoo commented
The one in https://github.com/ppy/osu/issues/13559#issuecomment-869936958

2021-06-29 11:57 UTC, bdach commented
For what it's worth I proposed in that issue thread that the `ToString()` method here could be made virtual and then overridden to call `.Humanize()` instead. But I still really want this structure to be data-backed in some way, and not basing it's equality operator on frivolously-allocated delegates all over.

2021-06-29 12:00 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +                        break;
Yeah the current implementation is quite inextensible with all the hardcoded cases in place. Didn't want to do it in this PR, but I see no reason not to do it right now and clean up the hardcoded mess.

2021-06-29 12:03 UTC, smoogipoo commented
I see, that's fair enough - I agree that a virtual `.ToString()` works better than the delegate. The rest of the comments I made above regarding the interface are still applicable for that to happen.

2021-06-29 13:28 UTC, smoogipoo commented on osu.Framework/Localisation/ILocalisableStringData.cs
> +        string GetLocalised(ILocalisationStore? store, bool preferUnicode);
I suggest exposing the bool from the store and leaving one parameter.

2021-06-29 13:29 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableString.cs
> -        public static implicit operator LocalisableString(LocalisableFormattable formattable) => new LocalisableString(formattable);
Keep these ones in if they can be, to prevent breaking changes.

2021-06-29 13:29 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableString.cs
> -        public static implicit operator LocalisableString(LocalisableFormattable formattable) => new LocalisableString(formattable);
I've moved them to each class, unless that still results in a breaking change I'm failing to see?

2021-06-29 13:38 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableString.cs
> -        public static implicit operator LocalisableString(LocalisableFormattable formattable) => new LocalisableString(formattable);
```
C c = new D();

----------------

public class C
{
    public void M()
    {
    }

    public static implicit operator C(D d) => new C();
}

public class D
{
}

IL_00cb: newobj       instance void D::.ctor()
IL_00d0: call         class C C::op_Implicit(class D)
IL_00d5: stloc.2      // c

----------------

public class C
{
    public void M()
    {
    }
}

public class D
{
    public static implicit operator C(D d) => new C();
}

IL_00cb: newobj       instance void D::.ctor()
IL_00d0: call         class C D::op_Implicit(class D)
IL_00d5: stloc.2      // c
```
So yes, at an IL level implicit operators are just `op_Implicit` method calls on one of the classes.

It seems like you can't define implicit conversions in both classes, so perhaps we leave the ones that are currently where they are, where they are.

2021-06-29 13:56 UTC, frenzibyte commented on osu.Framework/Localisation/ILocalisableStringData.cs
> +        string GetLocalised(ILocalisationStore? store, bool preferUnicode);
Exposing the bool from the store doesn't seem straightforward to do, unless it's fine to pass around the `FrameworkConfigManager` / bindable to each localisation store at construction.

And in the end, it doesn't really make sense to have that there... if you're proposing this to avoid adding more parameters here and causing breaking changes, maybe an args class would help?

Alternatively, I could pass the `LocalisationManager` here (maybe as `ILocalisationManager` for staying read-only) and avoid the args class.

2021-06-29 13:58 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
>              return false;
Is this still valid after adding the `ILocalisableStringData`? that already allows for implementing equality comparison at each data class implementing that interface.

2021-06-29 14:41 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
> +                    break;
I guess the purpose is for benchmarking equality and mainly hash code calculation of the classes themselves, yeah? i.e.:
```
|                           Method |     Mean |    Error |    StdDev |   Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------------------- |---------:|---------:|----------:|---------:|------:|------:|------:|----------:|
|       BenchmarkRomanisableEquals | 16.85 ns | 0.040 ns |  0.034 ns | 16.85 ns |     - |     - |     - |         - |
|      BenchmarkTranslatableEquals | 16.78 ns | 0.040 ns |  0.037 ns | 16.78 ns |     - |     - |     - |         - |
|       BenchmarkFormattableEquals | 40.95 ns | 7.437 ns | 21.928 ns | 32.95 ns |     - |     - |     - |         - |
|  BenchmarkRomanisableGetHashCode | 85.81 ns | 4.947 ns | 14.353 ns | 84.85 ns |     - |     - |     - |         - |
| BenchmarkTranslatableGetHashCode | 85.34 ns | 4.975 ns | 14.592 ns | 86.99 ns |     - |     - |     - |         - |
|  BenchmarkFormattableGetHashCode | 46.82 ns | 2.662 ns |  7.765 ns | 44.52 ns |     - |     - |     - |         - |
```
is that enough benchmarks?

2021-06-29 14:41 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
> +                    break;
Yep that's fine.

2021-06-29 15:15 UTC, bdach commented on osu.Framework/Localisation/ILocalisableStringData.cs
> +        string GetLocalised(ILocalisationStore? store, bool preferUnicode);
Only one implementation seemingly cares about `preferUnicode`, and it's `RomanisableString`, so this definitely looks bad slapped on this interface.

My gut feeling is that this interface is maybe too unified now, and the romanisable case maybe should still remain independent. But I'd be fine with passing in the config manager through this interface, too.

Not sure what passing in the localisation manager would even do in this context; its bindables are private and should arguably remain so.

2021-06-29 15:22 UTC, frenzibyte commented on osu.Framework/Localisation/ILocalisableStringData.cs
> +        string GetLocalised(ILocalisationStore? store, bool preferUnicode);
If we can pass the localisation manager (as readonly), we can expose the `PreferUnicode` bindable from there instead of passing the framework config manager, I think of it as a cleaner way, but the other way also works and I don't mind it.

2021-06-29 15:25 UTC, bdach commented on osu.Framework/Localisation/ILocalisableStringData.cs
> +        string GetLocalised(ILocalisationStore? store, bool preferUnicode);
I don't like the idea of re-exposing config settings via public members on non-config classes too much. Dunno if there is a precedent for that already that I don't know about, but it messes with separation of concerns a bit too much if you ask me.

2021-06-29 15:30 UTC, bdach commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +        public bool Equals(ILocalisableStringData? other)
Is there a reason why `Equals(LocalisableStringData?)` and `Equals(object?)` aren't just a:

```csharp
other is LocalisableFormattable otherFormattable && Equals(otherFormattable);
```

2021-06-29 15:35 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +        public bool Equals(ILocalisableStringData? other)
I guess, I wasn't sure which pattern the equality logic should follow given that `TranslatableString` and `RomanisableString` used one that's quite different from what we usually use here and osu!-side (`ReferenceEquals` rather than pattern-matching).

2021-06-29 20:41 UTC, bdach requested changes

2021-06-29 20:41 UTC, bdach commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
Ok, well, perhaps partially my bad for giving a bad suggestion, but this doesn't make much sense now, does it? Now both this bindable string and `RomanisableString` are reading the same config setting but separately, and it causes this warning disable and a whole mess of other awkwardnesses (like semi-pointlessly holding onto a reference to `config`...)

May be indeed best to cut losses at this point and expose the setting (as internal!) in `LocalisationManager`...

2021-06-29 20:41 UTC, bdach commented on osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
> +            hashCode.Add(obj.Data);
Can replace with a `HashCode.Combine()`

2021-06-29 20:44 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
> May be indeed best to cut losses at this point and expose the setting (as internal!) in LocalisationManager...

Yep, also keeps things in scope and allows for exposing further game-specific settings if wanted/needed.

2021-06-29 21:13 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
Actually, my bad on the reference holding part, could have just instantiated a local bindable and did `Config.BindWith` (which appears to not spark that inspection).

But either way, here's how it looks with the `LocalisationManager` (passed as `ILocalisationManager`) instead https://github.com/ppy/osu-framework/commit/f388d7138545d3cb413464ec07657024fedc2571, will leave it to you if you think it's an improvement.

2021-06-29 21:15 UTC, bdach commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
Not sure, feels half-way. Maybe the localisation store should also be exposed via the interface to keep 1 param instead of 2. Other opinions welcome.

2021-06-30 07:02 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
I've implemented my original vision of how this method should look (a72b44d6ec8491a68c6eed594d64ef70376777fc), please check it out and see if you agree.

2021-06-30 07:22 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +            private readonly IBindable<bool> preferUnicode;
I've applied a simple change to avoid the ReSharper inspection suppression, but looks pretty good overall, and allows for extensibility better than the other ways above.

2021-06-30 07:40 UTC, smoogipoo commented
Benchmark results (making sure there's no regression between `(string)"a"` and `(LocalisableString)(string)"a"`):
```
|                                Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------------- |----------:|----------:|----------:|------:|------:|------:|----------:|
|                 BenchmarkStringEquals |  4.075 ns | 0.0377 ns | 0.0314 ns |     - |     - |     - |         - |
|      BenchmarkLocalisableStringEquals |  7.042 ns | 0.0423 ns | 0.0396 ns |     - |     - |     - |         - |
|            BenchmarkRomanisableEquals | 13.177 ns | 0.2306 ns | 0.2157 ns |     - |     - |     - |         - |
|           BenchmarkTranslatableEquals | 10.599 ns | 0.0247 ns | 0.0231 ns |     - |     - |     - |         - |
|            BenchmarkStringGetHashCode |  2.165 ns | 0.0019 ns | 0.0015 ns |     - |     - |     - |         - |
| BenchmarkLocalisableStringGetHashCode | 18.292 ns | 0.1584 ns | 0.1323 ns |     - |     - |     - |         - |
|       BenchmarkRomanisableGetHashCode | 31.252 ns | 0.5610 ns | 0.5247 ns |     - |     - |     - |         - |
|      BenchmarkTranslatableGetHashCode | 39.200 ns | 0.3968 ns | 0.3518 ns |     - |     - |     - |         - |

After:

|                                Method |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------------- |----------:|----------:|----------:|------:|------:|------:|----------:|
|                 BenchmarkStringEquals |  4.367 ns | 0.0135 ns | 0.0120 ns |     - |     - |     - |         - |
|      BenchmarkLocalisableStringEquals |  7.026 ns | 0.0256 ns | 0.0239 ns |     - |     - |     - |         - |
|            BenchmarkRomanisableEquals | 14.885 ns | 0.2912 ns | 0.2582 ns |     - |     - |     - |         - |
|           BenchmarkTranslatableEquals | 15.184 ns | 0.2584 ns | 0.6039 ns |     - |     - |     - |         - |
|            BenchmarkFormattableEquals | 15.978 ns | 0.0047 ns | 0.0041 ns |     - |     - |     - |         - |
|            BenchmarkStringGetHashCode |  2.165 ns | 0.0009 ns | 0.0007 ns |     - |     - |     - |         - |
| BenchmarkLocalisableStringGetHashCode | 11.798 ns | 0.2674 ns | 0.4003 ns |     - |     - |     - |         - |
|       BenchmarkRomanisableGetHashCode | 19.493 ns | 0.3032 ns | 0.2688 ns |     - |     - |     - |         - |
|      BenchmarkTranslatableGetHashCode | 26.869 ns | 0.0941 ns | 0.0834 ns |     - |     - |     - |         - |
|       BenchmarkFormattableGetHashCode | 20.660 ns | 0.2058 ns | 0.1925 ns |     - |     - |     - |         - |
```

2021-06-30 07:40 UTC, smoogipoo submitted a review, later dismissed
Lgtm

2021-06-30 07:40 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
Maybe `LocalisableFormattableString` is a better fit?

2021-06-30 07:42 UTC, bdach commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
No strong feelings either way here.

2021-06-30 07:43 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
For comparison, the .NET type (for interpolated strings) is `FormattableString`.

2021-06-30 08:02 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
been wondering how humanisable strings will be named, `LocalisableHumanisable`? `LocalisableHumanisableString`?

2021-06-30 08:03 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
I was thinking `HumanisableString`, actually. I was also thinking `FormattableString` here, but that would conflict with the .NET name, which _may_ be fine since `FormattableString` is a very rarely used thing anyway.

2021-06-30 08:08 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
I wasn't sure because `RomanisableString` and `TranslateableString` are both names that fit correctly and imply being from the localisation system, but names like `HumanisableString` and `FormattableString` feel like they're not conveying enough they're localisable or in the localisation system... that's why I agreed with the original proposal of naming it `LocaliasbleFormattable`.

Not a big deal either way, maybe it makes sense to drop the `Localisable` part altogether since the data classes themselves just allow themselves to be "localised" (by implementing the `ILocalisableStringData`).

2021-06-30 18:15 UTC, bdach approved these changes

2021-07-01 07:12 UTC, peppy commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
I definitely thing this should be renamed to either `FormattableString` or `LocalisableFormattableString`. Indifferent as to which (second fits the existing classes better, but is long, but probably also rare usage so i don't know).

2021-07-01 07:14 UTC, peppy commented
I'm honestly not sure about the `parameters` flow. At this point it's all a bit hard to understand, but rather than hold things up let's go ahead with it. Just need to sort out the rename issue.

2021-07-01 10:07 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
I believe all usages that do stuff like `number.ToString("N0")` would use this string to display properly per-locale, so the usage may not be too rare... but still better to just consider `LocalisableFormattableString` at this point.

2021-07-01 10:23 UTC, peppy commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
Choose one and go with it. I guess the longer one would be preferable for consistency if no one else want to make a call.

2021-07-01 11:12 UTC, bdach commented on osu.Framework/Localisation/LocalisableFormattable.cs
> +    public class LocalisableFormattable : IEquatable<LocalisableFormattable>, ILocalisableStringData
Agree with longer one.

2021-07-01 19:10 UTC, bdach commented
Have made the name change.

2021-07-05 05:10 UTC, smoogipoo approved these changes

2021-07-05 05:42 UTC, smoogipoo approved these changes

2021-07-05 06:07 UTC, merged