Add factory method creating `BindableWithCurrent`s depending on the value type
ppy/osu-framework pull request #4554
Opened 2021-06-29 20:40 UTC by frenzibyte

Allows for having a `BindableWithCurrent` or `BindableNumberWithCurrent` instance depending on the value type itself, [as proposed here](https://github.com/ppy/osu/issues/13649#issuecomment-870006577).

Initially, I was going to privatize the classes' constructors and force all usages to call `IBindableWithCurrent<T>.Create()` to avoid potentially constructing `BindableWithCurrent<float>` instead of the correct `BindableNumberWithCurrent<float>`, but since that results in severe breaking changes, I've let that as-is for now.

2021-06-29 20:56 UTC, bdach commented on osu.Framework/Bindables/IBindableWithCurrent.cs
> +    public interface IBindableWithCurrent<T> : IBindable<T>
Any reason not to derive `IHasCurrentValue<T>` as well, therefore automatically inheriting the `Current` member without having to declare it?

2021-06-29 20:58 UTC, frenzibyte commented on osu.Framework/Bindables/IBindableWithCurrent.cs
> +    public interface IBindableWithCurrent<T> : IBindable<T>
Yeah can do it, just copied it from there since I felt `IHasCurrentValue<T>` should be for the UI elements specifically (which provide the `BindableWithCurrent`), but honestly no reason not to just inherit it here as well and save up code lines.

2021-06-29 21:01 UTC, bdach commented on osu.Framework/Bindables/IBindableWithCurrent.cs
> +    public interface IBindableWithCurrent<T> : IBindable<T>
It's not even entirely about the line count, it just makes sense to do semantically anyways.

2021-06-30 08:14 UTC, smoogipoo requested changes
Seems good otherwise

2021-06-30 08:14 UTC, smoogipoo commented on osu.Framework/Utils/Validation.cs
> +        internal static bool IsSupportedBindableNumberType<T>() =>
```suggestion
        public static bool IsSupportedBindableNumberType<T>() =>
```

2021-06-30 08:14 UTC, smoogipoo commented on osu.Framework/Bindables/BindableNumber.cs
>              // The check will become NOP after optimization.
Probably delete this, or move it to the `Validation` method.

2021-06-30 09:54 UTC, smoogipoo approved these changes

2021-06-30 10:43 UTC, merged