Reset a StepSlider to its default value when right-clicked
ppy/osu-framework pull request #4593
Opened 2021-07-11 12:52 UTC by HoLLy-HaCKeR

Allows the user to right-click a SliderStep in the test browser to reset it to its default value.

2021-07-11 13:53 UTC, bdach requested changes

2021-07-11 13:53 UTC, bdach commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (e.Button.HasFlagFast(MouseButton.Right))
`MouseButton` isn't a flag enum, so using `HasFlagFast` in this context is actively misleading.

```suggestion
            if (e.Button == MouseButton.Right)
```

This should also probably not fire when a drag is in progress, because it doesn't really work that well in that case.

2021-07-11 14:36 UTC, HoLLy-HaCKeR commented
Applied feedback. I'm willing to change the right-click to something else if it's better UX-wise, it just what seemed most natural to me.

2021-07-11 14:43 UTC, bdach submitted a review, later dismissed
Okay with this. As was said on discord, right click seems a bit of a weird interaction to choose for reset but given it's a test scene usage I'm not really willing to belabor that further.

2021-07-12 05:52 UTC, peppy requested changes

2021-07-12 05:52 UTC, peppy commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (!IsDragged && e.Button == MouseButton.Right)
This `IsDragged` check isn't going to be doing anything. A drawable doesn't become dragged until *after* the initial mousedown.

2021-07-12 06:01 UTC, bdach commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (!IsDragged && e.Button == MouseButton.Right)
I'm pretty sure I tested and this worked as expected...

Seems to check out against code, too. Drag handling seems to actually run on position changes (see mouse button event manager's `HandlePositionChange`)...?

2021-07-12 06:17 UTC, peppy commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (!IsDragged && e.Button == MouseButton.Right)
How did you test? I can't imagine a scenario where `IsDragged` becomes `true` before `OnMouseDown`. It would require two mouse events to be handled at once, before the mouse down, with a default movement of 10 screen pixels.

2021-07-12 06:34 UTC, bdach commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (!IsDragged && e.Button == MouseButton.Right)
I did the obvious thing - start dragging with left mouse, press right mouse, check that the reset didn't fire.

I suppose that does make two mouse down events. Unsure in which scenario this could fail (is dragging with right mouse even a thing?)

2021-07-12 06:37 UTC, peppy commented on osu.Framework/Testing/Drawables/Steps/StepSlider.cs
> +            if (!IsDragged && e.Button == MouseButton.Right)
Aha, dragging is a shared state in this case. Will add an inline comment mentioning this, as I obviously found it a bit confusing as-is.

2021-07-12 06:38 UTC, peppy approved these changes

2021-07-12 07:02 UTC, merged