Add ability to change case of a `LocalisableString`
ppy/osu-framework pull request #4603
Opened 2021-07-13 17:43 UTC by Game4all

Here is an initial implementation of case transformations for  `LocalisableString` as per the direction that was proposed in discussion of #4599. `LocalisableString` stores along its string data the case to apply on the final computed string in the `LocalisedBindableString`. 

Note that the case is intentionally set to `Default` for strings constructed from a plain string to allow casing the plain string using the BCL methods. Also, methods to change case of `LocalisableString` are implemented as extensions methods on `ILocalisableStringData` to construct a `LocalisableString` wrapping the data with the correct case instead of on the `LocalisableString`, since it's immutable anyway. This results in a syntax similar to string's one when dealing with `TranslatableString`.

2021-07-14 01:04 UTC, smoogipoo requested changes

2021-07-14 01:04 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
I don't like this existing in `LocalisableString`. It makes more sense in `TranslatableString` because those strings are coming from a different location.

2021-07-14 01:04 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
> +                        Value = applyCase(data.GetLocalised(parameters.Value));
Likewise, this would only exist internal to `TranslatableString`.

2021-07-14 02:15 UTC, frenzibyte commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
There's only one case I can think of where having this as-is would help (or even bringing back the proposed `TextTransform` property), and that is localisable formatted strings.

Moving this to `TranslatableString` will limit the possibility of having uppercase'd date formatted string (for example).

2021-07-14 02:20 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
For niche use cases like that, I would expect an override of `LocalisableFormattableString`. The main point is that I don't want to increase the size of `LocalisableString` itself.

2021-07-14 02:55 UTC, peppy commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
Agree with moving it. As per original discussion I was implying the implementation wouldn't necessarily be in the `LocalisableString` base class. I think `TranslateableString` is a good home for it for now.

2021-07-14 02:58 UTC, smoogipoo commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
From another perspective, I don't know how this is going to work with the localisation analyser... Is this the reason it was done this way?

2021-07-14 11:19 UTC, Game4all commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
I guess I may throw in the the rationnale for the proposed changes: basically the goal was to be able to allow changing the case of the final localised text whatever the underlying string type may be while providing an API mimicking somewhat how it is done with `string`. 

Moving this case stuff to a common class crossed my mind for a time but I decided still to store case info in `LocalisableString` itself to provide a `string` like API for any localisable string type (as long as it implements `ILocalisableStringData`) through extension methods. I understand the concern about keeping the struct size small but I think it doesn't add a too big overhead (4 bytes + the 8 previous bytes from the nullable string data) but I can certainly give a shot at moving case transform to a common class ...

2021-07-14 13:18 UTC, bdach commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
Another seemingly possible avenue that may be worth exploring is composition via the decorator pattern, eg. have a `LocalisableStringWithCasing` which accepts another `LocalisableString` and applies the casing convention to it.

2021-07-14 15:53 UTC, Game4all commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
I like this one altough declarations will get a bit long in some cases but adding extensions methods to `ILocalisableString` to wrap the string with the specified case should cover it.

2021-07-14 16:33 UTC, Game4all commented on osu.Framework/Localisation/LocalisableString.cs
> +        public readonly Casing Casing;
Just pushed what may be a potential implementation of the direction described above.

2021-07-14 16:43 UTC, frenzibyte requested changes
Few *small* details with the implementation, but sounds to be a good direction.

2021-07-14 16:43 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +        /// <param name="casing"></param>
Incomplete param docs

2021-07-14 16:43 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +        public TransformableString(ILocalisableStringData data, Casing casing)
Should accept a `LocalisableString` instead, all translatable strings defined in the `Strings` cases game-side are already implicitly converted to type `LocalisableString`:

![CleanShot 2021-07-14 at 19 39 51](https://user-images.githubusercontent.com/22781491/125659856-d038dd89-4fbc-4f49-b6dd-e44c1f639d5b.png)

2021-07-14 16:43 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +        public string GetLocalised(LocalisationParameters parameters)
Should match the rest of the string data implementations, for consistency purposes:
 - `ToString` returns cased strings with invariant culture.
 - `GetLocalised` returns cased strings with given culture, and falls back to `ToString` if the store is null.

2021-07-14 17:06 UTC, bdach commented on osu.Framework/Localisation/TransformableString.cs
> +        public TransformableString(ILocalisableStringData data, Casing casing)
Disagree with this. Doing this would force the extension methods to also accept `LocalisableString`s, which doesn't work with usages in which the type on which the extension is being called is not `LocalisableString` (i.e. the test added here does not compile).

2021-07-14 17:13 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +        public TransformableString(ILocalisableStringData data, Casing casing)
OK, this shouldn't actually force to accept a `LocalisableString`, but instead have an overload for each extension to accept `LocalisableString` and delegate that to `string.Data.ToXYZ();`.

Otherwise this won't work on usages, which I believe would be:
```csharp
Text = ButtonSystemStrings.Solo.ToTitle();
```

2021-07-14 17:15 UTC, bdach requested changes

2021-07-14 17:15 UTC, bdach commented on osu.Framework/Localisation/TransformableString.cs
> +    public enum Casing
Bit thrown off by the varying capitalisation of these enum members. Would stick to `UpperCase`, `LowerCase`, `TitleCase`.

2021-07-14 17:15 UTC, bdach commented on osu.Framework/Localisation/TransformableString.cs
> +    public class TransformableString : IEquatable<TransformableString>, ILocalisableStringData
Not super sold on this name. It doesn't mention casing in any way.

2021-07-14 17:15 UTC, bdach commented on osu.Framework.Tests/Localisation/LocalisationTest.cs
> +            config.SetValue(FrameworkSetting.Locale, "en");
Test coverage is needed for non-English locales/implementations of `To{Lower,Upper}`, ie.

```
> new System.Globalization.CultureInfo("en").TextInfo.ToUpper("this text has an i in it")
"THIS TEXT HAS AN I IN IT"

> new System.Globalization.CultureInfo("tr").TextInfo.ToUpper("this text has an i in it")
"THİS TEXT HAS AN İ İN İT"

> new System.Globalization.CultureInfo("en").TextInfo.ToLower("THIS TEXT HAS AN I IN IT")
"this text has an i in it"

> new System.Globalization.CultureInfo("tr").TextInfo.ToLower("THIS TEXT HAS AN I IN IT")
"thıs text has an ı ın ıt"
```

2021-07-14 17:39 UTC, Game4all commented on osu.Framework/Localisation/TransformableString.cs
> +        public TransformableString(ILocalisableStringData data, Casing casing)
Actually we may want to take a `LocalisableString` instead of the localisable string interface since `LocalisableString` can be constructed with a plain string. We may want to have overloads for both  `LocalisableString` and the interface for extensions methods.

2021-07-14 17:39 UTC, bdach commented on osu.Framework/Localisation/TransformableString.cs
> +        public TransformableString(ILocalisableStringData data, Casing casing)
Both is fine, I think.

2021-07-15 01:57 UTC, smoogipoo requested changes
I think the path taken now is good though. As you said, it should definitely take a `LocalisableString` as ctor param instead, and probably change the extension methods to `LocalisableString`.

2021-07-15 01:57 UTC, smoogipoo commented on osu.Framework/Localisation/TransformableString.cs
> +            return Casing == other.Casing && Data == other.Data;
Use `Data.Equals(other.Data)` instead.

2021-07-15 19:02 UTC, Game4all commented on osu.Framework.Tests/Localisation/LocalisationTest.cs
> +            config.SetValue(FrameworkSetting.Locale, "en");
Hopefully this should be covered by added test in 6307dbd

2021-07-16 04:44 UTC, peppy commented on osu.Framework/Localisation/TransformableString.cs
> +        UpperCase,
Was fine how you had it. "uppercase" is a valid word.

2021-07-16 04:47 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +        UpperCase,
It was done because of https://github.com/ppy/osu-framework/pull/4603#discussion_r669802447, which I agree with.

2021-07-16 06:33 UTC, smoogipoo requested changes

2021-07-16 06:33 UTC, smoogipoo commented on osu.Framework/Localisation/TransformableString.cs
> +
Please annotate with `#nullable enable`.

2021-07-16 10:55 UTC, smoogipoo commented on osu.Framework/Localisation/TransformableString.cs
> +        UpperCase,
@peppy can you confirm whether you're fine with it as is, or do you require this to be changed?

2021-07-16 12:17 UTC, peppy commented on osu.Framework/Localisation/TransformableString.cs
> +        UpperCase,
It's fine either way, I was just going for conformity with other cases that have come up until now.

2021-07-16 18:34 UTC, frenzibyte commented on osu.Framework/Localisation/TransformableString.cs
> +    public class TransformableString : IEquatable<TransformableString>, ILocalisableStringData
Gonna agree with this one. Since it's usually not constructed explicitly and is provided via extension methods, could rename to something more explicit but long, like `CaseTransformableString`.

2021-07-17 07:17 UTC, Game4all commented on osu.Framework/Localisation/TransformableString.cs
> +    public class TransformableString : IEquatable<TransformableString>, ILocalisableStringData
Sounds good to me.

2021-07-17 14:03 UTC, frenzibyte requested changes

2021-07-17 14:39 UTC, bdach commented on osu.Framework.Tests/Localisation/LocalisationTest.cs
> +            Assert.AreEqual(lowercasedText.Value, localisable_string_en_lowercase);
Agree with the above, so I've just went ahead and applied it more or less verbatim.

2021-07-17 14:40 UTC, bdach submitted a review, later dismissed

2021-07-17 14:42 UTC, frenzibyte approved these changes

2021-07-19 03:58 UTC, smoogipoo approved these changes
lgtm

2021-07-19 04:06 UTC, merged