Show soft keyboard on Android on click of an already focused TextBox
ppy/osu-framework pull request #4613
Opened 2021-07-17 14:51 UTC by Susko3

Closes https://github.com/ppy/osu/issues/5284

Right now, if you manually close the keyboard by pressing the system back button, the keyboard will not open again if you tap on the currently focused TextBox. This PR fixes that.

`ToggleSoftInputFromWindow` is depricated in Android API level 31 (see [here](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#toggleSoftInputFromWindow(android.os.IBinder,%20int,%20int))) so `ShowSoftInput` is used instead.

**For iOS:**
The way `UpdateFirstResponder` works means that just calling `view.KeyboardTextField.UpdateFirstResponder(true)` in `ShowSoftKeyboard()` won't work as expected, as the keyboard might not close when the textbox is unfocused.

I don't have an iOS device to test with, so it's on somebody else to implement this at a later time. (And to test if hiding the keyboard manually even causes problems in the first place.)

2021-07-17 15:52 UTC, bdach requested changes

2021-07-17 15:52 UTC, bdach commented on osu.Framework/Input/ITextInputSource.cs
> +        void ShowSoftKeyboard();
Can this be named differently? `Reactivate()`, maybe? `EnsureActivated()`? Having a mention of a "soft keyboard" just sticks out like a sore thumb in this very abstract interface.

2021-07-17 15:52 UTC, bdach commented on osu.Framework.iOS/Input/IOSTextInput.cs
> +            /// `responderSemaphore` currently works.
Quite confused by this. This is theoretical, right? You did not actually test this?

2021-07-17 16:13 UTC, Susko3 commented on osu.Framework.iOS/Input/IOSTextInput.cs
> +            /// `responderSemaphore` currently works.
Everything iOS is theoretical, I haven't tested anything.

But looking at this code, it seems that calling `UpdateFirstResponder(true)` multiple times is a bad idea. `responderSemaphore ` value will increase and the keyboard will never close on it's own.

https://github.com/ppy/osu-framework/blob/08ffacbb0733efeb8973842321aed7dab7f1d61e/osu.Framework.iOS/IOSGameView.cs#L214-L230

For the manually closing keyboard part:
Changing the `FirstResponder` (what presumably hides and shows the keyboard on iOS) is only done in `Activate` and `Deactivate` code in [IOSTextInput.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework.iOS/Input/IOSTextInput.cs), so it seems that nothing will open the keyboard if it's manually closed.

2021-07-17 16:45 UTC, Susko3 commented on osu.Framework/Input/ITextInputSource.cs
> +        void ShowSoftKeyboard();
I agree that this should be renamed. But if it were, then what would stick out even more is that the newly renamed `ShowSoftKeyboard()` doesn't have `(object sender)` as an argument, in contrast to `Activate` and `Deactivate`. Looking at git blame, it seems this was added for `lock`ing purposes a long time ago in https://github.com/ppy/osu-framework/commit/a6e152cb2931b54f772b730825e6b85edcc4c432.

The only thing that uses `Activate` and `Deactivate` is `TextBox`, and no locking seems to be done here. Removing `(object sender)` from  `Activate` and `Deactivate` doesn't seem to cause issues. Should I remove that, or is this out of scope for this PR?

2021-07-17 16:47 UTC, frenzibyte commented on osu.Framework/Input/ITextInputSource.cs
> +        void ShowSoftKeyboard();
That's irrelevant, you could just add `object sender` in the method and pass the same value that's passed in `Activate` and `Deactivate`, removing it can come in a separate PR if deemed right.

2021-07-17 16:54 UTC, bdach commented on osu.Framework/Input/ITextInputSource.cs
> +        void ShowSoftKeyboard();
I'm not necessarily opposed to removing? No strong opinions here. It does seem to be completely unused right now.

2021-07-20 03:32 UTC, smoogipoo commented
I think it's probably fine to get this in with minimal testing since it only affects Android for the time being?

2021-07-20 03:33 UTC, smoogipoo approved these changes

2021-07-20 03:54 UTC, merged