Flatten `PlatformAction` struct to an enum
ppy/osu-framework pull request #4622
Opened 2021-07-20 05:51 UTC by ekrctb

The `ActionType` and `ActionMethod` product only make sense for text edit operations, and it was confusing and cumbersome to use.
`PlatformAction.Delete` is added as an additional "Delete" key binding separate from `DeleteForwardChar`, as the later should only be used for text edit.
I have osu-side change <https://github.com/ppy/osu/compare/master...ekrctb:platform-action?expand=1>.

--- 

`PlatformAction` type is changed to an enum type.
If `PlatformAction.ActionType` was matched, change to a matching of `PlatformAction` itself like:

```diff
bool OnPressed(PlatformAction action) {
-    switch (action.ActionType)
+    switch (action)
    {
-        case PlatformActionType.Cut:
+        case PlatformAction.Cut:
```

For `PlatformActionMethod.Delete`, change to `PlatformAction.Delete`:

```diff
-    switch (action.ActionMethod)
+    switch (action)
    {
-        case PlatformActionMethod.Delete:
+        case PlatformAction.Delete:
```

2021-07-20 06:32 UTC, ekrctb commented
`CodeFactor` issues are false positive. It is not pointing to any changed code.

2021-07-20 07:38 UTC, frenzibyte commented
Or rather, they're just pointing issues in general, but only triggering when performing any change to said files.

2021-07-20 07:45 UTC, peppy commented
I think this looks like a good direction. Curious if anything specifically triggered the need for change though?

2021-07-20 17:39 UTC, bdach requested changes

2021-07-20 17:39 UTC, bdach commented on osu.Framework/Input/PlatformAction.cs
> +        MoveForwardChar,
Not sure I entirely like the terminology change from `Previous/Next` to `Backward/Forward` but I guess it's not a huge deal...

2021-07-20 17:39 UTC, bdach commented on osu.Framework.iOS/IOSGameHost.cs
> +            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteForwardChar),
```suggestion
            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteBackwardChar),
```

2021-07-20 17:39 UTC, bdach commented on osu.Framework/Graphics/UserInterface/TextBox.cs
>                      }
Opportunity to reuse `DeleteBy()` here.

2021-07-20 17:39 UTC, bdach commented on osu.Framework/Platform/GameHost.cs
> +            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteForwardChar),
```suggestion
            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteBackwardChar),
```

2021-07-20 17:39 UTC, bdach commented on osu.Framework/Platform/MacOS/MacOSGameHost.cs
> +            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteForwardChar),
```suggestion
            new KeyBinding(new KeyCombination(InputKey.Shift, InputKey.BackSpace), PlatformAction.DeleteBackwardChar),
```

2021-07-21 04:48 UTC, peppy commented
@smoogipoo are you okay with this as a breaking change without obsolescence? It's a pretty quick fix for osu! (see https://github.com/ppy/osu/compare/master...ekrctb:platform-action?expand=1) and I don't think too many people would be using it in more complicated ways than we are osu! side.

2021-07-21 05:15 UTC, smoogipoo commented
I think without obsolescence is fine.

2021-07-21 05:48 UTC, peppy commented on osu.Framework/Input/PlatformAction.cs
> +        MoveForwardChar,
I think `Previous`/`Next` sounds better in all cases. Shall we switch to that?

2021-07-21 05:50 UTC, peppy commented on osu.Framework/Input/PlatformAction.cs
> +        MoveForwardWord,
`MoveBackward` and `MoveForward` may be exceptions to the rule. They can likely remain as they are as they are describing motion rather than actions.

2021-07-21 05:51 UTC, peppy requested changes
As propose.

2021-07-21 05:54 UTC, ekrctb commented on osu.Framework/Input/PlatformAction.cs
> +        MoveForwardChar,
A reason I changed the name is because I thought next/previous might be confusing when the current cursor is *on* the word/line:

```
               ↓ cursor
PreviousWord Wo|rd NextWord
```

2021-07-21 05:59 UTC, ekrctb commented
Also this "backward/forward word" terminology is in the emacs document <https://www.gnu.org/software/emacs/manual/html_node/emacs/Words.html>

2021-07-21 06:01 UTC, peppy commented
Do emacs actually use backward/forward anywhere for an operation that isn't movement? I can understand the potential confusion in the case you mention, but I think as it stands it's more confusing for the majority case, where we'd benefit from the clarity of using Previous/Next.

2021-07-21 06:05 UTC, ekrctb commented
In the linked doc, 

> M-DEL
>    Kill back to the beginning of a word (backward-kill-word).

2021-07-21 06:08 UTC, peppy commented
I guess it's fine as-is. The extra case where it may be deleting from within a current word makes me more neutral to which we should use, and what you have seems to work.

2021-07-21 06:08 UTC, peppy approved these changes

2021-07-21 07:06 UTC, merged