Replace enum localisation mapper with general `LocalisableDescription` attribute
ppy/osu-framework pull request #4645
Opened 2021-07-30 22:34 UTC by frenzibyte

Currently, in order to add localisation support to an enum, a side mapper class will have to be added mapping each enum member to its `LocalisableString`:
```csharp
[LocalisableEnum(typeof(ExampleEnumLocalisationMapper))]
public enum Example
{
    Foo,
    Bar,
}

public class ExampleEnumLocalisationMapper : EnumLocalisationMapper<Example>
{
    public override LocalisableString Map(Example value)
    {
        switch (value)
        {
            case Example.Foo:
                return Strings.ExampleFoo;

            case Example.Bar:
                return Strings.ExampleBar;

            default:
                throw new ArgumentOutOfRangeException(nameof(value));
        }
    }
}
```

This PR instead replaces that enum-specific mapper code with a general `LocalisableDescription` attribute, similar to the commonly known `System.ComponentModel.Description` attribute.

The attribute accepts a declaring type and a member name to retrieve the `LocalisableString`, as attributes do not allow directly passing any value type out of the [permitted ones](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-parameter-types)):

```csharp
public enum Example
{
    [LocalisableDescription(typeof(Strings), nameof(Strings.ExampleFoo))]
    Foo,

    [LocalisableDescription(typeof(Strings), nameof(Strings.ExampleBar))]
    Bar,
}
```

I've added benchmarks for this method and have ran it before and after the changes, and the results show that the `LocalisableDescription` way is, interestingly, more performant than the `EnumLocalisationMapper` way:

- `EnumLocalisationMapper`:
    |                    Method | Times |          Mean |       Error |       StdDev |        Median |
    |-------------------------- |------ |--------------:|------------:|-------------:|--------------:|
    | GetLocalisableDescription |     1 |      6.866 us |   0.5021 us |     1.383 us |      6.316 us |
    | GetLocalisableDescription |    10 |     93.360 us |   4.9223 us |    13.883 us |     92.744 us |
    | GetLocalisableDescription |   100 |    817.775 us |  31.0268 us |    90.996 us |    812.132 us |
    | GetLocalisableDescription |  1000 | 10,794.319 us | 820.1783 us | 2,392.498 us | 10,718.182 us |

- `LocalisableString`:
    |                    Method | Times |         Mean |       Error |      StdDev |       Median |
    |-------------------------- |------ |-------------:|------------:|------------:|-------------:|
    | GetLocalisableDescription |     1 |     4.631 us |   0.1148 us |   0.3331 us |     4.514 us |
    | GetLocalisableDescription |    10 |    54.555 us |   1.3511 us |   3.9412 us |    54.440 us |
    | GetLocalisableDescription |   100 |   540.643 us |  15.9231 us |  45.6864 us |   539.138 us |
    | GetLocalisableDescription |  1000 | 7,218.708 us | 270.7659 us | 768.1179 us | 7,192.596 us |

2021-07-30 23:04 UTC, bdach commented
So upon looking at this in the profiler I guess this new proposed method is faster because it saves on the object instantiation and invocation of `Map()`, instead directly invoking field getters.

I don't like the string typing still but that's mostly personal opinion I guess.

2021-07-30 23:04 UTC, bdach requested changes

2021-07-30 23:07 UTC, frenzibyte commented on osu.Framework/Extensions/ExtensionMethods.cs
> +                type = value.GetType();
Interestingly `GetDescription` itself doesn't even get the `DescriptionAttribute` of the type itself, but always assumes it's an enum and does `value.GetType().GetField(value.ToString())`.

I wasn't sure whether to replicate its same exact behaviour, or make things more sane by using the type directly on non-enum cases, but I chose the latter.

I'll keep this as-is and add test coverage.

2021-07-30 23:10 UTC, bdach commented on osu.Framework/Extensions/ExtensionMethods.cs
> +                type = value.GetType();
I can't really think of a case where this could be used on a non-enum but I can't bring myself to care enough to argue for removal. But if it's to stay then it needs tests.

2021-07-31 14:59 UTC, bdach approved these changes

2021-08-02 02:04 UTC, smoogipoo commented
Will list the breaking change, but afaik there's no external usages of this attribute yet.

2021-08-02 02:04 UTC, smoogipoo approved these changes

2021-08-02 02:11 UTC, merged