Implement shader for SaturationValueSelector
ppy/osu-framework pull request #4646
Opened 2021-07-31 00:36 UTC by EVAST9919

In this pr I tried to fix the problem mentioned [here](https://github.com/ppy/osu/pull/13714#discussion_r661826143) by using shader instead of 3 boxes on top of each other. The final result is indistinguishable (as far as I can tell), however masking can be applied correctly now.
|master|pr|
|---|---|
|![old](https://user-images.githubusercontent.com/22874522/127723016-c64578ff-9382-412a-8c61-9f1f66e80d56.png)|![new](https://user-images.githubusercontent.com/22874522/127723025-f2bf9a69-1b69-4a1e-ac9f-a1a006f5f551.png)|

osu-side (needs a pr, removing `MaskingSmoothness = 0`)
|master|master without fix|osu-side pr|
|---|---|---|
|![picker-old](https://user-images.githubusercontent.com/22874522/127723125-843d2895-a30a-4b13-934e-ee790fc1d9e8.png)|![picker-old-aa](https://user-images.githubusercontent.com/22874522/127723134-06642d37-9581-4676-92cc-3adaa6872e49.png)|![picker-new](https://user-images.githubusercontent.com/22874522/127723140-434a992c-e483-4550-ac1c-9c64d28668e7.png)|

2021-07-31 06:49 UTC, bdach requested changes

2021-07-31 06:49 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
> +    vec2 resolution = vec2(v_TexRect[2] - v_TexRect[0], v_TexRect[3] - v_TexRect[0]);
Pretty sure this is wrong. It's not a problem because the only usage presumably has `v_TexRect[0] == v_TexRect[1]` but this should be

```suggestion
    vec2 resolution = vec2(v_TexRect[2] - v_TexRect[0], v_TexRect[3] - v_TexRect[1]);
```

The four items are left/top/right/bottom coordinates, in that order:

https://github.com/ppy/osu-framework/blob/5f59a64f6795d4dbdfbffe86977baefa6c18d9ea/osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs#L326

Also goes for the other shader, obviously.

2021-07-31 06:49 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
> +    vec2 pixelPos = vec2(v_TexCoord.x/resolution.x, v_TexCoord.y/resolution.y);
```suggestion
    vec2 pixelPos = v_TexCoord / resolution;
```

2021-07-31 06:49 UTC, bdach commented on osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
> +                public float HueValue
probably could just name this `Hue` to avoid confusion with the HSV colour model value

2021-07-31 11:00 UTC, bdach commented
Going to request a follow-up review on the drawnode stuff as I'm not overly familiar but looks good to me, generally.

2021-07-31 12:39 UTC, bdach submitted a review, later dismissed

2021-08-05 08:01 UTC, smoogipoo approved these changes
lgtm

2021-08-05 08:10 UTC, merged