Make font store has more flexibility to accept different type
ppy/osu-framework pull request #4656
Opened 2021-08-04 10:22 UTC by andy840119

Make `font store` has more flexibility to accept different types of `GlyphStore`.
For letting users customize glyph stores like `TtfGlyphStore` or `OtfGlyphStore`.

And here's the sample on rendering customize `.ttf` font in osu-framework:
- https://github.com/andy840119/osu-framework/pull/2

2021-08-04 12:14 UTC, frenzibyte requested changes

2021-08-04 12:14 UTC, frenzibyte commented on osu.Framework/IO/Stores/FontStore.cs
>              }
Not 100% sure about switching to LINQ on such method, could just add a `continue` until the font name matches.

2021-08-04 12:54 UTC, frenzibyte commented
Please refrain from force-pushing here.

2021-08-04 13:17 UTC, frenzibyte commented on osu.Framework/IO/Stores/IGlyphStore.cs
> +        int GetBaseHeight();
It should be removed if the method itself is written only to return something. I would even change it to a property but that's out of scope I guess.

2021-08-06 22:19 UTC, frenzibyte approved these changes
Was hoping for a proper abstraction and *potentially* reuse of `RawCachingGlyphStore` for custom glyph stores, but not going to insist too much on that with the current state it's in.

2021-08-07 12:29 UTC, bdach approved these changes
I guess I don't see any harm with this if this is enough exposition.

2021-08-10 05:11 UTC, peppy approved these changes

2021-08-10 05:20 UTC, merged