mark public CanBeNull as deprecated
ppy/osu-framework pull request #4659
Opened 2021-08-05 22:34 UTC by YVbakker

This will mark the currently public `CanBeNull` attribute of `ResolvedAttribute` as deprecated, as this should become private at some point in the future and this change is breaking.

closes #3849

2021-08-05 22:40 UTC, frenzibyte commented
Thanks for the contribution. Few points on the change:
- The way this is obsoleted does not seem 100% right, at this state you can only just mark it as `readonly` already.
- This should also apply for the other properties, all of them should only ever be set from the constructor and nowhere else.

2021-08-05 22:41 UTC, frenzibyte requested changes
As above.

2021-08-05 23:53 UTC, smoogipoo commented
I dunno... This seems like a waste of time for a breaking change that achieves nothing of particular importance.

2021-08-06 00:05 UTC, smoogipoo commented
Thanks for the contribution, but I'm going to take the decision to close this for the time being.

I need to see more discussion on the topic before I'm ready to consider this sort of change, such as what the C# best practices are for attributes. You can Google around to find [resources](https://www.codemag.com/article/0307041/Defining-and-Using-Custom-Attribute-Classes-in-C) hinting at using positional arguments as always-required params and named arguments as optional params, which is the complete inverse of this PR, as an example.

2021-08-06 00:05 UTC, closed without merging