Optimise `GetBoundCopy` to not rely on reflection to create bindable instances
ppy/osu-framework pull request #4689
Opened 2021-08-15 17:53 UTC by frenzibyte

Closes #4685 

|                                  Method |        Mean |     Error |    StdDev | Ratio | RatioSD |
|---------------------------------------- |------------:|----------:|----------:|------:|--------:|
|           CreateInstanceViaConstruction |    35.33 ns |  0.865 ns |  2.425 ns |  1.00 |    0.00 |
|    CreateInstanceViaActivatorWithParams | 1,036.88 ns | 20.764 ns | 60.239 ns | 29.39 |    2.69 |
| CreateInstanceViaActivatorWithoutParams |    87.84 ns |  2.584 ns |  7.539 ns |  2.49 |    0.30 |
| CreateInstanceViaBindableCreateInstance |    40.67 ns |  2.207 ns |  6.474 ns |  1.14 |    0.19 |

While this avoids reflection-based metods of creating a bindable instance, the new protected `CreateInstance` method has to check that the returned instance matches the same type as the original bindable which is to be bound against, and throw if it doesn't match.

Doing that causes JIT to disable inlining on the method (see https://github.com/ppy/osu-framework/issues/3470). I've defined a `ThrowHelper` class for that purpose, as otherwise `GetBoundCopy` would've been less performant.

---

The fact that all inheritors of `Bindable`s need to override `CreateInstance` is a bit disturbing, but since the chances of making a new bindable class is rare, I believe it's worth the optimisation.

I've left `LocalisedBindableString` from implementing `CreateInstance` on it as it doesn't seem possible to do so, and it's already broken before so I don't see any way of supporting that currently. Leaving it for later when deemed required.

2021-08-15 17:57 UTC, peppy commented
Why does the `throw` need to be there? Is this intended to protect third parties that may be implementing their own bindable incorrectly? Not sure we need that.

2021-08-15 18:01 UTC, peppy commented
In addition, I'm not sure why you've listed four types of invocation in the benchmark when there should only be two compared - what we were using and what the new code is providing. It's unclear immediately which two we should be looking at (guessing the first two, where the... second is the old?), especially since the `baseline` is set incorrectly to the new one, rather than the old.

Here's a better way (in my opinion) to create benchmark comparisons for PR descriptions:

- Copy the pre-changes version of `Bindable` to `BindableOld`
- Create two benchmark methods with the same content, one instantiating a `Bindable` and the other `BindableOld`. Set the old one as the baseline

2021-08-15 18:03 UTC, frenzibyte commented
> Why does the `throw` need to be there? Is this intended to protect third parties that may be implementing their own bindable incorrectly? Not sure we need that.

Added that for two reasons:
 1. Would act same as what happens when invoking `Activator.CreateInstance` on a bindable which doesn't implement a matching constructor.
 2. Avoids the chances of forgetting to override `CreateInstance`, which can happen silently and result in unexpected behaviour. I can imagine that potentially happening osu!-side, with bindables that override the `Value` setter for example.

That said, I'm wondering if there's a reason you're against having it?

2021-08-15 18:13 UTC, frenzibyte commented
> In addition, I'm not sure why you've listed four types of invocation in the benchmark when there should only be two compared - what we were using and what the new code is providing. It's unclear immediately which two we should be looking at (guessing the first two, where the... second is the old?), especially since the `baseline` is set incorrectly to the new one, rather than the old.
> 
> Here's a better way (in my opinion) to create benchmark comparisons for PR descriptions:
> 
> * Copy the pre-changes version of `Bindable` to `BindableOld`
> * Create two benchmark methods with the same content, except that one instantiates a `Bindable` and the other `BindableOld`. Set the old one as the baseline

I thought `Baseline` is supposed to be set on the pure way of creating a bindable, then the other benchmarks would scale based on it to show the ratio between the pure way and the other methods. But perhaps not.

Your way sounds good, I can't exactly copy the pre-changed version of `Bindable`, but I can at least make a bindable that overrides to create the instance via `Activator` to reflect the overhead.

2021-08-15 18:25 UTC, frenzibyte commented
Benchmarks updated, shows a ratio of 0.50 on the new way.

2021-08-15 18:30 UTC, peppy commented
I guess the throwing is required due to the `virtual` implementation in `Bindable`, seems fine to leave it.

The new benchmarks make me question whether this was required in the first place. At 2.3us this method likely does not need this change.

2021-08-15 18:31 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +        public Bindable<T> GetBoundCopy() => (Bindable<T>)((IBindable)this).GetBoundCopy();
pretty gnarly but i don't see how this can be avoided...

2021-08-15 18:31 UTC, bdach commented on osu.Framework/Bindables/LeasedBindable.cs
> +            : base(defaultValue)
is this change related?

2021-08-15 18:31 UTC, bdach commented on osu.Framework/Utils/ThrowHelper.cs
> +    }
I would rather have this scoped to the concrete bindable use case than just be a generic throw helper for one exception type. Or lean into it fully and have a `ThrowHelper<T>` (does that still get the perf benefits? need to check if going for that)

2021-08-15 18:34 UTC, frenzibyte commented on osu.Framework/Bindables/LeasedBindable.cs
> +            : base(defaultValue)
Brings it to a consistent state so I wouldn't have to pass `default` while constructing `LeasedBindable`, nothing important.

2021-08-15 18:36 UTC, frenzibyte commented on osu.Framework/Utils/ThrowHelper.cs
> +    }
Added it to be a good start for https://github.com/ppy/osu-framework/issues/3470, I'm wondering how it's possible to make `ThrowHelper` generic though? (assuming the generic parameter would be the exception)

2021-08-15 18:37 UTC, frenzibyte commented on osu.Framework/Bindables/Bindable.cs
> +        public Bindable<T> GetBoundCopy() => (Bindable<T>)((IBindable)this).GetBoundCopy();
Yeah...

2021-08-16 02:36 UTC, smoogipoo commented on osu.Framework/Bindables/Bindable.cs
> +        public Bindable<T> GetBoundCopy() => (Bindable<T>)((IBindable)this).GetBoundCopy();
Can this be extracted to a helper method rather than a sealed interface implementation?

2021-08-16 02:38 UTC, frenzibyte commented on osu.Framework/Bindables/Bindable.cs
> +        public Bindable<T> GetBoundCopy() => (Bindable<T>)((IBindable)this).GetBoundCopy();
Had thought about it but scratched that away for the fact that `CreateInstance` used to be protected, but now that I've made it `internal` as well, no reason not to.

2021-08-16 02:43 UTC, frenzibyte commented on osu.Framework/Bindables/Bindable.cs
> +        public Bindable<T> GetBoundCopy() => (Bindable<T>)((IBindable)this).GetBoundCopy();
This actually can't be a helper method as `IBindable<T>` has to return a bound `IBindable<T>` copy, while `Bindable<T>` has to return a bound `Bindable<T>` copy.

2021-08-16 07:37 UTC, peppy requested changes

2021-08-16 07:37 UTC, peppy commented on osu.Framework/Utils/ThrowHelper.cs
> +    }
At very least, this should have xmldoc attached to the class to mention why it's being done. And potentially linking to the issue as a TODO for future usage.

2021-08-16 11:15 UTC, frenzibyte commented on osu.Framework/Utils/ThrowHelper.cs
> +    }
Good note, I've added that.

2021-08-16 12:51 UTC, peppy submitted a review, later dismissed

2021-08-17 07:00 UTC, smoogipoo commented
I've refactored this to remove the back-and-forth casting.

* `IBindable` exposes a `GetBoundCopy()` method.
* Custom interfaces like `IBindable<T>` can expose their own typed variant of `GetBoundCopy()`
* The final implementation (e.g. `Bindable<T>`) implements `GetBoundCopy()` via `IBindable.GetBoundCopyImplementation(this)`.
* `IBindable.GetBoundCopyImplementation()` is only available within `IBindable` subclasses.
* `IBindable.CreateInstance()` is now only `protected` instead of `protected internal`.

|          Method |       Mean |   Error |  StdDev | Ratio |
|---------------- |-----------:|--------:|--------:|------:|
| GetBoundCopyOld | 1,729.3 ns | 2.92 ns | 2.59 ns |  1.00 |
|    GetBoundCopy |   797.9 ns | 7.01 ns | 6.22 ns |  0.46 |

Relative performance hasn't changed from the OP.

2021-08-17 07:03 UTC, frenzibyte reviewed
Looks good.

2021-08-17 07:07 UTC, peppy approved these changes

2021-08-17 07:09 UTC, smoogipoo approved these changes

2021-08-17 21:34 UTC, bdach approved these changes

2021-08-17 21:35 UTC, bdach commented
Code seems good to me. I've added a breaking change note to the PR description.

@frenzibyte before I go merging this, do you have the corresponding game-side changes ready? because this *will* break custom bindable types and the game has a few of those.

2021-08-17 23:56 UTC, frenzibyte commented
Yeah I'll ready up one now.

2021-08-18 01:08 UTC, merged