Use a temporary directory to store unit test headless run files
ppy/osu-framework pull request #4695
Opened 2021-08-18 06:45 UTC by peppy

Generally it's good practice to store temporary files to the OS defined directory. This avoids IDEs or other OS level operations (ie. spotlight) indexing the files as they are created.

This also has some fixes to avoid log entries being written after a test host has already been disposed. Not sure whether this will be accepted as a solution, but it seems like about the best we're going to be able to do given the `static`-ness of `Logger`. Works well in practice.

Some further changes are required osu!-side to make use of this new class (in non-standard scenarios).

2021-08-18 06:57 UTC, peppy commented on osu.Framework/Testing/TestRunHeadlessGameHost.cs
> +                Storage?.DeleteDirectory(string.Empty);
Turns out this is already done in `TestScene` itself, but I don't see harm in doing it locally as well.

2021-08-19 01:31 UTC, smoogipoo requested changes

2021-08-19 01:31 UTC, smoogipoo commented on osu.Framework/Testing/TestRunHeadlessGameHost.cs
> +                Storage?.DeleteDirectory(string.Empty);
Should have a try-catch around this.

2021-08-19 01:33 UTC, peppy commented on osu.Framework/Testing/TestRunHeadlessGameHost.cs
> +                Storage?.DeleteDirectory(string.Empty);
Was somehow hoping this wouldn't be required any more, since I didn't repro any failures, but sounds fair.

2021-08-19 01:35 UTC, smoogipoo commented
`drwxr-xr-x  3 smgi    smgi       60 Aug 19 10:33 of-test-headless`

Is there a reason why this doesn't append a GUID in all cases? We can't have tests re-using the same dir.

2021-08-19 01:42 UTC, peppy commented
> 
> 
> `drwxr-xr-x 3 smgi smgi 60 Aug 19 10:33 of-test-headless`
> 
> Is there a reason why this doesn't append a GUID in all cases? We can't have tests re-using the same dir.

The top level directory is intended so it's easy to clean up the files in one go. It's never used directly for a test - each test will use a subdirectory in that base path. GUIDs are already added to tests where they need unique directories, and the ones which don't (due to requiring constant names between test runs) tend to use a `CleanRunGameHost` or similar.

Basically nothing has changed from `master` to this in this regard. That said, if there is a way to handle a global "tests started" and "tests ended" I wouldn't be against making a unique subdirectory in the `of-test-headless` path for the full run, and potentially nuke it afterwards.

2021-08-19 01:45 UTC, smoogipoo commented
Ah, I thought that was the top-level directory for hosts. It's fine.

2021-08-19 01:48 UTC, smoogipoo approved these changes

2021-08-19 01:49 UTC, merged