Fix double disposal of `ThreadedTaskScheduler` throwing an exception
ppy/osu-framework pull request #4772
Opened 2021-09-13 09:38 UTC by peppy

2021-09-13 09:41 UTC, smoogipoo requested changes

2021-09-13 09:41 UTC, smoogipoo commented on osu.Framework.Tests/Threading/ThreadedTaskSchedulerTest.cs
> +            using var taskScheduler = new ThreadedTaskScheduler(4, "test");
We've blocked merging code using in-line using like this before. You could just dispose after the using block.

2021-09-13 18:47 UTC, bdach commented
The diff looks good, but I'm pretty sure the merge revert at the end of history here (a8ed603) is going to cause problems. Because it builds on the dependency commits and shares hashes with them, merging `master` back here will cause the dependency to be reverted.

The merge revert will either have to be reverted a second time, or force-pushed out entirely.

2021-09-14 01:10 UTC, peppy commented
Yeah, I'll have to deal with that at that point. Would usually force push for such a case, but alas. Will deal with after one of the two is merged.

2021-09-14 04:22 UTC, smoogipoo approved these changes

2021-09-14 04:22 UTC, merged