Remove obsolete framework settings
ppy/osu-framework pull request #4866
Opened 2021-11-07 13:22 UTC by frenzibyte

2021-11-07 13:50 UTC, bdach commented
This doesn't compile.

2021-11-07 13:51 UTC, bdach requested changes
see above

2021-11-07 14:05 UTC, bdach commented on osu.Framework.Tests/Configuration/InputConfigManagerTest.cs
> -#pragma warning restore 618
this entire test needs to go, no? it was testing that the old config pathway was getting persisted in the new format, which is no longer relevant/applicable, is it not?

2021-11-07 14:29 UTC, bdach commented on osu.Framework/Configuration/FrameworkConfigManager.cs
> -            }),
removing these causes the game-side `Ctrl`+`Alt`+`R` hotkey to reset sensitivity/raw input to not work anymore.

2021-11-07 15:00 UTC, Susko3 commented
Shouldn't `IHasCursorSensitivity` also be removed, since it's no longer used.

2021-11-08 03:10 UTC, frenzibyte commented
Going to close this for now as I thought it to be a simple change but turns out it breaks behaviour rather than removing obsolete methods.

2021-11-08 03:10 UTC, closed without merging