Improve test coverage of video playback
ppy/osu-framework pull request #4893
Opened 2021-11-13 16:56 UTC by Opelkuh

Depends on #4892 for one of the .webm tests to pass

Adds a simple video that I made to resources in 3 different formats, .mp4 and .avi with H.264 and .webm with VP9. I tried to make them as small as possible but they still take ~1MB.
Preview of the beauty:
https://raw.githubusercontent.com/Opelkuh/osu-framework/25ba3e0a2b1041f42eb9fb91d7509326587d8c1c/osu.Framework.Tests/Resources/Videos/sample-video.mp4

I made sure that it would've caught the .avi issues from #4858

2021-11-13 18:17 UTC, bdach requested changes

2021-11-13 19:03 UTC, Opelkuh commented on osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
> +                videoContainer.Child = video = new TestVideo(videoStore.GetStream($"sample-video.{format}"))
I think it gets disposed by `VideoDecoder`: https://github.com/Opelkuh/osu-framework/blob/25ba3e0a2b1041f42eb9fb91d7509326587d8c1c/osu.Framework/Graphics/Video/VideoDecoder.cs#L856

2021-11-13 19:06 UTC, Opelkuh commented on osu.Framework.Tests/Visual/FrameworkGridTestScene.cs
> +    public abstract class FrameworkGridTestScene : GridTestScene
Yes. It's only to get the `DllResourceStore` loaded for `TestSceneVideoLayout` and `TestSceneWrapModes`.

2021-11-13 19:07 UTC, bdach commented on osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
> +                videoContainer.Child = video = new TestVideo(videoStore.GetStream($"sample-video.{format}"))
Oh right, my bad. It's arguably a little hidden, but I should have spotted that either way.

2021-11-15 05:13 UTC, peppy commented on osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
> +            Cell(0, 0).Child = createTest("video - auto size", () => new TestVideo(new MemoryStream(videoData)));
Is there a reason these can't be direct calls to `game.Resources.GetStream`?

2021-11-15 11:44 UTC, Opelkuh commented on osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
> +            Cell(0, 0).Child = createTest("video - auto size", () => new TestVideo(new MemoryStream(videoData)));
Nope.

2021-11-15 17:22 UTC, bdach approved these changes
looks fine here, but going to wait for a double check

2021-11-16 02:05 UTC, peppy approved these changes

2021-11-16 02:06 UTC, merged