Add Orientation setting to framework config
ppy/osu-framework pull request #4897
Opened 2021-11-17 01:28 UTC by honguyenminh

This allows games to have an orientation setting, mainly for mobile devices.

2021-11-17 03:37 UTC, peppy commented
I don't get it. This needs implementation as well, right? To actually make it work?

2021-11-17 03:43 UTC, honguyenminh commented
The implementation will be done in the app that uses the framework. Apps might choose different flag for different options here.

In osu's case the setting will be shown in osu.Game setting overlay, implementation for Android will be in a class in osu.Android and same goes for iOS if needed later.
This is just to provide the setting for the game using the framework.
Or am I doing it wrong and this should be implemented in the framework?

2021-11-17 03:45 UTC, peppy commented
If the setting is at the framework side, the implementation should also be done here. We generally keep all low-level handling (like rotation) at the framework side, so this *is* the correct place to put it.

2021-11-17 05:35 UTC, Susko3 commented
Do keep in mind how [osu.Android/GameplayScreenRotationLocker](https://github.com/ppy/osu/blob/master/osu.Android/GameplayScreenRotationLocker.cs) works, so you may need to add additional options to the framework setting, or a "locking" logic to facilitate this.

May be useful to you, if you haven't seen it:
https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects

2021-11-18 00:26 UTC, honguyenminh commented
Implemented the logic

Client app can inherit the class to change the behavior, and/or wrap it in another class to extend functionality

2021-11-18 18:46 UTC, bdach requested changes

2021-11-18 18:46 UTC, bdach commented on osu.Framework/Configuration/Orientation.cs
> +    public enum Orientation
The enum should be arguably called `ScreenOrientation` rather than an arbitrary `Orientation`, and the xmldoc is barely (if at all) usable. It should explain that this is primarily intended for use with mobile platforms.

2021-11-18 18:46 UTC, bdach commented on osu.Framework/Platform/OrientationManager.cs
> +        protected Bindable<Orientation> OrientationBindable;
Should be `{ get; protected set; }` or similar.

2021-11-18 18:46 UTC, bdach commented on osu.Framework/Platform/OrientationManager.cs
> +        protected OrientationManager() { }
What is the point of this constructor? It should not exist.

2021-11-18 18:46 UTC, bdach commented on osu.Framework/Platform/OrientationManager.cs
> +        public abstract void OrientationSettingChangedHandler(ValueChangedEvent<Orientation> value);
This would fit existing naming conventions better if it was named `OnScreenOrientationChanged` or similar. Also, the xmldoc from the android implementation should be moved here to the base implementation.

2021-11-18 18:46 UTC, bdach commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
I don't see why this would need to be a field at all, or be publically exposed like it is. Would it not be enough to map the framework `Orientation` to android `ScreenOrientation` in the current `OrientationSettingChangedHandler`, and just delete this field?

2021-11-18 18:46 UTC, bdach commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +                default:
I prefer to handle unknown enum members by throwing `ArgumentOutOfRangeException` rather than assuming that `Auto` was wanted as done here.

2021-11-18 18:46 UTC, bdach commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        protected Activity GameActivity { get; set; }
Does not need to be `protected` until there are actual subclasses of this.

2021-11-18 18:46 UTC, bdach commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
Why was this changed?

2021-11-18 19:07 UTC, Susko3 commented on osu.Framework/Configuration/Orientation.cs
> +        Auto = 2
Since we'll need `Locked` for `GameplayScreenRotationLocker`, might be useful to have it here in framework so we can easily switch to it.

2021-11-18 19:25 UTC, bdach commented on osu.Framework/Configuration/Orientation.cs
> +        Auto = 2
I find having "landscape", "portrait", "auto" and "locked" in one enum type turbo weird. It feels so ill-defined, the last one isn't even specific (locked to landscape or portrait?). Not to mention that this enum should also work just as well for iOS, eventually.

[Apple's take on this](https://developer.apple.com/documentation/uikit/uiinterfaceorientation) - although apparently deprecated in favour of [some inscrutable "trait" thing](https://developer.apple.com/documentation/uikit/uitraitcollection) - seems to be designed towards allowed orientation and I think that it's a saner choice. Just basically have a flag enum like so:

```csharp
public enum ScreenOrientation
{
    LandscapeLeft,
    LandscapeRight
    Portrait,
    PortraitUpsideDown,
    AnyLandscape = LandscapeLeft | LandscapeRight,
    AnyPortrait = Portrait | PortraitUpsideDown,
    Any = AnyLandscape | AnyPortrait
}
```

It seems like that should map back to android & iOS-specific flags rather nicely...?

2021-11-18 19:54 UTC, Susko3 commented on osu.Framework/Configuration/Orientation.cs
> +        Auto = 2
Your enum looks much better, should give the user much more options.

`AnyLandscape` seems like a good default, since we set the default resolution on desktop to 1366x768.

We could have `Locked` logic local to `GameplayScreenRotationLocker` then.

Since we give the user more options in-app, I feel like these options should *always* override the screen rotation quick setting on Android. And possibly have an additional enum entry for 'follow system', which would let the system's auto-rotate setting control the orientation. (This is unnecessary for osu!, most users will be fine with the current options.)

**Rationale for this:**
I think most users set auto-rotate once and never change it. And when the user explicitly sets the orientation to landscape, they expect it to rotate both ways, regardless of set auto-rotate. This is how the YouTube app (will rotate both ways in fullscreen) and many landscape-only games behave.

Because of `GameplayScreenRotationLocker`, we'll have no problems with the orientation accidentally changing during gameplay and users being angry because they "clearly set auto-rotate to off in settings".

2021-11-18 22:42 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
Because `osu.Framework.Android.Platform` namespace is used by the Android orientation manager, and the current namespace is `osu.Framework.Android` so `Platform.` will be understood by the compiler as `osu.Framework.Android.Platform` instead of `osu.Framework.Platform`

Just there to make it compile basically.

2021-11-18 23:02 UTC, Susko3 commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
![image](https://user-images.githubusercontent.com/16479013/142510476-66523ea8-fd43-4a4f-b9ed-50010fe92faa.png)

The newly-added `AndroidOrientationManager` is in a new folder.

Maybe it's cleaner to do
```cs
using WindowState = osu.Framework.Platform.WindowState;
```

Or just move `AndroidOrientationManager` to `osu.Framework.Android`. After all, all other platform things such as `AndroidGameWindow` or `AndroidGameHost` reside in `osu.Framework.Android`.

2021-11-18 23:11 UTC, honguyenminh commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
Because we would need this exposed to implement the locking mechanism in osu.

2021-11-18 23:17 UTC, Susko3 commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
That is not necessarily required, as one can do `.TriggerChange` on the framework setting bindable to force framework to set the correct orientation again.

Or just run the current screen orientation trough `OrientationToScreenOrientation` when turning off locked orientation.

2021-11-18 23:22 UTC, bdach commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
I'm a strong believer that the game side rotation locking flow should still be using the framework setting added here, rather than manually sidestepping it by directly accessing the activity.

2021-11-18 23:22 UTC, honguyenminh commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        protected Activity GameActivity { get; set; }
Will be `private` in next commits

2021-11-18 23:24 UTC, bdach commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
Yeah the platform namespace suffix is probably not necessary. Pretty much everything residing in the android project is platform specific anyway.

2021-11-18 23:30 UTC, Susko3 commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
`Window.Attributes.ScreenOrientation` seems like a promising place to get the current orientation (direction specific) and then apply that.

2021-11-18 23:39 UTC, honguyenminh commented on osu.Framework/Platform/OrientationManager.cs
> +        protected Bindable<Orientation> OrientationBindable;
you mean `protected Bindable<Orientation> OrientationBindable { get; set; }`
or
`public Bindable<Orientation> OrientationBindable { get; protected set; }`?

I think the latter but not sure

2021-11-18 23:41 UTC, honguyenminh commented on osu.Framework/Platform/OrientationManager.cs
> +        protected OrientationManager() { }
So that people can't initialize the class without initializing the config to avoid bugs. But yeah, I'll make it private, protected doesn't make sense here.

2021-11-18 23:48 UTC, honguyenminh commented on osu.Framework/Platform/OrientationManager.cs
> +        protected OrientationManager() { }
Will be deleted in next commits

2021-11-18 23:49 UTC, honguyenminh commented on osu.Framework/Configuration/Orientation.cs
> +    public enum Orientation
Should I change everything else's name to match too (`ScreenOrientationManager`, `AndroidScreenOrientationManager`), or just change the enum only?

2021-11-18 23:56 UTC, honguyenminh commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +        public ScreenOrientation CurrentScreenOrientation { get; internal set; }
So we should implement and expose a lock and unlock method here too, right?

Honestly I don't think any game would actually use this apart from osu though, even other mobile rhythm games don't. But having a choice is still nice, I guess.

2021-11-18 23:57 UTC, honguyenminh commented on osu.Framework.Android/Platform/AndroidOrientationManager.cs
> +                default:
Will be changed in next commits

2021-11-18 23:58 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
Will move to outer namespace and revert this commit

2021-11-19 00:05 UTC, Susko3 commented
This PR desperately needs tests, because currently `OrientationManager` isn't hooked up to anything and the Android one isn't either.

Also, why does this have to be a class? Potential consumers should only interact with `FrameworkSetting.Orientation`.

This should be a simple `.BindValueChanged()` on the setting here:

https://github.com/ppy/osu-framework/blob/1d5c093173a803673baef6ce227c91e2175fcaef/osu.Framework.Android/AndroidGameActivity.cs#L61-L73

(Create a new public bindable at `GameHost` and use that here? Similar to `AllowScreenSuspension`.)

2021-11-19 10:11 UTC, honguyenminh commented on osu.Framework/Platform/OrientationManager.cs
> +        public abstract void OrientationSettingChangedHandler(ValueChangedEvent<Orientation> value);
Will change in next commits

2021-11-19 21:57 UTC, bdach requested changes

2021-11-19 22:26 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +                    return AndroidPM.ScreenOrientation.UserPortrait;
I think having `SensorLandscape` for `AnyLandscape` and `SensorPortrait` for `AnyPortrait` is more useful to / expected from users. Rationale: https://github.com/ppy/osu-framework/pull/4897#discussion_r752579428

After all, `ScreenOrientation.Any` uses `FullSensor`, not `FullUser`.

2021-11-19 22:48 UTC, Susko3 requested changes

2021-11-19 22:48 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public void SetOrientationLock(bool isLocked)
Should be moved to base class.

And probably move most of the `isLocked` logic there as well.

2021-11-19 22:48 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
I don't see how this being public is useful.

> Override this to customize orientation flags

If consumers want to modify screen orientation, they should do it exclusively trough `FrameworkSetting.ScreenOrientation`, without having to worry about the native implementation.

2021-11-19 22:48 UTC, Susko3 commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
As seen in this test, consumers have to create an `OrientationManager` if they want to use `FrameworkSetting.ScreenOrientation`. This doesn't make any sense. Framework settings should be self-contained in the framework.

All other `FrameworkSetting`s are bound to natively in the framework, and those bindings automatically run the necessary native functions.

2021-11-30 11:34 UTC, honguyenminh commented on osu.Framework/Configuration/ScreenOrientation.cs
> +        LandscapeRight = 2,
Fixed

2021-11-30 11:34 UTC, honguyenminh commented on osu.Framework/Configuration/ScreenOrientation.cs
> +        AnyLandscape = LandscapeLeft | LandscapeRight, // 3
It's just old habit, removed in next commits

2021-11-30 11:34 UTC, honguyenminh commented on osu.Framework.Tests.Android/AndroidVisualTestGame.cs
> +        // Allows dependency injection
Removed

2021-11-30 11:44 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
`Disabled` would disallow change to the setting while the game is being played (orientation locked) though. Wouldn't this break osu!'s hot setting change while playing feature?

2021-11-30 12:20 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +                    var nativeOrientation = manager.SettingToNativeOrientation(orientation);
Changed, i was weird that day

2021-11-30 12:27 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +                    return AndroidPM.ScreenOrientation.UserPortrait;
`AnyLandscape` and `AnyPortrait` are better than the sensor ones, because they are basically Sensors but they respect user's auto-rotate setting. Sensor are annoying, because they bypass the setting altogether.

I chose `FullSensor` for `Any` because it's the only one that does not reset back to standing portrait when user lock auto-rotate. If `FullUser` doesn't revert back to Portrait on lock, I'll totally use it. But it's not, so I had no other choice.

2021-11-30 12:54 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Was originally public to allow consumer to get the actual native flag of a setting, some app might need it, but yeah, if you deem it to be unnecessary I'll make it protected

2021-11-30 14:31 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public void SetOrientationLock(bool isLocked)
Moved

2021-11-30 15:39 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Will implement the class in android game host instead.
Sorry, I'm not used to the framework codebase yet, so I just don't know how to actually use it in the framework.

2021-11-30 17:16 UTC, Susko3 commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Could do something similar to this.  (Unless you found a better way.)

https://github.com/ppy/osu-framework/blob/16e9569a3fb613732accc1e701c9eac4d53cbb93/osu.Framework.Android/AndroidGameActivity.cs#L61-L73

2021-11-30 17:21 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Do you need a native orientation in the test? The only way to confirm that the test passed is to look at the actual screen orientation of the actual device.

If the reported/actual screen orientation is required for something else, it should be reported as `Framework.Configuration.ScreenOrientation`. Consumer should never have to worry about converting native orientation.

2021-11-30 17:34 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +                    return AndroidPM.ScreenOrientation.UserPortrait;
>Sensor are annoying, because they bypass the setting altogether.

That's why we differentiate `LandscapeLeft` and `LandscapeRight` from `AnyLandscape`. If the user wants to lock their orientation in a specific landscape, they can.

I can see `UserPortrait` being the expectation from users, but _every single landscape-supported app_ on my phone behaves like `SensorLandscape` when in landscape/fullscreen. By using `UserLandscape`, we are breaking user expectations.

2021-11-30 17:35 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
The orientation is unlocked when not playing / paused. So no problems hot swapping there.

2021-11-30 23:21 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Nah, it's just simply needed to show the current setting in the text box, tests passing does not depend on this.

If removed, we would need another way to update that textbox when the native screen orientation flag changes.

2021-11-30 23:23 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Now consumer only need to interact with the setting itself and use the lock bindable inside `GameHost` to lock the orientation.

2021-11-30 23:35 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Do we need that textbox?

2021-11-30 23:47 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
I mean, we are locking the screen orientation, not the setting itself, while `Disabled` is used to disable the setting altogether. Currently this separate variable allows consumer to change the setting even while playing (locked) and new setting will take effect after unlocked. This allows more flexibility for consumer imo.

If you think this is overkill then I'll move to `Disabled` property instead

2021-11-30 23:53 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
I mean it does occasionally helps me while debugging by telling me why the test failed.

If there's a `RequestedOrientationChanged` event in the Xamarin framework, I would never make it public in the first place.

So, we remove the textbox, right? I'll try to find a way to keep it without the method public, delete otherwise.

2021-11-30 23:53 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
I think you should move to `Disabled`, as currently, changing the framework setting won't update orientation if it's locked (early return [here](https://github.com/ppy/osu-framework/blob/90b0a57c088e9efc55d1b8dd21474f20e5f991ad/osu.Framework.Android/AndroidOrientationManager.cs#L64)). The setting is logically "disabled", makes more sense if it's actually `Disabled` in that case.

2021-12-01 00:01 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
If it's only for local debugging, you should remove it / not include it in the PR.

The test should, ideally, be platform-agnostic since it's testing sometimes common to all platforms -- a `FrameworkSetting`.

The test won't be of much use on desktop (only test that it doesn't crash; changing orientation is a noop on desktop), but it should be useful for both Android and iOS (when implementation comes).

So no platform specific orientations. (If it's really required for testing/debugging -- exposed as a raw `string`).

2021-12-01 01:53 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        public virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Is protected now. The event is triggered after the class has run, so textbox works fine without the method. I was based I guess.

2021-12-01 02:13 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
I'll leave this for user to discuss, tbh I still want to separate the locking mechanism (which change the actual screen orientation, not the setting) from disabling the setting at all.

2021-12-01 03:06 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Can I do something like in latest commit instead?

2021-12-01 03:07 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Kind of implemented it in the latest commit, can you review it?

2021-12-03 00:02 UTC, honguyenminh commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +            manager = new AndroidOrientationManager(config, gameActivity);
Can you review it again? I'm not sure about my approach on this.

2021-12-03 12:02 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +                    return AndroidPM.ScreenOrientation.UserPortrait;
My concerns here haven't been addressed. This conversion shouldn't be marked as resolved.

2021-12-03 12:22 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +                    return AndroidPM.ScreenOrientation.UserPortrait;
Fair enough.
Will change in next commit

2021-12-03 12:31 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
I'll keep the lock mechanism separate from `Disabled`, because using `Disabled` as lock control breaks consumer's expectation, and creates an edge case for this one setting, we would have to notice user in the docs about this too. Disabling a setting shouldn't create side effects like locking the orientation.

2021-12-03 12:33 UTC, Susko3 requested changes
CI isn't picking this up, but there are multiple inspections in the Android side of things.

2021-12-03 12:33 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        protected virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
As a consumer, it's not possible to override this behaviour (can't override the orientation manager provided by `GameHost`).

And I don't see how overriding this behaviour is necessary.

2021-12-03 12:33 UTC, Susko3 commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +    public abstract class ScreenOrientationManager
Should be `internal`, as it's managed entirely by framework/`GameHost`, and consumers should only interact with it indirectly trough the new setting and the `LockScreenOrientation` bindable.

Same goes for `AndroidOrientationManager`.

2021-12-03 12:33 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            screenOrientationManager = GetScreenOrientationManager();
Shouldn't `ScreenOrientationBindable` here be a simple function parameter to `GetScreenOrientationManager()`?
Instead of being a field that's accessed in `AndroidGameHost` for the sole reason of using it in the overridden `GetScreenOrientationManager()`

2021-12-03 12:33 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            };
Should probably be moved to `ScreenOrientationManager`. And then pass the bindable in the ctor.

2021-12-03 12:33 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +        protected virtual ScreenOrientationManager GetScreenOrientationManager() => null;
```suggestion
        protected virtual ScreenOrientationManager CreateScreenOrientationManager() => null;
```

Should be `Create...` for classes that are single-instanced. To match `CreateWindow()`, `CreateReadableKeyCombinationProvider()`, etc.

`GetClipboard()` is creating a new clipboard every time, so it's `Get...`.

2021-12-03 12:42 UTC, honguyenminh commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        protected virtual AndroidPM.ScreenOrientation SettingToNativeOrientation(ScreenOrientation orientation)
Will be private in next commit

2021-12-03 12:54 UTC, honguyenminh commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +    public abstract class ScreenOrientationManager
If `ScreenOrientationManager` is internal, we wouldn't be able to access (and derive from) it from `osu.Framework.Android` because it is in a different project (assembly) so I'll keep the base class public.
Android implementation can be internal though.

2021-12-03 12:56 UTC, Susko3 commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +    public abstract class ScreenOrientationManager
`osu.Framework.Android` should probably have `osu.Framework` internals visible.

Add it here: [osu.Framework/Properties/AssemblyInfo.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Properties/AssemblyInfo.cs)

2021-12-03 12:59 UTC, honguyenminh commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +    public abstract class ScreenOrientationManager
Changed in next commit

2021-12-03 14:50 UTC, honguyenminh commented on osu.Framework/Platform/GameHost.cs
> +            screenOrientationManager = GetScreenOrientationManager();
Changed in latest commit

2021-12-03 15:24 UTC, Susko3 commented on osu.Framework.Android/AndroidOrientationManager.cs
> +        private bool isLocked = false;
> breaks consumer's expectation

Don't think there is any consumer expectation about disabling settings/config bindables. Probably the only expectation is from the framework, and that is that those bindables aren't disabled by consumers. Maybe even don't do manual checks that the bindable is disabled, as it'll throw [here](https://github.com/ppy/osu-framework/blob/3a6512b948da679a6ded1b53ef27358d7eaf61e5/osu.Framework/Bindables/Bindable.cs#L90-L91) for you.

So agreed that a bindable at `GameHost` (like you have right now) is a better option.

2021-12-05 13:16 UTC, bdach requested changes
Still of the opinion that the "orientation manager" has no reason to exist at all.

2021-12-05 13:16 UTC, bdach commented on osu.Framework/Configuration/ScreenOrientation.cs
> +        /// Locked landscape, with top-down goes from left to right on the portrait screen
I don't get this xmldoc. Shouldn't this just say "device rotated 90 degrees left from default portrait orientation" or similar?

2021-12-05 13:16 UTC, bdach commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +        protected abstract void OnScreenOrientationLocked();
What's the point of these if the setting bindables are there already? Surely you could just `BindValueChanged()` onto the bindables rather than use this?

2021-12-05 13:16 UTC, bdach commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +                throw new InvalidOperationException("Can't change screen orientation lock when setting is disabled");
This makes no sense to me. What does this mean? How can this happen?

2022-01-10 10:31 UTC, honguyenminh commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +        protected abstract void OnScreenOrientationLocked();
Done. I totally overthink this.

2022-01-10 10:31 UTC, honguyenminh commented on osu.Framework/Platform/ScreenOrientationManager.cs
> +                throw new InvalidOperationException("Can't change screen orientation lock when setting is disabled");
This will throw if consumer disabled the orientation config, but still try to change the lock state. Or am I getting something wrong?

2022-01-17 03:27 UTC, peppy requested changes

2022-01-17 03:27 UTC, peppy commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    else host.ScreenOrientation.TriggerChange();
This is really bad. Split out the required logic to its own method rather than calling `TriggerChange`.

Or even better, simplify this whole block to:

```suggestion
  RunOnUiThread(() =>
                         {
                             RequestedOrientation = e.NewValue ? NativeOrientation.Locked : configToNativeOrientationEnum(host.ScreenOrientation.Value);
                         });
                    else host.ScreenOrientation.TriggerChange();
```

2022-01-17 03:27 UTC, peppy commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    if (host.ScreenOrientation.Disabled)
Why isn't this just a direct bind to avoid this nonsense?

2022-01-17 03:27 UTC, peppy commented on osu.Framework.Android/AndroidGameActivity.cs
> +                host.ScreenOrientation.BindValueChanged(e =>
Doesn't this need a `true` argument to ensure it's run once?

2022-01-17 03:27 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
I'm not sure how well these settings will play with what iOS exposes as configurable in terms of locking/rotating. That should be visited before merging this.

2022-01-17 04:26 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameWindow.cs
> +        public override Framework.Platform.WindowState WindowState
This change has been manually reverted at 712c8668112ddb637b2890c38b24066ec2d53279

2022-01-17 04:55 UTC, honguyenminh commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
From what I can find, setting iOS orientation will lock the orientation to 1 of the 4 possible orientations, so locking is possible, but I'm not sure if we can do something similar to "SensorLandscape" of Android (allow both rotation).
I found this repo that can be helpful for implementing this [here](https://github.com/wcoder/Xamarin.Plugin.DeviceOrientation/blob/master/src/DeviceOrientation/Plugin.DeviceOrientation.iOS/DeviceOrientationImplementation.cs)

I don't own an iOS device so I'm not sure how iOS users would expect the orientation to behave, so some elaboration from an actual user would be helpful.

2022-01-17 05:03 UTC, frenzibyte commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
I believe it is possible to have locking and `SensorLandscape`-like support for iOS. Will look into writing a simple implementation for it today.

2022-01-17 05:16 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    if (host.ScreenOrientation.Disabled)
You mean directly binding it to Disabled of the screen orientation setting?

IMO doing that makes it hard for consumer to know about this behavior, since `Disabled` doesn't imply Locking the setting too. But if you think that's better, I'll move this there and remove the `LockScreenOrientation` bindable.

2022-01-18 10:22 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    else host.ScreenOrientation.TriggerChange();
Changed in next commits.

2022-01-19 10:28 UTC, frenzibyte commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
Sorry for the delay, I've got an implementation ready for this now (95deedfac4fd83e2661c69d638946734dfa72988), and have got a video showcasing behaviour for iOS:

https://user-images.githubusercontent.com/22781491/150105768-6e47be45-e60a-43c7-b88c-8f2660d9013d.mp4

(also tested locally on my iPhone)

Implementation was indeed mostly straightforward, as I only had to update the `UIDevice` when user changes orientation and block autorotation when new one doesn't respect what the user has set (or if `LockScreenOrientation` is set).

Few notes while implementing and testing on iOS:
 1. iPhones without home buttons do not support the `ReversePortrait` orientation as mentioned in [apple docs](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations), therefore it should be completely hidden in game settings:
    ![CleanShot 2022-01-19 at 12 52 13](https://user-images.githubusercontent.com/22781491/150106838-4866a5fc-04a6-41a4-a9bd-11c9c9cdde0a.png)
 2. Applications in iOS cannot fully bypass the phone's "Portrait Orientation Lock" (unlike Android, which does with its `sensorLandscape`/`fullSensor` orientations), but setting the orientation to `LandscapeLeft`/`LandscapeRight` will still work. I think the best choice would be to hide the "Auto" orientation in game settings and include a note when using `AnyLandscape`/`Any` that it won't autorotate if the user has enabled portrait lock.

2022-01-24 06:18 UTC, peppy commented on osu.Framework.Android/AndroidGameActivity.cs
> +                host.ScreenOrientation.BindValueChanged(e =>
@honguyenminh are you going to test/apply this change? probably required to move forward with this PR.

2022-01-24 06:23 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
Well, more importantly, I think you'll find *none* of these options should be exposed to the user on iOS.

2022-01-24 06:23 UTC, peppy commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    if (host.ScreenOrientation.Disabled)
I think I misunderstood this, seems alright how you have it. Probably doesn't need the comment above as it's explaining exactly what the code is going (same goes for the comment on line 99).

2022-01-24 09:46 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameActivity.cs
> +                host.ScreenOrientation.BindValueChanged(e =>
Will change in next commit.
Sorry lunar new year's been dragging me back for a while.

2022-01-24 09:48 UTC, honguyenminh commented on osu.Framework.Android/AndroidGameActivity.cs
> +                    if (host.ScreenOrientation.Disabled)
Alrighty.

2022-01-24 10:33 UTC, frenzibyte commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
I don't follow what you mean? are you saying that iOS applications should usually not have a setting for changing orientation programmatically?

2022-01-24 10:49 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
Correct. I don't think I've ever seen it in an app, which means it's likely against the UX guidelines.

2022-01-24 10:51 UTC, honguyenminh commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
So this should be an Android-only thing?

I can try to move this to Android host specifically. Can't guarantee if I can actually do it without a mess of code though.

2022-01-24 10:51 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
No it's in the correct place. It just should not be exposed to the user.

2022-01-24 11:02 UTC, honguyenminh commented on osu.Framework/Platform/GameHost.cs
> +        public readonly Bindable<bool> LockScreenOrientation = new Bindable<bool>();
I do find a few interesting thing on android side too. The Any<Portrait/Landscape> settings will not actually rotate to the reverse orientation from the home button or the "main" orientation of current device.
For example: a tablet with default orientation of landscape 90deg *clockwise* will **NOT** auto rotate to landscape 90deg *counter-clockwise* on setting's `AnyLandscape` aka native's `SensorLandscape` or `UserLandscape`. Or for a normal portrait phone (the one I'm using to test this for example), will not rotate to reverse portrait on `AnyPortrait` or <Sensor/User>Portrait. Seems like what orientation will be blocked by this is defined by OEM, but I can't find docs about this yet.
I can't seem to find a way to bypass this from code though. Full<User/Sensor> will bypass this fine, but these allow all orientation so that only makes `Auto` and `Any` work.

2022-02-01 11:01 UTC, Susko3 commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +namespace osu.Framework.Tests.Android.Visual.Platform
![Screenshot_2022-01-24-13-02-39-11_fca46a2731136e673b8638a972bc0192(1)](https://user-images.githubusercontent.com/16479013/151955463-ae49fd85-69cc-4891-b539-b4be5b56b27f.jpg)

These Android-only tests do make the test browser a bit weird.

These tests also aren't really testing the behaviour (the actual rotation of the device), they are just testing whether the correct orientation flags are set. The usefulness of this is dubious for me. Only useful thing that it's doing is validating locking behavior.

2022-02-01 11:05 UTC, peppy commented
I've tidied this up, but in the process I'm still not making sense of how this is to be used by a consumer.

I don't think it should be in the config full stop. Android and iOS has rotation lock, so that doesn't need to be locked here. If anything, it should either be:

- A startup setting set by the game
- Something the game can change at runtime, but not the user (ie. it shouldn't be in config)

Also I don't think there needs to be a separate "locked" property. That's android specific, and can probably be merged into the main enum and throw if attempted to be used on a platform that isn't android.

2022-02-01 11:32 UTC, Susko3 commented
The original issue, for reference: https://github.com/ppy/osu/issues/12764 (not sure how this was lost in the PR).

My idea for the framework-side setting is to make it easier for consumers to change the setting without having to worry about running on UI thread, resolving the Activity, etc. And also to allow users to change the setting how they see fit. (Someone might want to play osu! in portrait, you never know.)

Exposing screen orientation to the user is common UX on Android.

>A startup setting set by the game

This is already how Android works, see `ScreenOrientation = ScreenOrientation.FullUser` [here (`OsuGameActivity`)](https://github.com/ppy/osu/blob/2c0c44a9504c831686d49f52b574051ec03cc092/osu.Android/OsuGameActivity.cs#L20).

We should probably change the default to be landscape.

2022-02-03 10:58 UTC, peppy requested changes

2022-02-03 10:58 UTC, peppy commented on osu.Framework.Tests.Android/Visual/Platform/TestSceneScreenOrientation.cs
> +namespace osu.Framework.Tests.Android.Visual.Platform
I'd argue that this test should be in the standard framework tests? Not sure why it needs to be in the android project.

2022-02-03 10:58 UTC, peppy commented on osu.Framework/Configuration/FrameworkConfigManager.cs
> +            SetDefault(FrameworkSetting.ScreenOrientation, ScreenOrientation.AnyLandscape);
This is changing the default for *all consumers*. This should not be the case.

2022-02-03 10:59 UTC, peppy commented
I can say that this will not be merged unless it is removed from the config. Keep it as a game host setting and document it with a note that it won't apply to anything but android.

Or just don't do any of this and leave it up to the consumer to implement android specific behaviour if they want it.

2022-02-03 11:06 UTC, peppy commented
Let's keep this simple and close this PR for now.

@honguyenminh sorry to do this after the work you've put in, but hopefully you can understand why. I am willing to bring this back if there is demand to have the setting in other consumer projects (if this was implemented for your own use in another project please say so - to my knowledge it was added specifically for osu!, where we have decided we likely won't need the functionality).

To summarise:

- On android users (sometimes) expect apps to allow them to set orientation settings within the app.
- On iOS, such settings are not ever present.
- On desktop platforms this is irrelevant.

Because we are targetting multiple platforms, but focusing on providing consolidated/consistent behaviour across them all (without platform-specific features wherever possible) this change doesn't align with our goals.

The recommended method is to set startup values via `Info.plist` (iOS) or `ActivityAttribute` (Android). If you decide that you want to expose settings to the user (I'd argue is a pretty weird/unexpected UX but I am an apple user where UX means everything so YMMV), it should be easy enough to copy the implementation in this pull request into your own project / `ConfigManager` and get the required behaviour.

2022-02-03 11:06 UTC, closed without merging