Hide `TextBox` caret when `GameHost` is inactive / keyboard focus is lost
ppy/osu-framework pull request #4910
Opened 2021-11-22 15:56 UTC by Susko3

A blinking cursor signals to the user that keyboard input will appear at that cursor.
This PR hides the caret when we lose keyboard focus to conform with that expectation.

Only hides the caret if there is no selection. The current show/hide logic on focus/unfocus is kept.
Native applications will usually grey-out the selection when inactive, but that is unnecessary for us.

2021-11-22 16:17 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +                    || selectionLength != 0);
would probably be better grouping the code and comment into one-liners, feels off to read it like that.

2021-11-22 20:02 UTC, bdach requested changes

2021-11-22 20:02 UTC, bdach commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +            isActive.BindValueChanged(_ => Scheduler.AddOnce(updateCaretVisibility));
`BindValueChanged` callbacks are usually registered in `LoadComplete()`.

Also this should presumably run the first time to avoid showing the caret if the window is initially unfocused? (i.e. call `BindValueChanged(..., true)`).

2021-11-22 20:02 UTC, bdach commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +                    || selectionLength != 0);
I would even go as far as to say that the comments bring no significant value as they mostly restate the code. A more pertinent comment would explain *why* such a conditional was written, not what was in it.

2021-11-22 21:52 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +            isActive.BindValueChanged(_ => Scheduler.AddOnce(updateCaretVisibility));
Caret is [initially hidden](https://github.com/ppy/osu-framework/pull/4910/files#diff-0931d11ac8154d00e8c67e85c8dd9e86cbacc227d9bbe2eab1a0232bd56b77adR149-R150), so no problem there.

2021-11-23 20:54 UTC, bdach commented
Implementation seems generally sane, and the UX looks to match standard textbox UI paradigms. Going to request a double check of this first, however.

2021-11-23 20:54 UTC, bdach approved these changes

2021-11-24 01:33 UTC, peppy approved these changes

2021-11-24 02:04 UTC, merged