Log loading components on test failure or game exit
ppy/osu-framework pull request #4938
Opened 2021-12-16 10:50 UTC by peppy

May help with figuring out the cause of intermittent failing tests. Just maybe.

```csharp
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #4 push slow
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #5 push slow
[runtime] 2021-12-16 10:42:53 [verbose]: 📺 ScreenStack transition (TestScreenSlow » TestScreenSlow)
[runtime] 2021-12-16 10:42:53 [verbose]: 🔸 Step #6 push slow
[runtime] 2021-12-16 10:43:03 [verbose]: 💥 Step #7 Until: wait for screen 2 to load (23962 tries)
[runtime] 2021-12-16 10:43:03 [verbose]: ⏳ Currently loading components
[runtime] 2021-12-16 10:43:03 [verbose]: - TestSceneScreenStack+TestScreenSlow LoadState:Loading Thread:ThreadedTaskScheduler (LoadComponentsAsync (standard))
[runtime] 2021-12-16 10:43:03 [verbose]: - TestSceneScreenStack+TestScreenSlow LoadState:Loading Thread:ThreadedTaskScheduler (LoadComponentsAsync (standard))
[runtime] 2021-12-16 10:43:03 [error]: An unhandled error has occurred.
```

2021-12-16 13:28 UTC, smoogipoo requested changes

2021-12-16 13:28 UTC, smoogipoo commented on osu.Framework/Logging/LoadingComponentsLogger.cs
> +                {
This is unnecessary, right?

2021-12-16 21:58 UTC, bdach approved these changes

2021-12-17 00:42 UTC, smoogipoo commented on osu.Framework/Logging/LoadingComponentsLogger.cs
> +                    Logger.Log($"- {c.GetType().ReadableName(),-16} LoadState:{c.LoadState,-5} Thread:{c.LoadThread.Name}");
Today I learnt about this alignment syntax. Though I'm not sure the -5 is doing much here - it would have to be -9 because that's the max length.

2021-12-17 00:42 UTC, smoogipoo approved these changes

2021-12-17 00:42 UTC, merged

2021-12-17 09:02 UTC, smoogipoo commented on osu.Framework/Logging/LoadingComponentsLogger.cs
> +        public static void LogAndFlush()
These will never run in osu!-side CI. This refers to the environment which o!f is compiled with. You'd need to make use of `DebugUtils` otherwise.

2021-12-17 09:04 UTC, peppy commented on osu.Framework/Logging/LoadingComponentsLogger.cs
> +        public static void LogAndFlush()
Hmm, that's unfortunate.

Does that also mean that this method should not be publicly exposed?

https://github.com/ppy/osu-framework/blob/dde9eb08ede4aa94d21590f92b7c60f85cac3947/osu.Framework/Logging/Logger.cs#L270-L274

2021-12-17 09:05 UTC, smoogipoo commented on osu.Framework/Logging/LoadingComponentsLogger.cs
> +        public static void LogAndFlush()
Yeah that will have the same issue.