Add Shadow Colour and Offset to SpriteIcon
ppy/osu-framework pull request #4939
Opened 2021-12-16 15:46 UTC by H2n9

Added properties for `ShadowOffset` and `ShadowColour`. 
Noticed these weren't exposed when working on my own framework project.

Example
![image](https://user-images.githubusercontent.com/7267697/146402196-23f5a3ec-a958-4f93-b234-564e4605fc4f.png)

Default values have been set to visually match previous behaviour. 
Test steps also added to `TestSceneSpriteIcon`.

2021-12-16 19:18 UTC, bdach requested changes

2021-12-16 19:18 UTC, bdach commented on osu.Framework/Graphics/Sprites/SpriteIcon.cs
> +                spriteShadow.Colour = shadowColour;
This setter is unsafe to call before BDL. See following patch:

```diff
diff --git a/osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs b/osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
index 0a6050b959..0e0f234ff9 100644
--- a/osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
+++ b/osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
@@ -77,6 +77,13 @@ public TestSceneSpriteIcon()
             AddStep("white background", () => background.FadeColour(Color4.White, 200));
             AddStep("move shadow offset", () => flow.Children.OfType<Icon>().ForEach(i => i.SpriteIcon.ShadowOffset += Vector2.One));
             AddStep("change shadow color", () => flow.Children.OfType<Icon>().ForEach(i => i.SpriteIcon.ShadowColour = Color4.Pink));
+            AddStep("add new icon", () => flow.Add(new SpriteIcon
+            {
+                Size = new Vector2(16),
+                Shadow = true,
+                ShadowOffset = new Vector2(5),
+                ShadowColour = Color4.Red
+            }));
         }
 
         private class Icon : Container, IHasTooltip
```

This leads to a crash on a null reference.

2021-12-16 21:26 UTC, H2n9 commented on osu.Framework/Graphics/Sprites/SpriteIcon.cs
> +                spriteShadow.Colour = shadowColour;
Should be fixed now. Test case added as well.

2021-12-16 22:10 UTC, bdach commented on osu.Framework/Graphics/Sprites/SpriteIcon.cs
> +                    spriteShadow.Colour = shadowColour;
The idea here is right, but this is usually done [by checking `IsLoaded` instead](https://github.com/ppy/osu-framework/blob/fa15cbee7992b7be1803042cedee233485003ee2/osu.Framework/Graphics/Containers/ModelBackedDrawable.cs#L47-L48), and having `LoadComplete()` [apply any values that were potentially set beforehand](https://github.com/ppy/osu-framework/blob/fa15cbee7992b7be1803042cedee233485003ee2/osu.Framework/Graphics/Containers/ModelBackedDrawable.cs#L91). ([Another game-side example.](https://github.com/ppy/osu/blob/7654df94f6f37b8382be7dfcb4f674e03bd35427/osu.Game.Tournament/Screens/Gameplay/Components/MatchHeader.cs))

Doing it that way is theoretically safer, because BDL executes on a separate thread rather than on the update thread, so with this implementation you could potentially have a race between the read of `spriteShadow` here and its write in BDL, which would cause a value set to be potentially silently dropped..

2021-12-16 22:22 UTC, H2n9 commented on osu.Framework/Graphics/Sprites/SpriteIcon.cs
> +                    spriteShadow.Colour = shadowColour;
Thanks for the explanation. If I am understanding correctly, would that also mean that [`bool Shadow`](https://github.com/ppy/osu-framework/blob/a5852bd26f0b4a1b21d1d9b9854e871432d4302c/osu.Framework/Graphics/Sprites/SpriteIcon.cs#L118-L119) has the same issue. Should I include a change for that aswell?

2021-12-16 22:25 UTC, bdach commented on osu.Framework/Graphics/Sprites/SpriteIcon.cs
> +                    spriteShadow.Colour = shadowColour;
Sure, I suppose. Probably never going to be a better time than now.

2021-12-18 20:00 UTC, bdach approved these changes
Seems harmless, but I'll wait for a second opinion that this API is wanted.

2021-12-19 05:17 UTC, peppy approved these changes
This change does make me question why the offset is different from `SpriteText`, but that's out of scope of what's being done here I guess.

2021-12-19 11:54 UTC, merged