Add `AndroidMouseHandler` and improve Android mouse input
ppy/osu-framework pull request #4971
Opened 2021-12-27 15:55 UTC by Susko3

This brings us one step closer to resolving https://github.com/ppy/osu-framework/issues/4373.

In addition to separating mouse from touch events, `AndroidMouseHandler` enables the following:
- support for all mouse buttons (including forward and back)
- support for scrolling
- starting point for implementing [pointer capture](https://github.com/ppy/osu-framework/issues/4373#issuecomment-836278499).

---

Tested on Realme 6, Android 11 (API 30) with a bluetooth mouse.
On-screen keyboard input works as expected.

Test existing behaviour isn't broken for:
- [ ] physical keyboard
- [ ] stylus

2021-12-27 20:00 UTC, bdach reviewed
seemingly correct but i have no actual means to test

2021-12-27 20:40 UTC, Susko3 commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +                    view.MouseKeyLongPress += onKeyDown;
It should be fine, as the button state won't change if a press is queued/applied and that button is already pressed:

https://github.com/ppy/osu-framework/blob/cf3687ed8bbeec6122110d71988f39dd07878038/osu.Framework/Input/States/ButtonStates.cs#L34-L43

But yeah, `MouseKeyLongPress` is unnecessary, as it will never change state, and probably will never get sent by Android. (From my testing, it's always a normal key down, never a long press.)

2021-12-27 21:18 UTC, Susko3 commented on osu.Framework.Android/AndroidGameView.cs
> +        public event Action<Keycode, KeyEvent> MouseKeyDown;
How about having a input handler parent to all android input handlers. Skeleton of the relevant bits:

```cs
public abstract class AndroidInputHandler : InputHandler
{
    protected abstract IEnumerable<InputSourceType> AllowedInputSources { get; }

    // since InputSourceType is a bitmask, we can precompute it and quickly match it.

    protected bool IsEventSourceCorrect(MotionEvent motionEvent)
    {
        // return true if event source matches AllowedInputSources.
    }
}
```

And then have all handlers inherit `AndroidInputHandler` and check the event source:

```cs
public class AndroidTouchHandler : AndroidInputHandler
{
    protected override IEnumerable<InputSourceType> AllowedInputSources => new[] { InputSourceType.Stylus, InputSourceType.Touchscreen };

    // ...
    
    private void handleTouch(object sender, View.TouchEventArgs e)
    {
        if (!IsEventSourceCorrect(e.Event)) return;
        
        // handle the event...
    }  
}
```

With that, we can have handlers subscribe to generic motion events, and avoid doing the source check in AndroidGameView.

2021-12-28 08:20 UTC, bdach commented on osu.Framework.Android/Input/AndroidKeyboardHandler.cs
> +            if (!ShouldHandleEvent(e)) return;
I can generally agree with this overall structure but the base class should be responsible for checking `ShouldHandleEvent()` rather than each individual handler, if possible. Too easy to forget about it otherwise.

2021-12-28 08:20 UTC, bdach commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +                // ReSharper disable once BitwiseOperatorOnEnumWithoutFlags (InputSourceType is a flags enum, but is not properly marked as such)
Please don't put textual comments about resharper disables in the same line as the disable as that can have unintended effects such as disabling all inspections file-wide. See https://github.com/ppy/osu-framework/pull/4847#issuecomment-953180147, https://github.com/ppy/osu-framework/pull/4847#issuecomment-953464505.

2021-12-28 13:22 UTC, Susko3 commented on osu.Framework.Android/Input/AndroidTouchHandler.cs
>          {
Using `MotionEvent` because `e.Event` is nullable and I didn't want to have a null check.

2021-12-29 09:29 UTC, bdach commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +        protected abstract IEnumerable<InputEventType> HandledEventTypes { get; }
Not super sure on this setup. Rather than having to declare event types the handler is interested in and then having to override the correct methods (lest you get `NotSupportedException` at runtime), you could just subscribe to all events but leave the handlers empty. That'd get rid of some of the boilerplate.

I don't *hate* this setup though, will wait for more opinions.

2022-01-03 02:22 UTC, peppy commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +        protected abstract IEnumerable<InputEventType> HandledEventTypes { get; }
I can agree with this. Seems like too much boilerplate for an edge case usage as it's currently written.

2022-01-03 03:38 UTC, peppy requested changes
PR in general seems pretty fine, but would like to see it with manual event binding at each usage as proposed.

2022-01-04 03:04 UTC, peppy commented
Code looks good now. I'll try and give it a test today against touch and stylus.

2022-01-04 10:45 UTC, peppy commented
Stylus and touch work as expected here 👍

2022-01-04 20:42 UTC, bdach commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +            throw new NotSupportedException($"{nameof(HandleCapturedPointer)} subscribed to {nameof(View.CapturedPointer)} but the relevant method was not overriden.");
This isn't quite what I had in mind with my [last review](https://github.com/ppy/osu-framework/pull/4971#discussion_r776229506) but I suppose it works...?

To clarify, I was proposing subscribing to *all* input events which are available on the view at the `AndroidInputHandler` level, and calling the `OnEvent` methods on them there - as long as they match `eventSourceBitmask` - but leaving the input handlers blank to be overridden by inheritors. That way the only thing that needs to be done to handle an event in an implementation of this is overriding the correct handler, while this solution also requires manually hooking the events up in `OnInitialize()`.

2022-01-04 20:42 UTC, bdach commented on osu.Framework.Android/Input/AndroidKeyboardHandler.cs
> -        }
Also I notice that these unsubscribes on disposal seem to have been trimmed. Is something else going to do this automatically? It's probably not a huge deal either way but I feel safer with an explicit unsubscribe on disposal.

2022-01-04 20:47 UTC, Susko3 commented on osu.Framework.Android/Input/AndroidKeyboardHandler.cs
> -        }
https://github.com/ppy/osu-framework/blob/53b222719e0875c77f21737022f2194d7bb13c73/osu.Framework/Input/Handlers/InputHandler.cs#L79-L86

Base input handler sets enabled to false, so we're safe here.

2022-01-04 20:59 UTC, Susko3 commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +            throw new NotSupportedException($"{nameof(HandleCapturedPointer)} subscribed to {nameof(View.CapturedPointer)} but the relevant method was not overriden.");
I tried doing it how [peppy suggested](https://github.com/ppy/osu-framework/pull/4971#pullrequestreview-842470905), and figured it was less wasteful than your proposal. So I went with that.

2022-01-04 21:02 UTC, bdach commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +            throw new NotSupportedException($"{nameof(HandleCapturedPointer)} subscribed to {nameof(View.CapturedPointer)} but the relevant method was not overriden.");
Not sure any overhead from these events is ever going to matter but I don't feel like splitting hairs over this.

2022-01-04 21:03 UTC, bdach approved these changes
code seems fine, haven't tested, relying on @peppy's testing as i could only test the same part of this PR at most (don't have required hardware to test mouse)

2022-01-05 04:39 UTC, peppy approved these changes

2022-01-05 04:39 UTC, merged