Do not bypass the compositor on Linux by default
ppy/osu-framework pull request #4976
Opened 2021-12-31 13:58 UTC by Speykious

This PR aims at fixing #4693.

The change has been tested and successful so far on Arch Linux with the KDE desktop environment (basically: it works on my machine), specifically by opening the visual tests window which would have normally disabled the compositor.
Given that this change is just about the compositor, it shouldn't impact anything else in the framework, so testing-wise I think it's fine.
(also it's quite literally a single line change.)

Last thing: with that in mind, games which do want to bypass the compositor (such as osu!) would have to use the `SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR` environment variable, unless we directly code in a way to specify whether we want to do that. What would be the preferred way here in your view?

2021-12-31 15:16 UTC, peppy commented
I'm not even sure it's worth keeping this open. In its current state it is useless. You can add this hint in your application and get the same effect.

By adding it in the framework without any way to mutate it, you are making a breaking change, and one that we likely do not want.

2021-12-31 16:42 UTC, Speykious commented
Hmmm... Looks a tiny bit tricky to do the exposing right. I'll try though.

Wouldn't adding this hint in other applications require adding the `ppy.SDL2-CS` package to dependencies as well? In my view letting the framework expose it is the best option.

2021-12-31 17:03 UTC, Speykious commented
I'm really unsure if the `LinuxGameHost` should be responsible for this, not to mention that I then had to add an additional argument to the method in the static `Host` class...

2022-01-01 04:02 UTC, peppy commented
To confirm, having compositor enabled means the window is being re-buffered and thus introducing addition latency, correct?

2022-01-01 12:21 UTC, bdach commented
[This SDL thread](https://discourse.libsdl.org/t/stop-sdl2-telling-linux-to-disable-desktop-compositor/23206/2) mentions something about keeping the compositor enabled "lowering framerate", so I'd wager that it does indeed incur latency. So definitely not something that should be blanket enabled like this pull originally did.

2022-01-01 12:22 UTC, bdach requested changes

2022-01-01 12:22 UTC, bdach commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
This is most definitely not the right place to put the switch though.

2022-01-01 18:41 UTC, Speykious commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
Figured. I felt dirty putting it there lol. But now I really wonder what's a cleaner way that I can do it.

2022-01-03 02:59 UTC, peppy commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
Well I was also thinking along these lines, but if it is here, it would need to be named something more generic (and we'd need to ascertain if the same should/could be applied to other platforms).

For instance, on windows this is similar to the concept of exclusive fullscreen, and on macOS there are multiple fullscreen modes, one which actually gives the application more direct control of the screen.

2022-01-03 05:43 UTC, bdach commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
Not sure about clumping compositor switches with exclusive fullscreen. A closer windows analogue would be to disable DWM somehow. No idea about Macs.

I'd see this option best placed on a `LinuxDesktopWindow : SDL2DesktopWindow`. And probably configured in-source per framework user (as either the end application is a game and wants compositor off, or is an... application, and wants to keep it on).

2022-01-03 05:56 UTC, peppy commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
we probably need a `Configuration` class to pass into `GetSuitableHost` so we can extend these kinds of settings without adding more parameters..

2022-01-03 16:21 UTC, Speykious commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
SO some kind of `HostConfiguration` instead of several parameters then?

2022-01-03 16:45 UTC, peppy commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
I think that's best for now yep. Just keep in mind the existing methods should also be kept in place for compatibility reasons.

2022-01-03 16:45 UTC, Speykious commented on osu.Framework/Host.cs
> +        public static DesktopGameHost GetSuitableHost(string gameName, bool bindIPC = false, bool portableInstallation = false, bool bypassCompositorOnLinux = true)
Ok, I'll keep that in mind.

2022-01-03 17:15 UTC, bdach requested changes

2022-01-03 17:15 UTC, bdach commented on osu.Framework/Host.cs
> +            return RuntimeInfo.OS switch
Please use a normal switch statement rather than a switch expression (as that is the accepted code convention in this repository).

2022-01-03 17:15 UTC, bdach commented on osu.Framework/Host.cs
> +                _ => throw new InvalidOperationException($"Could not find a suitable host for the selected operating system ({Enum.GetName(typeof(RuntimeInfo.Platform), RuntimeInfo.OS)})."),
Seems overkill?

```suggestion
                _ => throw new InvalidOperationException($"Could not find a suitable host for the selected operating system ({RuntimeInfo.OS)})."),
```

2022-01-03 17:15 UTC, bdach commented on osu.Framework/HostConfig.cs
> +        public bool BypassCompositor { get; set; }
These should all have xmldoc.

2022-01-03 17:15 UTC, bdach commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
Not sure why `struct`. If it's not going to be a performance killer (which it isn't) I prefer `class`. Less gotchas.

2022-01-03 17:15 UTC, bdach commented on osu.Framework/HostConfig.cs
> +        public static HostConfig GameConfig(string gameName, bool bindIPC = false, bool portableInstallation = false)
Unsure that these need to exist.

2022-01-03 17:25 UTC, Speykious commented on osu.Framework/Host.cs
> +            return RuntimeInfo.OS switch
Ah, ok, didn't know.

2022-01-03 17:26 UTC, Speykious commented on osu.Framework/Host.cs
> +                _ => throw new InvalidOperationException($"Could not find a suitable host for the selected operating system ({Enum.GetName(typeof(RuntimeInfo.Platform), RuntimeInfo.OS)})."),
I agree (all I did was copy the exception from the old method)

2022-01-03 17:26 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +        public bool BypassCompositor { get; set; }
Will try to come up with good ones

2022-01-03 17:30 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +        public static HostConfig GameConfig(string gameName, bool bindIPC = false, bool portableInstallation = false)
I thought it would make the intent of the program more explicit.

2022-01-03 17:31 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
I guess

2022-01-03 17:32 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
I think that I did that not for performance but rather semantic reasons, since it has no instance methods.

2022-01-03 17:37 UTC, bdach commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
I suppose? Would also be fine with `readonly struct` I guess, but that won't work well without `get; init;` which I'm not sure will be allowed given the .NET Standard dual-targeting which is required for mobile.

Mutable structs are the worst of both worlds IMO as you cannot just mutate an instance of a struct anyway because the member access operator returns a temporary.

2022-01-03 18:04 UTC, Susko3 commented on osu.Framework/Platform/DesktopGameHost.cs
>          }
[`HeadlessGameHost`](https://github.com/ppy/osu-framework/blob/44794a221458d9cbb9fc67050c2e5c949a0d23fe/osu.Framework/Platform/HeadlessGameHost.cs#L33-L37) is using this obsolete ctor, and so are some tests.

2022-01-03 18:04 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
Oh, I didn't know about `init;`, that's a nice feature.
The netstandard2.1 target doesn't use the latest C# version?

2022-01-03 18:05 UTC, Speykious commented on osu.Framework/Platform/DesktopGameHost.cs
>          }
Ah, I overlooked the tests!

2022-01-03 18:09 UTC, bdach commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
As I said already, I don't know. But going off docs [I would wager that the answer is no](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#when-to-target-net50-or-net60-vs-netstandard).

netstandard cannot be dropped yet because that's what mobile platforms use. with some luck .NET 6 could allow dropping that but i have no idea if it actually will.

2022-01-03 18:15 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +    public struct HostConfig
I see. Well, good to know that .NET 6 might fix things like this.
I'll turn it into a class for now.

2022-01-03 19:46 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +        public static HostConfig GameConfig(string gameName, bool bindIPC = false, bool portableInstallation = false)
I thought about it a bit more and I think we can just do without.

2022-01-03 20:58 UTC, Speykious commented on osu.Framework/Platform/DesktopGameHost.cs
>          }
Alright, I think I took all tests into account now.

2022-01-03 21:06 UTC, Speykious commented
Time to fix failing tests (looks like it's only about obsolete ctors still in use).

2022-01-03 21:41 UTC, Speykious commented
Some of the tests only had a constructor with a single `string name` parameter, so I left those as-is and only modified the internal code to use the non-obsolete constructor.

2022-01-03 22:20 UTC, Susko3 commented on osu.Framework/Platform/Windows/WindowsGameHost.cs
>          }
Since this is `internal`, this could be removed without an `[Obsolete]`.
The obsolete `GetSuitableHost()` could then just construct a `HostConfig` and pass it onto `GetSuitableHost(HostConfig)`.

Same goes for other desktop hosts.

2022-01-03 23:59 UTC, Susko3 requested changes

2022-01-03 23:59 UTC, Susko3 commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(hostConfig.With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
Currently, `HeadlessGameHost` allows parameter-less construction. Same goes for inheritors of `HeadlessGameHost`.

`TestLogging` and some usages osu-side use parameter-less construction, with this, those usages can remain the same.

If this is something we want to keep, we can do this:

```suggestion
        public HeadlessGameHost(HostConfig hostConfig = null)
            : base((hostConfig ??= new HostConfig()).With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
```

with adequate changes to inheriting classes.

2022-01-03 23:59 UTC, Susko3 commented on osu.Framework/HostConfig.cs
> +            Name = @"";
Currently, `HeadlessGameHost` expects a null name as a default (so it can fall back to generating GUID), while `DesktopGameHost` and `GameHost` expect an empty string.

Probably best to have this null, and have a null check in `DesktopGameHost` or `GameHost`. But I'm not sure what is the definitive meaning of `strting.Emtpy` for Name in the context of different `GameHost`s.

Currently, having an empty name will cause `Storage` to be rooted in `%appdata%` on Windows, something we probably don't want. Empty path should probably throw in `DesktopGameHost`.

Empty string might be "supported" when using a portable installation.

Empty string seems to be used for mobile platforms, though.

2022-01-03 23:59 UTC, Susko3 commented on osu.Framework/Testing/TestRunHeadlessGameHost.cs
>          }
This should probably also use `this(HostConfig, bool)` ctor (same as `HeadlessGameHost`) instead of relying on the obsolete ctor in `HeadlessGameHost`. This will reduce code duplication.

Same goes for `BackgroundGameHeadlessGameHost`.

2022-01-04 03:49 UTC, Speykious commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(hostConfig.With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
I cannot make this because the deprecated constructor still exists and covers the parameterless construction.

2022-01-04 03:51 UTC, Speykious commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(hostConfig.With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
Actually, if I edit the deprecated constructor to have the first argument mandatory, I could make the new constructor optionally parameterless...

2022-01-04 03:51 UTC, Speykious commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(hostConfig.With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
Actually, if I edit the deprecated constructor to have the first argument mandatory, I could make the new constructor optionally parameterless...

2022-01-04 15:42 UTC, bdach commented on osu.Framework/HostConfig.cs
> +            Name = @"";
If null and empty string are going to mean different things (which I don't know that they should), then `Name` better be annotated as `string?` and xmldoc'd properly to explain what the point of that is.

2022-01-04 15:54 UTC, Speykious commented on osu.Framework/HostConfig.cs
> +            Name = @"";
`string?` would give me a code style warning. I think it would make more sense once osu!framework gets ported to .NET 6 if it enables nullables.

2022-01-04 15:59 UTC, bdach commented on osu.Framework/HostConfig.cs
> +            Name = @"";
then jetbrains' `[CanBeNull]` at least

2022-01-05 05:54 UTC, peppy approved these changes

2022-01-05 06:05 UTC, peppy commented
Please don't self-resolve review comments. I can't see what I even said any more.

2022-01-05 06:09 UTC, peppy commented
This has turned into a bit of a mess..

2022-01-05 06:22 UTC, peppy requested changes

2022-01-05 06:22 UTC, peppy commented on osu.Framework/Host.cs
why was this order even changed?

2022-01-05 06:22 UTC, peppy commented on osu.Framework/Host.cs
> +                    throw new InvalidOperationException($"Could not find a suitable host for the selected operating system ({RuntimeInfo.OS}).");
Why was this changed?

2022-01-05 06:22 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        [CanBeNull]
Specify `#nullable enable` on the file instead.

2022-01-05 06:22 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        public bool Realtime { get; set; }
Shouldn't be here. Put back in parameters for the local usage for now.

2022-01-05 06:22 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        public bool BypassCompositor { get; set; }
Unsure this should be directly in `HostOptions` if it's going to specifically mention `Linux`.

We may want to consider `LinuxHostOptions : HostOptions { bool BypassCompositor }` or `HostOptions { PlatformHostOptions PlatformOptions { get; set; } }`

Open to opinions on this.

2022-01-05 06:22 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        public bool BindIPC { get; set; }
I think this is also desktop specific? Not sure it should be sent the whole way down. Maybe okay.

2022-01-05 06:31 UTC, peppy commented
I've self-applied the review comments I left to try and breathe some sense into the diff for further review. Still need discussion on whether the compositor option should sit inside `HostOptions` or not. Maybe it's fine to leave it in there for simplicity, but thinking forward it may not be the best place if we are looking for a permanent home.

2022-01-05 06:37 UTC, Susko3 commented on osu.Framework/HostOptions.cs
> +        public bool BypassCompositor { get; set; }
I'm opposed to `LinuxHostOptions` and the like.

Consumers ares supposed to use `HostOptions` in `GetSuitableHost()`. Feels wrong having to pass `LinuxHostOptions` even if not running on linux. If in the future we have eg. `WindowsHostOptions`, trying to pass in both windows and linux options won't easily work.

2022-01-05 06:39 UTC, Susko3 commented on osu.Framework/HostOptions.cs
> +        public bool BindIPC { get; set; }
Same can be argued for `PortableInstallation`.

But the whole `GetSuitableHost()` is desktop specific, as-is.

2022-01-05 06:41 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        public bool BypassCompositor { get; set; }
Yeah, for sure. If anything I think it should be the second of the proposed (having a separate `Options` class for platform specific options).

2022-01-05 06:41 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        public bool BindIPC { get; set; }
Maybe it's fine to leave desktop-related settings here for simplicity as it's the majority use case.

2022-01-05 08:50 UTC, Speykious commented
> Please don't self-resolve review comments. I can't see what I even said any more.

Sorry about that, understood

2022-01-05 08:52 UTC, Speykious commented
> but thinking forward it may not be the best place if we are looking for a permanent home.

What do you mean by permanent home?

2022-01-05 08:52 UTC, peppy commented
Aka future proofing its location so we don't need to move it again in the future when we add even more options.

2022-01-05 08:55 UTC, Speykious commented on osu.Framework/Host.cs
I... don't know. I guess it should stay the same

2022-01-05 08:56 UTC, peppy commented on osu.Framework/Host.cs
It's fine to leave it for now, just curious.

2022-01-05 08:56 UTC, Speykious commented on osu.Framework/Host.cs
> +                    throw new InvalidOperationException($"Could not find a suitable host for the selected operating system ({RuntimeInfo.OS}).");
See https://github.com/ppy/osu-framework/pull/4976#discussion_r777601844

2022-01-05 09:07 UTC, Speykious commented
Ah, I see... I think it's fine keeping platform-specific options in `HostOptions`. It puts all relevant host options in one place, and the only thing that happens when it doesn't apply to the platform is that it gets ignored.
There may be a better way inside of `HostOptions` to organize fields based on which platform they apply in, but externally when that object is passed around it's fine

2022-01-05 20:43 UTC, bdach commented on osu.Framework/HostOptions.cs
> +        /// </remarks>
This property is now doubly confusing in that (a) I'd expect `null` to be the default value if it's permissible and does a different thing than an empty string does, and (b) `HeadlessGameHost` is now *not* using the null special path (as opposed to manually specifying `Guid.NewGuid` via the ctor overload with no explicit name in it).

In fact as far as I can tell all paths now expect this to be non-null, so this xmldoc is just stale and can be removed safely?

```suggestion
```

2022-01-05 20:43 UTC, bdach commented on osu.Framework/HostOptions.cs
> +        public bool BypassCompositor { get; set; }
Maybe if we ever get to a point wherein this starts becoming a mess then we could arrange the platform specific stuff in a hierarchical manner, e.g.

```
HostOptions
 |- // general options go here
 |- LinuxOptions
 |   |- BypassCompositor
 |- DesktopOptions
     |- PortableInstallation
     |- BindIPC
```

But that's probably a bit too baroque for now... Maybe just throw some `#region`s in, grouping the platform specific options, and call it a day?

2022-01-05 20:54 UTC, bdach commented on osu.Framework/HostOptions.cs
> +        /// </remarks>
Also, if the above understanding is correct and the null path is not required anymore, I'd probably consider forcing all users to specify a name for their game by adding a ctor that requires it (and therefore preventing construction of `HostOptions` without giving it a name).

2022-01-05 20:54 UTC, bdach commented on osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
> +                using (var host = new TestRunHeadlessGameHost(new HostOptions { Name = $"{GetType().Name}-{Guid.NewGuid()}" }))
`realtime: false` spec looks to have been dropped here

2022-01-05 20:54 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +        [Obsolete("Use HeadlessGameHost(HostConfig hostConfig) instead.")]
obsolete notices need updating too

```suggestion
        [Obsolete("Use HeadlessGameHost(HostOptions hostOptions) instead.")]
```

removal dates also missing (goes for more places than this one)

2022-01-05 20:59 UTC, Susko3 requested changes

2022-01-05 20:59 UTC, Susko3 commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(options ?? new HostOptions { Name = Guid.NewGuid().ToString() })
This is currently different from `master`:

```cs
new HeadlessGameHost(bindIPC: true);
```
will produce different results to 
```cs
new HeadlessGameHost(new HostOptions { BindIPC = true });
```

The former will have guid name, while the latter will have empty name.

This was correct previously:
```cs
: base(hostConfig.With(name: hostConfig.Name ?? Guid.NewGuid().ToString()))
```

2022-01-05 20:59 UTC, Susko3 commented on osu.Framework/Platform/HeadlessGameHost.cs
> +        public HeadlessGameHost(string gameName, bool bindIPC = false, bool realtime = true, bool portableInstallation = false)
Method signature was changed from `master` (`gameName` no longer defaults to null).

2022-01-05 21:03 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +        public HeadlessGameHost(string gameName, bool bindIPC = false, bool realtime = true, bool portableInstallation = false)
I believe this was intentional? You can't have two ctors with all parameters having default values, the compiler will correctly complain that it cannot choose between the two. The other ctor will take over the default `null` case (although, as you rightly mentioned in the other comment, it doesn't behave 100% correctly if `HostOptions` are specified with no name spec).

2022-01-06 03:30 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +            : base(options ?? new HostOptions { Name = Guid.NewGuid().ToString() })
I've removed the `With` method for simplicity. We can't use that.

2022-01-06 03:30 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +        [Obsolete("Use HeadlessGameHost(HostConfig hostConfig) instead.")]
I intentionally didn't add/update these until we are ready to agree on this PR (don't think that time has come yet).

2022-01-06 03:31 UTC, peppy commented on osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
> +                using (var host = new TestRunHeadlessGameHost(new HostOptions { Name = $"{GetType().Name}-{Guid.NewGuid()}" }))
I believe I did this intentionally as it's the default.

2022-01-06 03:31 UTC, peppy commented on osu.Framework/HostOptions.cs
> +        /// </remarks>
I'm all for moving the name back out.

2022-01-06 06:30 UTC, peppy commented
I've made some further changes.

Note that all the empty `new HostOptions()` presence is to avoid ambiguity in ctor calls. These can be removed once the obsoleted methods are removed in the future.

2022-01-06 08:17 UTC, bdach commented
I think this diff looks fine now with the latest changes.

2022-01-06 08:18 UTC, bdach approved these changes

2022-01-06 14:00 UTC, Susko3 requested changes
Also missing `// Can be removed` comments.

2022-01-20 13:05 UTC, peppy approved these changes

2022-01-20 13:05 UTC, merged