Make ToolWindow use FillFlowContainer for its content to allow for toolbar height changes
ppy/osu-framework pull request #4977
Opened 2022-01-01 00:09 UTC by dekrain

This allows for tool windows to have more buttons, as presented by adding a button for Draw Visualiser that inspects the game drawable.

2022-01-01 00:12 UTC, dekrain commented
There's a fix needed because now the content overflows under the visible area.

2022-01-01 01:08 UTC, dekrain commented
Now it should be good, but I think it would be better to put all that into a separate container class.

2022-01-01 01:09 UTC, dekrain commented on osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
> +// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
Not sure what happened there

2022-01-01 02:18 UTC, Susko3 commented on osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
> +// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
Encoding changed UTF-8 <-> UTF-8 BOM.

2022-01-01 02:28 UTC, dekrain commented on osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
> +// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
Ah, makes sense

2022-01-03 03:27 UTC, peppy commented
Is this PR titled wrong? It looks to be adding a new button / feature but mentions that nowhere.

2022-01-03 13:20 UTC, dekrain commented
It's a fix that enables to add more buttons or other widgets. It wasn't possible before, because the toolbar will overflow and the tool content will overlap with buttons on the second row.

2022-01-03 15:57 UTC, bdach commented
The point is that on this PR's branch there is a button that isn't there on master:

![2022-01-03-165319_585x671_scrot](https://user-images.githubusercontent.com/20418176/147951667-532aa9ce-8a78-499a-8483-dc36be3561bf.png)

Nothing in this PR thread so much as mentions why this would be added. I'd go as far as to say that I consider the usefulness of this button dubious as it is, as in many *many* hours of using the visualiser I don't recall ever having to go back to the root drawable.

If the button was added just to show that the fix works then that is not the right way to go about it.

2022-01-12 04:13 UTC, dekrain commented
The button just showcases that the fix works, yes. I'll move it to a separate tool that'd be designed for inspecting objects. I also wanted to find a cleaner way to lay out the content properly. I might do something similar to what osu!'s `SectionsContainer` does.

2022-01-13 07:32 UTC, frenzibyte commented
I think it would be best grouping this flexibility change with the feature that needs it rather than separating it to its own PR. Right now there's no benefit from this change as it stands, and, if that were to be added, we may not want the "inspect root" button to be displayed in such place to begin with. (maybe a clickable "go to root" text at the bottom, for instance).

2022-01-13 20:55 UTC, bdach commented on osu.Framework/Graphics/Visualisation/ToolWindow.cs
> +            }
Personally I'm okay with this being a standalone PR but what I'm less okay with is how this logic reads. Half-manual layouting like this shouldn't be done unless strictly necessary. Fill flows and containers are there to be used after all.

Have you tried any alternative solutions that don't do this, and if yes, do they have issues?

2022-01-14 05:20 UTC, dekrain commented on osu.Framework/Graphics/Visualisation/ToolWindow.cs
> +            }
The problem is that I've searched for a container that would handle it itself (I used `FillFlowContainer` originally, but it couldn't autosize the bottom part) and haven't found what I needed, and I noticed that osu `SectionsContainer` does something similar akin to this. I wouldn't be against having a similar logic in a separate container and using it instead, though.

2022-01-15 13:28 UTC, bdach commented on osu.Framework/Graphics/Visualisation/ToolWindow.cs
> +            }
The only reason why this sort of manual workaround exists is only because the existing layouting looks pretty weird overall. As far as I can tell it should ideally be looking something like

```
TooltipContainer
  GridContainer
    GridRow (Mode = AutoSize)
      Header
    GridRow (Mode = Distributed)
      MainHorizontalContent
```

And yes I know that `master` has a comment about `GridContainer` being unviable there. But things have changed since (that comment is almost 3 years old, and since then a significant change in invalidation handling has been merged), so I'd like confirmation that it is still unviable before proceeding.

2022-01-26 00:27 UTC, dekrain commented on osu.Framework/Graphics/Visualisation/ToolWindow.cs
> +            }
Fixed it.

2022-01-26 00:28 UTC, dekrain commented
I also fixed a smaller issue with the fact that in `PropertyDisplay` and `TransformDisplay` the scrollbar overflows on the bottom due to padding being applied to the scroll container.

2022-01-26 06:09 UTC, frenzibyte commented
> I also fixed a smaller issue with the fact that in `PropertyDisplay` and `TransformDisplay` the scrollbar overflows on the bottom due to padding being applied to the scroll container.

It's always best to separate irrelevant changes to their own PRs, so that they can be easily reviewed rather than mixing them together in one. But now that you've pushed it here, I suppose there's no point anymore.

2022-01-30 09:30 UTC, peppy requested changes

2022-01-30 09:30 UTC, peppy commented on osu.Framework/Graphics/Containers/ScrollContainer.cs
> +        public float ScrollbarMovementExtent => Math.Max(DrawSize[ScrollDim] - Scrollbar.DrawSize[ScrollDim] - Padding.Total[ScrollDim], 0);
This change needs test coverage and/or rationale. We can't go changing a central class like `ScrollContainer` without testing.

2022-03-09 18:31 UTC, dekrain commented on osu.Framework/Graphics/Containers/ScrollContainer.cs
> +        public float ScrollbarMovementExtent => Math.Max(DrawSize[ScrollDim] - Scrollbar.DrawSize[ScrollDim] - Padding.Total[ScrollDim], 0);
I merged the implementation from upstream.

2022-03-10 07:31 UTC, peppy approved these changes

2022-03-10 08:12 UTC, merged