Replace all usages of `Task.Wait`/`Task.Result` with safer alternatives
ppy/osu-framework pull request #4980
Opened 2022-01-03 08:13 UTC by peppy

As seen recently, it is quite easy in our semi-`async` world to accidentally cause a deadlock in the TPL thread pool. The cause of this is a `.Wait()` or `.Result` from within an already `async` context.

Finding these cases by reading code is quite hard, as they can be nested multiple calls deep. Likewise, I couldn't find an existing analyser that finds such cases (and to some it is considered a non-issue as the thread pool should grow to add new threads when it gets in this state - but for us this can take too long).

This is a proposal to replace all calls with a custom method with added safety. Note that this PR will intentionally fail as it points out the issues that are fixed in https://github.com/ppy/osu-framework/pull/4973.

The rationale for this change was that I couldn't cover all cases in osu!  side `TestMultiplayerClient` by reading the code alone.

2022-01-03 08:22 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T WaitSafelyForResult<T>(this Task<T> task)
Due to the caveat mentioned below (line 31) maybe this should be called `SafelyConsumeResult` or something else?

2022-01-03 19:37 UTC, bdach commented
Needs conflict resolution against master post-merge of #4973 now.

2022-01-03 19:42 UTC, bdach reviewed
Seems generally sane but I'm not super sure whether a runtime crash is much better than a deadlock? Going to ask for a second opinion for sure on this one.

2022-01-03 19:53 UTC, bdach commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T WaitSafelyForResult<T>(this Task<T> task)
After looking at the game-side PR I'd agree with renaming. Calling `WaitSafelyForResult()` from continuations wherein the result is known to be present and that there will be no waiting involved reads really strangely otherwise.

2022-01-04 03:00 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T WaitSafelyForResult<T>(this Task<T> task)
An alternative to renaming would be to add one more property, something like `.CompletedResult` or I don't know (naming is hard) which throws in the case the task is not completed. We would use this in continuations where it was guaranteed that the result is ready.

2022-01-04 04:29 UTC, peppy commented
> Seems generally sane but I'm not super sure whether a runtime crash is much better than a deadlock? Going to ask for a second opinion for sure on this one.

Have to consider that this both:
- Make failures consistent (deadlocks can sometimes only happen one in 10 or 20 CI runs), and in many cases the banned symbol portion will heed user caution when using the replacement methods.
- Give a call stack on CI showing the exact location of the issue, something that is very hard to attain when the run ends in a deadlock/timeout.

2022-01-04 05:05 UTC, bdach commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T WaitSafelyForResult<T>(this Task<T> task)
That works too. No strong preference here.

2022-01-04 05:14 UTC, peppy commented
I've had to make a fix to `VideoDecoder` that makes this PR a bit larger. Let me know if you'd prefer it is split out for review purposes.

2022-01-04 17:34 UTC, bdach commented
I'm ok with the `VideoDecoder` change being here. Not like it's a huge one anyhow.

Not sure if you wanted to go ahead with any of the [renames suggested above](https://github.com/ppy/osu-framework/pull/4980#pullrequestreview-842541841); looks fine to me otherwise.

2022-01-05 06:57 UTC, peppy commented
I've added a second method for continuation purposes. I think this feels better. Not sure about naming.

2022-01-05 20:30 UTC, bdach reviewed
One more nit and then looks good to go as far as I can tell :+1: Probably still going to wait for @smoogipoo's opinion on this though.

2022-01-05 20:30 UTC, bdach commented on CodeAnalysis/BannedSymbols.txt
> +P:System.Threading.Tasks.Task`1.Result;Don't use Task.Result. Use Task.WaitSafelyForResult() to ensure we avoid deadlocks.
Should also suggest `GetCompletedResult()` as an alternative.

```suggestion
P:System.Threading.Tasks.Task`1.Result;Don't use Task.Result. Use Task.GetCompletedResult() to safely retrieve the result of a completed task, or Task.WaitSafelyForResult() to synchronously wait for and retrieve the result of a not-completed task in a way that ensures that it will not deadlock.
```

2022-01-06 08:39 UTC, smoogipoo requested changes

2022-01-06 08:39 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +            // We commonly access `.Result` from within `ContinueWith`, which is a safe usage (the task is guaranteed to be completed).
It's not guaranteed to be completed. It can be failed, in which case accessing `.Result` causes an exception. In that case, the code below is going to throw the incorrect exception.

2022-01-06 08:39 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +            if (Thread.CurrentThread.IsThreadPoolThread && !task.IsCompleted)
As per above, I suggest adding additional cases to this which bypass to the `.Result` call (such as `&& !task.IsFaulted && !task.IsFailed`).

2022-01-06 08:39 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
I really don't understand the purpose of this method, and why it should ever be used instead of `WaitSafelyForResult`.

2022-01-06 08:41 UTC, bdach commented on osu.Framework/Extensions/TaskExtensions.cs
> +            // We commonly access `.Result` from within `ContinueWith`, which is a safe usage (the task is guaranteed to be completed).
I believe that comment is actually outdated, the intention was to use `GetCompletedResult()` from within continuations.

2022-01-06 12:18 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
Apart from the different naming which feels better, it describes intent. This one is only to be used when the caller is 100% sure the task is completed. You can see example usages in the [osu! side PR](https://github.com/ppy/osu/pull/16309).

2022-01-06 12:19 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +            // We commonly access `.Result` from within `ContinueWith`, which is a safe usage (the task is guaranteed to be completed).
Are you confusing `IsCompleted` for `IsCompletedSuccessfully`?

```csharp
    /// <summary>Gets a value that indicates whether the task has completed.</summary>
    /// <returns>
    /// <see langword="true" /> if the task has completed (that is, the task is in one of the three final states: <see cref="F:System.Threading.Tasks.TaskStatus.RanToCompletion" />, <see cref="F:System.Threading.Tasks.TaskStatus.Faulted" />, or <see cref="F:System.Threading.Tasks.TaskStatus.Canceled" />); otherwise, <see langword="false" />.</returns>
    public bool IsCompleted { get; }
```

2022-01-06 13:23 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +            // We commonly access `.Result` from within `ContinueWith`, which is a safe usage (the task is guaranteed to be completed).
Indeed, I missed that.

2022-01-06 13:23 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
Is there a point to this? It looks like a usage "error" waiting to happen.

2022-01-06 13:26 UTC, bdach commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
If you're okay with always calling `WaitSafelyForResult` even inside continuations (which looks weird to me personally, given there will never be actual any waiting there) then might as well revert the addition of this method.

2022-01-06 13:27 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
If we're reverting, the other one needs a better name. I'm personally not happy with calling `WaitSafely` from a continuation - it *looks* like an error.

2022-01-06 13:29 UTC, smoogipoo commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
It doesn't have to be called `WaitSafelyForResult` in the first place. Why not just `GetResultSafely`? The main point is I don't want to have a ton of special cases for the user - call `WaitSafely()` instead of `Wait()` and `GetResultSafely()` instead of `Result`, that's simple to me.

2022-01-06 13:40 UTC, bdach commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
`GetResultSafely()` works for me.

2022-01-06 13:50 UTC, peppy commented on osu.Framework/Extensions/TaskExtensions.cs
> +        public static T GetCompletedResult<T>(this Task<T> task)
Will revert. I found the two methods super helpful when searching for usages to check they were correct, but I guess that's an edge case.

2022-01-07 07:56 UTC, smoogipoo approved these changes

2022-01-07 08:00 UTC, merged