Output performance log messages when schedulers have long queues
ppy/osu-framework pull request #4991
Opened 2022-01-13 05:44 UTC by peppy

This intends to expose cases of schedulers being enqueued to but not running, which is something that has come up in the past and can cause unforeseen overheads or memory leaks.

Would be nice if we could better identify the owner of the scheduler, but not sure it's worth passing a reference in to the drawable or not. Can be added if that's seen as a requirement.

2022-01-13 21:33 UTC, bdach commented on osu.Framework/Threading/Scheduler.cs
> +                    Logger.Log($"{nameof(Scheduler)} has {timedTasks.Count} timed tasks pending", LoggingTarget.Performance);
Similar log statement is in `enqueue()`, but one prints `nameof(Scheduler)` and one prints `this.ToString()`. Is this intentional?

2022-01-13 21:33 UTC, bdach commented on osu.Framework/Logging/Logger.cs
> +        public int TotalLogOperations => logCount.Value;
Looks unused.

2022-01-13 21:34 UTC, bdach commented
Tests are failing because they happen to run after `TestLogging`, and one of those tests is setting `Logger.Enabled = false`.

2022-01-14 02:08 UTC, peppy commented on osu.Framework/Logging/Logger.cs
> +        public int TotalLogOperations => logCount.Value;
Yeah it ended up being. Left it here since it might be useful in the future, but can remove instead of we don't want it.

2022-01-14 10:48 UTC, peppy commented on osu.Framework/Threading/Scheduler.cs
> +                            if (timedTasks.Count > LOG_EXCESSSIVE_QUEUE_LENGTH_INTERVAL)
which part? the reduction to 100?

2022-01-14 10:50 UTC, smoogipoo commented on osu.Framework/Threading/Scheduler.cs
> +                            if (timedTasks.Count > LOG_EXCESSSIVE_QUEUE_LENGTH_INTERVAL)
Correct

2022-01-14 10:50 UTC, peppy commented on osu.Framework/Threading/Scheduler.cs
> +                            if (timedTasks.Count > LOG_EXCESSSIVE_QUEUE_LENGTH_INTERVAL)
So 1000 for both cases?

2022-01-14 10:51 UTC, smoogipoo commented on osu.Framework/Threading/Scheduler.cs
> +                            if (timedTasks.Count > LOG_EXCESSSIVE_QUEUE_LENGTH_INTERVAL)
Sure, or have this be its own thing.

2022-01-15 12:51 UTC, bdach commented on osu.Framework/Logging/Logger.cs
> +        public int TotalLogOperations => logCount.Value;
Can stay, was just wondering whether that was intentional.

2022-01-15 13:00 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Isn't this kinda dicey? It's going to be disabling all logging which is enabled by default.

If anything the logger test was in the wrong by polluting the tests' logging configuration with a non-default value in the end...?

2022-01-15 15:02 UTC, peppy commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
I'm just doing what the other logger tests already do. Logging is enabled by `GameHost` which should handle most cases we'd expect it to be outputting:

https://github.com/ppy/osu-framework/blob/97a12382e7b68b571c13885fbb2d2fe7cbc8e0d0/osu.Framework/Platform/GameHost.cs#L842

2022-01-15 15:14 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
But the game host is initialised once per full test run, isn't it? If it wasn't and it was being restored before every test, then there would be no issue with what the logger tests were doing, as in disabling the logging and causing other tests to fail?

2022-01-15 15:19 UTC, peppy commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Bit confused. Is it not once per test class? That's how they get their own directories and stuff.

2022-01-15 15:31 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
The scheduler tests don't use game hosts at all. They're just plain nunit fixtures. So if those tests run after the logger tests, which (mistakenly) expect that they can set `Logger.Enabled` to false because every game host will re-enable logging, then every test that's not run under a game host and is just a plain nunit fixture will have logging disabled (until someone creates another game host, because the field is process-global).

2022-01-15 15:32 UTC, peppy commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Sure, but that's how it's been until now? `GameHost` also disabled logging on exit.

Also logging only works with a storage, so outside of a `GameHost` its usage seems undefined in the first place?

2022-01-15 15:34 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
If logging outside of a host is to be considered undefined behaviour then all of the logic inside of `TestLogOutputFromManyQueuedTasks` and `TestLogOutputFromManyQueuedScheduledTasks` would need to run under a game host explicitly created as part of the test, correct? Which it isn't right now.

2022-01-15 15:34 UTC, peppy commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Except Logger.Enabled is being called here, making it work.

2022-01-15 15:42 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
I suppose so. Note, however, that the scheduler test isn't setting `Logger.Storage`, which means it silently either doesn't use any storage (if the test is ran in isolation) or uses the last set storage. It has no effect on the outcome of the test due to how it is written but maybe a bit ehh. Not sure, I don't want to prolong this conversation.

2022-01-15 15:43 UTC, peppy commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Can set to `null` here (alongise the `Enabled=true` part) if that reads better

2022-01-15 16:46 UTC, bdach commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            Logger.Enabled = false;
Sure, I guess I'd be fine with that.

2022-01-17 03:14 UTC, smoogipoo requested changes

2022-01-17 03:14 UTC, smoogipoo commented on osu.Framework.Tests/Threading/SchedulerTest.cs
> +            using (var storage = new TemporaryNativeStorage(nameof(TestLogOutputFromManyQueuedTasks)))
Wrong method reference.

2022-01-17 08:45 UTC, smoogipoo approved these changes
Looks fine to me

2022-01-17 08:45 UTC, merged