Update OpenTabletDriver NuGet package to v0.6.0.2
ppy/osu-framework pull request #4993
Opened 2022-01-18 05:02 UTC by InfinityGhost

Updated the OpenTabletDriver NuGet package to v0.6.0.2

Multiple tablets are supported in this version of the package, however this is only set up to use the first detected tablet to match the previous version's implementation.

2022-01-23 14:58 UTC, bdach commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +                return true;
If the return value of this is mostly to be used by inheritors then maybe best to seal this class for the time being (as the implication is that nothing should inherit it, so there's no need to use an actual value here)?

That said, I think the return value of `base.Detect()` a bit higher up could be used as well, and would be the proper one? Not sure it's that much effort to just use that.

2022-01-23 14:58 UTC, bdach commented on osu.Framework.Benchmarks/BenchmarkTabletDriver.cs
> +            driver = serviceProvider.GetRequiredService<TabletDriver>();
This pattern shows up a lot, to kind of jerry-rig Microsoft-provided DI to work. Maybe this could be extracted to a `public static TabletDriver Create()` in `TabletDriver`, though? You'd then be able to just call `TabletDriver.Create()` everywhere.

2022-01-23 14:58 UTC, bdach commented on osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
> +                                endpoint.Report += handleDeviceReport;
Will these subscriptions be correctly removed when the input handler is disabled/re-enabled a second time? I don't see an explicit unsubscription path.

2022-01-23 19:18 UTC, InfinityGhost commented on osu.Framework.Benchmarks/BenchmarkTabletDriver.cs
> +            driver = serviceProvider.GetRequiredService<TabletDriver>();
Agreed, will do.

2022-01-23 19:29 UTC, InfinityGhost commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +                return true;
It is not worth the effort to pull the actual value from the above task. Sealing the class is likely the better move here.

2022-01-31 19:27 UTC, bdach commented on osu.Framework.Benchmarks/BenchmarkTabletDriver.cs
> +            driver = serviceProvider.GetRequiredService<TabletDriver>();
`BenchmarkTabletDriver` pointed out in this conversation is still manually doing the `ServiceProvider` song and dance rather than using `TabletDriver.Create()`.

2022-01-31 19:40 UTC, bdach commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public TabletDriver([NotNull] ICompositeDeviceHub deviceHub, [NotNull] IReportParserProvider reportParserProvider, [NotNull] IDeviceConfigurationProvider configurationProvider)
Now that `TabletDriver.Create()` exists, thoughts on privatising this ctor to boot? I'm not sure there is need for it to be public, and having a single point of entry will avoid confusing any further users (if any).

2022-01-31 19:40 UTC, bdach commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +                                };
What's the lifetime of the `endpoint` object here? I'm asking because I'm a bit worried about potentially subscribing multiple times to `ConnectionStateChanged`, as it can be called multiple times via toggling `OpenTabletDriverHandler.Enabled` off and on. The inner unsubscription of `DeviceReport` should probably also contain a self-cleanup of the `ConnectionStateChanged` callback itself?

2022-02-01 08:11 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public TabletDriver([NotNull] ICompositeDeviceHub deviceHub, [NotNull] IReportParserProvider reportParserProvider, [NotNull] IDeviceConfigurationProvider configurationProvider)
DI constructors have to be public, so we can't change this one unfortunately.

2022-02-01 08:15 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +                                };
Checking the underlying code, it does look safe (once a device enters a `Connected==false` state it will never return to `true`).

2022-02-01 08:16 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +                                };
Which leaves me questioning the value of the unbind of `endpoint.Report` then. Seems like we could just leave it to die alongside reference loss?

2022-02-01 08:22 UTC, peppy requested changes

2022-02-01 08:22 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public override bool Detect()
This scares me beyond belief. This is a method exposed by OTD, which we are overriding and the delegating the `base` work *to another thread*. Was this your intention? I don't think this can be how we do things.

2022-02-01 08:22 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
> +                        device = e.Any() ? tabletDriver.InputDevices.First() : null;
What's a `TreeList` vs a `Tree`? By only handling the first "tree" in the "tree list" here are we potentially missing devices?

2022-02-01 14:38 UTC, InfinityGhost commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public override bool Detect()
As bad as this looks being that we're overriding it, the returned value is just a hint that doesn't actually get used for any logic at any point except if desired by an implementer such as the OpenTabletDriver desktop program and osu! framework. We plan on removing it and integrating this optimization so this isn't necessary in v0.7. We could make this method sync then just call a Task that does this in the background instead if that's more preferable.

2022-02-01 14:41 UTC, InfinityGhost commented on osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
> +                        device = e.Any() ? tabletDriver.InputDevices.First() : null;
This was some naming mess that we didn't end up cleaning up like we intended, however in future versions (v0.7 and onward) it'll be referred changed from  `InputDeviceTree` -> `InputDevice` for the actual device and `InputDevice` `InputDeviceEndpoint`. `InputDeviceTreeList` is just a `Collection<InputDevice>` that disposes devices between detects and it will also be renamed in the future.

2022-02-01 14:43 UTC, InfinityGhost commented on osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
> +                        device = e.Any() ? tabletDriver.InputDevices.First() : null;
Forgot to answer the rest of your question here, but no we are not missing devices this way.

2022-02-02 04:06 UTC, peppy commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public override bool Detect()
I'm still not too sure why this is required in the first place. Would the following patch not be an amicable solution:

```diff
diff --git a/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs b/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
index e7c634f15..f31281f45 100644
--- a/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
+++ b/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
@@ -22,63 +22,53 @@ public sealed class TabletDriver : Driver
     {
         private static readonly IEnumerable<int> known_vendors = Enum.GetValues<DeviceVendor>().Cast<int>();
 
+        private CancellationTokenSource cancellationSource;
+
+        public event EventHandler<IDeviceReport> DeviceReported;
+
         public TabletDriver([NotNull] ICompositeDeviceHub deviceHub, [NotNull] IReportParserProvider reportParserProvider, [NotNull] IDeviceConfigurationProvider configurationProvider)
             : base(deviceHub, reportParserProvider, configurationProvider)
         {
             Log.Output += (sender, logMessage) => Logger.Log($"{logMessage.Group}: {logMessage.Message}", level: (LogLevel)logMessage.Level);
+
             deviceHub.DevicesChanged += (sender, args) =>
             {
                 // it's worth noting that this event fires on *any* device change system-wide, including non-tablet devices.
                 if (!Tablets.Any() && args.Additions.Any())
-                    Detect();
+                {
+                    cancellationSource?.Cancel();
+                    cancellationSource = new CancellationTokenSource();
+
+                    Task.Run(() => detectAsync(cancellationSource.Token), cancellationSource.Token);
+                }
             };
         }
 
-        private readonly object detectLock = new object();
-
-        private CancellationTokenSource cancellationSource;
+        private async Task detectAsync(CancellationToken cancellationToken)
+        {
+            // wait a small delay as multiple devices may appear over a very short interval.
+            await Task.Delay(50, cancellationToken).ConfigureAwait(false);
 
-        public event EventHandler<IDeviceReport> DeviceReported;
+            int foundVendor = CompositeDeviceHub.GetDevices().Select(d => d.VendorID).Intersect(known_vendors).FirstOrDefault();
 
-        public override bool Detect()
-        {
-            lock (detectLock)
+            if (foundVendor > 0)
             {
-                cancellationSource?.Cancel();
+                Logger.Log($"Tablet detected (vid{foundVendor}), searching for usable configuration...");
 
-                var cancellationToken = (cancellationSource = new CancellationTokenSource()).Token;
+                Detect();
 
-                Task.Run(async () =>
+                foreach (var device in InputDevices)
                 {
-                    // wait a small delay as multiple devices may appear over a very short interval.
-                    await Task.Delay(50, cancellationToken).ConfigureAwait(false);
-
-                    int foundVendor = CompositeDeviceHub.GetDevices().Select(d => d.VendorID).Intersect(known_vendors).FirstOrDefault();
-
-                    if (foundVendor > 0)
+                    foreach (var endpoint in device.InputDevices)
                     {
-                        Logger.Log($"Tablet detected (vid{foundVendor}), searching for usable configuration...");
-
-                        base.Detect();
-
-                        foreach (var device in InputDevices)
+                        endpoint.Report += DeviceReported;
+                        endpoint.ConnectionStateChanged += (sender, connected) =>
                         {
-                            foreach (var endpoint in device.InputDevices)
-                            {
-                                endpoint.Report += DeviceReported;
-                                endpoint.ConnectionStateChanged += (sender, connected) =>
-                                {
-                                    if (!connected)
-                                        endpoint.Report -= DeviceReported;
-                                };
-                            }
-                        }
+                            if (!connected)
+                                endpoint.Report -= DeviceReported;
+                        };
                     }
-                }, cancellationToken);
-
-                // ideally this would return if a tablet was detected, however it is not required.
-                // it is only used a hint that one or tablets were detected to be used by inheritors.
-                return true;
+                }
             }
         }
```

2022-02-03 21:58 UTC, InfinityGhost commented on osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
> +        public override bool Detect()
Would work just fine, for some reason that didn't cross my head at the time of writing that code.

2022-02-04 04:41 UTC, peppy approved these changes
Seems to work fine with my two test devices.

2022-02-04 04:47 UTC, merged