Add missing thread safety check in `LoadComponentsAsync`
ppy/osu-framework pull request #4999
Opened 2022-01-24 10:09 UTC by peppy

2022-01-24 10:11 UTC, smoogipoo approved these changes

2022-01-24 16:55 UTC, bdach commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            EnsureMutationAllowed(nameof(LoadComponentsAsync));
The exception message that results from this is a little funny:

> Cannot mutate the LoadComponentsAsync of a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.

Probably could use a bit more polish.

2022-01-25 03:40 UTC, peppy commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            EnsureMutationAllowed(nameof(LoadComponentsAsync));
Should be better now, well spotted.

2022-01-25 03:49 UTC, smoogipoo requested changes

2022-01-25 03:49 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            ThreadSafety.IsUpdateThread = false;
Unintended, yeah?

2022-01-25 04:11 UTC, peppy commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +            ThreadSafety.IsUpdateThread = false;
😳

2022-01-25 04:13 UTC, smoogipoo approved these changes

2022-01-25 04:28 UTC, merged