Implement `SetImage`
ppy/osu-framework pull request #5014
Opened 2022-02-05 10:04 UTC by uzervlad

ppy/osu#16775

Implements `SetImage` in `WindowsClipboard`, hopefully with support for other platforms coming soon

Not sure if we really need `GetImage`, but if so, I'll give it a try too

2022-02-05 14:18 UTC, uzervlad commented on osu.Framework.iOS/IOSClipboard.cs
> +            throw new NotImplementedException();
What should I do instead of an exception then?

2022-02-05 14:19 UTC, bdach commented on osu.Framework.iOS/IOSClipboard.cs
> +            throw new NotImplementedException();
if you're not aiming to implement the other platforms here, then the only reasonable remaining option is to do nothing (and probably warn in the xmldoc of the base `Clipboard` that platform support is limited).

2022-02-05 14:20 UTC, peppy commented on osu.Framework.iOS/IOSClipboard.cs
> +            throw new NotImplementedException();
If we're throwing it needs to be documented in the xmldoc (and should be `PlatformNotSupportedException` I guess).

Since we generally avoid that, a `bool` return type with success status may work better?

2022-02-05 14:30 UTC, Susko3 commented
This needs some tests so it can be verified this works, and to show consumers how to use this properly (checking the return value, etc.).

2022-02-05 14:34 UTC, bdach commented
the test would probably have to be fully manual though (i.e. without asserts), and limited to windows only for now. there's not really a reasonable way to test this using assertions i don't think.

2022-02-05 14:47 UTC, uzervlad commented on osu.Framework.iOS/IOSClipboard.cs
> +            throw new NotImplementedException();
> Since we generally avoid that, a `bool` return type with success status may work better?

Seems like a good solution to me

2022-02-05 16:31 UTC, frenzibyte requested changes

2022-02-05 16:31 UTC, frenzibyte commented on osu.Framework/Platform/Windows/WindowsClipboard.cs
> +            }
This can probably be shared with the existing logic in `SetText` via a private `setClipboard(hGlobal, format)` or something.

2022-02-05 16:31 UTC, frenzibyte commented on osu.Framework/Platform/Clipboard.cs
> +        /// </summary>
nit: Might as well fill the entire `Clipboard` class with xmldoc.

2022-02-05 19:37 UTC, frenzibyte reviewed
Code-wise seems fine (minus or plus some details), but I can't test this yet so I'll defer that to someone else.

2022-02-06 13:37 UTC, bdach commented
well there are no tests whatsoever here still, or any other functionality that calls `SetImage()`, so it's unclear how this can actually be tested right now

2022-02-09 18:48 UTC, uzervlad commented
So I made a visual test, but I'm not sure how to do the first step right. The last one looks absurd, though it runs pretty much instantly for me.

<details>
<summary>Code</summary>

```cs
[Test]
public void TestScreenshotCopy()
{
    AddStep("screenshot screen", () =>
    {
        using (var image = host.TakeScreenshotAsync().GetAwaiter().GetResult())
        {
            originalImage = image.Clone();
        }
    });

    AddStep("copy image to clipboard", () =>
    {
        clipboard.SetImage(originalImage);
    });

    AddStep("retrieve image from clipboard", () =>
    {
        clipboardImage = clipboard.GetImage<Rgba32>();
    });

    AddAssert("compare images", () =>
    {
        if (originalImage.Width != clipboardImage.Width && originalImage.Height != clipboardImage.Height)
            return false;

        for (int x = 0; x < originalImage.Width; x++)
        {
            for (int y = 0; y < originalImage.Height; y++)
            {
                if (originalImage[x, y] != clipboardImage[x, y])
                    return false;
            }
        }

        return true;
    });
}
```
</details>

2022-02-09 19:14 UTC, bdach commented
You shouldn't be using `.GetAwaiter().GetResult()` (which is basically bypassing the `.Result` property which is banned API in this project). We have a `.GetResultSafely()` overload for that.

However, looking at how `.TakeScreenshotAsync()` is implemented, it will deadlock when you try to run the test in single threaded mode. That is because the screenshot implementation works via a task completion source, and enqueues the actual work of taking the screenshot onto the draw thread. In multi-threaded mode that's fine, but in single-threaded mode the update and draw "threads" run in an interleaved manner on one OS thread, and so the update thread will block waiting for the screenshot, but the screenshot - which is supposed to be taken by the draw thread - will never actually have a chance to be taken (because the update thread will be blocking the draw thread).

I think what you'll want to do there is something like the following:

```csharp
AddStep("screenshot screen", () =>
{
    host.TakeScreenshotAsync().ContinueWith(t =>
    {
        var image = t.GetResultSafely();
        originalImage = image.Clone();
        image.Dispose();
    });
});
AddUntilStep("screenshot taken", () => originalImage != null);
```

This works because continuations are automatically scheduled/enqueued for execution on the next update frame (via the `SynchronizationContext` installed by the framework).

2022-02-10 05:30 UTC, peppy requested changes
Seems to work on windows as expected. A couple of issues I'd probably fix first.

2022-02-10 05:30 UTC, peppy commented on osu.Framework/Platform/Windows/WindowsClipboard.cs
> +                // The bitmap file header should not be included in clipboard
Need a reference stating why this is the case.

2022-02-10 05:30 UTC, peppy commented on osu.Framework.Tests/Visual/Platform/TestSceneClipboard.cs
> +    [Ignore("This test cannot be run in headless mode (a window instance is required).")]
You could test using a constructed image rather than a screenshot and remove this requirement. That said, i think it should still be ignored due to the fact it will mutate the clipboard even when running in the background.

I'd probably update the ignore message to state this as the reason, though.

2022-02-10 17:40 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneClipboard.cs
> +    [Ignore("This test cannot be run in headless mode (a window instance is required).")]
The bigger reason to ignore this test is that as written it will fail on platforms that don't implement `{Get,Set}Image`.

2022-02-10 18:20 UTC, uzervlad commented on osu.Framework/Platform/Windows/WindowsClipboard.cs
> +                // The bitmap file header should not be included in clipboard
Not sure why exactly, I just found [this answer on StackOverflow](https://stackoverflow.com/a/7052068) which had those 14-bytes trimmed

2022-02-11 04:39 UTC, peppy commented on osu.Framework/Platform/Windows/WindowsClipboard.cs
> +                // The bitmap file header should not be included in clipboard
This seems to suggest that any non-bitmap content in the clipboard will fail with `GetImage`, right? and the function doesn't need a generic type at this point?

2022-02-12 12:39 UTC, bdach commented on osu.Framework/Platform/Windows/WindowsClipboard.cs
> +                // The bitmap file header should not be included in clipboard
I believe so, yeah. It can only be a bitmap.

2022-02-15 09:21 UTC, peppy approved these changes

2022-02-15 09:29 UTC, merged