Implement `SafeAreaPadding` on Android
ppy/osu-framework pull request #5016
Opened 2022-02-05 14:54 UTC by Susko3

Superseded https://github.com/ppy/osu-framework/pull/5012.

Tested on:
- Realme 6 / RMX2001 (Android 11 / API 30)
- LG G7 Fit / LG-Q850EMW (Android 9 / API 28)
- LG G Pad 8.3 / LG-V500 (Android 8.1 / API 27)

Testing methodology involves using multi-window and trying out different screen orientations.

Some of the extra code (compared to the original PR) seems to be working around a platform issue with my main device (Realme 6), as the original PR works just fine on the LG G7 Fit 🙃

At least we got non-complaint devices covered.

Anyways, I feel much safer calculating all the insets on the screen area, and then intersecting with the view at the very end.

2022-02-05 15:27 UTC, bdach commented
> Some of the extra code (compared to the original PR) seems to be working around a platform issue with my main device (Realme 6), as the original PR works just fine on the LG G7 Fit

do you mean the multi-window thing by this? because if yes, then i just checked and we either both have non-compliant devices or something in android itself changed something between API 28 and 30, because multi-window is also broken on my API 30 device in the same way you mentioned previously.

2022-02-05 15:30 UTC, bdach commented on osu.Framework.Android/AndroidGameView.cs
> +        public readonly AndroidGameActivity Activity;
kind of weird to see a `get; private set;` property next to a `public readonly` field - would prefer to keep it consistent one way or the other

2022-02-05 15:51 UTC, Susko3 commented on osu.Framework.Android/AndroidGameView.cs
> +            Activity = activity;
We currently have `(AndroidGameActivity)view.Context` sprinkled around in our code. Having the activity directly accessible like this should improve code quality.

This change was taken from a cleanup branch, useful here because of `Activity.IsInMultiWindowMode` later in the PR.

2022-02-05 22:15 UTC, Susko3 commented
> > Some of the extra code (compared to the original PR) seems to be working around a platform issue with my main device (Realme 6), as the original PR works just fine on the LG G7 Fit
> 
> do you mean the multi-window thing by this? because if yes, then i just checked my solution again and we either both have non-compliant devices or something in android itself changed something between API 28 and 30, because multi-window is also broken on my API 30 device in the same way you mentioned previously.

Hmm, looks like something changed on Android's part. The view would draw under the status bar previously, but it doesn't in the new version, the status bar is just black. Google Maps draws under the status bar in multi-window, so there must be some flag (or similar) to set. Anyways, it's not really important.

I presume this PR works fine on your devices?

2022-02-06 13:27 UTC, bdach commented
> I presume this PR works fine on your devices?

have tested only just now. appears to work correctly.

2022-02-06 13:30 UTC, bdach approved these changes

2022-02-10 06:13 UTC, peppy requested changes

2022-02-10 06:13 UTC, peppy commented on osu.Framework.Android/AndroidGameView.cs
> +            Host.InputThread.Scheduler.Add(updateSafeArea);
I'd feel a lot safer if these could be placed above the `Host.Run` call (to ensure beyond doubt that the event handling at https://github.com/ppy/osu-framework/pull/5016/files#diff-1f9486dea90c3d24267f78ddcaaf9155ede2cfc612414bf25cfe5877d75fa9d4R35 is not bound too late to handle an initial callback), is that possible?

I think the above is already impossible due to order of execution, but when reading just this code it feels a bit flaky.

2022-02-11 04:46 UTC, peppy approved these changes

2022-02-11 17:09 UTC, merged