Save the `input.json` config when input settings are changed
ppy/osu-framework pull request #5019
Opened 2022-02-07 16:48 UTC by Susko3

Closes https://github.com/ppy/osu-framework/issues/4950.

The code is a bit ugly, but that's to be expected when doing reflection with generics.

Quickly realized that constructing a `Action<ValueChangedEvent<T>>`  and calling `BindValueChanged` directly was gonna be very hard and even uglier.

Works as you'd expect. Tested with the mouse settings in `TestSceneInputManager`.

2022-02-07 20:06 UTC, bdach approved these changes
seems fine for the time being, at least until the dispose kinks are sorted out - i can see that having some knock on effects in this reflectiony logic

2022-02-07 20:31 UTC, frenzibyte requested changes
Not sure how to feel about using reflection, but since it is the simplest way through I suppose it's fine for the time being.

Missing test coverage, should be simple to add one (would imagine it to test modifying handler-specific properties, and also shared ones present at an `InputHandler` level such as `Enabled`).

2022-02-07 20:31 UTC, frenzibyte commented on osu.Framework/Configuration/InputConfigManager.cs
> +                    var bindableType = property.PropertyType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IBindable<>));
By accepting `IBindable<>` properties, this can potentially bind to non-configurable settings (e.g. `OpenTabletDriverHandler.Tablet`):

![CleanShot 2022-02-07 at 23 13 13](https://user-images.githubusercontent.com/22781491/152864304-536ce5f2-4264-45b6-ba45-ebee38422361.png)
https://github.com/ppy/osu-framework/blob/b9e666caba764ddacda2303b85181fffe0b2890a/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L37-L39

All configurable settings should be of type `Bindable<>` anyways so it should be safe limiting to that instead.

2022-02-07 20:37 UTC, bdach commented on osu.Framework/Configuration/InputConfigManager.cs
> +                    var bindableType = property.PropertyType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IBindable<>));
even if this was a real issue (which it arguably isn't), how is scoping down to the abstract class an actual fix to this, rather than adding some facility to ignore a bindable?

2022-02-07 20:37 UTC, Susko3 commented on osu.Framework/Configuration/InputConfigManager.cs
> +                    var bindableType = property.PropertyType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IBindable<>));
I was going off what is saved in `input.json`.
This does look like it saves too much.

<details>

<summary>input.json</summary>

```json
{
    "InputHandlers": [
        {
            "$type": "osu.Framework.Input.Handlers.Keyboard.KeyboardHandler, osu.Framework",
            "Description": "Keyboard",
            "IsActive": true,
            "Enabled": true
        },
        {
            "$type": "osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler, osu.Framework",
            "IsActive": true,
            "AreaOffset": {
                "x": 0.0,
                "y": 0.0
            },
            "AreaSize": {
                "x": 0.0,
                "y": 0.0
            },
            "Rotation": 0.0,
            "Tablet": null,
            "Description": "OpenTabletDriver",
            "Enabled": true
        },
        {
            "$type": "osu.Framework.Input.Handlers.Joystick.JoystickHandler, osu.Framework",
            "Description": "Joystick / Gamepad",
            "IsActive": true,
            "Enabled": true
        },
        {
            "$type": "osu.Framework.Input.Handlers.Midi.MidiHandler, osu.Framework",
            "Description": "MIDI",
            "IsActive": true,
            "Enabled": true
        },
        {
            "$type": "osu.Framework.Platform.Windows.WindowsMouseHandler, osu.Framework",
            "IsActive": true,
            "UseRelativeMode": false,
            "Sensitivity": 1.0,
            "Description": "Mouse",
            "Enabled": true
        }
    ]
}
```

</details>

2022-02-07 20:44 UTC, bdach commented on osu.Framework/Configuration/InputConfigManager.cs
> +                    var bindableType = property.PropertyType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IBindable<>));
the only things that are possibly extraneous there are `IsActive` on all handlers and the `Tablet` property i guess. but again, i argue that the way to go there is to stick a `[JsonProperty]` on all settings that are supposed to go to the file, enable explicit opt-in serialisation for `input.json`, and check for the presence of `[JsonProperty]` when doing the reflection logic which is already here. not sure whether that's in scope of this pull.

2022-02-07 20:45 UTC, frenzibyte commented on osu.Framework/Configuration/InputConfigManager.cs
> +                    var bindableType = property.PropertyType.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IBindable<>));
I would at least scope it down rather than allowing unnecessary properties regardless of whether it's a real issue, as I see no harm in that. Adding a way to ignore certain bindables sounds like another solution but feels slightly more overengineered to me.

2022-02-07 23:34 UTC, frenzibyte commented
The test doesn't have to ensure the full saving flow works, but only ensure that at least `Save` is called when any setting is changed, as that's what's being changed/achieved in this PR (i.e. via a `TestInputConfigManager` class overriding `PerformSave`/`PerformLoad` to not interact with a real storage, and not require a game host).

Would like to note that not providing test coverage for changes like these could silently regress with any underlying change to the `Bindable` structure or the `ConfigManager` structure, and that's why I believe it is warranted here (especially for the fact that it's relying solely on reflection).

2022-02-08 04:12 UTC, peppy commented on osu.Framework.Tests/Configuration/InputConfigManagerTest.cs
> +            Thread.Sleep(150); // wait for QueueBackgroundSave() debounce.
As shown by the test failures, we probably can't rely on timings like this for CI (all the `Thread.Sleep`s used in these tests are going to have similar intermittent problems). I'd probably just wait for it with a timeout (I think nunit's `Is.True.After` constraint may work well if you can't use `ManualResetEventSlim` style signalling).

2022-02-11 00:17 UTC, frenzibyte approved these changes

2022-02-11 04:43 UTC, peppy commented on osu.Framework.Tests/Configuration/InputConfigManagerTest.cs
> +            Assert.IsTrue(config.SaveEvent.WaitOne(200)); // wait for QueueBackgroundSave() debounce.
Any reason for using a value this low? I think we've seen CI potentially stall for longer than this, so I'd suggest 1 or 10 seconds.

2022-02-11 11:29 UTC, peppy approved these changes

2022-02-11 11:39 UTC, merged