Create helper methods to ensure stream reads are read correctly to the expected length
ppy/osu-framework pull request #5024
Opened 2022-02-11 04:18 UTC by peppy

Based loosely around the solution proposed [here](https://stackoverflow.com/a/221941).

The only thing I'm not 100% on is whether we should use the `EndOfStreamException` here as there could be a super edge case where a stream reads past the end of the expected length? Not sure that will ever happen though.

- [ ] Depends on #5022

2022-02-11 07:51 UTC, peppy commented
Blocking temporarily to add test coverage.

2022-02-12 12:03 UTC, bdach commented on osu.Framework/Platform/TcpIpcProvider.cs
> +            int read = await stream.ReadAsync(header.AsMemory(), cancellationToken).ConfigureAwait(false);
Shouldn't this be a

```csharp
byte[] header = await stream.ReadBytesToArrayAsync(header_length, cancellationToken).ConfigureAwait(false);
```

call instead?

2022-02-12 12:05 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                Debug.Assert(stream.Length < int.MaxValue);
Due to the int cast in the next line. Can remove if you don't think it's required.

2022-02-12 12:06 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +            return stream.ReadAllRemainingBytesToArray();
Can do, was a toss up for me.

2022-02-12 12:06 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +            byte[] buffer = new byte[16 * 1024];
Matches .net internals

2022-02-12 12:14 UTC, bdach commented on osu.Framework/Extensions/StreamExtensions.cs
> +                Debug.Assert(stream.Length < int.MaxValue);
Oh, I see. I think I'd rather change `ReadBytesToArray(Async)` to accept length as `long` rather than `int`. Seems like it will generate less friction against the underlying stream API anyhow.

2022-02-12 12:19 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                Debug.Assert(stream.Length < int.MaxValue);
The base API only allows `int` as far as I could see :(.

2022-02-12 12:27 UTC, bdach commented on osu.Framework/Extensions/StreamExtensions.cs
> +                Debug.Assert(stream.Length < int.MaxValue);
Oh because `Read()` takes `int` and `Position`/`Length` takes `long`... Kinda icky.

You could arguably handle that mismatch internally - since `ReadBytesToArray()` will only ever read at most 16 * 1024 bytes at a time, you could change that method to accept `long` and safely cast down the result of the `Math.Min()` operation to `int`. But given that `int.MaxValue` bytes is about 2GB of data then maybe no real need to worry about it because hopefully nobody is reading that much...?

2022-02-12 12:38 UTC, bdach commented
For kicks I've also written a quick and terrible `MemoryStream`-like implementation that only ever reads one byte at a time, to see if it would pass the tests added here - and the tests do indeed pass. Not sure if it's worth including but I'll leave here for posterity at least?

<details>
<summary>the slowest stream implementation to ever exist</summary>

```csharp
        private class SingleByteReadingMemoryStream : Stream
        {
            private readonly byte[] buffer;

            public SingleByteReadingMemoryStream(byte[] buffer)
            {
                this.buffer = buffer;
            }

            #region Reading

            public override bool CanRead => true;

            public override int Read(byte[] destination, int offset, int count)
            {
                if (count < 1 || position >= Length)
                    return 0;

                destination[offset] = buffer[position];
                position += 1;
                return 1;
            }

            #endregion

            #region Writing

            public override bool CanWrite => false;

            public override void Write(byte[] destination, int offset, int count) => throw new NotSupportedException();

            public override void Flush() => throw new NotSupportedException();

            public override void SetLength(long value) => throw new NotSupportedException();

            #endregion

            #region Seek support

            public override long Length => buffer.Length;

            private long position;

            public override long Position
            {
                get => position;
                set => Seek(value, SeekOrigin.Begin);
            }

            public override bool CanSeek => true;

            public override long Seek(long offset, SeekOrigin origin)
            {
                switch (origin)
                {
                    case SeekOrigin.Begin:
                        position = offset;
                        break;

                    case SeekOrigin.Current:
                        position += offset;
                        break;

                    case SeekOrigin.End:
                        position = Length + offset;
                        break;
                }

                return position;
            }

            #endregion
        }
```

</details>

The async test cases take 11 seconds (!!!) to complete with that implementation. I don't even want to think about the TPL thrashing that is causing.

2022-02-12 12:52 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.GetBuffer();
that's why there's a length check, yep.

2022-02-12 13:03 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                Debug.Assert(stream.Length < int.MaxValue);
yeah, i doubt it'll be an issue. we can handle if someone hits the exception.

2022-02-12 13:04 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.GetBuffer();
to clarify, this usage in fact doesn't require the specific length check as the initial capacity was specified (which sets the internal buffer size).

2022-02-13 12:46 UTC, bdach submitted a review, later dismissed

2022-02-14 05:50 UTC, smoogipoo requested changes

2022-02-14 05:50 UTC, smoogipoo commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.ToArray();
Any reason for this to use `.ToArray()` when the others use `.GetBuffer()`?

2022-02-14 05:50 UTC, smoogipoo commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.ToArray();
Here too.

2022-02-14 05:50 UTC, smoogipoo commented on osu.Framework/Extensions/StreamExtensions.cs
> +                while ((read = await stream.ReadAsync(buffer.AsMemory(), cancellationToken).ConfigureAwait(false)) > 0)
Any reason for using `.AsMemory()`?

2022-02-14 05:50 UTC, smoogipoo commented on osu.Framework/Extensions/StreamExtensions.cs
> +        /// <returns>The full byte content.</returns>
I'd prefer that these methods had `<exception>` docs for their special cases, which show up in Rider:
![image](https://user-images.githubusercontent.com/1329837/153807121-3c6fe6cc-6563-483d-876f-64153f516448.png)
As opposed to a non-explicit tidbit in the remarks.

I don't mean just this method too, but `ReadBytesToArray()` as well because, as far as I know, `Stream.Read(length)` defines a _maximum_ read length, whereas the implementations below throw `EndOfStreamException`s in the same scenario.

2022-02-14 06:02 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                while ((read = await stream.ReadAsync(buffer.AsMemory(), cancellationToken).ConfigureAwait(false)) > 0)
Already touched on [in this discussion](https://github.com/ppy/osu-framework/pull/5024#discussion_r805152756).

The internal buffer is not equal to the actual read length as it uses the standard .NET buffer expansion (doubles in size each time it needs to). Requesting `GetBuffer` would return an array with zero bytes at the end in most cases, which we don't want here.

2022-02-14 06:03 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.ToArray();
Already touched on [in this discussion](https://github.com/ppy/osu-framework/pull/5024#discussion_r805152756).

The internal buffer is not equal to the actual read length as it uses the standard .NET buffer expansion (doubles in size each time it needs to). Requesting `GetBuffer` would return an array with zero bytes at the end in most cases, which we don't want here.

2022-02-14 06:04 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                while ((read = await stream.ReadAsync(buffer.AsMemory(), cancellationToken).ConfigureAwait(false)) > 0)
No need, was a remnant of a previous version.

2022-02-14 06:06 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +        /// <returns>The full byte content.</returns>
Have added.

2022-02-14 06:07 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                return ms.ToArray();
Similar case to the one explained above. The only special case where I'm using `GetBuffer` is where the `new MemoryStream(length)` ctor is used, along with a length check (and throw) before returning the buffer.

2022-02-14 06:29 UTC, smoogipoo requested changes

2022-02-14 06:29 UTC, smoogipoo commented on osu.Framework/Extensions/StreamExtensions.cs
> +                    await ms.WriteAsync(buffer, 0, read, cancellationToken).ConfigureAwait(false);
Is there a reason for not using `stream.CopyToAsync()`? Seems like it does everything here plus uses the global array pool.

Would prefer to not reinvent the wheel.

2022-02-14 06:31 UTC, smoogipoo commented
I have my gripes with this but let's see how it goes with the current implementation... What I was going to post is as follows, but I don't want to start a discussion about it:

I really don't know about this... The SO thread is based on the presumption that you can't trust `stream.Length`, but this code is explicitly saying you _can_ trust it (at least in the case of `ReadAllBytesToArray()`, which event asserts as much).  
Whether you can trust it in the case of e.g. network streams, is an answer I can't provide, because I simply don't know every edge case that exists. While it's true that [`Stream.Length`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.length?view=net-6.0) throws an exception if not seekable which is covered by the guard in `ReadAllBytesToArray()`, could data be streamed in and `.Length` not represent the true length of the stream? Sounds possible to me, or at least there's preventing this.

Personal preference would be for the EOS exception to not exist and the methods to read as much as they can until EOS.

2022-02-14 06:36 UTC, peppy commented
> Personal preference would be for the EOS exception to not exist and the methods to read as much as they can until EOS.

Main reason for not doing this is it results in a second copy of the array being required, unless you want to branch for that exception case and add more complexity (something I was trying to avoid here because I agree with not wanting to reinvent the wheel, the point I wish these methods existed somewhere else and we didn't need to write them).

2022-02-14 06:39 UTC, smoogipoo commented
Dunno. Take that as you may. I don't think copying is a huge deal - at the point you're reading so much data that that's a point of concern, you probably shouldn't be doing this in the first place. But you could also return sliced `Memory` instances instead if that's that big of a concern.

2022-02-14 06:41 UTC, smoogipoo approved these changes

2022-02-14 06:42 UTC, peppy commented
This is being used for loading of all resources (aka `DllResourceStore`), which can be hundreds of megabytes for a game. So I thought it was a point of concern already. I was consciously benchmarking memory usage when writing these methods.

2022-02-14 06:48 UTC, merged