Rework CircularProgress to use shader
ppy/osu-framework pull request #5065
Opened 2022-03-10 15:14 UTC by EVAST9919

To make things easy to review this pr brings only basic shader implementation, smoothening will come in a separate pr.
Also I'm not sure so I'll ask here: do we need `Rounded` version?

2022-03-10 17:07 UTC, frenzibyte reviewed
Left a few nits, I'm not sure about the trigonometry behind this as I'm not knowledgable on that, but overall this looks pretty good. Nice work.

2022-03-10 19:11 UTC, EVAST9919 commented
Applied suggestions and added rounded version

2022-03-10 20:19 UTC, bdach requested changes

2022-03-10 20:19 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +#define PI 3.1415926538
Interesting value of pi there, should be

```suggestion
#define PI 3.1415926536
```

going off of the math books that I have. (Incidentally the first result of googling "glsl pi" contains this same wrong value.)

Not that this is going to ever realistically matter but let's attempt to get the basic math constants right.

2022-03-10 20:19 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    float angle = atan(0.5 - pixelPos.y, 0.5 - pixelPos.x) - PI / 2.0;
use swizzling

```suggestion
    float angle = atan(0.5 - pixelPos.yx) - PI / 2.0;
```

2022-03-10 20:19 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    vec2 resolution = vec2(v_TexRect[2] - v_TexRect[0], v_TexRect[3] - v_TexRect[1]);
use swizzling

```suggestion
    vec2 resolution = v_TexRect.zw - v_TexRect.xy;
```

2022-03-10 20:19 UTC, bdach commented on osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs
> +                        Size = new Vector2(350)
Kind of weird to always force 1:1 aspect ratio in this test when it wasn't enforced previously. Would have liked to keep a test or even a step showing that this also works for arbitrary aspect ratios.

2022-03-10 20:19 UTC, bdach commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    float innerBorder = 0.5 - (0.5 * innerRadius);
weird way to write this, would prefer

```suggestion
    float innerBorder = 0.5 * (1 - innerRadius);
```

2022-03-10 20:20 UTC, bdach commented
Review comments above apply to both shader files, of course, I just didn't want to double post.

2022-03-10 20:22 UTC, frenzibyte requested changes
In addition to the above.

2022-03-10 20:22 UTC, frenzibyte commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +}
Can have this logic moved to a header file and included in both `sh_CircularProgress` and `sh_CircularProgressRounded` to avoid code duplication (has been done before with other shaders like `sh_Video`, see `sh_yuv2rgb.h`).

2022-03-10 20:31 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    vec2 resolution = vec2(v_TexRect[2] - v_TexRect[0], v_TexRect[3] - v_TexRect[1]);
Yeah, just went with what is used elsewhere

2022-03-10 20:32 UTC, frenzibyte commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    float angle = atan(0.5 - pixelPos.y, 0.5 - pixelPos.x) - PI / 2.0;
Swizzling won't work on `atan` since it always expects two `y` and `x` parameters (crashes with `Incompatible types in initialization (and no available implicit conversion)`)

2022-03-10 20:37 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    float angle = atan(0.5 - pixelPos.y, 0.5 - pixelPos.x) - PI / 2.0;
Will not work since I'm using `atan(value1, value2)`, not `atan(vec2)`

2022-03-10 20:56 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +}
True, looks much cleaner now

2022-03-10 21:31 UTC, bdach commented
Code seems fine but before approval this probably needs testing on iOS and android to make sure this doesn't fall over there due to insufficient `v_TexRect` precision like the hue/saturation shader already does.

2022-03-10 22:57 UTC, frenzibyte commented
iOS is broken in the same way as the HSV shaders, which means this will have to stay blocked until that is resolved, otherwise mobile devices will no longer be able to render any `CircularProgress`.

2022-03-14 00:40 UTC, EVAST9919 commented
I've added precision modifiers since I'm guessing that may be the case , but unfortunately I can't really test this.

2022-07-20 07:10 UTC, smoogipoo commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    highp vec2 pixelPos = v_TexCoord / resolution;
The alternative is to have `#if` directives for high precision vertex input.

2022-07-20 14:59 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_CircularProgress.fs
> +    highp vec2 pixelPos = v_TexCoord / resolution;
I assume you are suggesting this?
```
#ifdef GL_ES
    precision highp float;
#endif
```

2022-10-11 16:38 UTC, EVAST9919 commented
Added potential fix which is a combination of suggestions [here](https://github.com/ppy/osu-framework/pull/5065#discussion_r926182315) and [here](https://github.com/ppy/osu-framework/pull/4702#issuecomment-903304728).
Works fine on Windows but not tested on other platforms (mobile ones especially)

2022-10-12 08:22 UTC, smoogipoo approved these changes
Needs testing on mobile but otherwise lgtm

2022-10-13 14:24 UTC, frenzibyte approved these changes
Works well, tested on iOS.

2022-10-13 14:35 UTC, merged