Improve the Windows borderless hack
ppy/osu-framework pull request #5068
Opened 2022-03-11 20:07 UTC by Susko3

Closes https://github.com/ppy/osu-framework/issues/3456.

Goals for this change
---

1. have the hack not be noticeable by multi-monitor users
    - partially resolved, will now show black instead of bleeding the game over. would be great if the pixels could be transparent
2. render the game at display resolution
3. don't cause off-by-one errors (eg. in mouse input, when translating game coordinates to window/screen space)
4. don't break things reliant on window size, such as screenshots
5. still prevent windows or drivers from putting the game in exclusive fullscreen

Implementation/changes
---

Will now only increase the window width by 1px (as opposed to both width and height, in addition to offsetting the window position). This is done to satisfy 2. and 3. while keeping 5.

Modifying the height (while satisfying 2. and 3.) requires messing with the GL viewport, as the GL origin is the bottom left corner, while windows uses top left. So I decided against that.

Tricking the game into thinking the window is smaller seems to have no ill side effects. The only (minor) problem is the mouse being able to go one pixel too far when it's confined. This can be fixed with `SDL_SetWindowMouseRect`, but since most users will use relative mode (which works fine), I don't think it's worth it.

---

You can test out how the hack looks when the window is even wider, eg. set `WindowsBorderlessWidthHack` to `20` -- the game will neatly render on it's display, while showing a black bar on the display to the right.

On my machines, setting this to `0` will cause the game to enter quasi-exclusive fullscreen, eg. the screen will briefly flash black when alt-tabbing. So expanding only width seems to work just fine for tricking windows and drivers.

Tested on:
- Windows 10 21H1, AMD Radeon R7 370 (desktop)
- Windows 10 21H2, AMD Ryzen 7 5700U with Radeon graphics (laptop)

2022-03-11 20:31 UTC, Susko3 commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                value.Width -= WindowsBorderlessWidthHack;
This is done here (instead of in `WindowsWindow`) in case some SDL window event causes the size to be recalculated.

2022-03-11 23:21 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                value.Width -= WindowsBorderlessWidthHack;
You can still keep this in `WindowsWindow` via overrides, no? `Size` can be virtualised, and `updateWindowStateAndSize` can be exposed as protected and virtualised as well. Don't think there's too much of an issue with that.

2022-03-12 01:56 UTC, frenzibyte requested changes
Seems fine in general. Haven't tested this, only read through code.

2022-03-12 01:56 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +        protected int WindowsBorderlessWidthHack;
I find the existence of this property unnecessary. The value itself can be moved to a constant and the application in `Size` can be conditioned based on whether `WindowState == WindowState.FullscreenBorderless`. 

That will make moving all this logic to `WindowsWindow` be done with only virtualising `Size`'s setter instead of having to expose `updateWindowStateAndSize`, and will read better in general.

2022-03-13 03:21 UTC, frenzibyte approved these changes

2022-03-13 04:04 UTC, peppy commented
Interestingly I was recently working around similar code on stable to fix a long-time bug. I have a good set of manual tests to go through to make sure things are working as intended, so will do that today.

2022-03-14 01:53 UTC, peppy approved these changes
Works fine with multi-monitor multi-refresh

2022-03-14 01:53 UTC, merged