Bring Android framework to .NET 6
ppy/osu-framework pull request #5080
Opened 2022-03-26 14:44 UTC by huoyaoyuan

- [ ] Requires https://github.com/ppy/osuTK/pull/75

### Development requirement

Run `dotnet workload install android` to install the necessary SDK components (may require `sudo`).
Xamarin toolchain in Visual Studio should be still required. I haven't tested if the managed components can be compiled without Xamarin installed.

The framework visual test works fine on my phone.

2022-03-26 15:09 UTC, huoyaoyuan commented
![image](https://user-images.githubusercontent.com/5644458/160245624-99662762-fe0e-4ec8-b1a3-520b5e92c686.png)
The constants are all correct on Windows. The video test failure shouldn't be my fault since I don't touch anything else.

2022-03-26 17:48 UTC, huoyaoyuan commented
This will require 2 rounds of deployment: the first one to deploy updated NativeLibs, the second one to update android framework.
The CI build accepting updated NativeLibs should not show `warning XA4301`. I tested it with local folder as nuget source.

2022-03-26 18:03 UTC, bdach commented on osu.Framework.Android.props
> -  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
Slightly uncomfortable with all of these removals - was this all default settings? How closely was it checked that nothing important is being deleted here?

2022-03-26 18:05 UTC, huoyaoyuan commented on osu.Framework.Android.props
> +    <RuntimeIdentifiers>android-x86;android-arm;android-arm64</RuntimeIdentifiers>
There is a warning says that `AndroidSupportedAbis` is deprecated instead of RIDs. For reference, in Windows desktop (WindowsAppSDK) development, the RIDs are used to specify the platforms.

2022-03-26 18:06 UTC, bdach commented
Also, re: [a267cf6](https://github.com/ppy/osu-framework/pull/5080/commits/a267cf66d616a2db904bcaeb2330be46fe9e7aa3) - it looks a bit weird to create an empty dir in a correct location just so RID fallback to linux doesn't happen. Is it viable to perhaps move binaries out of `osu.Framework.Android` to the nativelibs project? Seems like that'd be a cleaner resolution.

2022-03-26 18:08 UTC, huoyaoyuan commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +#pragma warning disable 1574 // unresolved cref attribute
There's a series of events mentioned in this file, but only a portion of them implemented.
The other CS1574 is not specific for Android, which I'm going to resolve in another PR.

2022-03-26 18:08 UTC, frenzibyte commented on osu.Framework.Android.props
> +    <RuntimeIdentifiers>android-x86;android-arm;android-arm64</RuntimeIdentifiers>
I think what's being suggested here is to just do:
```suggestion
    <RuntimeIdentifiers>android</RuntimeIdentifiers>
```

2022-03-26 18:13 UTC, huoyaoyuan commented on osu.Framework.Android.props
> -  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
I used VS designer to view the evaluated properties.
Like the transition from .NET Framework projects, most Debug conditional properties are set by the SDK.
The only thing changed is `Bundle assemblies into native code`. I did make a deep research of it, but setting it increases APK size significantly, so I left it unset.

2022-03-26 18:14 UTC, huoyaoyuan commented
> Is it viable to perhaps move binaries out of `osu.Framework.Android` to the nativelibs project? Seems like that'd be a cleaner resolution.

Yes I've considered this option. The downside is to increase nuget restore size for desktop only development. Leaving for decision here.

2022-03-26 18:17 UTC, huoyaoyuan commented on osu.Framework.Android.props
> +    <RuntimeIdentifiers>android-x86;android-arm;android-arm64</RuntimeIdentifiers>
I tried and it simply doesn't compile: `error XA0035: Unable to determine the Android ABI from the value 'android'. Edit the project file in a text editor and set the 'RuntimeIdentifiers' MSBuild property to contain only valid identifiers for the Android platform.`

2022-03-26 19:42 UTC, huoyaoyuan commented on osu.Framework.Android/Input/AndroidInputHandler.cs
> +#pragma warning disable 1574 // unresolved cref attribute
Well the other warnings only gets exposed if Android enabled. Android build has its own quirk that enables xmldoc anyway. I'm going to fix them too in this PR.

2022-03-28 20:12 UTC, Susko3 commented
Crashes when returning from activity pause (eg. press home and open the game again) with `InvalidFramebufferOperationExt`. Only happens on debug build, release works fine.

Can repro on two devices, API 28 and 30. 
Are you able to reproduce?

```cs
2022-03-28 21:31:43.319 10374-10374/osu.Framework.Tests.Android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: osu.Framework.Tests.Android, PID: 10374
    android.runtime.JavaProxyThrowable: osuTK.Graphics.GraphicsErrorException: InvalidFramebufferOperationExt
        at osuTK.Graphics.ES30.ErrorHelper.CheckErrors()
        at osuTK.Graphics.ES30.ErrorHelper.Dispose()
        at osuTK.Graphics.ES30.GL.Clear(ClearBufferMask mask)
        at osu.Framework.Graphics.OpenGL.GLWrapper.Clear(ClearInfo clearInfo)
        at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(Vector2 size)
        at osu.Framework.Threading.DrawThread.OnInitialize()
        at osu.Framework.Threading.GameThread.Initialize(Boolean withThrottling)
        at osu.Framework.Platform.ThreadRunner.ensureCorrectExecutionMode()
        at osu.Framework.Platform.ThreadRunner.Start()
        at osu.Framework.Platform.GameHost.Resume()
        at osu.Framework.Android.AndroidGameActivity.OnRestart()
        at Android.App.Activity.n_OnRestart(IntPtr jnienv, IntPtr native__this)
        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
        at crc64eb0f9b4bca91a892.AndroidGameActivity.n_onRestart(Native Method)
        at crc64eb0f9b4bca91a892.AndroidGameActivity.onRestart(AndroidGameActivity.java:61)
        at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1445)
        at android.app.Activity.performRestart(Activity.java:8261)
        at android.app.ActivityThread.performRestartActivity(ActivityThread.java:5305)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:243)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:255)
        at android.app.ActivityThread.main(ActivityThread.java:8212)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

2022-03-29 07:47 UTC, huoyaoyuan commented
No, it works fine on my phone, using framework visual tests in Debug. The device is Android 11.

2022-03-29 11:12 UTC, Susko3 commented
Seems the crashes are caused by running/building `ppy.osuTK.NS20` in debug configuration. So it doesn't crash with your method.

In my original testing, I changed both `ppy.osuTK.NS20` and `ppy.osuTK.Android` to use a local checkout (at your PR).
With only `ppy.osuTK.Android` being a local checkout (and `ppy.osuTK.NS20` using the same nuget package as `master`), it doesn't crash in debug.

Crashes with your method if using local checkout of both `osuTK.NS20` and `osuTK.Android` (local checkout at `master`)

But this doesn't seem like a blocker for this PR, as `osuTK` is used in release configuration.

2022-03-31 04:25 UTC, smoogipoo requested changes

2022-03-31 04:25 UTC, smoogipoo commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
This isn't required here, right? This is only building the desktop project.

2022-03-31 04:25 UTC, smoogipoo commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
Same thing here?

2022-03-31 04:25 UTC, smoogipoo commented on osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
> +    <None Include="runtimes\**\native\*">
Is this just to not include the ffmpeg build script for macOS? Probably an unnecessary change if so since these scripts have to be moved to CI anyway.

2022-03-31 04:25 UTC, smoogipoo commented on osu.Framework/Graphics/Video/FFmpegConstants.cs
> +    internal static class FFmpegConstants
We already have `FFmpegFuncs` for this. Would prefer this to be moved into there.

2022-03-31 04:31 UTC, smoogipoo commented
Going to block this until the osu!-side blocking issue is fixed. We typically keep osu! and osu!framework in sync and it's hard to say how long the blocked issue will take to be resolved (or even what the rollout timetable looks like for dotnet android).

2022-03-31 04:41 UTC, peppy commented
I've pushed out an osuTK build to nuget including https://github.com/ppy/osuTK/pull/75, so packages can be updated after packages are indexed (needs 30 minutes or so).

2022-04-01 04:51 UTC, huoyaoyuan commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
I'm not sure which CI is actually used, so I just changed all of them. Should we preserve this for further migration if wanted?

2022-04-01 04:51 UTC, huoyaoyuan commented on osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
> +    <None Include="runtimes\**\native\*">
Yes, I touched it since I touched the native libs.

2022-04-03 12:58 UTC, huoyaoyuan commented
After updating osuTK to net6 compiled version, the Realm issue disappears (tested with framework visual test), but another null pointer dereference appears when testing with full game. Aiming to identify it.

2022-04-03 14:18 UTC, huoyaoyuan commented
Highlight the TBD here: should we (try to) move android native assets into NativeLibs?

2022-04-03 14:42 UTC, bdach commented
probably best to leave as is in this pull and move them as a follow up even if it is decided to be the right direction.

2022-04-03 14:56 UTC, bdach commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
I'm not sure what "further migration" means here but I don't see any reason why any job that doesn't build android projects should be installing android workloads.

2022-04-03 15:00 UTC, huoyaoyuan commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
Well I misread the file context when replying this. It should be removed is not building android.

2022-04-03 15:03 UTC, huoyaoyuan commented on .github/workflows/ci.yml
> +        run: dotnet workload install android
Oh I didn't mention that InspectCode inspects desktop only now. Should be removed until we want to inspect android code.

2022-04-03 15:04 UTC, bdach commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            if (OperatingSystem.IsAndroidVersionAtLeast(23))
* Why version 23? The [event in question](https://developer.android.com/reference/android/view/View.OnGenericMotionListener) seems to have been a thing since API 12?
* Prefer to early return in these cases rather than nest further.

2022-04-03 15:08 UTC, huoyaoyuan commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            if (OperatingSystem.IsAndroidVersionAtLeast(23))
The `ActionButton` property is annotated with API 23. I'm not sure the correct behaviour if it's unavailable.

2022-04-03 15:16 UTC, bdach commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            if (OperatingSystem.IsAndroidVersionAtLeast(23))
Docs [appear to indicate](https://developer.android.com/reference/android/view/MotionEvent#getActionButton()) that [`ButtonState`](https://developer.android.com/reference/android/view/MotionEvent#getButtonState()) is the legacy path for this pre-API 23. Unsure if worth handling, though.

2022-04-04 03:30 UTC, peppy commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            if (OperatingSystem.IsAndroidVersionAtLeast(23))
Definitely deserves an inline comment with a link to the docs.

2022-04-04 08:13 UTC, turbedi commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            // ActionButton is not available before API 21
```suggestion
            // ActionButton is not available before API 23
```
Typo?

2022-04-04 08:13 UTC, turbedi commented on osu.Framework.Android/Input/AndroidMouseHandler.cs
> +            // ActionButton is not available before API 21
```suggestion
            // ActionButton is not available before API 23
```
Same as above

2022-04-08 08:56 UTC, huoyaoyuan commented
Confirmed with debugger and decompiled code that `InvocationPointer` is java_vm.

2022-04-10 12:27 UTC, bdach commented
I've attempted to test this today and am not sure where to start, because:

* I can no longer debug any of the android projects. The option just isn't there, because I can't deploy projects in debug onto android:

  ![image](https://user-images.githubusercontent.com/20418176/162617887-7f571e2b-3553-476a-aa6d-a13784a0e3d8.png)

  The above has a bit of polish but hopefully you get the point - the run button is supposed to be listing off all available devices to deploy to. It doesn't anymore if I'm not on a release config. And if I try to debug a release build, then it just doesn't work anymore, the debugger does not attach.

* On both my test devices, I am seeing native crashes in logcat when attempting to run visual testts.

Device 1 (Samsung SM-J710F, api level 24):

```
04-10 14:08:36.421	Samsung SM-J710F	Error	31958	DEBUG	pid: 31910, tid: 31910, name: k.Tests.Android  >>> osu.Framework.Tests.Android <<<
04-10 14:08:36.421	Samsung SM-J710F	Error	31958	DEBUG	signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x3a127fd7
    r0 3a127fcb  r1 00000000  r2 00000000  r3 00000000
    r4 ffa2ff8c  r5 3a127fcb  r6 00000000  r7 ffa2ffd0
    r8 00000000  r9 f3bbce17  sl 00000043  fp 00000000
    ip f3f78b20  sp ffa2feb8  lr f3e387c1  pc f3bbfe64  cpsr 600e0030
04-10 14:08:36.425	Samsung SM-J710F	Error	31958	DEBUG	backtrace:
    #00 pc 000b0e64  /system/lib/libart.so (_ZN3art9ArtMethod23GetOatQuickMethodHeaderEj+19)
    #01 pc 003297bd  /system/lib/libart.so (_ZN3art12StackVisitor9WalkStackEb+116)
    #02 pc 003348d7  /system/lib/libart.so (_ZNK3art6Thread16GetCurrentMethodEPjb+54)
    #03 pc 00261975  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+1152)
    #04 pc 0002ad0b  /data/app/osu.Framework.Tests.Android-1/lib/arm/libmonodroid.so (java_interop_jnienv_find_class+24)
    #05 pc 00003f14  <anonymous:eae25000>
```

Device 2 (OnePlus KB2003, api 30):

```
04-10 14:13:24.124	OnePlus KB2003	Error	23722	DEBUG	pid: 28032, tid: 28032, name: k.Tests.Android  >>> osu.Framework.Tests.Android <<<
04-10 14:13:24.124	OnePlus KB2003	Error	23722	DEBUG	signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
04-10 14:13:24.124	OnePlus KB2003	Error	23722	DEBUG	Cause: null pointer dereference
    x0  4060000000000030  x1  0000000000000000  x2  0000007fc0b93400  x3  0000000000000000
    x4  00000000132d73c0  x5  0000000013a80ea8  x6  4200000400000000  x7  4200000400000000
    x8  0000007fc0b8af60  x9  0000000000000000  x10 0000007fc0b8af60  x11 0000000040600000
    x12 0000000000000000  x13 0000000000000038  x14 0000000040600000  x15 40600000320f3016
    x16 0000000040600000  x17 fffffffffffffffe  x18 00000070952b4000  x19 0000007fc0b93640
    x20 0000000000000000  x21 0000007fc0b936b0  x22 0000007fc0b940f0  x23 0000007fc0b94050
    x24 0000006d9dd05e40  x25 0000006d9dd06210  x26 0000000000000000  x27 0000000000000030
    x28 0000007094646000  x29 0000007fc0b93590
    lr  0000006d9e14de54  sp  0000007fc0b933c0  pc  0000006d9e14dc48  pst 0000000000001000
04-10 14:13:24.170	OnePlus KB2003	Error	23722	DEBUG	backtrace:
      #00 pc 0000000000584c48  /apex/com.android.art/lib64/libart.so (void art::StackVisitor::WalkStack<(art::StackVisitor::CountTransitions)1>(bool)+136) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #01 pc 00000000005b9fb8  /apex/com.android.art/lib64/libart.so (void art::Thread::VisitRoots<false>(art::RootVisitor*)+1320) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #02 pc 0000000000268090  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::ThreadFlipVisitor::Run(art::Thread*)+308) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #03 pc 00000000005c4454  /apex/com.android.art/lib64/libart.so (art::ThreadList::FlipThreadRoots(art::Closure*, art::Closure*, art::gc::collector::GarbageCollector*, art::gc::GcPauseListener*)+1152) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #04 pc 0000000000254ff4  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::FlipThreadRoots()+292) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #05 pc 00000000002536a0  /apex/com.android.art/lib64/libart.so (art::gc::collector::ConcurrentCopying::RunPhases()+1024) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #06 pc 000000000027700c  /apex/com.android.art/lib64/libart.so (art::gc::collector::GarbageCollector::Run(art::gc::GcCause, bool)+300) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #07 pc 0000000000293e80  /apex/com.android.art/lib64/libart.so (art::gc::Heap::CollectGarbageInternal(art::gc::collector::GcType, art::gc::GcCause, bool)+4144) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #08 pc 0000000000004f08  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_GC+164) (BuildId: ef162aca91c49e678fee75b29fa972fb)
      #09 pc 00000000000815fc  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+124) (BuildId: aece9284df80b1815bdaf34e52f290399c49da97)
      #10 pc 000000000009b620  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Runtime.gc+96) (BuildId: aece9284df80b1815bdaf34e52f290399c49da97)
      #11 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #12 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #13 pc 0000000000555598  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+468) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #14 pc 0000000000555738  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #15 pc 00000000003aba24  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660) (BuildId: e841be9816817e37b70ebf4a461a916e)
      #16 pc 00000000000283ac  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonodroid.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+116) (BuildId: 6e521e11e0c16c91d944e41591484727b79a9f43)
      #17 pc 0000000000026be0  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonodroid.so (xamarin::android::internal::OSBridge::gc_cross_references(int, MonoGCBridgeSCC**, int, MonoGCBridgeXRef*)+224) (BuildId: 6e521e11e0c16c91d944e41591484727b79a9f43)
      #18 pc 00000000000d8030  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #19 pc 000000000011e0c8  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #20 pc 000000000011aff0  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #21 pc 000000000011abcc  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #22 pc 0000000000110074  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #23 pc 00000000000e3568  /data/app/~~QwSnIcJf7DGwRKt9OCBJBg==/osu.Framework.Tests.Android-ib8ldIfSgmF9U3iLixWhKA==/lib/arm64/libmonosgen-2.0.so (BuildId: 7310e0da105e448374721a35c0841ba1673fb87a)
      #24 pc 00000000000a2950  /data/app/~~QwSnIcJf7 [...]

2022-04-10 12:32 UTC, bdach commented on osu.Framework/Graphics/Video/FFmpegFuncs.cs
> +        public static readonly int EAGAIN = RuntimeInfo.IsApple ? 35 : 11;
Also just going to note for the record that this is going to need to be checked on linux and apple devices. I'll grab linux later, but I can't do anything about apple. Random googles suggest that this will be ok, but I'd rather be certain.

2022-04-10 12:55 UTC, huoyaoyuan commented
@bdach Since the workload is effectively preview, I'd suggest to update .NET SDK to latest first. I'm using SDK 6.0.201, and the version of Microsoft.Android.Sdk.Windows (located in `C:\Program Files\dotnet\packs`) is 31.0.200-preview.14.106.

I've installed the Xamarin workload in Visual Studio, and the deployment just works like before. Maybe restarting Visual Studio/rebuilding or whatever can update the deployment action.

Is your crash happening on startup? As a remainder, fully uninstall previous versions and do full rebuild may cause difference.

2022-04-10 12:57 UTC, huoyaoyuan commented on osu.Framework/Graphics/Video/FFmpegFuncs.cs
> +        public static readonly int EAGAIN = RuntimeInfo.IsApple ? 35 : 11;
I grabbed the value [here](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/24da0e7cd0db359f817f3e3ddf947940a2e9b368/FFmpeg.AutoGen/FFmpeg.cs#L41-L45), and supposed iOS to be the same with mac. It's not that obvious in [source](https://github.com/mono/mono/blob/4b5e2591eb299eb34d60b5217b14c1ad9f11e238/mcs/class/corlib/System/Environment.cs#L217-L220).

2022-04-10 13:03 UTC, bdach commented
Crash occurs immediately on startup yes. Uninstalled previous app versions from devices before.

2022-04-10 14:30 UTC, huoyaoyuan commented
Hopefully you can bring debugger working. Try to do `dotnet build` and reopen VS or whatever. Since sample game is working, at least you should be able to step in until it crashes.
Video related issues shouldn't throw until you touch the video decoder tests.
You can also see if release build is working. The call stacks indicates something really bad. `java_interop_jnienv_find_class` looks like misconfigured reflection, and the second one like crash from GC. Anyway, updating .NET SDK may resolve issue in mono itself.

2022-04-10 17:35 UTC, bdach commented
I've jiggled everything I could think of (updated VS 2022, updated dotnet SDK, rebooted machine, cleaned solution), and looks like it helped for whatever reason, both issues are gone.

2022-04-13 00:06 UTC, frenzibyte commented on osu.Framework/Graphics/Video/FFmpegFuncs.cs
> +        public static readonly int EAGAIN = RuntimeInfo.IsApple ? 35 : 11;
On a quick check, iOS apps do yield true for `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)`, [which is the backend of that `LibraryLoader.GetPlatformId` method](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/24da0e7cd0db359f817f3e3ddf947940a2e9b368/FFmpeg.AutoGen/Native/LibraryLoader.cs#L13-L25):

<img width="1333" alt="CleanShot 2022-04-13 at 02 38 07@2x" src="https://user-images.githubusercontent.com/22781491/163071581-9d144f04-517e-40b1-ae46-b4e9227e52cf.png">

And on further google search, [the `EAGAIN 35` value comes from BSD](https://github.com/apple/darwin-xnu/blob/8f02f2a044b9bb1ad951987ef5bab20ec9486310/bsd/sys/errno.h#L131), which iOS is also based on (macOS/iOS -> Darwin -> BSD).

2022-05-15 13:29 UTC, bdach commented
We may need to fast forward this a bit, as [android builds started inexplicably failing yesterday](https://github.com/ppy/osu-framework/runs/6436416811?check_suite_focus=true#step:5:418) and this pull [seems to fix it](https://github.com/ppy/osu-framework/runs/6441234897?check_suite_focus=true).

2022-05-16 02:31 UTC, smoogipoo requested changes
Apart from a small clarification, from a code-only perspective this is g2g.

2022-05-16 02:31 UTC, smoogipoo commented on osu.Framework/IO/Network/WebRequest.cs
> +                }
Can there be a comment as to why using a different type is required? Potentially this relates to the override in the props file, but I also don't understand why that's required (probably explained earlier in this PR but such info is going to get lost to time).

2022-05-16 07:00 UTC, huoyaoyuan commented on osu.Framework/IO/Network/WebRequest.cs
> +                }
The platform handler specified in props file is only invoked by `HttpClientHandler`. It invokes `SocketsHttpHandler` on desktop, but we need direct access to `SocketsHttpHandler` to use `ConnectCallback`.

2022-05-16 07:06 UTC, smoogipoo commented on osu.Framework/IO/Network/WebRequest.cs
> +                }
Sure. I'm basically asking for two comments:
1) Why we use the handler specified in the props file and not whatever Mono does automatically.
2) Why `HttpClientHandler` is used. Basically what you're written your response.

2022-05-16 07:42 UTC, smoogipoo approved these changes
Code-only review

2022-05-16 08:14 UTC, huoyaoyuan commented
Reminder: this requires deployment for Framework, Framework.Android and NativeLibs.
After deploying NativeLibs, WarningAsError could be turned on for Android CI.

2022-05-18 02:35 UTC, smoogipoo commented
Just to confirm, there are no longer any issues with this across both osu and osu-framework projects, in either debug or release mode configs?

2022-05-18 03:31 UTC, huoyaoyuan commented
Confirmed following actions with latest commits of both PRs, in Debug and Release:
- Run framework test, play video and audio
- Login into production server
- Download a beatmap with video, play and run autoplay

If the SSL issue with downlevel OS found by @bdach is no longer present, I can't see any issue now.

2022-05-18 19:59 UTC, bdach commented
Didn't find any issues last time I tested this.

2022-05-19 05:59 UTC, peppy commented
Shall we look at getting this in after the next framework release?

2022-05-19 19:52 UTC, bdach commented
With the interim android build fix merged I don't see any particular reason to hurry too much with these changes anymore. I don't have any more code/testing issues to point out at this juncture, so it all boils down as to when you get the time/space to figure out the tooling/deployment end issues (if any).

2022-07-07 09:13 UTC, smoogipoo commented on osu.Framework.Android/osu.Framework.Android.csproj
> +    <PackageReference Include="ppy.osuTK.Android" Version="1.0.189" />
We will need to re-deploy osuTK from master (package is currently built from [master-before-net6](https://github.com/ppy/osuTK/tree/master-before-net6)) prior to this PR being merged.

2022-07-07 09:17 UTC, peppy commented on osu.Framework.Android/osu.Framework.Android.csproj
> +    <PackageReference Include="ppy.osuTK.Android" Version="1.0.189" />
Has been deployed as (`1.0.193`)

2022-07-08 04:45 UTC, smoogipoo approved these changes
@peppy This is just awaiting on you now. Others have tested it to work previously, and it looks good code-wise from my side.

2022-07-08 11:24 UTC, peppy commented
Unfortunately my android test device will no longer boot (suffered from a bulging battery but totally conked it now). Will test with emulator to make sure the tooling works I guess.

2022-07-08 22:26 UTC, Susko3 commented
Using `HttpClientHandler` or `SocketsHttpHandler` was [previously discussed](https://github.com/ppy/osu/pull/17462#discussion_r854491633). There were problems with both handlers on @bdach, @huoyaoyuan and my (Realme 6) test devices. Results were inconclusive and could change with different `dotnet workload install android` versions. I've done the following testing to get a conclusive answer of which to use.

I've tested osu! with a local framework checkout with a matrix of devices and configurations. Main focus was testing the difference of `HttpClientHandler` and `SocketsHttpHandler` on `Release` and `Debug` build configurations. Additionally, `Release` was tested with and without [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained).

`HttpClientHandler` or `SocketsHttpHandler`?
---

Changing `HttpClientHandler` (the current default in this PR) to `SocketsHttpHandler` (used on desktop net6.0):

```diff
diff --git a/osu.Framework/IO/Network/WebRequest.cs b/osu.Framework/IO/Network/WebRequest.cs
index 4fea6062b..f139ac6a7 100644
--- a/osu.Framework/IO/Network/WebRequest.cs
+++ b/osu.Framework/IO/Network/WebRequest.cs
@@ -154,7 +154,7 @@ private set
 #if NET6_0_OR_GREATER
             // SocketsHttpHandler causes crash in Android Debug, and seems to have compatibility issue on SSL
             // Use platform HTTP handler which is invoked by HttpClientHandler for better compatibility and app size
-            RuntimeInfo.IsMobile
+            RuntimeInfo.IsMobile && false
                 ? new HttpClientHandler
                 {
                     Credentials = CredentialCache.DefaultCredentials,
```

Trimming
---

By default, Android will build with trimming enabled. To disable trimming, the following was added to both `osu.Framework.Android.props` and `osu.Android.props`:

```xml
<PropertyGroup>
  <PublishTrimmed>false</PublishTrimmed>
</PropertyGroup>
```

# The data

Realme 6 (API 30) | Release not trimmed | Release trimmed | Debug
-- | -- | -- | --
HttpClientHandler | works fine | **(!) login fails with `MethodInfo` nullref** | works fine
SocketsHttpHandler | works fine | works fine | works fine

Samsung A02s (API 30) | Release not trimmed | Release trimmed | Debug
-- | -- | -- | --
HttpClientHandler | works fine | **(!) login fails with `MethodInfo` nullref** | works fine
SocketsHttpHandler | works fine | works fine | works fine

LG Q6 (API 27) | Release not trimmed | Release trimmed | Debug
-- | -- | -- | --
HttpClientHandler | works fine | **(!) login fails with `MethodInfo` nullref** | works fine
SocketsHttpHandler | **(!) login fails with SSL error** | **(!) login fails with SSL error** | **(!) login fails with SSL error**

### `network.log` excerpts:

LG Q6, `SocketsHttpHandler`, all configurations:

```cs
2022-07-08 21:11:22 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2022-07-08 21:11:22 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
2022-07-08 21:11:22 [verbose]: ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
2022-07-08 21:11:22 [verbose]: --- End of inner exception stack trace ---
2022-07-08 21:11:22 [verbose]: at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
2022-07-08 21:11:22 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: --- End of inner exception stack trace ---
2022-07-08 21:11:22 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
2022-07-08 21:11:22 [verbose]: at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1[[System.Net.Http.HttpConnection, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-07-08 21:11:22 [verbose]: at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-07-08 21:11:22 [verbose]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken).
2022-07-08 21:11:22 [verbose]: Login failed!
```

All devices, `HttpClientHandler`, Release trimmed:

```cs
2022-07-08 19:26:36 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, method
2022-07-08 19:26:36 [verbose]: at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
2022-07-08 19:26:36 [verbose]: at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
2022-07-08 19:26:36 [verbose]: at System.Delegate.CreateDelegate(Type type, MethodInfo method)
2022-07-08 19:26:36 [verbose]: at Java.Interop.JavaConvert.GetJniHandleConverterForType(Type )
2022-07-08 19:26:36 [verbose]: at Java.Interop.JavaConvert.GetJniHandleConverter(Type )
2022-07-08 19:26:36 [verbose]: at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership , Boolean& )
2022-07-08 19:26:36 [verbose]: at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership )
2022-07-08 19:26:36 [verbose]: at Android.Runtime.JavaDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.IList`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Get(String )
2022-07-08 19:26:36 [verbose]: at Android.Runtime.JavaDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.IList`1[[System.String, System.Private. [...]

2022-07-09 03:34 UTC, huoyaoyuan commented
I can login with the default trimming option in Release. I didn't build framework in Release though.

The trimming issue looks like https://github.com/ppy/osu/pull/17462/commits/9b50fa346ff2868e160e2f8f9cd669593a180f1f , which is already resolved newer SDK.
@Susko3 can you confirm your android SDK version at `dotnet\packs\Microsoft.Android.Runtime.32.android-arm64`? Can you run `dotnet workload update` to ensure you are at latest version?

If you decompile the assembly at `32.0.xxx\runtimes\android-arm64\lib\net6.0\Mono.Android.dll`, can you see the trimmer annotation on the method?
![image](https://user-images.githubusercontent.com/5644458/178089927-8c270b81-77e7-402b-a9cf-30e10b5db9a9.png)

Or, does it work if you redo the workaround in that commit? I reverted it because it was fixed in SDK.

2022-07-09 08:03 UTC, Susko3 commented
I was on `31.0.200-preview.14.106`. No amount of `dotnet workload update` and `install` would get me to version 32. [Probably](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install#results-vary-by-sdk-version) because I was using `dotnet` version `6.0.203`. Downloading the newer version (`6.0.301`) now (will take some time, crappy internet).

Can confirm that the aforementioned method does _not_ have the trimmer annotation.

This is really fucking stupid. Is there some way to block or show a warning/error to people (like me) who are using older versions.

2022-07-09 08:18 UTC, Susko3 commented
Using [`global.json`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) in the root of the repo works (errors on build). Using `global.json` in `osu.Framework.Android` folder does not work. iOS seems to be using `global.json` in [the subfolder](https://github.com/ppy/osu-framework/blob/0cd3a93acc9be0d0936af1b89792d09167172cf0/osu.Framework.iOS/global.json).

Specifying the exact SDK version in the .csproj is hit or miss, sometimes giving warnings, sometimes building fine:
```diff
diff --git a/osu.Framework.Android/osu.Framework.Android.csproj b/osu.Framework.Android/osu.Framework.Android.csproj
index 819f5306f..d6a6063fe 100644
--- a/osu.Framework.Android/osu.Framework.Android.csproj
+++ b/osu.Framework.Android/osu.Framework.Android.csproj
@@ -1,4 +1,4 @@
-﻿<Project Sdk="Microsoft.NET.Sdk">
+﻿<Project Sdk="Microsoft.NET.Sdk/6.0.301">
   <PropertyGroup Label="Project">
     <TargetFramework>net6.0-android</TargetFramework>
     <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
```

(I've done this testing with `6.0.203` installed only, I didn't have `6.0.301` installed.)

2022-07-09 09:26 UTC, Susko3 commented
I've updated to android workload `32.0.415` and now `HttpClientHandler` works fine with `Release trimmed` on my `Relame 6` phone.

But is trimming something we want? It's not enabled on desktop platforms. Enabling it there shows some warnings, but I'm not seeing those warnings when building Android.

2022-07-10 08:00 UTC, huoyaoyuan commented
> But is trimming something we want? It's not enabled on desktop platforms.

Probably yes, because it is the default, and we do not allow custom rulesets on mobile (nor typical app store will do).



> This is really fucking stupid. Is there some way to block or show a warning/error to people (like me) who are using older versions.

The warning should be present when building the framework itself, since it is using reflection in fact.


> Using [`global.json`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) in the root of the repo works (errors on build). Using `global.json` in `osu.Framework.Android` folder does not work. iOS seems to be using `global.json` in [the subfolder](https://github.com/ppy/osu-framework/blob/0cd3a93acc9be0d0936af1b89792d09167172cf0/osu.Framework.iOS/global.json).

In fact I always use `global.json` in my personal project to guard for issues fixed in patch releases, especially for newly introduced workloads like CsWinRT.
I remember there was a root `global.json` for the repo. Is there any reason it's removed?

2022-07-11 19:38 UTC, bdach commented
`global.json` was removed during upgrade efforts to .NET 5 in https://github.com/ppy/osu-framework/pull/4012/commits/369b7e3d98b40817c040900d96ce07c5fe903869. Not sure on the exact rationale. The PR thread offers nothing.

2022-07-12 05:42 UTC, peppy commented
> `global.json` was removed during upgrade efforts to .NET 5 in [369b7e3](https://github.com/ppy/osu-framework/commit/369b7e3d98b40817c040900d96ce07c5fe903869). Not sure on the exact rationale. The PR thread offers nothing.

If I recall, it as removed because it made development hard. It was pinning a specific release, and if you didn't have that release locally things would fall over. I'm not against adding it back if the specification allows for minor sdk updates without issue.

2022-07-12 08:47 UTC, huoyaoyuan commented
> If I recall, it as removed because it made development hard. It was pinning a specific release, and if you didn't have that release locally things would fall over. I'm not against adding it back if the specification allows for minor sdk updates without issue.

Previously I set `rollForward` to `minor` when minor release was a thing. For now since the compatibility of SDK is often not an issue, setting it to `major` will allow any SDK version >= specified version to success.

I pushed `global.json` to game repo since the code there does need higher SDK version. Otherwise `TargetFramework` can be used as a "soft" constraint of SDK version. Should I also add a `global.json` in framework repo?

2022-07-14 04:16 UTC, peppy commented
Initial testing shows that:

- Rider will deploy to the emulator (but the `SampleGame` app will crash, not sure if relevant, do others also see this?)
- Rider will attempt to deploy to device but:

```csharp
  Xamarin.Android.Common.Debugging.targets(611, 5): [XA0137] The 'run-as' command failed with 'run-as: Could not set capabilities: Operation not permitted
'.
Fast Deployment is not currently supported on this device.
Please file an issue with the exact error message using the 'Help->Send Feedback->Report a Problem' menu item in Visual Studio
or 'Help->Report a Problem' in Visual Studio for Mac.
Please set the 'EmbedAssembliesIntoApk' MSBuild property to 'true' to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor.
```

2022-11-02 07:08 UTC, huoyaoyuan commented
I don't have Rider or Mac environment currently. Can anyone provide help for the deployment failure?

It still runs fine with latest update at my side.

2022-12-07 20:42 UTC, frenzibyte commented
I haven't deeply checked, but while I was working on the iOS side, I noticed the desktop nativelibs are in a `target == netcore` conditional, which will be the case for mobile projects as well once we switch to .NET 6 (no longer rely on netstandard)

![CleanShot 2022-12-07 at 23 37 41](https://user-images.githubusercontent.com/22781491/206290296-dc8ff608-fc30-4ad1-8e85-eaeda8885df3.png)

I believe that will result in desktop nativelibs becoming included in mobile nupkgs.

2022-12-08 23:41 UTC, frenzibyte commented on osu.Framework.Android.props
> +    <!-- NullabilityInfoContextSupport is disabled by default for Android -->
This is also the case on iOS, so a comment is probably not required.
```suggestion
```

2022-12-09 00:20 UTC, Susko3 commented
This PR solves some [problems](https://github.com/ppy/osu/issues/21516) with the linker stripping away symbols.

For example, with Release configuration, this diff crashes on `master` due to missing `System.Globalization.ThaiBuddhistCalendar`, but works fine with this PR.

```diff
diff --git a/osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs b/osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs
index 2759e275e..1a2bcb27c 100644
--- a/osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs
+++ b/osu.Framework.Tests/Visual/Platform/TestSceneActiveState.cs
@@ -3,6 +3,7 @@
 
 #nullable disable
 
+using System.Globalization;
 using osu.Framework.Allocation;
 using osu.Framework.Bindables;
 using osu.Framework.Graphics;
@@ -47,6 +48,10 @@ protected override void LoadComplete()
                     Anchor = Anchor.TopRight,
                     Origin = Anchor.TopRight,
                 },
+                new SpriteText
+                {
+                    Text = new CultureInfo("th-TH").DateTimeFormat.LongDatePattern
+                }
             };
 
             isActive.BindValueChanged(active => isActiveBox.Colour = active.NewValue ? Color4.Green : Color4.Red, true);
```

2022-12-09 01:34 UTC, huoyaoyuan commented on osu.Framework.Android.props
> +    <!-- NullabilityInfoContextSupport is disabled by default for Android -->
I think it's necessary to describe their different with desktop

2022-12-09 04:58 UTC, peppy commented
Revisiting this to see how things are today.

On trying to deploy `SampleGame.Android` from the android slnf file:

![JetBrains Rider 2022-12-09 at 04 55 49](https://user-images.githubusercontent.com/191335/206627097-fc5e6d79-8446-4775-a506-6a8d3c30ed1e.png)

```sh
osu-framework on  net6.0-android via .NET v7.0.100
❯ dotnet workload restore
Unhandled exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/usr/local/share/dotnet/sdk/7.0.100/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/7.0.100/Xamarin/iOS/Xamarin.iOS.CSharp.targets" is correct, and that the file exists on disk.  /Users/dean/Projects/osu-framework/SampleGame.iOS/SampleGame.iOS.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.DotNet.Workloads.Workload.Restore.WorkloadRestoreCommand.RunTargetToGetWorkloadIds(IEnumerable`1 allProjects)
   at Microsoft.DotNet.Workloads.Workload.Restore.WorkloadRestoreCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Should I be uninstalling .NET 7 for now?

2022-12-09 05:01 UTC, smoogipoo commented
That looks like it's trying to restore the iOS workload, but that hasn't been upgraded to NET6 in this PR. You should use `dotnet workload install android` instead

2022-12-09 06:29 UTC, peppy commented
`SampleGame.Android` failing on device:

```
12-09 15:28:15.569  3740  5183 D ActivityTrigger: Activity is Triggerred in full screen 
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.570  3740  5183 D ActivityManager: moveToFront() : reason=startedActivity setFocusedActivity isAttached=true TaskRecord{bc5387ad0 #87 A=SampleGame.Android U=0 StackId=1 sz=1}
12-09 15:28:15.570  3740  5183 D ActivityManager: setFocusStackUnchecked: reason=startedActivity setFocusedActivity focusCandidate=ActivityStack{9ff40bad0 stackId=1, 2 tasks} caller=com.android.server.am.ActivityStack.moveToFront:874 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:2006 
12-09 15:28:15.570  3740  7737 D TelephonyManager: getAllCellInfo : Caller (PID / UID / TID): 3740 / 1000 / 7737
12-09 15:28:15.572  3740  5183 D InputDispatcher: Focused application set to: xxxx
12-09 15:28:15.572  3740  5183 D InputDispatcher: Focus left window: 5260
12-09 15:28:15.572  3740  5183 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{bc5387ad0 #87 A=SampleGame.Android U=0 StackId=1 sz=1} next=ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87} mFocusedStack=ActivityStack{9ff40bad0 stackId=1, 2 tasks}
12-09 15:28:15.573  3740  5183 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-09 15:28:15.573  3740  5183 D GameManagerService: sem_perfomance_mode: 3
12-09 15:28:15.575  3740  3766 D WindowManager: addWindow: android.view.ViewRootImpl$W@ceda488 displayId=0
12-09 15:28:15.576  3740  3766 D InputTransport: Input channel constructed: fd=330
12-09 15:28:15.576  3740  3766 D InputTransport: Input channel constructed: fd=425
12-09 15:28:15.576  3740  3766 D WindowManager: openInputChannel mInputChannel: 280ae21 Starting SampleGame.Android (server)
12-09 15:28:15.576  3740  3766 D ViewRootImpl@28a682b[Android]: setView = DecorView@45e6246[Android] touchMode=true
12-09 15:28:15.578  5260  5260 D Launcher: onPause, Launcher: 135272777
12-09 15:28:15.578  5260  5260 D Launcher.HomeView: onPause
12-09 15:28:15.578  5260  5260 D Launcher.Workspace: exitWidgetResizeMode. isClearResizeFrame is false
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.579  3740  5975 D ActivityManager: clearAppIconInfo()
12-09 15:28:15.580  3740  5975 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{974cbed0 #75 A=com.sec.android.app.launcher U=0 StackId=0 sz=1} next=ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87} mFocusedStack=ActivityStack{9ff40bad0 stackId=1, 2 tasks}
12-09 15:28:15.580  3740  5975 D ActivityManager: applyOptionsLocked(), pendingOptions : ActivityOptions(105208839), mPackageName=com.sec.android.app.launcher, mAnimationType=1001, mStartX=583, mStartY=744, mWidth=272, mHeight=420
12-09 15:28:15.581  3740  5975 E ActivityManager: applyOptionsLocked: pendingOptions.getStartX()=583pendingOptions.getStartY()=744
12-09 15:28:15.581  3740  5975 D SamsungWindowManager: overridePendingAppTransitionCustomScaleUp, mNextAppTransitionStartX : 583, mNextAppTransitionStartY : 744, mNextAppTransitionStartWidth : 272, mNextAppTransitionStartHeight : 420
12-09 15:28:15.581  3740  5975 D ActivityManager: applyOptionsLocked, ANIM_CUSTOM_SCALE_UP, x : 583, y : 744, isHomeItem : false
12-09 15:28:15.581  3740  5975 D ActivityManager: applyOptionsLocked, ANIM_CUSTOM_SCALE_UP, task.getRootActivity() : ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87}, task.getTaskToReturnTo() : 1
12-09 15:28:15.581  3740  5975 D ActivityManager: setAppIconInfo(), x : 583, y : 744, width : 272, height : 420, isHomeItem : false
12-09 15:28:15.581  3740  5975 D MountService: getExternalStorageMountMode : 1
12-09 15:28:15.582  3740  5975 D MountService: getExternalStorageMountMode : 3
12-09 15:28:15.582  3740  5975 D MountService: getExternalStorageMountMode : final mountMode=1, uid : 10191, packageName : SampleGame.Android
12-09 15:28:15.585  3740  3766 D ViewRootImpl@28a682b[Android]: dispatchAttachedToWindow
12-09 15:28:15.586  3740  3766 V WindowManager: Relayout Window{280ae21d0 u0 Starting SampleGame.Android}: viewVisibility=0 req=1440x2464 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#830118 pfl=0x20011 wanim=0x1030001 vsysui=0x400 needsMenuKey=2 naviIconColor=0}
12-09 15:28:15.589  3151  3151 I SurfaceFlinger: id=65 createSurf (1x1),2 flag=404, Bndroid
12-09 15:28:15.591 29647 29647 E Zygote  : v2
12-09 15:28:15.591 29647 29647 I libpersona: KNOX_SDCARD checking this for 10191
12-09 15:28:15.591 29647 29647 I libpersona: KNOX_SDCARD not a persona
12-09 15:28:15.591  3740  5975 I ActivityManager: Start proc 29647:SampleGame.Android/u0a191 for activity SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity
12-09 15:28:15.592 29647 29647 E Zygote  : accessInfo : 0
12-09 15:28:15.592 29647 29647 W SELinux : SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0009, [-1 -1 -1 -1 0 1]
12-09 15:28:15.593 29647 29647 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=SampleGame.Android 
12-09 15:28:15.596 29647 29647 I art     : Late-enabling -Xcheck:jni
12-09 15:28:15.603  3740  3766 D ViewRootImpl@28a682b[Android]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 502159402496} surfaceGenerationChanged=true
12-09 15:28:15.604  5260  5260 D ViewRootImpl@220bc5b[LauncherActivity]: MSG_WINDOW_FOCUS_CHANGED 0
12-09 15:28:15.606  5260  5260 D SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
12-09 15:28:15.633 29647 29647 D TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
12-09 15:28:15.635  3740  3766 D WindowManager: finishDrawingWindow: Window{280ae21d0 u0 Starting SampleGame.Android} mDrawState=DRAW_PENDING
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.635  3740  3751 I ActivityManager: DSS on for SampleGame.Android and scale is 1.0
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.639  3740  3751 V WindowOrientationListener: OrientationSensorJudge.getProposedRotation, Rotation: -1
12-09 15:28:15.639  3740  3751 V WindowOrientationListener: OrientationSensorJudge.getProposedRotation, Rotation: -1
12-09 15:28:15.639  3740  3751 V WindowManager: rotationForOrientationLw(orient=-1, last=0); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.643  3740  3751 D GameManagerService: sem_perfomance_mode: 3
12-09 15:28:15.643  3740  3740 D GameManagerService: NotifyRunnable. pkg: SampleGame.Android, type: 4, isMinimized: false, isTunableApp: false
12-09 15:28:15.643  3740  3740 D GameManagerService: unexpected mPrevNotiType: -1
12-09 15:28:15.644  3740  3751 D SamsungWindowManager: createSamsungCustomAnimationLocked, mNextAppTransitionStartX : 583, mNextAppTransitionStartY : 744, mNextAppTransitionStartWidth : 272, mNextA [...]

2022-12-09 06:38 UTC, peppy commented
`SampleGame.Android` failing on device:

```
12-09 15:28:15.569  3740  5183 D ActivityTrigger: Activity is Triggerred in full screen 
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.570  3740  5183 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.570  3740  5183 D ActivityManager: moveToFront() : reason=startedActivity setFocusedActivity isAttached=true TaskRecord{bc5387ad0 #87 A=SampleGame.Android U=0 StackId=1 sz=1}
12-09 15:28:15.570  3740  5183 D ActivityManager: setFocusStackUnchecked: reason=startedActivity setFocusedActivity focusCandidate=ActivityStack{9ff40bad0 stackId=1, 2 tasks} caller=com.android.server.am.ActivityStack.moveToFront:874 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:2006 
12-09 15:28:15.570  3740  7737 D TelephonyManager: getAllCellInfo : Caller (PID / UID / TID): 3740 / 1000 / 7737
12-09 15:28:15.572  3740  5183 D InputDispatcher: Focused application set to: xxxx
12-09 15:28:15.572  3740  5183 D InputDispatcher: Focus left window: 5260
12-09 15:28:15.572  3740  5183 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{bc5387ad0 #87 A=SampleGame.Android U=0 StackId=1 sz=1} next=ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87} mFocusedStack=ActivityStack{9ff40bad0 stackId=1, 2 tasks}
12-09 15:28:15.573  3740  5183 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-09 15:28:15.573  3740  5183 D GameManagerService: sem_perfomance_mode: 3
12-09 15:28:15.575  3740  3766 D WindowManager: addWindow: android.view.ViewRootImpl$W@ceda488 displayId=0
12-09 15:28:15.576  3740  3766 D InputTransport: Input channel constructed: fd=330
12-09 15:28:15.576  3740  3766 D InputTransport: Input channel constructed: fd=425
12-09 15:28:15.576  3740  3766 D WindowManager: openInputChannel mInputChannel: 280ae21 Starting SampleGame.Android (server)
12-09 15:28:15.576  3740  3766 D ViewRootImpl@28a682b[Android]: setView = DecorView@45e6246[Android] touchMode=true
12-09 15:28:15.578  5260  5260 D Launcher: onPause, Launcher: 135272777
12-09 15:28:15.578  5260  5260 D Launcher.HomeView: onPause
12-09 15:28:15.578  5260  5260 D Launcher.Workspace: exitWidgetResizeMode. isClearResizeFrame is false
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.579  3740  3758 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.579  3740  5975 D ActivityManager: clearAppIconInfo()
12-09 15:28:15.580  3740  5975 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{974cbed0 #75 A=com.sec.android.app.launcher U=0 StackId=0 sz=1} next=ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87} mFocusedStack=ActivityStack{9ff40bad0 stackId=1, 2 tasks}
12-09 15:28:15.580  3740  5975 D ActivityManager: applyOptionsLocked(), pendingOptions : ActivityOptions(105208839), mPackageName=com.sec.android.app.launcher, mAnimationType=1001, mStartX=583, mStartY=744, mWidth=272, mHeight=420
12-09 15:28:15.581  3740  5975 E ActivityManager: applyOptionsLocked: pendingOptions.getStartX()=583pendingOptions.getStartY()=744
12-09 15:28:15.581  3740  5975 D SamsungWindowManager: overridePendingAppTransitionCustomScaleUp, mNextAppTransitionStartX : 583, mNextAppTransitionStartY : 744, mNextAppTransitionStartWidth : 272, mNextAppTransitionStartHeight : 420
12-09 15:28:15.581  3740  5975 D ActivityManager: applyOptionsLocked, ANIM_CUSTOM_SCALE_UP, x : 583, y : 744, isHomeItem : false
12-09 15:28:15.581  3740  5975 D ActivityManager: applyOptionsLocked, ANIM_CUSTOM_SCALE_UP, task.getRootActivity() : ActivityRecord{333536ed0 u0 SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity t87}, task.getTaskToReturnTo() : 1
12-09 15:28:15.581  3740  5975 D ActivityManager: setAppIconInfo(), x : 583, y : 744, width : 272, height : 420, isHomeItem : false
12-09 15:28:15.581  3740  5975 D MountService: getExternalStorageMountMode : 1
12-09 15:28:15.582  3740  5975 D MountService: getExternalStorageMountMode : 3
12-09 15:28:15.582  3740  5975 D MountService: getExternalStorageMountMode : final mountMode=1, uid : 10191, packageName : SampleGame.Android
12-09 15:28:15.585  3740  3766 D ViewRootImpl@28a682b[Android]: dispatchAttachedToWindow
12-09 15:28:15.586  3740  3766 V WindowManager: Relayout Window{280ae21d0 u0 Starting SampleGame.Android}: viewVisibility=0 req=1440x2464 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#830118 pfl=0x20011 wanim=0x1030001 vsysui=0x400 needsMenuKey=2 naviIconColor=0}
12-09 15:28:15.589  3151  3151 I SurfaceFlinger: id=65 createSurf (1x1),2 flag=404, Bndroid
12-09 15:28:15.591 29647 29647 E Zygote  : v2
12-09 15:28:15.591 29647 29647 I libpersona: KNOX_SDCARD checking this for 10191
12-09 15:28:15.591 29647 29647 I libpersona: KNOX_SDCARD not a persona
12-09 15:28:15.591  3740  5975 I ActivityManager: Start proc 29647:SampleGame.Android/u0a191 for activity SampleGame.Android/crc6442f6b31f4c7ca286.SampleGameActivity
12-09 15:28:15.592 29647 29647 E Zygote  : accessInfo : 0
12-09 15:28:15.592 29647 29647 W SELinux : SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0009, [-1 -1 -1 -1 0 1]
12-09 15:28:15.593 29647 29647 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=SampleGame.Android 
12-09 15:28:15.596 29647 29647 I art     : Late-enabling -Xcheck:jni
12-09 15:28:15.603  3740  3766 D ViewRootImpl@28a682b[Android]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 502159402496} surfaceGenerationChanged=true
12-09 15:28:15.604  5260  5260 D ViewRootImpl@220bc5b[LauncherActivity]: MSG_WINDOW_FOCUS_CHANGED 0
12-09 15:28:15.606  5260  5260 D SEM_CLIP_SemClipboardManager: isCocktailBarDisplayed : false
12-09 15:28:15.633 29647 29647 D TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
12-09 15:28:15.635  3740  3766 D WindowManager: finishDrawingWindow: Window{280ae21d0 u0 Starting SampleGame.Android} mDrawState=DRAW_PENDING
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.635  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.635  3740  3751 I ActivityManager: DSS on for SampleGame.Android and scale is 1.0
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.637  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.639  3740  3751 V WindowOrientationListener: OrientationSensorJudge.getProposedRotation, Rotation: -1
12-09 15:28:15.639  3740  3751 V WindowOrientationListener: OrientationSensorJudge.getProposedRotation, Rotation: -1
12-09 15:28:15.639  3740  3751 V WindowManager: rotationForOrientationLw(orient=-1, last=0); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: mCompatibilityFlags - 0
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: applicationDensity - 640
12-09 15:28:15.642  3740  3751 D CompatibilityInfo: applicationScale - 1.0
12-09 15:28:15.643  3740  3751 D GameManagerService: sem_perfomance_mode: 3
12-09 15:28:15.643  3740  3740 D GameManagerService: NotifyRunnable. pkg: SampleGame.Android, type: 4, isMinimized: false, isTunableApp: false
12-09 15:28:15.643  3740  3740 D GameManagerService: unexpected mPrevNotiType: -1
12-09 15:28:15.644  3740  3751 D SamsungWindowManager: createSamsungCustomAnimationLocked, mNextAppTransitionStartX : 583, mNextAppTransitionStartY : 744, mNextAppTransitionStartWidth : 272, mNextA [...]

2022-12-09 10:41 UTC, frenzibyte commented on osu.Framework.Android.props
> +    <!-- NullabilityInfoContextSupport is disabled by default for Android -->
Right I thought this was specific to mobile projects. Should be reworded to clarify that it's happening on mobile not just Android.

2022-12-09 19:06 UTC, Susko3 commented
@peppy from [your previous comment](https://github.com/ppy/osu-framework/pull/5080#issuecomment-1183967341), looks like fast deployment (only used in Debug configurations) doesn't work on your specific device. This is a [known issue](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#fast-deployment) on older devices.

Try applying this diff to disable fast deployment:
(Fast deployment stores files in persistent storage on the phone, so you might also need to manually uninstall the app for it to work properly.)

```diff
diff --git a/osu.Framework.Android.props b/osu.Framework.Android.props
index d29a2244e..71cc98e4e 100644
--- a/osu.Framework.Android.props
+++ b/osu.Framework.Android.props
@@ -7,5 +7,6 @@
     <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidMessageHandler</AndroidHttpClientHandlerType>
     <!-- NullabilityInfoContextSupport is disabled by default for Android -->
     <NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
+    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
   </PropertyGroup>
 </Project>
```

2022-12-11 04:52 UTC, huoyaoyuan commented on osu.Framework.Android.props
> +    <MandroidI18n>CJK;Mideast;Rare;West;Other;</MandroidI18n>
I'm not sure whether it's needed in osu. I just set the value as what project designer sets.
Maybe we can totally remove this.

2022-12-11 17:22 UTC, frenzibyte commented on osu.Framework.Android.props
> +    <MandroidI18n>CJK;Mideast;Rare;West;Other;</MandroidI18n>
As per a [discord discussion](https://discord.com/channels/188630481301012481/589331078574112768/1051260125643550880), let's remove these for now and see whether anything breaks (nothing happened on my end).

2022-12-12 06:16 UTC, peppy commented
> Try applying this diff to disable fast deployment: (Fast deployment stores files in persistent storage on the phone, so you might also need to manually uninstall the app for it to work properly.)
> 
> ```diff
> diff --git a/osu.Framework.Android.props b/osu.Framework.Android.props
> index d29a2244e..71cc98e4e 100644
> --- a/osu.Framework.Android.props
> +++ b/osu.Framework.Android.props
> @@ -7,5 +7,6 @@
>      <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidMessageHandler</AndroidHttpClientHandlerType>
>      <!-- NullabilityInfoContextSupport is disabled by default for Android -->
>      <NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
> +    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
>    </PropertyGroup>
>  </Project>
> ```

This worked. I've committed the change.

2022-12-12 06:18 UTC, peppy commented on osu.Framework.Android.props
> +    <MandroidI18n>CJK;Mideast;Rare;West;Other;</MandroidI18n>
I've removed these.

2022-12-12 06:18 UTC, peppy commented
This is fine from my end now.

2022-12-12 06:38 UTC, merged