Implements a dragging tolerance parameter for drawables.
ppy/osu-framework pull request #5083
Opened 2022-03-27 17:55 UTC by ekgame

Related PR: TODO.

This PR implements a dragging tolerance parameter for drawables. This change allows an object to define how sensitive it should be to dragging.

Generally, most draggable elements should have some room for error where the mouse can move just a bit and the action should still be considered a click. However, in some cases it's desirable to handle the drag right away, ex.: for small adjustments in an editor.

2022-03-27 18:06 UTC, bdach requested changes
Not sure we want this. Tests also missing.

2022-03-27 18:06 UTC, bdach commented on osu.Framework/Graphics/Containers/ScrollContainer.cs
> +            dragBlocksClick |= Math.Abs(e.MouseDownPosition[ScrollDim] - e.MousePosition[ScrollDim]) > Content.DragTolerance;
Both usages of `MouseButtonEventManager.ClickDragDistance` were replaced with `Content.DragTolerance` but `ClickDragDistance` is not removed or marked as obsolete - as it should be if nothing reads it anymore, to avoid confusing framework consumers.

2022-03-27 18:33 UTC, ekgame commented on osu.Framework/Graphics/Containers/ScrollContainer.cs
> +            dragBlocksClick |= Math.Abs(e.MouseDownPosition[ScrollDim] - e.MousePosition[ScrollDim]) > Content.DragTolerance;
Good catch, removed.

2022-03-27 18:34 UTC, ekgame commented
I'll wait for more opinions before adding tests.

2022-03-28 07:23 UTC, smoogipoo commented
If this is to be considered, I would be interested to know how other frameworks (WinForms/WPF/JS) handle this.

The MDN [example](https://jsfiddle.net/radonirinamaminiaina/zfnj5rv4/) for drag has a similar tolerance, so we're not doing something outlandish compared to other frameworks already. Is there a way to customise this behaviour in JS?

2022-04-02 21:39 UTC, jai-x commented
I don't believe this is user configurable in Javascript and is defined by the browser.

For reference here are the minimum threshold values for a drag event in Chrome:
https://github.com/chromium/chromium/blob/7bcf5f930c9e6795b8d6539129b01fa5f43c928c/third_party/blink/renderer/core/input/mouse_event_manager.cc#L121-L130

2022-04-04 03:32 UTC, peppy commented
I'm open to reducing the leniences to roughly match what chrome uses for testing, but do consider that our use case is slightly different (with tablet users being more dominant in the user base).

I don't think this PR is something we want though.

If others agree, I'm open to reducing the leniences and see if people complain. Maybe half way between what we are using and what chrome has (something like 6 or 7px).

2022-04-04 03:32 UTC, closed without merging