Implement screen event args and add destination screen event for `OnExiting`
ppy/osu-framework pull request #5095
Opened 2022-04-08 00:01 UTC by Joehuu

2022-04-08 00:06 UTC, PercyDan54 commented on osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
> +            public IScreen DestinationIs;
This reads weird, I think this should be just `Destination`

2022-04-08 02:25 UTC, peppy commented
Before even getting into review: this is a *super* breaking change that will break 100% of framework projects. We either want backwards compatibility / obsolescence or a very good reason not to require that.

Can you start by stating the use case for this change?

2022-04-08 04:09 UTC, bdach commented
The use case is the linked game side PR, as far as I can tell.

2022-04-08 04:11 UTC, peppy commented
I saw that, but I'd prefer a PR that has this large an effect explains in the description the goals.

2022-04-08 04:13 UTC, peppy requested changes

2022-04-08 04:13 UTC, peppy commented on osu.Framework/Screens/ScreenResumeEvent.cs
> +        /// The next Screen.
Is this wrong?

2022-04-08 04:13 UTC, peppy commented on osu.Framework/Screens/ScreenSuspendEvent.cs
> +        /// The new Screen.
All of these xmldoc seem randomly chosen and don't make much sense.

2022-04-08 04:13 UTC, peppy commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
Is there any reason this can't have `Last` and `Next` and act as the event which is used for all of the flows? I'm not sure we need to complicate things but having different subclassed types when they all have the same available properties.

2022-04-08 23:05 UTC, Joehuu commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
I don't think that will work out. What will `Next` be on `OnEntering` / `OnResuming` and `Last` be on `OnExiting`/`OnSuspending`? They will also have different xmldoc which I will improve.

`OnExiting` is also a special case where it is called multiple times (e.g. Editor -> Song Select -> Main Menu) then `Game` window exiting, which is why in this PR, I added the `Destination` property which cannot be used with the other flows.

2022-04-08 23:05 UTC, Joehuu commented on osu.Framework/Screens/ScreenResumeEvent.cs
> +        /// The next Screen.
I just copied the existing xmldoc, will improve.

2022-04-12 22:34 UTC, frenzibyte reviewed
> Can you start by stating the use case for this change?

@peppy I think the use case, as I understand it, can be shortened to the following: 

A screen wants to interrupt a multiple exiting operation (caused by `MakeCurrent` on a far behind screen) to display a "confirm exit" dialog. The blocking screen is unaware of the destination screen, therefore it can't continue the exiting chain properly without exposing the destination screen as done in this PR.

This seems fine to me as long as obsoletions are in place and xmldocs are clear enough (right now `Next` and `Destination` feel slightly confusing together).

2022-04-12 22:34 UTC, frenzibyte commented on osu.Framework/Screens/ScreenExitEvent.cs
> +        /// The final <see cref="IScreen"/> of an exit operation.
```suggestion
        /// The final <see cref="IScreen"/> of this exit operation.
```
I think `this` reads better? Unsure, reading this at first glance made me question the difference between `Next` and `Destination`.

Maybe should explicitly clarify in `Destination` that it's different from `Next` when this is a multiple exiting operations (i.e. from `MakeCurrent`).

2022-04-12 22:34 UTC, frenzibyte commented on osu.Framework/Screens/Screen.cs
>          }
In regards to obsoletion, the old method signatures can still remain but obsoleted, with the new event-based variants still redirecting to them if not overriden.
```csharp
#pragma warning disable CS0618
        public virtual void OnEntering(ScreenEnterEvent e) => OnEntering(e.Last);

        public virtual bool OnExiting(ScreenExitEvent e) => OnExiting(e.Next);

        public virtual void OnResuming(ScreenResumeEvent e) => OnResuming(e.Last);

        public virtual void OnSuspending(ScreenSuspendEvent e) => OnSuspending(e.Next);
#pragma warning restore CS0618

        [Obsolete("Override OnEntering(ScreenEnterEvent) instead.")] // Can be removed 20221013
        public virtual void OnEntering(IScreen last)
        {
        }

        [Obsolete("Override OnExiting(ScreenExitEvent) instead.")] // Can be removed 20221013
        public virtual bool OnExiting(IScreen next) => false;

        [Obsolete("Override OnResuming(ScreenResumeEvent) instead.")] // Can be removed 20221013
        public virtual void OnResuming(IScreen last)
        {
        }

        [Obsolete("Override OnSuspending(ScreenSuspendEvent) instead.")] // Can be removed 20221013
        public virtual void OnSuspending(IScreen next)
        {
        }
```

This will cover 99% of all use cases, with the only remaining exceptions being the special logic in `OnlinePlayScreen` which forwards screen event calls to its own screen stack. I think it should be fine breaking just that specific case, rather than adding this obsoletion logic in `IScreen` as well.

2022-04-13 02:14 UTC, peppy commented on osu.Framework/Screens/Screen.cs
>          }
Looks fine, feel free to commit this to the PR.

2022-04-13 02:27 UTC, peppy requested changes

2022-04-13 02:27 UTC, peppy commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
> I don't think that will work out. What will `Next` be on `OnEntering` / `OnResuming` and `Last` be on `OnExiting`/`OnSuspending`? They will also have different xmldoc which I will improve.

The answers to these should be obvious. I'm not sure how to answer. `OnEntering` is *entering* a screen. That screen that is entering is the next screen displayed.

When exiting, the last screen is exiting. So it should be `Last`.

If this doesn't make sense it's going to be faster for me to apply code changes, which I can do if you'd prefer.

I'd also rename this event to `ScreenTransitionEvent` to match the actual usage.

> `OnExiting` is also a special case where it can be called multiple times (e.g. Editor -> Song Select -> Main Menu) then `Game` window exiting, which is why in this PR, I added the `Destination` property to let the exit dialog know the final screen, which cannot be used with the other flows.

That's fine. You can make a separate event type for exit specifically.

2022-04-13 02:30 UTC, peppy commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
@smoogipoo at a conceptual level can you confirm you agree with this? ie. all these events should use a shared

```chspar
event ScreenTransitionEvent
{
    IScreen Last;
    IScreen Next;
}```

2022-04-13 02:57 UTC, Joehuu commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
So it's just equivalent to `this`, right? In that comment, I wanted to imply that adding those are redundant but wasn't clear enough.

You can apply the changes yourself if you think that structure is okay.

2022-04-13 02:59 UTC, peppy commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
The main goal is that it greatly simplifies explaining the last and next properties, or from the flip-side, understanding them during implementation. Dealing with the same event for each of the overridden methods rather than having to double-check each time is a positive in my eyes.

2022-04-13 03:28 UTC, smoogipoo commented on osu.Framework/Screens/ScreenEvent.cs
> +    public class ScreenEvent
> at a conceptual level can you confirm you agree with this

Sounds good to me

2022-04-13 21:56 UTC, frenzibyte approved these changes

2022-04-14 08:11 UTC, smoogipoo approved these changes
Lgtm

2022-04-14 09:12 UTC, peppy commented
Hold off momentarily on this one. I was reviewing the osu!-side change today and I'm still not 100% it's the correct way to be handling it (and if it's the only reason to be adding these events then it may be a blocking factor).

2022-04-14 09:13 UTC, smoogipoo commented
Awaiting your review, all good.

2022-04-20 05:42 UTC, peppy commented
While I think that the `PerformFromScreen` solution is likely better for the original use case this change had, I think adding these `EventArgs` is also beneficial in terms of code quality. I can imaging adding further properties in the future. Let's get this in 👍 .

2022-04-20 05:42 UTC, peppy approved these changes

2022-04-20 05:52 UTC, merged

2022-04-21 20:26 UTC, bdach commented
Added a [breaking change note](https://github.com/ppy/osu-framework/wiki/Breaking-changes#iscreen-navigation-interface-methods-now-receive-an-event-args-structure) about this on the wiki.