Improve `CurrentDisplayMode` logic in `SDL2DesktopWindow`
ppy/osu-framework pull request #5103
Opened 2022-04-15 00:42 UTC by Susko3

Should fix https://github.com/ppy/osu/issues/17804.

The problem boils down to differences between [`SDL_GetWindowDisplayMode`](https://wiki.libsdl.org/SDL_GetWindowDisplayMode) and [`SDL_GetCurrentDisplayMode`](https://wiki.libsdl.org/SDL_GetCurrentDisplayMode). The former (roughly) gives the display mode that would be used if the window were set to fullscreen (without changing the mode). So in windowed, it could match a resolution lower than the native one (and presumably a high refresh rate display supports only 60 Hz on lower resolutions).

For that reason, we use `SDL_GetCurrentDisplayMode` in windowed modes which will give us the correct (desktop) mode.

As noted by the TODOs, some things are still broken.
- `CurrentDisplayMode` will always have an invalid index (-1) (not really important)
- `CurrentDisplayBindable` is really broken (see 0e7b66600fc20450e63bd092949fe612d82b6c53) (out of scope for this PR)
   - [`Display.Equals()`](https://github.com/ppy/osu-framework/blob/189633892af4b798743fc4365d767120affc11ec/osu.Framework/Platform/Display.cs#L47-L53) only checking the index probably doesn't help.

`CurrentDisplayMode` is only used in

https://github.com/ppy/osu-framework/blob/3f707df24d2efbc1ff44ed80c55d445911df8091/osu.Framework/Platform/GameHost.cs#L1030

so this should be a safe change. (No usages osu!-side.)

---

Tested on:
- [x] Windows
- [ ] Linux
- [ ] macOS

For testing, you should run the test four times, each time starting the visual tests in a different `WindowMode` and running trough all tests. For fullscreen, test twice, once with `FrameworkSetting.SizeFullscreen` set to default (`9999x9999`) and once with non-native resolution (could also test with resolution set to native).

2022-04-15 14:57 UTC, respektive commented
I ran the tests on Linux and they seem to be working fine on my machine.

Just got one question. When the resolution in fullscreen is set to `1280x720` the refresh rate is set to 60, because that's the highest my monitor supports on that resolution. Switching then to `1920x1080` will keep the refresh rate at 60 even though there are higher ones available. Is that the intended behaviour?

2022-04-15 15:29 UTC, Susko3 commented
> Just got one question. When the resolution in fullscreen is set to `1280x720` the refresh rate is set to 60, because that's the highest my monitor supports on that resolution. Switching then to `1920x1080` will keep the refresh rate at 60 even though there are higher ones available. Is that the intended behaviour?

It's intended, as we're getting the closest mode with the current refresh rate:

https://github.com/ppy/osu-framework/blob/0ef012aefcfbfec8708d21e95326fa715aa44603/osu.Framework/Platform/SDL2DesktopWindow.cs#L1078

I guess we don't have a framework setting for refresh rate...

---

If you go
- fullscreen
- 1280x720
- 1920x1080 (this should be 60 Hz)
- switch windowed or borderless (you should have >60 Hz)
- switch back to fullscreen
- you should have 1920x1080 (>60 Hz)

Is that correct, or are you still getting 60 fps?

2022-04-15 15:52 UTC, respektive commented
> If you go
> 
>     * fullscreen
> 
>     * 1280x720
> 
>     * 1920x1080 (this should be 60 Hz)
> 
>     * switch windowed or borderless (you should have >60 Hz)
> 
>     * switch back to fullscreen
> 
>     * you should have 1920x1080 (>60 Hz)
> 
> 
> Is that correct, or are you still getting 60 fps?

I just wanted to confirm that this is the case, but now I am facing a really strange error. Everytime i switch from 1280x720 to 1920x1080 my monitor gets completely disabled now. This is the output in the console.

```
[runtime] 2022-04-15 15:41:30 [verbose]: Updated display mode (from fullscreen) to: Size: {Width=1280, Height=720}, BitsPerPixel: 32, RefreshRate: 60, Format: SDL_PIXELFORMAT_RGB888, Index: -1, DisplayIndex: 0
[runtime] 2022-04-15 15:41:36 [debug]: MouseDownEvent(Left) handled by BasicScrollContainer.
[runtime] 2022-04-15 15:41:36 [debug]: ClickEvent(Left) handled by "set fullscreen to 1920x1080" SingleStepButton.
[runtime] 2022-04-15 15:41:36 [debug]: MouseClick handled by "set fullscreen to 1920x1080" SingleStepButton.
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x0
  Serial number of failed request:  3543
  Current serial number in output stream:  3543
```
Also gonna attach a screenshot of xrandr and my display settings once the monitor gets disabled.

![](https://pek.li/7l9zpm.png)

2022-04-15 16:38 UTC, respektive commented
> Is that correct, or are you still getting 60 fps?

By running the tests on my second monitor I was able to confirm that these steps do exactly what they're expected to do.

The issue described in the comment above only happens on my main monitor for some reason. (and weirdly enough just a few hours ago I was able to run the tests just fine without this issue and a reboot didn't fix it either)

2022-04-15 17:58 UTC, bdach commented
We can't do anything with the error above in this repository, that is a failure somewhere in upstream (SDL).

2022-04-16 01:43 UTC, frenzibyte reviewed
From a quick skim at diff, haven't tested yet.

2022-04-16 01:43 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +    [System.ComponentModel.Description("For complete validation, this test should run be with different WindowModes at startup, and with different resolutions in Fullscreen")]
Can be vastly shortened:
```suggestion
    [System.ComponentModel.Description("For complete validation, run this with different window modes and resolutions")]
```

2022-04-16 01:43 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                    Logger.Log($"Stored displayIndex ({displayIndex}) doesn't match real index ({localIndex})");
```suggestion
                    Logger.Log($"Stored display index ({displayIndex}) doesn't match current index ({localIndex})");
```

2022-04-16 01:43 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                    break;
I think it would be better adding an explanation why this could fall back to query by desktop (in fullscreen case) and query by fullscreen (in non-fullscreen case).

2022-04-16 01:43 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                case WindowState.Minimised:
```suggestion
                default:
```

2022-04-16 14:31 UTC, bdach reviewed
baffled by this diff

2022-04-16 14:31 UTC, bdach commented on osu.Framework.Tests/Visual/Drawables/TestSceneUpdateBeforeDraw.cs
> +    [System.ComponentModel.Description("Tests whether drawable updates occur before drawing.")]
Not sure why this is being touched in this diff at all. Yes the class may be wrong but that's not in scope of this pull.

2022-04-16 14:31 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +            }
Why is this here? The entire test fixture is ignored already, is it not?

2022-04-16 14:31 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +            AddAssert("Size matches actual display resolution", () => displayMode.Size == window.Displays.ElementAt(displayMode.DisplayIndex).Bounds.Size);
I'm deeply confused by all of this. Why is the check against `currentDisplay.Bounds.Size` conditional, but the check against `window.Displays.ElementAt(displayMode.DisplayIndex).Bounds.Size)` is not conditional?

Also I find `"Size matches fullscreen resolution"` as a step name really misleading. What this is checking is that the config matches the actual fullscreen size, no? The word "config" is really missing there.

2022-04-16 14:31 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +            // && left.Index == right.Index
Aside but `Index` should really be renamed to `ModeIndex` or similar. Having both `Index` and `DisplayIndex` in one class is not great.

2022-04-16 14:31 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                    Logger.Log($"Stored displayIndex ({displayIndex}) doesn't match real index ({localIndex})");
Why is this being logged even?

2022-04-16 14:31 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex, -1);
Why are both branches here passing -1 as the mode?

2022-04-16 17:10 UTC, Susko3 commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex, -1);
Would you rather have it so one of the branches sets `-2`?
I don't see how it makes a difference, as display modes should never be considered equal based on the index alone.

Plus, the mode index is a leftover from osuTK, SDL doesn't have the mode index in it's `SDL_DisplayMode` struct. It should probably be removed from the framework struct, as it gives no useful information.

2022-04-16 17:12 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex, -1);
Would agree with removing it if it's useless. And if it doesn't take too many changed files then I would be in favour of removing it now rather than later.

2022-04-16 17:13 UTC, bdach commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex, -1);
> Plus, the mode index is a leftover from osuTK,

Well this explains a lot - but then, what is this todo about?

https://github.com/ppy/osu-framework/blob/e9726bb51d90434a6643e7688227f8c8e951c109/osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs#L141-L142

The above todo is being added in this pull, mind you.

2022-04-16 17:20 UTC, Susko3 commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                    Logger.Log($"Stored displayIndex ({displayIndex}) doesn't match real index ({localIndex})");
It is somewhat of a debug log that was added as I was working on this. But since it's still broken, I left it in to show that it's broken.

2022-04-16 20:26 UTC, frenzibyte requested changes
Looks to work well on macOS. Left a few notes on code, seems fine otherwise.

2022-04-16 20:26 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        // if we failed to get the fullscreen mode, query the desktop mode so that we always have an up-to-date display mode.
I meant explaining how this could possibly happen, but if there is no possible explanation then it can be left with no comments rather than adding redundant ones.

2022-04-16 20:26 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                }
I think `Updated display mode to fullscreen resolution` reads better than `Updated display mode (from fullscreen) to` (also simplifies the mode print to `widthxheight@rate`, rather than the full `ToString` implementation):
```suggestion
                if (queryFullscreenMode)
                {
                    if (SDL.SDL_GetWindowDisplayMode(SDLWindowHandle, out var mode) >= 0)
                    {
                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex);
                        Logger.Log($"Updated display mode to fullscreen resolution: {mode.w}x{mode.h}@{mode.refresh_rate}");
                        return true;
                    }

                    Logger.Log($"Failed to get fullscreen display mode. Display index: {localIndex}. SDL error: {SDL.SDL_GetError()}", level: LogLevel.Error);
                    return false;
                }
                else
                {
                    if (SDL.SDL_GetCurrentDisplayMode(localIndex, out var mode) >= 0)
                    {
                        currentDisplayMode.Value = mode.ToDisplayMode(localIndex);
                        Logger.Log($"Updated display mode to desktop resolution: {mode.w}x{mode.h}@{mode.refresh_rate}");
                        return true;
                    }

                    Logger.Log($"Failed to get desktop display mode. Display index: {localIndex}. SDL error: {SDL.SDL_GetError()}", level: LogLevel.Error);
                    return false;
                }
```

2022-04-16 20:31 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                    Logger.Log($"Stored displayIndex ({displayIndex}) doesn't match real index ({localIndex})");
I feel this is warranting an issue thread instead of this log at best. With an inline comment on top of the display index query mentioning why it isn't using the stored one.

2022-04-17 20:33 UTC, Susko3 commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                }
Decided to keep `Format` as it may be useful in debugging issues where the wrong display mode gets set.

2022-04-17 20:37 UTC, Susko3 commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +                    setFullscreenResolution(1920, 1080);
Went with `Display.FindDisplayMode`, with the resolution resolved on test startup. If it was dynamically resolved, it would be hard to explain in text.

This will break if testing on another display, so the tests should be reloaded in that case.

2022-04-17 20:38 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +                        Logger.Log($"Updated display mode to desktop resolution: {mode.w}x{mode.h}@{mode.refresh_rate}, {currentDisplayMode.Value.Format}");
```suggestion
                        Logger.Log($"Updated display mode to fullscreen resolution: {mode.w}x{mode.h}@{mode.refresh_rate}, {currentDisplayMode.Value.Format}");
```

2022-04-17 20:50 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs
> +                    setFullscreenResolution(1920, 1080);
You could avoid reloading it by performing the find display mode logic as part of the step itself:
```csharp
void setFullscreenResolution(Size resolution)
{
    AddStep($"set resolution near {resolution.Width}x{resolution.Height}", () => currentDisplay.FindDisplayMode(resolution));
}
```

But either-or works I suppose.

2022-04-20 05:31 UTC, peppy commented
The code changes look roughly sane, but running the test scene destroyed macOS. I ended up with my second monitor thinking it was in a different place to where it should be, and an assertion failure:

```csharp
-framework/osu.Framework.Tests/bin/Debug/net6.0/osu.Framework.Tests
[runtime] 2022-04-20 05:27:21 [verbose]: GL Initialized
[runtime] 2022-04-20 05:27:21 [verbose]: GL Version:                 2.1 ATI-4.8.13
[runtime] 2022-04-20 05:27:21 [verbose]: GL Renderer:                AMD Radeon Pro 580X OpenGL Engine
[runtime] 2022-04-20 05:27:21 [verbose]: GL Shader Language version: 1.20
[runtime] 2022-04-20 05:27:21 [verbose]: GL Vendor:                  ATI Technologies Inc.
[runtime] 2022-04-20 05:27:21 [verbose]: GL Extensions:              GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
[runtime] 2022-04-20 05:27:21 [verbose]: Stored display index (-1) doesn't match current index (0)
[runtime] 2022-04-20 05:27:21 [verbose]: Updated display mode to desktop resolution: 2560x1440@144, SDL_PIXELFORMAT_ARGB8888
[runtime] 2022-04-20 05:27:21 [verbose]: Host execution state changed to Running
[runtime] 2022-04-20 05:27:21 [verbose]: Execution mode changed to MultiThreaded
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font Roboto-Regular...
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font FontAwesome-Solid...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font FontAwesome-Solid!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font FontAwesome-Regular...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font FontAwesome-Regular!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font FontAwesome-Brands...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font FontAwesome-Brands!
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font Roboto-Regular!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font Roboto-RegularItalic...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font Roboto-RegularItalic!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font Roboto-Bold...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font Roboto-Bold!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font Roboto-BoldItalic...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font Roboto-BoldItalic!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font RobotoCondensed-Regular...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font RobotoCondensed-Regular!
[runtime] 2022-04-20 05:27:22 [debug]: Loading Font RobotoCondensed-Bold...
[runtime] 2022-04-20 05:27:22 [debug]: Loaded Font RobotoCondensed-Bold!
[runtime] 2022-04-20 05:27:22 [verbose]: 🔈 BASS initialised
[runtime] 2022-04-20 05:27:22 [verbose]: BASS version:           2.4.16.7
[runtime] 2022-04-20 05:27:22 [verbose]: BASS FX version:        2.4.12.6
[runtime] 2022-04-20 05:27:22 [verbose]: BASS MIX version:       2.4.11.1
[runtime] 2022-04-20 05:27:22 [verbose]: Device:                 Default
[runtime] 2022-04-20 05:27:22 [verbose]: Driver:
[runtime] 2022-04-20 05:27:22 [verbose]: Update period:          5 ms
[runtime] 2022-04-20 05:27:22 [verbose]: Device buffer length:   -1 ms
[runtime] 2022-04-20 05:27:22 [verbose]: Playback buffer length: 100 ms
[performance] 2022-04-20 05:27:22 [verbose]: TextureAtlas initialised (1024x1024)
[runtime] 2022-04-20 05:27:23 [verbose]: 🔸 Step #2 DisplayModeSanity()
[runtime] 2022-04-20 05:27:23 [verbose]: 💨 DisplayMode(TestSceneDisplayMode) DisplayModeSanity()
[runtime] 2022-04-20 05:27:23 [verbose]: 🔸 Step #3 mode has valid DisplayIndex
[runtime] 2022-04-20 05:27:24 [debug]: MouseDownEvent(Left) handled by BasicScrollContainer.
[runtime] 2022-04-20 05:27:29 [debug]: MouseDownEvent(Left) handled by BasicScrollContainer.
[runtime] 2022-04-20 05:27:33 [debug]: ClickEvent(Left) handled by BasicCheckbox.
[runtime] 2022-04-20 05:27:33 [debug]: MouseClick handled by BasicCheckbox.
[runtime] 2022-04-20 05:27:34 [verbose]: 🔸 Step #2 DisplayModeSanity()
[runtime] 2022-04-20 05:27:34 [verbose]: 💨 DisplayMode(TestSceneDisplayMode) DisplayModeSanity()
[runtime] 2022-04-20 05:27:34 [verbose]: 🔸 Step #3 mode has valid DisplayIndex
[runtime] 2022-04-20 05:27:34 [verbose]: 🔸 Step #4 DisplayIndex matches display
[runtime] 2022-04-20 05:27:34 [verbose]: 🔸 Step #5 display has current mode
[runtime] 2022-04-20 05:27:35 [verbose]: 🔸 Step #6 mode has valid RefreshRate
[runtime] 2022-04-20 05:27:35 [verbose]: 🔸 Step #7 Size matches bindable display resolution
[runtime] 2022-04-20 05:27:35 [verbose]: 🔸 Step #8 Size matches actual display resolution
[runtime] 2022-04-20 05:27:35 [verbose]: 🔸 Step #9 DisplayModeSanity(Windowed)
[runtime] 2022-04-20 05:27:35 [verbose]: 💨 DisplayMode(TestSceneDisplayMode) DisplayModeSanity(Windowed)
[runtime] 2022-04-20 05:27:35 [verbose]: 🔸 Step #10 change to Windowed
[runtime] 2022-04-20 05:27:36 [verbose]: 🔸 Step #11 DisplayIndex matches display
[runtime] 2022-04-20 05: [...]

2022-04-20 07:26 UTC, Susko3 commented
```cs
[runtime] 2022-04-20 05:27:38 [verbose]: 🔸 Step #25 set fullscreen to 9999x9999
[runtime] 2022-04-20 05:27:39 [verbose]: 🔸 Step #26 wait for resolution change 0/5
[runtime] 2022-04-20 05:27:39 [verbose]: ✔️ 5 repetitions
[runtime] 2022-04-20 05:27:40 [verbose]: Updated display mode to fullscreen resolution: 2560x1440@144, SDL_PIXELFORMAT_ARGB8888
```

Looks like the display mode is updated after "wait for resolution change". Could be because your monitor/SDL is taking a lot of time to switch to fullscreen. [Increase the delay](https://github.com/ppy/osu-framework/blob/90238117519cdbb3e32160e834034fdbb890cbf6/osu.Framework.Tests/Visual/Platform/TestSceneDisplayMode.cs#L163) or try running the steps manually.

2022-04-22 02:47 UTC, peppy commented
Running through manually seems to kind of work? But it says it's 1280x720 and isn't (is running 2560x1440) - is this intended?

![Discord PTB 2022-04-22 at 02 47 26](https://user-images.githubusercontent.com/191335/164586292-8f7e5c9a-9de1-4bd8-b8c5-c855b4838cf0.png)

2022-04-22 15:58 UTC, Susko3 commented
That's really strange. Weird how the tests passed, looks like the internal SDL state got messed up -- as both the current mode and display have the inaccurate resolution. (Or maybe framework didn't fully sync state with SDL.)

Interesting how the client size is correct, will add a step that checks that client size matches.

Anyways, fixing the resolution mismatch / fullscreen resolution not working is out of scope for this PR.

2022-04-26 03:49 UTC, peppy approved these changes

2022-04-26 19:09 UTC, bdach commented
@frenzibyte fine to dismiss your review here? Blocking automerge right now.

2022-04-26 19:31 UTC, merged