Optimise operations of Streams
ppy/osu-framework pull request #5140
Opened 2022-04-29 09:19 UTC by huoyaoyuan

- Override `Span` based write methods for derived streams since they are preferred in many library code.
- Optimise the extension methods, which are the main way we access streams in osu. Reduce allocations and copies.

Not touching some cases like TcpIpc, because it should be a rare path. It's too bothersome to maximise performance everywhere.

2022-04-29 09:23 UTC, huoyaoyuan commented on osu.Framework/Audio/Track/TrackBass.cs
> +            }
I have a total rewrite of AsyncBufferStream to favor the performance of FileStream, but it requires .NET 6. I tend to left it as is now.

2022-04-29 09:23 UTC, huoyaoyuan commented on osu.Framework/IO/Stores/RawCachingGlyphStore.cs
> +                }
I originally want to add a ReadToFulFill extension method, but in osu we generally use the extension methods only. Since it's planned for .NET 7, and after investigating the access pattern in game, I think it's not worthy for new extension methods.

2022-04-29 09:23 UTC, huoyaoyuan commented on osu.Framework/IO/Stores/RawCachingGlyphStore.cs
> +            byte[] readBuffer = ArrayPool<byte>.Shared.Rent(characterByteRegion);
Texture is somehow hot, so I choose to use array pool here.

2022-04-29 22:26 UTC, bdach commented
No benchmarking results whatsoever here, profile snapshots, anything? I'm definitely not going to attempt judging whether these optimisations actually optimise anything without looking at a prepared benchmark. I'll review the code, but I still want that to be backed by actual performance numbers.

2022-04-29 22:51 UTC, bdach commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +            if (!dataStream.CanSeek) return 0;
Not sure what these sorts of changes are doing in an "optimisation" PR but ok.

2022-04-29 22:51 UTC, bdach commented on osu.Framework/Audio/Track/TrackBass.cs
> +                    // Is it benenitial to buffer over OS and .NET file buffering?
I'm not sure what this comment-question is supposed to be achieving. Is this apparently going to get replaced with net6, or what's the deal here? If it's getting replaced then this should just be a TODO saying so rather than a cryptic question.

2022-04-29 22:51 UTC, bdach commented on osu.Framework/Extensions/StreamExtensions.cs
> +                remaining = remaining[bytesRead..];
Not sure we have universal agreement on adopting range syntax. Maybe best to call `.Slice()` for the time being.

2022-04-30 01:44 UTC, peppy commented
We do have some benchmark coverage of streams already, but there are some changes in this PR which I'm not sure are covered (which should be if they aren't) like the texture retrieval.

As above, would appreciate benchmark run results as a starting point.

2022-04-30 06:28 UTC, huoyaoyuan commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +            if (!dataStream.CanSeek) return 0;
This is actually "correction". Non seekable stream throws for Length.

2022-04-30 06:30 UTC, huoyaoyuan commented on osu.Framework/Extensions/StreamExtensions.cs
> +                remaining = remaining[bytesRead..];
It is already used in some places.

2022-04-30 06:59 UTC, huoyaoyuan commented
Benchmark added for extension methods. Since the code patterns are similar, I'm only testing for sync path.

PR:
|              Method |  Length |         Mean |        Error |       StdDev |    Gen 0 |    Gen 1 |    Gen 2 |   Allocated |
|-------------------- |-------- |-------------:|-------------:|-------------:|---------:|---------:|---------:|------------:|
| ReadAllBytesToArray |     100 |     20.43 ns |     0.471 ns |     0.628 ns |   0.0153 |        - |        - |       128 B |
| ReadAllBytesToArray |   10000 |    438.81 ns |     8.662 ns |    16.481 ns |   1.1973 |   0.0424 |        - |    10,024 B |
| ReadAllBytesToArray | 1000000 | 95,501.93 ns | 2,396.354 ns | 6,990.276 ns | 175.5371 | 175.4150 | 175.4150 | 1,000,079 B |

master:
|              Method |  Length |         Mean |       Error |       StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|-------------------- |-------- |-------------:|------------:|-------------:|---------:|---------:|---------:|----------:|
| ReadAllBytesToArray |     100 |     488.5 ns |     9.46 ns |     10.13 ns |   1.9798 |   0.0010 |        - |     16 KB |
| ReadAllBytesToArray |   10000 |   1,333.7 ns |    25.77 ns |     25.31 ns |   3.1643 |   0.1888 |        - |     26 KB |
| ReadAllBytesToArray | 1000000 | 158,213.4 ns | 5,924.38 ns | 17,187.69 ns | 202.1484 | 199.7070 | 199.7070 |    993 KB |

Extremely improves small streams, since the 16KB buffer allocation is massive. Note that 16KB array belongs to small object heap, and will add significant GC pressure. 
For large streams, the performance is ~1.5x by saving a copy.

2022-04-30 07:05 UTC, huoyaoyuan commented
The texture retrieval one is more like a clean up & correction. Reading stream in a loop is correct pattern for Stream contract. Moving the buffer from field to array pool helps enabling concurrency.

2022-04-30 07:11 UTC, huoyaoyuan commented on osu.Framework/Audio/Track/TrackBass.cs
> +                    // Is it benenitial to buffer over OS and .NET file buffering?
I wrote this before I constructed the .NET 6 rewrite. Yes, it could be a TODO here.

2022-04-30 13:21 UTC, huoyaoyuan commented
The title of this PR would be "clean up & optimisation". I wrote this mainly for clean up. Performance is improved by the way since redundant copy is eliminated.

2022-05-02 07:15 UTC, peppy requested changes

2022-05-02 07:15 UTC, peppy commented on osu.Framework/Extensions/StreamExtensions.cs
> +                remaining = remaining[bytesRead..];
With the naming of the variable as `remaining`, this code is absolutely unreadable to my eyes. I'm not sure on a better name yet, but just putting that out there.

2022-05-02 07:15 UTC, peppy commented on osu.Framework/IO/Stores/RawCachingGlyphStore.cs
> +                    buffer = buffer[bytesRead..];
As above, I don't know how to read this. Having this variable called `buffer` sourced from `readBuffer` makes this code read very badly IMHO.

2022-05-02 07:26 UTC, bdach commented
Also just to go back to this for a second:

> Moving the buffer from field to array pool helps enabling concurrency.

I'm not sure how this is helping to "enable concurrency". `RawCachingGlyphStore.createTextureUpload()` is being called in one place only - namely `RawCachingGlyphStore.LoadCharacter()`, which already takes a lock on `pageLookup`. How is concurrency relevant in this context?

2022-05-02 07:28 UTC, peppy commented
For what it's worth I'm currently running benchmarks on the font store as I am also not sure whether the array pool usage is an improvement without it.

2022-05-02 07:36 UTC, huoyaoyuan commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +            if (!dataStream.CanSeek) return 0;
I think it's better to mark it `internal`. This class is quite tighten with BASS, and not useful elsewhere.

2022-05-02 07:36 UTC, peppy commented
Master:


|                   Method | FetchCount |           Mean |        Error |       StdDev | Ratio |     Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|------------------------- |----------- |---------------:|-------------:|-------------:|------:|----------:|--------:|--------:|----------:|
| BenchmarkRawCachingReuse |          1 |       901.9 us |      7.68 us |      7.18 us |  0.08 |   43.9453 | 35.1563 | 28.3203 |    277 KB |
|      BenchmarkRawCaching |          1 |    11,641.7 us |    161.12 us |    142.83 us |  1.00 |   15.6250 |       - |       - |    371 KB |
|                          |            |                |              |              |       |           |         |         |           |
| BenchmarkRawCachingReuse |         10 |     2,947.5 us |     14.58 us |     12.17 us |  0.08 |   74.2188 | 58.5938 | 54.6875 |    417 KB |
|      BenchmarkRawCaching |         10 |    36,140.4 us |    573.19 us |    536.16 us |  1.00 |         - |       - |       - |    746 KB |
|                          |            |                |              |              |       |           |         |         |           |
| BenchmarkRawCachingReuse |        100 |    16,526.8 us |     75.99 us |     67.36 us |  0.24 |   62.5000 | 31.2500 | 31.2500 |    581 KB |
|      BenchmarkRawCaching |        100 |    68,041.1 us |  1,218.80 us |  1,496.80 us |  1.00 |         - |       - |       - |  1,089 KB |
|                          |            |                |              |              |       |           |         |         |           |
| BenchmarkRawCachingReuse |       1000 |   157,595.5 us |  1,955.15 us |  1,828.85 us |  0.72 |         - |       - |       - |  2,391 KB |
|      BenchmarkRawCaching |       1000 |   219,043.5 us |  1,633.69 us |  1,528.15 us |  1.00 |         - |       - |       - |  2,871 KB |
|                          |            |                |              |              |       |           |         |         |           |
| BenchmarkRawCachingReuse |      10000 | 1,543,063.2 us | 14,221.47 us | 13,302.77 us |  0.94 | 1000.0000 |       - |       - | 15,186 KB |
|      BenchmarkRawCaching |      10000 | 1,642,248.3 us |  7,982.10 us |  7,466.46 us |  1.00 | 1000.0000 |       - |       - | 15,664 KB |


This PR:


|                   Method | FetchCount |           Mean |        Error |      StdDev | Ratio |     Gen 0 |  Gen 1 | Allocated |
|------------------------- |----------- |---------------:|-------------:|------------:|------:|----------:|-------:|----------:|
| BenchmarkRawCachingReuse |          1 |       882.3 us |      4.16 us |     3.69 us |  0.08 |    9.7656 | 2.9297 |    114 KB |
|      BenchmarkRawCaching |          1 |    11,405.3 us |    118.77 us |   111.10 us |  1.00 |   15.6250 |      - |    205 KB |
|                          |            |                |              |             |       |           |        |           |
| BenchmarkRawCachingReuse |         10 |     2,867.9 us |     29.81 us |    26.42 us |  0.08 |   11.7188 | 3.9063 |    152 KB |
|      BenchmarkRawCaching |         10 |    34,729.9 us |    251.93 us |   223.33 us |  1.00 |         - |      - |    484 KB |
|                          |            |                |              |             |       |           |        |           |
| BenchmarkRawCachingReuse |        100 |    16,393.2 us |    129.55 us |   121.18 us |  0.25 |         - |      - |    305 KB |
|      BenchmarkRawCaching |        100 |    64,976.6 us |    317.63 us |   297.12 us |  1.00 |         - |      - |    828 KB |
|                          |            |                |              |             |       |           |        |           |
| BenchmarkRawCachingReuse |       1000 |   157,922.0 us |  1,578.43 us | 1,476.47 us |  0.75 |         - |      - |  2,130 KB |
|      BenchmarkRawCaching |       1000 |   210,225.8 us |  2,191.94 us | 1,830.37 us |  1.00 |         - |      - |  2,606 KB |
|                          |            |                |              |             |       |           |        |           |
| BenchmarkRawCachingReuse |      10000 | 1,543,722.5 us | 11,257.69 us | 9,979.65 us |  0.94 | 1000.0000 |      - | 14,925 KB |
|      BenchmarkRawCaching |      10000 | 1,647,745.3 us | 11,297.06 us | 9,433.56 us |  1.00 | 1000.0000 |      - | 15,403 KB |

2022-05-02 07:42 UTC, huoyaoyuan commented on osu.Framework/IO/Stores/RawCachingGlyphStore.cs
> +                    buffer = buffer[bytesRead..];
I feel it's better to encapsulate the loop reading pattern into a helper method, but the use cases are too few now. Maybe an internal extension method?

2022-05-02 07:49 UTC, peppy commented on osu.Framework/IO/Stores/RawCachingGlyphStore.cs
> +                    buffer = buffer[bytesRead..];
Might help, give it a try.

2022-05-02 15:24 UTC, peppy submitted a review, later dismissed
Seems fine now

2022-05-02 21:24 UTC, frenzibyte requested changes
Had a read through this and so far it looks good (except for a seemingly looking oversight).

2022-05-02 21:24 UTC, frenzibyte commented on osu.Framework/IO/AsyncBufferStream.cs
> +            data.AsSpan(position).CopyTo(buffer[..amountBytesToRead]);
`amountBytesToRead` can be smaller than `data.Length - position`, which means that the destination span may become smaller than the source span, which is an [invalid operation](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.copyto?view=net-6.0#exceptions).
```suggestion
            data.AsSpan(position, amountBytesToRead).CopyTo(buffer);
```

2022-05-03 04:56 UTC, huoyaoyuan commented on osu.Framework/IO/AsyncBufferStream.cs
> +            data.AsSpan(position).CopyTo(buffer[..amountBytesToRead]);
You're right. I did not test this.

2022-05-03 15:24 UTC, bdach approved these changes

2022-05-04 12:09 UTC, frenzibyte requested changes
Looks good except for the note below, which I found as I was checking game-side with these changes.

2022-05-04 12:09 UTC, frenzibyte commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +    internal class DataStreamFileProcedures : IFileProcedures
This is regressing osu!-side usage for checking too short audio files in editor:

<img width="1665" alt="CleanShot 2022-05-04 at 15 01 37@2x" src="https://user-images.githubusercontent.com/22781491/166677568-15edfbe5-9bb8-49ce-a1f5-1de8eff6a4c7.png">

```suggestion
    public class DataStreamFileProcedures : IFileProcedures
```

2022-05-04 12:12 UTC, bdach commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +    internal class DataStreamFileProcedures : IFileProcedures
I'd just revert the modifier change honestly.

2022-05-05 11:41 UTC, huoyaoyuan commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +    internal class DataStreamFileProcedures : IFileProcedures
Should we add a null check then, probably just in constructor?

2022-05-05 11:42 UTC, frenzibyte commented on osu.Framework/Audio/Callbacks/DataStreamFileProcedures.cs
> +    internal class DataStreamFileProcedures : IFileProcedures
`?? throw new ArgumentNullException` makes sense given that the game is not fully NRT-enabled.

2022-05-05 12:38 UTC, frenzibyte approved these changes

2022-05-05 17:03 UTC, peppy approved these changes

2022-05-06 09:25 UTC, smoogipoo reviewed
I've done a code-only pass through this and everything looks correct. I won't be able to merge this within the next couple of days as I'd like to test in-game with sound, but if others have tested then feel free to merge.

2022-05-10 11:36 UTC, peppy commented
I've tested this on macOS, no issues here.

2022-05-10 11:39 UTC, smoogipoo approved these changes

2022-05-10 12:00 UTC, merged