Refactor `TextureStore` to improve nesting support
ppy/osu-framework pull request #5240
Opened 2022-06-13 00:59 UTC by frenzibyte

- Closes #5220 

This refactors `TextureStore` into explicitly having two types of stores:
 - Texture data lookup store, in the form of `IResourceStore<TextureUpload>`, used for looking up texture data and loading a `Texture` for.
 - Nested texture store, in the form of `ITextureStore`, used as a secondary store if the `Texture` could not be found in the main store.

Which, in turn, removes the `TextureStore : ResourceStore<TextureUpload>` inheritance and forces `TextureStore`s to not be used only for lookup when nested in another store.

I've kept the name `AddStore` for nesting texture stores inline with `ResourceStore`, but can consider renaming to `AddNested` if that reads better.

# vNext

## `TextureStore.AddStore/RemoveStore` have been split into "store" and "lookup" methods

In an effort to make the texture API easier to comprehend, the `AddStore`/`RemoveStore` methods have been split into two varieties:
 - `AddLookup`/`RemoveLookup`, for adding/removing texture data lookup sources (i.e. `TextureLoaderStore`)
 - `AddStore`/`RemoveStore`, for adding/removing `TextureStore`s.

Any existing usages of `AddStore` for adding lookup sources must be changed to use `AddLookup` instead.

2022-06-13 05:50 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        /// Other <see cref="TextureUpload"/> stores are also allowed to be used as lookup sources.
Aren't these two lines contradictory? If this needs to be said it should be worded more like "Lookup sources can be implemented easily using a `TextureLoaderStore` to provide the final `TextureUpload`."

2022-06-13 05:50 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
I don't like the `Lookup` naming here. This is more like a transformer flow, right?

2022-06-13 08:36 UTC, frenzibyte commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
Yeah unsure about the namings I used, thinking about this for a bit it might make much more sense using `AddStore` here and `AddNested` for the other one.

I went with `AddLookup` only to have it make more sense to the end consumer, since this sort of store is only used to look up texture uploads to load textures for, not look up full `Texture`s.

Interested in more opinions.

2022-06-13 08:44 UTC, frenzibyte commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        /// Other <see cref="TextureUpload"/> stores are also allowed to be used as lookup sources.
I personally never understood the point of a `TextureLoaderStore` until I went to the framework source code and read through it, so I believe having at least one xmldoc explaining how to transform image file stores into `TextureUpload` stores would give a better idea to the consumer on how that side works. The xmldoc you proposed sounds better and still hints at it.

2022-06-13 09:46 UTC, bdach commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
Not sure what the "transformer flow" mention is supposed to mean in this context, but I'd name this something like `AddTextureSource()` or something.

2022-06-13 10:00 UTC, bdach commented
Would be interested to see the corresponding osu!-side changes for this. I doubt there are none.

2022-06-13 10:04 UTC, frenzibyte commented
It's only a two lines at the time I checked, will PR it for visibility.

2022-06-13 10:08 UTC, frenzibyte commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
That sounds good as well, would want to use `AddSource` to keep it short in usages if that's agreeable.

2022-06-13 22:35 UTC, frenzibyte commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
Now that I look at it, `AddSource` would mix rather badly with `AddStore`, I'm fine with going for `AddTextureSource` unless one has a second opinion.

2022-06-14 14:10 UTC, bdach commented on osu.Framework/Graphics/Textures/ITextureStore.cs
> +#nullable enable
```suggestion
```

no longer required after #5241

2022-06-15 04:33 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +        public virtual void AddLookup(IResourceStore<TextureUpload> store) => uploadStore.AddStore(store);
Let's go with `AddTextureSource` for now.

2022-06-15 05:54 UTC, peppy commented
Thoughts on also renaming `AddStore` to `AddFallbackStore` while we're here? As it stands I have a lot of trouble understanding that one, especially with the presence of this new method.

2022-06-15 05:59 UTC, frenzibyte commented
That wouldn't work well with cases like texture stores with custom filtering mode added to main `TextureStore`, i.e.:
```csharp
var nearestTextureStore = new TextureStore(nearestTextures, filteringMode: All.Nearest);
Textures.AddFallbackStore(nearestTextureStore);
```

Would you be fine with calling it `AddNestedStore` at least?

2022-06-15 06:00 UTC, peppy commented
I think something larger is wrong, because it's clear I'm not understanding the purpose of the method.

Will revisit this when I have the time to go over the full flow. If I can't make sense of it there's no way a consumer will.

2022-06-15 09:57 UTC, smoogipoo commented
The problem at large is the distinction between a `TextureLoaderStore` and a `TextureStore`. Would be nice if we didn't have to do the `TextureLoaderStore` dance...

2022-06-20 07:38 UTC, peppy commented
I've added some further xmldoc to help me understand this. I think I'm on board with these changes.

I have one remaining question though:

> Any existing usages of `AddStore` for adding lookup sources must be changed to use `AddLookup` instead.

It looks like even with the changes on this branch, previous code using `AddStore` will still compile and run. Will it fail in some unknown way, or still work fine, just be sub-optimal?

2022-06-20 08:04 UTC, frenzibyte commented
> > Any existing usages of `AddStore` for adding lookup sources must be changed to use `AddLookup` instead.
> 
> It looks like even with the changes on this branch, previous code using `AddStore` will still compile and run. Will it fail in some unknown way, or still work fine, just be sub-optimal?

Previously `AddStore` would accept both `TextureStore`s and `TextureLoaderStore`s. But now, if a consumer uses `AddStore` for `TextureLoaderStore` (the likely case), they'll have to update to `AddLookup`.

2022-06-20 08:08 UTC, peppy commented
So in the case of this:

https://github.com/ppy/osu/blob/495d747da55eab3cbfcc8331ffe5f6e73c6e3618/osu.Game/OsuGameBase.cs#L243

There is no real change in behaviour, apart from things being structured internally a bit weirdly?

2022-06-20 08:50 UTC, bdach commented
CI is failing here now, since the template projects actually are being built with these changes after #5250.

2022-06-20 09:10 UTC, frenzibyte commented
The template change didn't turn out as expected by this PR (using `AddStore` on a nested texture store with nearest filtering mode), since the entire resources assembly is added to `Resources`, which the base `Textures` store use as a lookup source. Therefore the template game has to still create a `TextureStore` and cache it instead of the base `Textures` one.

2022-06-20 09:16 UTC, peppy requested changes

2022-06-20 09:18 UTC, bdach commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
I believe this won't work as written because of the implicit ordering between `AddLookup()` and `AddStore()`. `Textures` will try itself first before proceeding to use nested stores. Because both stores use the same resources, then `Textures` wouldn't even use the `nearestNeighbourStore`, it would fetch the resource itself from `Resources` and then return it with the unexpected filtering mode.

2022-06-20 09:25 UTC, peppy commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
Right. But that also means this whole PR doesn't fix the issue it's proposing to close?

2022-06-20 09:27 UTC, frenzibyte commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
I can see two ways towards resolving this:
 1. Prioritise nested stores over main store (which would make more sense if we rename it to a "child"/"sub" texture store, or something of the sorts)
 2. Expose lookup resource store from `TextureStore` and use in the above case by doing:
    ```csharp
    var textures = new TextureStore(filteringMode: All.Nearest);
    textures.AddLookup(Textures.Sources);
    dependencies.Cache(textures);
    ```
    (that still means caching, but at least not duplicating the main texture store lookup sources)

2022-06-20 09:28 UTC, bdach commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
I suppose so. It substitutes one unexpected behaviour (`AddStore()` working counterintuitively, because it only helps the texture store *look up* resources from the `TextureStore` provided, rather than allow it to be used wholesale) for another (you can do the above, but you have to keep in mind the inner workings of how `AddStore()` and `AddLookup()` interact).

I don't really claim know what the answer is here because the behaviour is inherently complex when two layers of lookup are permitted.

2022-06-20 09:51 UTC, peppy commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
Another proposal would be to presume that if a user wants to change the filtering mode, it would be something they want changed globally, and expose it in some way at a `Game` level via a `virtual` property or otherwise.

2022-06-20 22:08 UTC, frenzibyte commented on osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs
>              dependencies.Cache(textures);
Since PR'ing this, I've been under the thought that consumers would nest texture stores for cases where there is a specific store away from the main `Game.Resources` one, and customise the texture store to use different filtering mode / scale adjust / etc.

> A proposal would be to just add the ability to specify the filter mode when adding a lookup store and having it all managed internally.

That would be pretty much what `AddStore(new TextureStore(lookupStore, filteringMode: ...))` should achieve. Except that in the flappydon case, the lookup store is already added to the main `Game.Resources` store, making this approach not quite feasible unless we prioritise nested stores over main store as mentioned.

> Another proposal would be to presume that if a user wants to change the filtering mode, it would be something they want changed globally, and expose it in some way at a `Game` level via a `virtual` property or otherwise.

This sounds pretty good for the flappydon case, and probably something that consumers would find better than creating a nested texture store that wraps the main `Textures` one (i.e. what flappydon does currently). I'll go with this approach for now, and we can reiterate later I think.

2022-06-21 01:03 UTC, peppy commented on osu.Framework/Game.cs
> +        protected virtual bool LinearTextureFiltering => true;
I think we should make this `DefaultTextureFilteringMode` and allow the user to choose either `Linear` or `Nearest` (does a better job at explaining what the choice means.

2022-06-21 01:05 UTC, frenzibyte commented on osu.Framework/Game.cs
> +        protected virtual bool LinearTextureFiltering => true;
Initially had it that way but thought I could simplify it to a boolean. This would also mean defining a new `FilteringMode` enum since we use OpenGL's `All` which we don't want to rely on as part of the public API.

2022-06-21 03:16 UTC, peppy commented
I'm still a bit lost as to potential usages of the newly added flows, but assuming there is valid reason for them that I'm missing, I'm generally okay with this structure now so I'll shoot a tentative approval.

Would want to make sure both @smoogipoo and @bdach are on board with the changes as they currently stand.

2022-06-21 03:16 UTC, peppy approved these changes

2022-06-22 07:03 UTC, smoogipoo approved these changes
Lgtm

2022-06-22 07:08 UTC, smoogipoo requested changes
Whoops I added a comment >_>

2022-06-22 07:13 UTC, frenzibyte commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +                return uploadStore.GetAvailableResources().Concat(nestedStores.SelectMany(s => s.GetAvailableResources()).ExcludeSystemFileNames());
Right since it's lazy enumeration, making the lock unnecessary. Feel free to apply that.

2022-06-22 08:10 UTC, peppy approved these changes

2022-06-22 08:18 UTC, merged