Internalise `TextureGL` and rewrite `Texture` to take its role
ppy/osu-framework pull request #5330
Opened 2022-08-02 10:24 UTC by smoogipoo

- `TextureGL*` classes merged into one.
- Opacity calculation and subtexturing has been moved to `Texture`. 
- `Texture` no longer exposes the underlying native texture.
- `Texture`s must be created through the `IRenderer`.

The rest should be explainable via the breaking changes below:

# vNext

## `WrapMode` and `Opacity` enums have been re-namespaced

Their new location is `osu.Framework.Graphics.Textures`.

## `Texture.WhitePixel` has been moved to `IRenderer`

It is no longer provided as a static member. Instead, [resolve](/ppy/osu-framework/wiki/Dependency-Injection) an `IRenderer` and access `IRenderer.WhitePixel`.

```diff
public class MyDrawable : Drawable
{
+   [BackgroundDependencyLoader]
+   private void load(IRenderer renderer)
+   {
+       texture ??= renderer.WhitePixel;
+   }

    private Texture texture;

    public Texture Texture
    {
-       get => texture ?? Texture.WhitePixel;
+       get => texture;
        set => texture = value;
    }
}
```

## `TextureStore`, `FontStore` and `LargeTextureStore` construction parameters have changed

- Requires an `IRenderer` parameter (via dependency injection).
- Filter mode parameter changed from `All` to `TextureFilteringMode`.

One common use case is to provide a new texture store from inside a derived `Game`, for which the following change is required:

```diff
public class TestGame : osu.Framework.Game
{
    private DependencyContainer dependencies;

    protected override IReadOnlyDependencyContainer CreateChildDependencies(IReadOnlyDependencyContainer parent) =>
        dependencies = new DependencyContainer(base.CreateChildDependencies(parent));

    [BackgroundDependencyLoader]
    private void load()
    {
-       var largeStore = new LargeTextureStore(Host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(Resources, @"Textures")), All.Nearest);
+       var largeStore = new LargeTextureStore(Host.Renderer, Host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(Resources, @"Textures")), TextureFilteringMode.Nearest);
        largeStore.AddTextureSource(Host.CreateTextureLoaderStore(new OnlineStore()));
        dependencies.Cache(largeStore);
    }
}
```

## `Texture` cannot be used to create textures

`Texture` must now be created via `IRenderer`.

```diff
public class MyDrawable : Drawable
{
-   private readonly Texture texture;

-   public MyDrawable()
-   {
-       texture = new Texture(100, 100);
-       texture.SetData(...);
-   }
+   private Texture texture;

+   [BackgroundDependencyLoader]
+   private void load(IRenderer renderer)
+   {
+       texture = renderer.CreateTexture(100, 100);
+       texture.SetData(...);
+   }
}
```

`DummyRenderer` may be used for cases where textures need to be created and neither an `IRenderer` nor `GameHost` is accessible:

```diff
[TestFixture]
public class MyTestFixture
{
    public void CreateATexture()
    {
-       Texture texture = new Texture(1, 1);
+       Texture texture = new DummyRenderer().CreateTexture(1, 1);
    }
}
```

## Texture drawing methods moved from `DrawNode` to `IRenderer` extension methods

Appearing alongside `IRenderer` is the new `RendererExtensions` class providing extension helper methods for common drawing procedures.

An example of the type of change required `DrawNode`:
```diff
public class MyDrawNode : DrawNode
{
    public override void Draw(IRenderer renderer)
    {
        base.Draw(renderer);

-       DrawQuad(renderer.WhitePixel, ...);
+       renderer.DrawQuad(renderer.WhitePixel, ...);
    }
}
```

The following methods have been moved to this class:
```
DrawTriangle()
DrawQuad()
DrawClipped()
DrawFrameBuffer()
```

## `TextureGL` is no longer accessible

Properties such as `TextureGL.BypassTextureUploadQueueing` have been moved to `Texture` itself, and `Texture` can be used for all drawing procedures.

During rendering, textures may now be bound via an integer sampling unit.

```diff
public class MyDrawable : Drawable
{
    private Texture texture;

    [BackgroundDependencyLoader]
    private void load(IRenderer renderer)
    {
        texture = renderer.CreateTexture(100, 100);
        texture.BypassUploadQueueing = true;
        texture.SetData(...);
    }
}

public class MyDrawNode : DrawNode
{
    private Texture texture;

    public override void Draw(IRenderer renderer)
    {
        base.Draw(renderer);

-       texture.TextureGL.Bind();
-       texture.TextureGL.Bind(TextureUnit.Texture1);
+       texture.Bind();
+       texture.Bind(1);

        // Note: The texture binding above isn't required in either case for the call below.
-       DrawQuad(texture.TextureGL, ...);
+       renderer.DrawQuad(texture, ...);
    }
}
```

2022-08-03 06:59 UTC, peppy requested changes

2022-08-03 06:59 UTC, peppy commented on osu.Framework.Tests/Graphics/TextureAtlasTest.cs
> +            var tex2 = tex1.Crop(new RectangleF(0, 0, 1, 1));
Would it be worth adding test coverage of the resultant texture sizes being correct for these?

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
Can the renderer actually be passed in as null? Had to double-take on this because NRT isn't applied on this file (might be a good time to apply that, if only here).

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
> -            counterBarBackground?.Texture.SetData(columnUpload);
Not an issue, but I'm really curious where this texture came from in the original code...

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Rendering/INativeTexture.cs
> +        bool IsQueuedForUpload { get; set; }
Is this required to have a setter?

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Rendering/INativeTexture.cs
> +        /// The total amount of times this <see cref="INativeTexture"/> was bound.
Might help to make it clear that this is not a per-frame counter.

```suggestion
        /// The total amount of times this <see cref="INativeTexture"/> was bound (ever).
```

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/DisposableTexture.cs
> +            NativeTexture.Dispose();
I found this a bit awkward to read. One would assume that a `Texture` would be responsible for cleaning up the `NativeTexture`, but that's not the case (which is fine but on fresh eyes it may look like a wtf).

I think leaving xmldoc or a comment on the `NativeTexture` property in `Texture` explaining why the lifetime/disposal of this is not managed by the `Texture` itself would help.

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +                        new DisposableTexture(tex).Dispose();
Was this change just to keep everything going through the one disposal path? I think this cold also be written as

```csharp
tex.NativeTexture.Dispose();
tex.Dispose();
```

similar to the old code and still work correctly.

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureRegion.cs
> +            // Todo: Not sure if this is correct...
Are you still unsure? If so, of which part?

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureAtlas_InternalAtlasTexture.cs
> +        private class InternalAtlasTexture : Texture
`BackingTexture` or `AtlasBackingTexture`?

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureAtlas.cs
> +                // atlasTexture can't be null after findPosition().
`Debug.Assert` instead in that case, after the `findPosition` method call preferrably.

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/TextureAtlas.cs
> +                return new TextureWhitePixel(atlasTexture.AsNonNull());
I'd probably also use a `Debug.Assert` here too.

2022-08-03 06:59 UTC, peppy commented on osu.Framework/Graphics/Textures/Texture.cs
> +        public string Filename = string.Empty;
`Filename` is not used in framework or osu!, and is pretty pointless considering `AssetName` below. Might as well remove it as part of this PR?

2022-08-03 07:05 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
It can only during construction time, since `Width`/`Height` are set from the base ctor. NRT won't help with this :/

2022-08-03 07:10 UTC, smoogipoo commented on osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
> -            counterBarBackground?.Texture.SetData(columnUpload);
In the constructor https://github.com/ppy/osu-framework/pull/5330/files#diff-3a107db5547cd47903bd20ce803297d8ffe8e65b30c595f3ea1e66949c2e41f2L155 . Unless you mean original code as in the code that was written 6 years ago, then idk.

2022-08-03 07:12 UTC, peppy commented on osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
> -            counterBarBackground?.Texture.SetData(columnUpload);
Right, I see it now.

2022-08-03 07:13 UTC, peppy commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
And this is actually accessed in such a state? Feels a bit haphazard TBH.. if we can avoid it I would recommend doing so.

2022-08-03 07:13 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/DisposableTexture.cs
> +            NativeTexture.Dispose();
The doc is in `Texture.Dispose()` itself. Best would be to add a doc _here_ if anything.

2022-08-03 07:17 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/TextureStore.cs
> +                        new DisposableTexture(tex).Dispose();
Yes, it could be written that way, but I don't want to add accesses to `NativeTexture`.

There's only one reference to `NativeTexture` outside of `Texture` & co, and that is `OpenGLRenderer`, and I would like to remove that also.

2022-08-03 07:49 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/TextureRegion.cs
> +            // Todo: Not sure if this is correct...
I wasn't sure about the opacity update, but I've added it back in here. The comment is from early days.

For reference, see: https://github.com/ppy/osu-framework/blob/60f5b5871786a3520f59f62157e0112ed730e37c/osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs#L104-L127

2022-08-03 07:49 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/DisposableTexture.cs
> +            NativeTexture.Dispose();
I've added a remark on the xmldoc.

2022-08-03 07:50 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/INativeTexture.cs
> +        bool IsQueuedForUpload { get; set; }
No, technically shouldn't exist at all (specific to GL implementation), but can be cleaned up later. Removed setter for now.

2022-08-03 07:52 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
Here's a few options:
1. Not have `TextureGL` take `width`/`height` ctor parameters, and instead do something like `new TextureGL(...) { Width = ... , Height = ... }`
2. Have `INativeTexture` expose `Width`/`Height` as get-only and `SetWidth()`/`SetHeight()` methods that `Texture` calls into.

Pick your poison, or.. any better suggestions?

2022-08-03 07:53 UTC, peppy commented on osu.Framework/Graphics/Rendering/INativeTexture.cs
> +        bool IsQueuedForUpload { get; set; }
I did notice that it's not being accessed even via the getter, so it could potentially be removed right now?

2022-08-03 07:54 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/INativeTexture.cs
> +        bool IsQueuedForUpload { get; set; }
Sure, done.

2022-08-03 07:57 UTC, smoogipoo commented on osu.Framework.Tests/Graphics/TextureAtlasTest.cs
> +            var tex2 = tex1.Crop(new RectangleF(0, 0, 1, 1));
The size of textures retrieved from atlases being correct is checked a few tests up above, but I've added a new test for `TextureRegion` specifically since that's a path that isn't tested and very important to drawing as a whole.

2022-08-03 07:59 UTC, peppy commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
I'm fine with it with your change to remove the null check.

2022-08-03 08:00 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
> +                set => base.Width = renderer == null ? value : Math.Clamp(value, 1, GLWrapper.MaxTextureSize);
.... I made that change and promptly forgot I made it. Yes the nullcheck isn't required anymore since `Renderer` is exposed as protected from `TextureGL` :sweat_smile:

2022-08-03 08:02 UTC, peppy approved these changes

2022-08-03 08:03 UTC, smoogipoo commented on osu.Framework/Graphics/Textures/Texture.cs
> +        public virtual RectangleF GetTextureRect(RectangleF? area = null)
One thing I forgot to mention is that I had a lot of trouble getting this `GetTextureRect()` method to work due to working in two "coordinate spaces".

In this PR, I've tried to use the terminology "texture-space" and "display-space" to describe which coordinate space the user or reviewer of code should be thinking of.
- "texture-space" is in coordinates `(0, 0, Width, Height)`
- "display-space" is in coordinates `(0, 0, DisplayWidth, DisplayHeight)`

This method here is one example, as well as:

- The XMLDoc on `TextureRegion`: https://github.com/ppy/osu-framework/pull/5330/files#diff-296537cb3a9b525374da9be847ea69b5532c71516de14c76ab09a73e1b373df0R17-R25
- The implementation of `TextureRegion`: https://github.com/ppy/osu-framework/pull/5330/files#diff-296537cb3a9b525374da9be847ea69b5532c71516de14c76ab09a73e1b373df0R60-R78

2022-08-05 06:21 UTC, merged

2022-08-25 06:41 UTC, frenzibyte reviewed
Looks good on a post-merge read.