Add stencil support for renderers
ppy/osu-framework pull request #5351
Opened 2022-08-11 08:06 UTC by Flutterish

This adds `StencilInfo` and appropriate methods to renderers. It also adds an 8-bit stencil buffer to the screen buffers (please doublecheck if all window types have it, I only added it to the SDL window as I have no way to check if the mobile ones or OsuTkWindow work).
This is a part of my work towards #3510 - the even-odd fill algorithm is very easy to implement with a stencil buffer.

2022-08-11 10:02 UTC, smoogipoo requested changes
Rest looks okay

2022-08-11 10:02 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +using osuTK.Graphics.ES30;
Can't reference ES30. You need to make appropriate o!f enums.

2022-08-11 10:30 UTC, smoogipoo requested changes

2022-08-11 10:30 UTC, smoogipoo commented on osu.Framework/Platform/SDL2DesktopWindow.cs
> +            SDL.SDL_GL_SetAttribute(SDL.SDL_GLattr.SDL_GL_STENCIL_SIZE, 8);
This can't be in the window. It should be somewhere inside the `SDL2GraphicsBackend` (temporarily, because that class is going to go away). Perhaps it could fit in the constructor, or in a method like `InitialiseBeforeWindow()`.

As an aside... That entire class is kinda weird - `SDL2DesktopWindow` -> `IGraphicsBackend.Initialise()` -> `SDL2GraphicsBackend.Initialise()` -> `PassthroughGraphicsBackend.Initialise()` -> `SDL2GraphicsBackend.CreateContext()`. Too much back and forth.

2022-08-11 10:41 UTC, Flutterish commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +using osuTK.Graphics.ES30;
I copied this from DepthInfo which also references ES30. I will make custom enums, but in that case you should also look into the existing structs which do this.

2022-08-11 10:43 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +using osuTK.Graphics.ES30;
Ouch, yeah that needs to change.

2022-08-11 11:24 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +        /// The operation to perform on the stencil buffer in case the stencil test passed.
```suggestion
        /// The operation to perform on the stencil buffer when both the depth and stencil tests pass.
```

2022-08-11 11:24 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +        /// The operation to perform on the stencil buffer in case the depth test failed.
```suggestion
        /// The operation to perform on the stencil buffer when the depth test fails.
```

2022-08-11 11:24 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +        /// The operation to perform on the stencil buffer in case the stencil test failed.
```suggestion
        /// The operation to perform on the stencil buffer when the stencil test fails.
```

2022-08-11 11:24 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/StencilInfo.cs
> +using osuTK.Graphics.ES30;
In https://github.com/ppy/osu-framework/pull/5352 I've added `DepthStencilFunction`, which you should be able to reuse here.

2022-08-11 13:09 UTC, Flutterish commented
Waiting for #5352 to be merged before I can use the `DepthStencilFunction`.

2022-08-12 07:08 UTC, smoogipoo commented
Looks good. Added a test scene to demonstrate usage + test it.

2022-08-12 07:14 UTC, Flutterish commented
Do you have a way to test whether mobile/ios "windows" (`OsuTkWindow`) have the stencil buffer attached? I suspect they might not but I don't think I have a way to test that myself.

2022-08-12 07:24 UTC, smoogipoo commented
I don't. As far as I know we're requesting the default context provided by the platforms.

2022-08-12 07:24 UTC, smoogipoo approved these changes

2022-08-12 10:01 UTC, peppy approved these changes

2022-08-12 10:14 UTC, merged