Add callbacks to text selection events of TextBox
ppy/osu-framework pull request #5366
Opened 2022-08-19 08:44 UTC by nekodex

Will be used for adding audio feedback to text selection in lazer

2022-08-20 09:42 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        }
Having both `TextSelectionType.Deslect` and `OnTextDeselected()` feels wrong to me. Either remove `OnTextDeselected()`, or add a note to `OnTextSelectionChanged` that it won't be called with `TextSelectionType.Deslect`.

2022-08-20 09:57 UTC, frenzibyte commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        }
This sounds like `TextSelectionType.Deselect` shouldn't be a thing to begin with.

2022-08-20 10:20 UTC, Susko3 requested changes

2022-08-20 10:20 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +            onTextSelectionChanged(newSelectionLength > 0 ? TextSelectionType.Character : TextSelectionType.Deselect);
Not sure this is valid, as IME input is quite different from regular text input. I'd rather add `newSelectionLength` (or `textSelected`) to `OnImeComposition`.

With the osu!-side PR, this currently produces sounds for both `OnImeComposition` and `OnTextSelectionChanged`.

2022-08-20 10:20 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +                    if (lastSelectionStart != lastSelectionEnd && (lastSelectionStart > 0 || lastSelectionEnd > 0))
```suggestion
                    if (lastSelectionStart != lastSelectionEnd)
```

| `lastSelectionStart` | `lastSelectionEnd` | `lastSelectionStart != lastSelectionEnd` | `lastSelectionStart > 0 \|\| lastSelectionEnd > 0` |
| -- | -- | -- | -- |
| 0 | 0 | false | false |
| 0 | 5 | true | true |
| 4 | 0 | true | true |
| 4 | 5 | true | true |
| 4 | 4 | false | true |

2022-08-24 13:38 UTC, nekodex commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +            onTextSelectionChanged(newSelectionLength > 0 ? TextSelectionType.Character : TextSelectionType.Deselect);
Hrm, I'll re-check the behaviour with IME.

2022-08-25 08:05 UTC, peppy commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        private void storeTextSelectionBeforeChange()
Before I propose a change here, can you confirm that the `lastSelectionX` values are always intended to be used immediately in the method this is called from? ie. it doesn't really need to be stored to fields in `TextBox`?

2022-08-25 08:20 UTC, nekodex commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        private void storeTextSelectionBeforeChange()
That method is used to set the `lastSelectionX` values (before a selection change occurs) which are then compared against later in `onTextSelectionChanged`/`onTextDeselected`, if that's what you mean.

2022-08-25 08:20 UTC, peppy commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        private void storeTextSelectionBeforeChange()
I'm thinking the method should return a tuple with the two values for local use, which could then be passed into those two methods as a single parameter rather than storing to `TextBox` fields. Would that work?

2022-08-25 08:28 UTC, nekodex commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +        private void storeTextSelectionBeforeChange()
Aha yeah, I'll do that.

2022-08-25 09:22 UTC, peppy approved these changes

2022-08-25 09:23 UTC, peppy commented on osu.Framework/Graphics/UserInterface/TextBox.cs
> +            onTextSelectionChanged(newSelectionLength > 0 ? TextSelectionType.Character : TextSelectionType.Deselect);
Has been removed.

2022-08-25 09:38 UTC, merged