Update `IContainer` interface to add explicit disposal argument on `Remove` methods
ppy/osu-framework pull request #5382
Opened 2022-08-26 06:06 UTC by peppy

Closes #5378.

## Breaking Changes

### `IContainer.Remove`, `IContainer.RemoveRange` and `IContainer.RemoveAll` now require a `bool` parameter

A common mistake we've seen made osu!-side is where drawables are `Remove`d from the hierarchy with the intention of never using them again. In such cases, disposal is not guaranteed – nor is unbinding of `Bindable` fields/properties – which can lead to event and object leakage.

To prevent this from happening, a new `disposeImmediately` parameter has been added.

Generally this should be set to `true` unless you intent to reuse the removed drawable (ie. by adding back to the hierarchy at a different location).

2022-08-26 06:07 UTC, peppy commented
I'm making an osu!-side companion to this still, will block until done and confirmed all is okay.

2022-08-26 06:49 UTC, peppy commented
I've tested various gameplay scenarios and things seem to be working well enough.

![JetBrains Rider 2022-08-26 at 06 48 51](https://user-images.githubusercontent.com/191335/186840384-6b88881e-d763-4417-a215-8e061ddc75cd.png)

2022-08-26 11:12 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/Container.cs
> +        }
Is there a reason `RemoveInternal` isn't updated to contain this argument as well, similar to `ClearInternal`?

2022-08-26 11:14 UTC, peppy commented on osu.Framework/Graphics/Containers/Container.cs
> +        }
It likely should be, but it's a lot of extra work (many usages). I can look at that if deemed best to do it all in one swoop.

2022-08-26 11:27 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/Container.cs
> +        }
The diff is already large as it stands and is a breaking change, so I think it's worth breaking `RemoveInternal` similarly while at it rather than leaving it for later.

2022-08-29 07:10 UTC, peppy commented on osu.Framework/Graphics/Containers/Container.cs
> +        }
Have added this. Also updated osu-side changes and confirmed tests pass.

2022-08-29 09:36 UTC, frenzibyte requested changes

2022-08-29 09:36 UTC, frenzibyte commented on osu.Framework/Graphics/Containers/AudioContainer.cs
> +        bool ICollection<T>.Remove(T item) => container.Remove(item, true);
This comment is for another day, but the code here makes me wonder if `Container` should inherit from `ICollection<T>` in the first place. It already inherits `IReadOnlyList<T>` so LINQ operations will remain to be possible, but having it inherit `ICollection<T>` gets bad given the side effects of immediately disposing drawables on removal.

2022-08-29 09:36 UTC, frenzibyte commented on osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
> +        void IContainVisualisedDrawables.RemoveVisualiser(VisualisedDrawable visualiser) => flow.Remove(visualiser, true);
This method is used for transferring parents or changing child ID as well:
https://github.com/ppy/osu-framework/blob/04c5dd65bfb42e48afaa3aab2f9dd0bab28db3b8/osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs#L460-L466
https://github.com/ppy/osu-framework/blob/04c5dd65bfb42e48afaa3aab2f9dd0bab28db3b8/osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs#L287-L288
```suggestion
        void IContainVisualisedDrawables.RemoveVisualiser(VisualisedDrawable visualiser) => flow.Remove(visualiser, false);
```

2022-08-31 10:27 UTC, frenzibyte approved these changes

2022-09-01 07:40 UTC, smoogipoo approved these changes

2022-09-01 07:50 UTC, merged