Fix window size properties not correct on Hi-DPI screens
ppy/osu-framework pull request #5452
Opened 2022-10-08 12:20 UTC by frenzibyte

Came across it while checking out https://github.com/ppy/osu-framework/pull/5450. Testing with the M1 Pro's retina screen.

Before:

![CleanShot 2022-10-08 at 15 15 40@2x](https://user-images.githubusercontent.com/22781491/194707068-31dc3ec4-3ebd-4c05-909b-b3f1d9d2afe4.png)

After:

<img width="1728" alt="CleanShot 2022-10-08 at 15 13 56@2x" src="https://user-images.githubusercontent.com/22781491/194707000-241e6251-aee2-4ac8-96cc-f3a4a1859293.png">

2022-10-11 08:39 UTC, smoogipoo commented
Missing some code here

2022-10-11 21:29 UTC, Susko3 requested changes

2022-10-11 21:29 UTC, Susko3 commented on osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
> +                    SDL.SDL_SetWindowSize(SDLWindowHandle, Size.Width, Size.Height);
I would expect `FrameworkSetting.WindowedSize` / `sizeWindowed` to match `ClientSize` (as that's exposed in `IWindow` -- `Size` is specific to `SDL2DesktopWindow`).

Have not tested this, not sure how it behaves on startup.

Also https://github.com/ppy/osu-framework/issues/5131 is something to keep in mind.

2022-10-11 21:54 UTC, frenzibyte commented on osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
> +                    SDL.SDL_SetWindowSize(SDLWindowHandle, Size.Width, Size.Height);
This PR shouldn't change behaviour so it's out of scope here, but I believe it's correct to make `WindowedSize` based on window size rather than client size, specifically in a scenario where a window is displayed on a 200% dpi display, but the window was moved back to a 100% dpi display (in which case, if `WindowedSize == ClientSize`, then the window will display 2x its size on the normal display, unlike `WindowedSize == Size`).

`IWindow` already explicitly names the client size as `ClientSize`, but if required, it can expose the `Size` property as `WindowSize`.

2022-10-11 23:12 UTC, Susko3 approved these changes

2022-10-21 13:52 UTC, peppy approved these changes

2022-10-21 13:52 UTC, merged