Implement DrawableShader component
ppy/osu-framework pull request #5494
Opened 2022-10-29 05:49 UTC by EVAST9919

More and components are sharing similar logic so I thought a parent class for them would be a nice thing to have.
Not sure about the name though.

2022-10-29 10:46 UTC, frenzibyte commented on osu.Framework/Graphics/DrawableShader.cs
> +    public class DrawableShader : Sprite
Would call this `ShaderBasedSprite`, but generally, I think having this as a protected constructor in `Sprite` would make sense, or even make this an abstract `TexturedShaderDrawable` class, use the existing `TexturedShaderDrawNode` as its draw node, and make `Sprite` derive from it. Interested in more opinions.

2022-11-01 11:45 UTC, smoogipoo requested changes

2022-11-01 11:45 UTC, smoogipoo commented on osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
> +                        shader.GetUniform<float>("hue").UpdateValue(ref hue);
Technically all of these should call `base.UpdateUniforms()`. I think that's a good precedent to set for this shader.

2022-11-01 11:48 UTC, smoogipoo commented
I think this is fine as an initial implementation. It's a bit deviating from another idea I had (shader passes), but still probably useful to have.

2022-11-23 18:31 UTC, EVAST9919 commented
Would probably be cool to have something like caching via `IFrameBuffer` in this component, so once drawn - we will be drawing only the texture instead of calling the shader every frame. In theory elements like `CircularBlob` will greatly benefit from that.

2023-03-27 11:49 UTC, EVAST9919 commented
Closing as outdated

2023-03-27 11:49 UTC, closed without merging