Use (high resolution) waitable timers on windows when available
ppy/osu-framework pull request #5501
Opened 2022-11-06 06:41 UTC by peppy

Intends to fix the remaining inaccuracy that can be seen when running at frame rates close to the maximum precision provided by `Thread.Sleep` on windows.

A few preliminary notes:

- This is windows only. Other (unix/linux) platforms already had higher precision thread sleep. Of note, this does now perform `Thread.Sleep` using floating point rather than hard `int` rounding, so it may marginally improve results on non-windows platforms
- Frame jitter is now displayed on the frame statistics display. This is standard deviation between `NewFrame` calls averaged over last 256 frames
- Don't trip over the pinvoke code. I considered using [Vanara](https://github.com/dahall/Vanara) for this but that had a few issues (and the DLL is a bit large so we'd want pruning support). See https://github.com/dahall/Vanara/issues/339, may be something we can switch to in the future rather than implementing pinvokes locally, as it's much better documented and tested.
- CPU usage is basically unaffected, which is good.

Results:

Before (`Thread.Sleep`):
![mpv_2022-11-06_15-01-51](https://user-images.githubusercontent.com/191335/200157123-3e0e6f73-71d3-4ee6-9ff2-ac72bcd21be6.png)

![image](https://user-images.githubusercontent.com/191335/200157134-724c1ba9-6c43-43d9-9bba-6c7fdae2521d.png)

After (`WaitableTimer`):
![mpv_2022-11-06_15-02-07](https://user-images.githubusercontent.com/191335/200157125-a472268c-2658-4e5a-91eb-2179423be9e4.png)

![image](https://user-images.githubusercontent.com/191335/200157140-4e918bfe-6409-45fd-ade6-15576e24d467.png)

You can count the individual frames being run. In both profile runs above, the reported frame rate is 1,000, but in the first multiple frames were being coalesced into single back-to-back executions (which is basically pointless to us).

Note that even when not using `HIGH_PRECISION` mode, the results are basically the same. So this should improve the experience not only on recent window builds but most all.

- [ ] Needs testing on machines which are limited in performance (ie. not capping the frame limiter out). Should we still invoke the timer wait when time-to-be-waited is zero?)

2022-11-06 12:31 UTC, Susko3 requested changes
Appears to work fine, the `waitableTimer` survives trough `ExecutionMode` changes.

2022-11-06 12:31 UTC, Susko3 commented on osu.Framework/Timing/ThrottledFrameClock.cs
> +            }
I'd replace this with an `RuntimeInfo.OS` check instead of trying to call winapi on other platforms.

2022-11-06 12:31 UTC, Susko3 commented on osu.Framework/Timing/ThrottledFrameClock.cs
> +            }
If `SetWaitableTimerEx` fails, `Thread.Sleep` is skipped.

Something like

```cs
if (waitableTimer != IntPtr.Zero
    && Execution.SetWaitableTimerEx(waitableTimer, Execution.CreateFileTime(timeSpan), 0, null, default, IntPtr.Zero, 0))
{
    Execution.WaitForSingleObject(waitableTimer, Execution.INFINITE);
}
```

Or combine `Set` and `Wait` into a single helper function in `Execution`.

2022-11-06 12:31 UTC, Susko3 commented on osu.Framework/Timing/ThrottledFrameClock.cs
> +                // ReSharper disable once BitwiseOperatorOnEnumWithoutFlags
Unnecessary with the local implementation.

```suggestion
```

2022-11-06 14:18 UTC, peppy commented on osu.Framework/Timing/ThrottledFrameClock.cs
> +            }
Hmm, this was kind of intentional though, pending testing the todo point. Also I'm not sure the `Create` can succeed but the `Set` fail in any normal circumstance.

2022-11-07 01:44 UTC, peppy commented
Tested at lower frame rates to work as expected.

2022-11-07 01:53 UTC, peppy commented on osu.Framework/Timing/ThrottledFrameClock.cs
> +            }
After further testing I've updated to do the fallback to `Thread.Sleep`, although I couldn't find a case it would actually occur.

2022-11-10 06:08 UTC, smoogipoo approved these changes

2022-11-10 06:09 UTC, merged