Stop `OnDrag`, `OnDragEnd`, `OnMouseUp`, etc. from firing on removed / disposed drawables
ppy/osu-framework pull request #5557
Opened 2022-12-01 06:25 UTC by peppy

RFC

Closes ppy/osu#21294 and other similar cases.

Interested in whether people agree with this direction or not. I think there's valid arguments in both directions, but I'm leaning towards this feeling more developer / implementation friendly.

A similar approach could/should be applied to focus events to address issues like #5156 if this direction is decided on. Would likely be as simple as adding an `IsRooted` check around https://github.com/ppy/osu-framework/blob/2e3e66598a5ef14c8810cf498452fb3552975218/osu.Framework/Input/InputManager.cs#L409

2022-12-02 06:20 UTC, smoogipoo requested changes
Primary concern is performance. Need to mull over this one more

2022-12-02 06:20 UTC, smoogipoo commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
This is... expensive... Potentially an O(n^2) operation in case no clicks are ever handled (i.e. click in dead space, so like the background in gameplay).

2022-12-02 06:20 UTC, smoogipoo commented on osu.Framework/Input/ButtonEventManager.cs
> +#nullable enable
```suggestion
```

2022-12-02 06:20 UTC, smoogipoo commented on osu.Framework/Input/MouseButtonEventManager.cs
> +        protected WeakReference<Drawable> ClickedDrawable = new WeakReference<Drawable>(null!);
`TryGetTarget()` seems [annotated accordingly](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/WeakReference.T.cs,59), so maybe this can just be nullable?

2022-12-02 06:20 UTC, smoogipoo commented on osu.Framework/Input/MouseButtonEventManager.cs
> +            DraggedDrawable.Invalidated += draggedDrawableInvalidated;
Is this ever unbound?

2022-12-02 06:43 UTC, peppy commented on osu.Framework/Input/MouseButtonEventManager.cs
> +        protected WeakReference<Drawable> ClickedDrawable = new WeakReference<Drawable>(null!);
It gets weird if doing this (you'd have to `Debug.Assert` or conditionally check the `Drawable` is non-null after `TryGetTarget`), so I'd prefer to leave it like this.

2022-12-02 06:45 UTC, peppy commented on osu.Framework/Input/MouseButtonEventManager.cs
> +            DraggedDrawable.Invalidated += draggedDrawableInvalidated;
Oops maybe not.

2022-12-02 06:54 UTC, peppy commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
Yeah. Needs consideration.

2022-12-02 08:44 UTC, frenzibyte commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
An alternative way to approach this would be propagating to the intersection of the button down input queue and the current input queue (similar to how it's done in `handleClick`).

2022-12-02 09:23 UTC, smoogipoo commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
Yeah, I'd thought there was an existing case that did that. Sounds reasonable.

2023-07-19 15:44 UTC, peppy commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
This doesn't work because we want to send `MouseUp` even when the cursor has moved away from the drawable. Using the `Intersect` method will break this.

```diff
diff --git a/osu.Framework/Input/ButtonEventManager.cs b/osu.Framework/Input/ButtonEventManager.cs
index fe63172e2..37962586e 100644
--- a/osu.Framework/Input/ButtonEventManager.cs
+++ b/osu.Framework/Input/ButtonEventManager.cs
@@ -97,7 +97,7 @@ private void handleButtonUp(InputState state)
         {
             Debug.Assert(ButtonDownInputQueue != null);
 
-            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
+            HandleButtonUp(state, ButtonDownInputQueue.Intersect(InputQueue).ToList());
             ButtonDownInputQueue = null;
         }
 
```

Breaks this test:

https://github.com/ppy/osu-framework/blob/edb86a430aef51459af8e72f93e8cf6905293dd8/osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs#L409-L422

2023-07-22 12:10 UTC, bdach commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
So first of all...

> Potentially an O(n^2) operation in case no clicks are ever handled (i.e. click in dead space, so like the background in gameplay).

It does look expensive yes, but I'm not sure the performance characterisation above is correct? `ButtonDownInputQueue` is being enumerated eagerly due to the `.ToList()` at the end, so it means that the _entire_ button down queue has to be checked for rootedness, _all_ of the time. So doing this really just punishes deep drawable hierarchies, I think?

That said, I did some profiling, and I'm not sure whether I messed anything up, but it... doesn't look that tragic? I tested both on a [test scene I wrote quickly to exercise deep hierarchies](https://gist.github.com/bdach/715b618a1cd0ce8ad62518f08d5164ef), and game-side, and got this back:

| test | master | this PR |
| :- | :-: | :-: |
| test scene (N=20 boxes) | ![1690026525](https://github.com/ppy/osu-framework/assets/20418176/2b3b2459-cf80-4522-87d4-679cac9ac7a5) | ![1690026536](https://github.com/ppy/osu-framework/assets/20418176/c80b8884-774d-4df0-ad9c-dbe817ea8877) |
| test scene (N=40 boxes) | ![1690027329](https://github.com/ppy/osu-framework/assets/20418176/063c11f9-1ae1-4ac5-b312-18bd6702d9e4) | ![1690027340](https://github.com/ppy/osu-framework/assets/20418176/f479966f-b640-4298-9860-57be5e9eefd1) |
| game side | ![1690027350](https://github.com/ppy/osu-framework/assets/20418176/c3be6130-24c5-4dba-9db5-2800009077bf) | ![1690027583](https://github.com/ppy/osu-framework/assets/20418176/142b824d-1581-4edd-86e4-df81d5a57de9) |

which... doesn't look tragic?

That said, if the above is still a worry, then here's an idea: We already have `Drawable.GetContainingInputManager()`, and use it relatively often for stuff. How about if we made a property out of that? Would be

```csharp
public InputManager ContainingInputManager { get; }
```

and it would be backed by a `LayoutValue` which re-validates after `Invalidation.Parent`. It's probably going to be a bit involved to make happen, but maybe worthwhile?

2023-07-22 12:30 UTC, bdach commented
Looks fine to me, except for the performance discussion, but [I can't exactly see it being disastrous in profiling](https://github.com/ppy/osu-framework/pull/5557#discussion_r1271288786) - unless I'm looking wrong I guess.

2023-07-22 12:36 UTC, peppy commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
I think the suggestion sounds good, but likely adds complexity that we don't need until we hit a real-world performance issue from this. The profiling makes it looks maybe unnecessary. The only reason I'd consider it is that it's the kind of performance overhead which could go unnoticed, as it is only incurrent on a mouse click.

2023-07-22 12:41 UTC, bdach commented on osu.Framework/Input/ButtonEventManager.cs
> +            HandleButtonUp(state, ButtonDownInputQueue.Where(d => d.IsRootedAt(InputManager)).ToList());
There's also the part where I recall you saying a while back that you wanted input handling to be zero-alloc. I don't believe we ever fully got there, but there was a decent push to eliminate those a while back, and doing this `.ToList()` dump adds one again.

2023-07-22 13:28 UTC, peppy commented
Passes osu-side tests FWIW

![2023-07-22 22 28 30@2x](https://github.com/ppy/osu-framework/assets/191335/01f3126c-006a-4adb-bfd4-b37fe406abe6)

2023-07-22 13:35 UTC, bdach submitted a review, later dismissed

2023-07-24 11:24 UTC, smoogipoo commented
I'm seemingly unable to profile this effectively, but putting a stopwatch around it shows it usually spends anywhere from 0.2 to 0.5ms on average inside that method, sometimes spiking to several milliseconds.

I'll tentatively okay this for a merge, though I'm weary that due to the nature of the hierarchy any issues arising from this won't be discoverable.

2023-07-24 11:33 UTC, smoogipoo commented on osu.Framework/Graphics/DrawableExtensions.cs
> +            }
Shouldn't a drawable be "rooted" at itself?

2023-07-24 11:51 UTC, smoogipoo commented
As discovered in Discord convo, my stopwatch was profiling the whole `HandleButtonUp()` method call. It looks like this is well under 0.1ms in general.

2023-07-24 16:50 UTC, peppy commented on osu.Framework/Graphics/DrawableExtensions.cs
> +            }
as in this check should be done before the first parent navigation?

2023-07-24 16:55 UTC, bdach commented on osu.Framework/Graphics/DrawableExtensions.cs
> +            }
Sounds like it. Either that, or `do..while` I guess (although I'm never super sure if I'm correctly converting `while` to `do..while` in such cases...)

2023-07-24 18:29 UTC, peppy commented on osu.Framework/Graphics/DrawableExtensions.cs
> +            }
I prefer just having an explicit line here. Reads better.

2023-07-24 22:19 UTC, bdach approved these changes

2023-07-24 22:32 UTC, merged