Enforce presence of all fragment shader inputs in Veldrid
ppy/osu-framework pull request #5687
Opened 2023-03-19 06:32 UTC by frenzibyte

- Reverts https://github.com/ppy/osu-framework/commit/53272d8cafc35bb60c7e9ee40f17f41413e92435 in favour of this PR
- Closes https://github.com/ppy/osu/pull/22883
- [ ] Must revert https://github.com/ppy/osu-resources/pull/249

This works around D3D11 not working on shaders that don't make use of all members in the fragment input / vertex output. It seems D3D11 naturally expects all vertex output members are used in the fragment shader, and its optimisation of culling out unused fragment input members seems to affect the vertex output / fragment input structure.

One solution was to design localised vertex structures that match the needs of the fragment shader, but that turned out to be not pretty as time went and more shaders required this workaround.

This solution, on the other hand, prevents D3D11 from culling out unused fragment input by adding each of them via regex and passing them in the output structure.

Tested to work with Parallels, with no major changes performance-wise.

2023-03-19 07:28 UTC, smoogipoo requested changes
Seems okay, just a few nits.

2023-03-19 07:28 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +            int fragmentOutputLayoutIndex = shader_output_pattern.Matches(fragmentOutputCode).Count;
Isn't this the same as the `Output` field? Also I don't think `Count` is generally correct though for our common cases it will be - any reason for not using `Max(Output.Location)`?

2023-03-19 07:28 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +                fragmentOutputAssignment.AppendLine($"o_{attribute.Name} = {attribute.Name};");
I would probably give this a GUID. Something like `unused_{Guid.NewGuid().ToString("N")}`.

2023-03-19 07:42 UTC, frenzibyte commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +            int fragmentOutputLayoutIndex = shader_output_pattern.Matches(fragmentOutputCode).Count;
Good catch, didn't think this one properly.

2023-03-19 08:14 UTC, smoogipoo commented
> Must revert https://github.com/ppy/osu-resources/pull/249

Can you explain why it "must" be reverted? As far as I understand this change should work regardless?

2023-03-19 09:07 UTC, frenzibyte commented
Since the PR depends on osu!-side changes, it's better to revert it and close the osu!-side PR rather than the other way around.

Now that I look at it though, I thought the changes required osu! to use a different vertex type, but it seems the only changes required are just using the new vertex shader, so it's not that big of a deal.

2023-06-06 04:57 UTC, peppy commented
What's the status of this PR? Might be worth revisiting and closing if deemed unnecessary at this point, or bringing up-to-date.

2023-06-07 01:00 UTC, frenzibyte commented
It's still valid for merge and would avoid all the vertex shaders that were created specifically to work around this (e.g. `sh_Blur.vs` and `sh_LogoAnimation.vs`)

2023-06-07 03:00 UTC, peppy commented
👍 

Needs some conflict resolution at very least then

2023-06-07 05:00 UTC, frenzibyte commented
Have updated this now, but do note that I haven't tested it on DirectX because compiling and running on a VM is kind of a pain for me. Testing and making sure blurred framebuffers renders correctly on DirectX would be appreciated.

2023-06-08 01:35 UTC, smoogipoo requested changes

2023-06-08 01:35 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +            var unusedFragmentInput = vertexOutput.Where(a => !fragmentOutputCode.Contains(a.Name)).ToList();
Is there a reason for using name rather than layout index? Something like `vertexOutput.Where(vo => !Input.Any(fi => fi.Location == vo.Location))`.

Also sticking with the above naming, this would be `unusedVertexOutputs`.

2023-06-08 01:35 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +        public VeldridShaderPart WithFragmentOutput(IEnumerable<VeldridShaderAttribute> vertexOutput)
How about either `WithVertexOutput()` or  `WithPassthroughInput(IEnumerable<VeldridShaderAttribute> input)`?

2023-06-08 01:35 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +                fragmentOutputAssignment.Append($"o_{name} = {name};\n    ");
Would probably change to `__unused_o_{name}` or something like that, just to prevent potential naming conflicts.

2023-06-08 01:35 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +        public IReadOnlyList<VeldridShaderAttribute> Output { get; private set; } = new List<VeldridShaderAttribute>();
I feel like `Inputs` / `Outputs` works better but maybe this is okay.

2023-06-08 01:35 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +                Output = Output
The assigned lists don't have the added inputs/outputs, probably best to clone the lists and add them?

2023-06-12 10:44 UTC, frenzibyte commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +        public VeldridShaderPart WithFragmentOutput(IEnumerable<VeldridShaderAttribute> vertexOutput)
`WithPassthroughInput` sounds better, I'll go with that one.

2023-06-12 11:06 UTC, frenzibyte commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +        public IReadOnlyList<VeldridShaderAttribute> Output { get; private set; } = new List<VeldridShaderAttribute>();
Hmm, since it's countable let's go with `Inputs`/`Outputs`.

2023-06-12 11:09 UTC, frenzibyte commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +                Output = Output
I don't quite follow what you mean.

2023-06-12 11:45 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
> +                Output = Output
You're adding new inputs and outputs via `attributesLayout`. Those aren't included in the returned lists here.

2023-06-13 09:34 UTC, smoogipoo approved these changes

2023-06-13 09:48 UTC, merged