Move gamma correction logic from renderer/shader to vertex input
ppy/osu-framework pull request #5721
Opened 2023-03-30 00:47 UTC by frenzibyte

- Closes https://github.com/ppy/osu/issues/22990
- Alternative to / closes https://github.com/ppy/osu-framework/pull/5713

We've generally been passing colours to the shaders in linear space, and convert the colours within the shader into sRGB space.

In Veldrid, this broke colour blending on buffered containers, as can be seen here:
![image](https://user-images.githubusercontent.com/22781491/228691637-007afc15-bd83-49a0-b5b5-4c43977823ba.png)
(on the right is a box split into 50% and 100% opacity of the colour `#FF6633`, and on the left is the same but wrapped in a buffered container)

This breakage is essentially happening due to rendering happening in two stages and both the GPU driver and shader are incorrectly converting colour between sRGB and linear space until it ended up rendering the buffered container with a broken blend.

Rather than going through this fiasco, I've stopped both the renderer and the shader from ever applying any colour conversion in the shader, and I've instead let the framework pass colours to the shader in sRGB format.

The only difference this PR resulted in is `ColourInfo.Gradient{Horizontal,Vertical}` interpolating in sRGB space (gamma-incorrect), making it stand different from the other samples in the test scene:

![image](https://user-images.githubusercontent.com/22781491/228696485-1c6e3474-2cad-4489-9f0c-cb4164566b65.png)

But this matches both [browser](https://jsfiddle.net/uf621L3p/), and figma as well:

![CleanShot 2023-03-30 at 03 20 23](https://user-images.githubusercontent.com/22781491/228696604-eca66c21-bb9b-4f71-a69f-c11dce2d274e.png)

So we're pretty much golden. I've updated the test scene to point as such. We can also consider replacing `Interpolation.ValueAt(Colour4)` with two different versions specifying in which space colours are being blended in, but I'll leave that for a follow-up PR since this one is quite stuffed.

2023-03-30 11:43 UTC, peppy commented on osu.Framework/Graphics/Colour/SRGBColour.cs
> +        public readonly Vector4 ToVector() => new Vector4(SRGB.R, SRGB.G, SRGB.B, SRGB.A);
The code quality failures here are likely worth considering. At very least we'd want to reduce the copy count to one by moving the property access to a local field, or at best avoid it being a computed property in the first place.

```suggestion
        public readonly Vector4 ToVector()
        {
            var linear = Linear;
            return new Vector4(linear.R, linear.G, linear.B, linear.A);
        }
```

Although I don't see this inspection locally so I'm not sure where it's coming from..

2023-03-30 17:52 UTC, bdach commented on SampleGame/SampleGameGame.cs
I'm slightly weirded out that the display of `SampleGame` is being changed just for this pull. I'd have put the boxes in a test scene instead.

2023-03-30 17:52 UTC, bdach commented on osu.Framework/Graphics/Colour/SRGBColour.cs
> +    /// This struct converts to sRGB space by using the <see cref="SRGB"/> member.
After https://github.com/ppy/osu-framework/pull/5721/commits/afa5ebc97f71a680ba0d5fa71e8972622e959d22 this is no longer correct.

```suggestion
    /// Internally this struct stores the colour in sRGB space, which is exposed by the <see cref="SRGB"/> member.
    /// This struct converts to linear space by using the <see cref="Linear"/> member.
```

2023-03-30 17:52 UTC, bdach commented on osu.Framework/Graphics/Rendering/GlobalUniformData.cs
> +        private readonly UniformPadding12 pad1;
We have padding here and padding at the end of the global uniform block that comes out to 16 bytes total. Could/should we rearrange members here to consolidate the padding like [the other pull did](https://github.com/ppy/osu-framework/pull/5713/files#diff-1cd10e4e223070fbc73287aacb08684a05edd074e64f411ee595d2e5731fe4a2)?

2023-03-30 18:08 UTC, frenzibyte commented on SampleGame/SampleGameGame.cs
Uh, this was definitely not intended.

2023-03-30 18:13 UTC, frenzibyte commented on osu.Framework/Graphics/Colour/SRGBColour.cs
> +        public readonly Vector4 ToVector() => new Vector4(SRGB.R, SRGB.G, SRGB.B, SRGB.A);
I guess it's more of which is prominent in the codebase now (in terms of direct usages). I didn't notice the operators were widely used though.

2023-03-30 18:39 UTC, bdach commented on osu.Framework/Graphics/Colour/SRGBColour.cs
> +        public readonly Vector4 ToVector() => new Vector4(SRGB.R, SRGB.G, SRGB.B, SRGB.A);
That said on second thought draw nodes are subject to invalidation, so the `ApplyChild()` calls should be 99% one-and-done init logic. So optimising for reads and avoiding `.ToLinear()` calls on the cpu *is* probably what we want.

2023-03-30 20:23 UTC, Susko3 requested changes

2023-03-30 20:23 UTC, Susko3 commented on osu.Framework.Tests/Visual/Drawables/TestSceneGammaCorrection.cs
> +                        Text = $"{nameof(Interpolation)}.{nameof(Interpolation.ValueAt)}(Red, Red) with 1px boxes",
```suggestion
                        Text = $"{nameof(Interpolation)}.{nameof(Interpolation.ValueAt)}(Red, Blue) with 1px boxes",
```

2023-03-30 20:23 UTC, Susko3 commented on osu.Framework.Tests/Visual/Drawables/TestSceneGammaCorrection.cs
> +                        Text = $"{nameof(ColourInfo)}.{nameof(ColourInfo.GradientHorizontal)}(Blue, Red)"
```suggestion
                        Text = $"{nameof(ColourInfo)}.{nameof(ColourInfo.GradientHorizontal)}(Red, Blue)"
```

2023-03-31 11:02 UTC, peppy approved these changes

2023-03-31 11:22 UTC, smoogipoo approved these changes

2023-03-31 14:02 UTC, merged