Change transform loop to use a counter
ppy/osu-framework pull request #5737
Opened 2023-04-09 21:56 UTC by hwabis

Fixes https://github.com/ppy/osu-framework/issues/5445

But even with these changes, the storyboard here https://github.com/ppy/osu/issues/12401#issue-857227725 still takes forever to load.

2023-04-10 10:22 UTC, smoogipoo requested changes
At a surface level, without having profiled to see the results, I think this looks fine. Will need a review from peppy because he's more in depth with transforms.

2023-04-10 10:22 UTC, smoogipoo commented on osu.Framework/Graphics/Transforms/Transform.cs
>          public bool IsLooping { get; internal set; }
Is it possible to make this a `get`-only member, implemented like: `IsLooping => LoopCount > 0`, or is there a reason it's kept as a separate value?

2023-04-10 11:19 UTC, bdach requested changes

2023-04-10 11:19 UTC, bdach commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                            t.LoopCount--;
This PR breaks loops with finite counts. To reproduce, apply the following test:

```diff
diff --git a/osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs b/osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
index 023bd17f0..b2de05f53 100644
--- a/osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
+++ b/osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
@@ -343,6 +343,24 @@ public void LoopSequence()
             }
         }
 
+        [Test]
+        public void FiniteLoopSequence()
+        {
+            boxTest(box => { box.RotateTo(0).RotateTo(90, interval).Loop(0, 2); });
+
+            checkAtTime(0, box => box.Rotation == 0);
+            checkAtTime(interval - 1, box => Precision.AlmostEquals(box.Rotation, 90, 1));
+            checkAtTime(interval + 1, box => Precision.AlmostEquals(box.Rotation, 0, 1));
+            checkAtTime(2 * interval - 1, box => Precision.AlmostEquals(box.Rotation, 90, 1));
+
+            checkAtTime(3 * interval - 1, box => Precision.AlmostEquals(box.Rotation, 90, 1));
+
+            checkAtTime(2 * interval - 1, box => Precision.AlmostEquals(box.Rotation, 90, 1));
+            checkAtTime(interval + 1, box => Precision.AlmostEquals(box.Rotation, 0, 1));
+            checkAtTime(interval - 1, box => Precision.AlmostEquals(box.Rotation, 90, 1));
+            checkAtTime(0, box => box.Rotation == 0);
+        }
+
         [Test]
         public void StartInMiddleOfLoopSequence()
         {
```

Passes on `master`, fails on this branch. I strongly suspect (but haven't confirmed) this decrement to be incorrect without a corresponding increment when rewindable transforms are played back in the backward direction.

2023-04-10 20:15 UTC, hwabis commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                            t.LoopCount--;
Yes, applied

2023-04-10 20:24 UTC, hwabis commented on osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
> +                            t.LoopCount--;
Added the test and it's passing now.

I don't think it was about adding a `LoopCount` increment (although would it still make sense to have it somewhere?), but it was in `makeTransformsLooping`. (See the `pushForwardCount` part. Example: a transform list of `0-0ms 0->0deg, 0-250ms 0->90deg` makes `sortedTransforms` become `0-250ms 0->90deg, 250-250ms 0->0deg`, so we decrement the `LoopCount` for that shifted transform.)

2023-04-13 16:30 UTC, hwabis commented on osu.Framework/Graphics/Transforms/Transform.cs
>          public bool IsLooping { get; internal set; }
Applied

2023-04-14 13:57 UTC, peppy commented
I believe this looks quite correct now. Let's hope no one was using `LoopCount` and expecting it to be immutable from the user set value (probably unlikely).

2023-04-14 13:57 UTC, peppy approved these changes

2023-04-18 09:40 UTC, peppy commented
I'm gonna get this one in since I'm pretty confident. Will deal with any fallout after it's discovered.

2023-04-18 10:14 UTC, peppy approved these changes

2023-04-18 10:15 UTC, merged