Add source generator for IsLongRunning property
ppy/osu-framework pull request #5763
Opened 2023-04-29 00:32 UTC by smoogipoo

Prereqs:
- [ ] https://github.com/ppy/osu-framework/pull/5760

Removes yet another reflection usage inside `Drawable`.

2023-05-10 20:22 UTC, bdach requested changes
Rest of dependency injection tests need updating (see CI). Other than that source looks okay, though I have not done testing.

2023-05-10 20:22 UTC, bdach commented on osu.Framework.SourceGeneration/SyntaxHelpers.cs
> +            => type?.Name == "LongRunningLoadAttribute";
This only checks the direct type name again rather than fully qualified, but given the surrounding code I'm probably more willing to look away.

2023-06-25 06:44 UTC, bdach commented
Have fixed merge conflicts and resolved blockers. @smoogipoo please check on my changes where able and take a look whether I haven't broken anything.

If everything looks okay I'll proceed with further testing with game prior to merge.

2023-06-26 04:17 UTC, smoogipoo commented
Only thing is, I want to see if this can be changed to use the same structure as https://github.com/ppy/osu-framework/pull/5761

2023-07-07 11:25 UTC, closed without merging