Make frame statistics display usable on mobile platforms
ppy/osu-framework pull request #5897
Opened 2023-07-06 00:23 UTC by frenzibyte

RFC. Only affects debug builds.

This pull request adds the following features:
- Double-click on any area on the bottom right corner of the screen to cycle between frame statistics display (and also make it visible from hidden state).
- Tap with a single finger to expand the frame statistics display when in full state (similar to holding <kbd>Ctrl</kbd>).
- Tap with a second finger to freeze the frame statistics display (similar to holding <kbd>Shift</kbd>).

Definitely not the best UX, but it would help to have anything like this to easily view the frame graphs and counters without modifying my builds and waiting for compilation every time.

2023-07-06 03:35 UTC, peppy requested changes

2023-07-06 03:35 UTC, peppy commented on osu.Framework/Game.cs
> +            protected override bool OnClick(ClickEvent e) => true;
Have you tested this with osu..? It feels like blocking clicks in this area could have adverse effects?

Any reason it's not only handling touch as well?

2023-07-06 03:35 UTC, peppy commented on osu.Framework/Game.cs
> +                Add(new FrameStatisticsTouchReceptor(this)
Should this be `AddInternal`? This is going to add inside user defined content, which will likely break in some cases.

2023-07-06 03:35 UTC, peppy commented on osu.Framework/Game.cs
> +                Add(new FrameStatisticsTouchReceptor(this)
Almost think it would be better off to have this be a visible element on the screen for touch devices so you know where to interact with it.

2023-07-06 03:35 UTC, peppy commented on osu.Framework/Graphics/Performance/PerformanceOverlay.cs
> +                    if (State == FrameStatisticsMode.Full)
This would work better if it only expanded while holding, and reverted on `TouchUp`. Same goes for the two finger version below.

2023-07-06 03:40 UTC, frenzibyte commented on osu.Framework/Game.cs
> +            protected override bool OnClick(ClickEvent e) => true;
The component is placed below everything in the game, so as long as absolutely nothing handles click at the moment I touch the screen, the game will respond to that and handle the double click to cycle between frame statistics modes.

2023-07-06 03:42 UTC, frenzibyte commented on osu.Framework/Game.cs
> +                Add(new FrameStatisticsTouchReceptor(this)
Sure, it can be `AddInternal`, but I don't know about making it visible, I would hope for it to be as hidden as possible so it doesn't potentially obscure anything in the area it handles.

2023-07-06 03:44 UTC, frenzibyte commented on osu.Framework/Graphics/Performance/PerformanceOverlay.cs
> +                    if (State == FrameStatisticsMode.Full)
For sure, that was how I had it initially, but I switched to this behaviour because originally I made the performance overlay change modes by holding in the bottom-right area, which was conflicting with this. But now that I changed it to double-click, we can make this work using hold instead.

2023-07-08 01:04 UTC, frenzibyte commented on osu.Framework/Game.cs
> +            if (DebugUtils.IsDebugBuild)
I've touched on this in OP, but this line has been a burden ever since I've first utilised this PR for my investigations. Because, in order for the numbers to have any meaning, I need to build in "release" mode with AOT enabled. And 99% the times I would forget to comment this line, and the end up waiting another 30 minutes for another build which has this line commented.

How opposed would you be towards making an envvar for this instead? That way I can have local run configurations which enable this, but mainly I wouldn't have to wait for another build to have the receptor added.

2023-07-11 14:15 UTC, smoogipoo commented on osu.Framework/Game.cs
> +            if (Environment.GetEnvironmentVariable("OSU_FRAME_STATISTICS_VIA_TOUCH") == "1" || DebugUtils.IsDebugBuild)
Move to `FrameworkEnvironment` please.

2023-07-12 03:42 UTC, peppy approved these changes

2023-07-12 05:56 UTC, merged