Avoid initialising textures when unnecessary
ppy/osu-framework pull request #5901
Opened 2023-07-06 07:19 UTC by peppy

It turns out we were initialising every mipmap level of every textures, while it is only actually required in scenarios we are not already replacing every pixel of the texture.

For framework usages, this is for atlases alone.

I've implemented this by changing the `initialisationColour` to be nullable. For native textures, it has a `null` default, which is perfect to cover all overrides (`VideoTexture` and `FrameBufferTexture`).

For the `IRenderer` exposed usage, the parameter was already required, so there is no default. This is good as it ensures a consume isn't going to see a change in behaviour out-of-the-blue.

2023-07-06 08:34 UTC, smoogipoo requested changes

2023-07-06 08:34 UTC, smoogipoo commented on osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
> +        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, not initialisation is provided out-of-the-box.</param
```suggestion
        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, no initialisation is provided out-of-the-box.</param>
```

2023-07-06 08:34 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/IRenderer.cs
> +        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, not initialisation is provided out-of-the-box.</param
```suggestion
        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, no initialisation is provided out-of-the-box.</param>
```

2023-07-06 08:34 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Renderer.cs
> +        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, not initialisation is provided out-of-the-box.</param
```suggestion
        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, no initialisation is provided out-of-the-box.</param>
```

2023-07-06 08:34 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
> +        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, not initialisation is provided out-of-the-box.</param
```suggestion
        /// <param name="initialisationColour">The colour to initialise texture levels with (in the case of sub region initial uploads). If null, no initialisation is provided out-of-the-box.</param>
```

2023-07-07 09:49 UTC, smoogipoo approved these changes

2023-07-07 10:02 UTC, merged

2023-07-08 01:19 UTC, frenzibyte reviewed
Late review but this looks pretty good.