Add a fence pool for frame tracking fences
ppy/osu-framework pull request #5921
Opened 2023-07-11 05:07 UTC by peppy

Ignoring the fact that these tracking fences are doing nothing in D3D (they are set immediately https://github.com/ppy/veldrid/blob/6a43198af1b069e56ac53770249a5424c1859500/src/Veldrid/D3D11/D3D11GraphicsDevice.cs#L229-L232):

This is a regression so let's fix it locally for the time being.

Time spent in `ManualResetEvent` construction:

![Parallels Desktop 2023-07-11 at 05 01 20](https://github.com/ppy/osu-framework/assets/191335/42f7bfa6-7147-4634-a0c7-89f55aed2406)

Before this PR:

![Parallels Desktop 2023-07-11 at 05 07 32](https://github.com/ppy/osu-framework/assets/191335/ea5a597e-0841-488c-b1b5-9f37e6a22a5e)

After this PR:

![Parallels Desktop 2023-07-11 at 05 05 52](https://github.com/ppy/osu-framework/assets/191335/4f5d4555-ef15-498f-a6b7-13a0c29a2e39)

2023-07-11 05:11 UTC, smoogipoo requested changes

2023-07-11 05:11 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
> +            for (int i = 0; i < 16; i++)
Is this 16 a magic number? What happens in the (unlikely) even that the pool runs dry, crash on `Dequeue()`?

2023-07-11 05:14 UTC, peppy commented on osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
> +            for (int i = 0; i < 16; i++)
Yep. On metal I've never seen usages increase above 1. If we exceed 3 then we're probably going to see texture corruption and stuff elsewhere though? I can use 3 instead of 16 if it feels more robust.

2023-07-11 05:15 UTC, peppy commented on osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
> +            for (int i = 0; i < 16; i++)
Or we can change it to add to the pool locally, should also be fine.

2023-07-12 11:06 UTC, peppy commented
I think we still want this in, at least for now. Can potentially be reverted if we decide we don't want end-of-frame fencing on all platforms.

2023-07-12 12:30 UTC, smoogipoo approved these changes

2023-07-12 12:31 UTC, merged