Improve vertex upload performance significantly on iOS
ppy/osu-framework pull request #5931
Opened 2023-07-15 12:36 UTC by frenzibyte

- Closes https://github.com/ppy/osu-framework/issues/5920

With the new performance test scenes we have, VBO uploads have shown to be quite poor on iOS, even when building in AOT.

After multiple days of investigation (interrupted by regressions in our rendering systems), it turns out the intermediate vertex storage allocated in `VeldridVertexBuffer` have a significant hit on performance. In an isolated environment, there's +5ms aggregate CPU overhead when uploading to an intermediate vertex storage followed by uploading to the GPU buffer, from uploading & drawing 10k quads.

Shaving that overhead off improves performance on iOS significantly, especially in scenes with a high number of vertex uploads:
| `master` | this PR |
|----------|---------|
| ![IMG_6194](https://github.com/ppy/osu-framework/assets/22781491/f5830571-1c46-4a3d-a38f-e9b5710f9dbe) | ![IMG_6203](https://github.com/ppy/osu-framework/assets/22781491/9815838b-8fad-4b6f-abd9-e8f6acd49926) |
| ![IMG_6195](https://github.com/ppy/osu-framework/assets/22781491/496497db-f244-4ee4-a5f4-3098f78b8c0b) | ![IMG_6204](https://github.com/ppy/osu-framework/assets/22781491/5e2557c2-f688-43ef-b33c-91c1e5c7fc70) |
| ![IMG_6196](https://github.com/ppy/osu-framework/assets/22781491/d7d6e751-2a75-4221-9b37-1de7367ee793) | ![IMG_6205](https://github.com/ppy/osu-framework/assets/22781491/b585eeb2-253a-40ff-98bc-45d8f92d0172) |

To add this into our implementation appropriately, I've took the time to refactor index buffer storage to become separated from `VeldridVertexBuffer` (and also make more sense), @smoogipoo requesting your review to make sure you're on board with this new structure.

Initially I didn't want to make this change since it keeps on increasing the diversity between backends within the framework project while it still uses Veldrid, but the resultant gain is 100% worth it. Eventually I plan to work on a Metal renderer implementation away from Veldrid, using .NET's API that's shipped with iOS / Mac Catalyst. But for now, I've added this as a separate VBO class for Metal renderers specifically.

2023-07-15 12:57 UTC, smoogipoo commented
Can you also test desktop in the same situation? I tried this a long time ago (before the VBO invalidation work that's been put on the backburner - maybe time to bring that back...) and found similar results that in general we'd get higher FPS by not doing the deduping, but there were certain scenarios where that would fall apart. I can't remember the exact case though, so I hope it's reached by the test cases...

@peppy I also want you to test this on desktop metal, on your x86 PC.

2023-07-15 17:26 UTC, frenzibyte commented
M1 Pro:
| `master` | this PR |
|----------|---------|
| ![CleanShot 2023-07-15 at 20 25 01](https://github.com/ppy/osu-framework/assets/22781491/2701acb6-0a6f-4d2f-bfb4-1b2d3c8ca0c6) | ![CleanShot 2023-07-15 at 20 23 17](https://github.com/ppy/osu-framework/assets/22781491/5010f74b-0a75-4801-a0c0-b25b631d2799) |
| ![CleanShot 2023-07-15 at 20 25 16](https://github.com/ppy/osu-framework/assets/22781491/1243516a-5eb0-4c62-b516-6824e470f60c) | ![CleanShot 2023-07-15 at 20 23 32](https://github.com/ppy/osu-framework/assets/22781491/797e30f4-cb7f-4837-8ca3-900c4cd7b379) |
| ![CleanShot 2023-07-15 at 20 24 01](https://github.com/ppy/osu-framework/assets/22781491/1bee302d-a9f5-42bd-ade7-7a48e66f978f) | ![CleanShot 2023-07-15 at 20 25 21](https://github.com/ppy/osu-framework/assets/22781491/3419a4e4-8123-4284-9741-391510ba7cb8) |

2023-07-16 04:28 UTC, peppy commented
M2 (minor improvements across the board):

| Before | After |
|:------:|:-----:|
| ![2023-07-16 13 24 07@2x](https://github.com/ppy/osu-framework/assets/191335/e2731f0a-3a21-4f79-8762-6f89283bb8de) | ![2023-07-16 13 21 07@2x](https://github.com/ppy/osu-framework/assets/191335/f717a5ec-63cc-4ac3-9d97-411bcc8af652) |
| ![2021-09 13 23 30@2x](https://github.com/ppy/osu-framework/assets/191335/b88e5a35-3f26-46ed-a524-e48cd727016d) | ![2023-07-16 13 20 36@2x](https://github.com/ppy/osu-framework/assets/191335/70014205-e80e-4775-b71a-32433c612478) |
| ![2021-09 13 22 53@2x](https://github.com/ppy/osu-framework/assets/191335/44ab4e35-8ed1-4fd2-a652-c93876dc25be) | ![2023-07-16 13 25 35@2x](https://github.com/ppy/osu-framework/assets/191335/08ad394d-5c43-434d-b2f1-fba3d6b2eeb1) |

2023-07-16 05:44 UTC, peppy commented
macOS / Intel / AMD (considerable improvements across the board!):

| Before | After |
|:------:|:-----:|
| ![osu Framework Tests 2021-09 at 05 41 58](https://github.com/ppy/osu-framework/assets/191335/a6f4c42b-26ef-4f78-b6b3-9b6d034031f9) | ![osu Framework Tests 2023-07-16 at 05 39 49](https://github.com/ppy/osu-framework/assets/191335/a754aa4c-497c-45a7-9f84-dd47a0902994) |
| ![osu Framework Tests 2021-09 at 05 41 19](https://github.com/ppy/osu-framework/assets/191335/deaa8776-6d2f-48fa-a7fa-f5a148f5afea) | ![osu Framework Tests 2023-07-16 at 05 40 42](https://github.com/ppy/osu-framework/assets/191335/3fd70488-19bc-4739-945f-db71c3ea5398) |
| ![osu Framework Tests 2021-09 at 05 41 34](https://github.com/ppy/osu-framework/assets/191335/ca62cd88-8289-4f99-8fd0-2078c9219280) | ![osu Framework Tests 2023-07-16 at 05 40 19](https://github.com/ppy/osu-framework/assets/191335/aad90097-e125-426a-b91f-775e5904564c) |

2023-07-16 07:54 UTC, peppy commented
Windows / Direct X / Nvidia (no difference / within error margins):


| Before | After |
|:------:|:-----:|
|![osu Framework Tests_2023-07-16_16-49-57](https://github.com/ppy/osu-framework/assets/191335/81a7ec34-b9fa-4bc0-bcdf-f36aa15ca573)|![image](https://github.com/ppy/osu-framework/assets/191335/9952901d-3f5e-4005-8143-63a61f0fd43f)|
|![image](https://github.com/ppy/osu-framework/assets/191335/40fc471e-713b-4288-82db-990461724aa9)|![image](https://github.com/ppy/osu-framework/assets/191335/b04aaf5c-bba1-4591-aa31-bab9bdea24b7)|
|![image](https://github.com/ppy/osu-framework/assets/191335/566d24fb-17ab-4e13-bec8-15004227715b)
|![image](https://github.com/ppy/osu-framework/assets/191335/54db36f9-1c57-4cb8-b5aa-582466157c6f)|

2023-07-16 08:22 UTC, smoogipoo commented
As far as I can tell this isn't enabled on D3D, so unless you're making those changes yourself you wouldn't see a difference.

2023-07-16 08:27 UTC, frenzibyte commented
Yeah backends other than Metal are unaffected in this PR.

2023-07-16 15:27 UTC, peppy commented
> As far as I can tell this isn't enabled on D3D, so unless you're making those changes yourself you wouldn't see a difference.

yep, i was just testing to confirm there was no regression mostly.

2023-07-18 07:08 UTC, peppy submitted a review, later dismissed
As far as I can tell this performs and is structured fine.

@smoogipoo will need your review

2023-07-20 18:12 UTC, smoogipoo approved these changes
As always, my concern with these sorts of changes is still undefined GPU behaviour. I just hope our double-triple-buffered VBOs is enough, and given that others have tested it and haven't experienced glitchiness, I'm willing to give this a pass.

2023-07-20 18:17 UTC, smoogipoo requested changes

2023-07-20 18:17 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
> +            renderer.BindIndexBuffer(VeldridIndexLayout.Quad, Size);
Is this supposed to change depending on the layout type?

2023-07-20 18:25 UTC, frenzibyte commented on osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
> +            renderer.BindIndexBuffer(VeldridIndexLayout.Quad, Size);
Yes, my bad.

2023-07-20 18:32 UTC, frenzibyte commented
> As always, my concern with these sorts of changes is still undefined GPU behaviour. I just hope our double-triple-buffered VBOs is enough, and given that others have tested it and haven't experienced glitchiness, I'm willing to give this a pass.

And this behaviour is specific to us not 100% guarding against access between CPU & GPU using fences and what not, right? Asking just to confirm knowledge, not hinting at anything.

2023-07-21 06:14 UTC, smoogipoo approved these changes

2023-07-21 06:14 UTC, merged

2023-07-21 06:14 UTC, smoogipoo commented
> And this behaviour is specific to us not 100% guarding against access between CPU & GPU using fences and what not, right

Yes, that's correct.