Implement window flashing
ppy/osu-framework pull request #5970
Opened 2023-08-19 02:23 UTC by ItsShamed

The implementation is quite simple (thanks to SDL), but what worries me is _where_ it should be implemented and/or exposed.

Currently, the behaviour is implemented in `SDL2DesktopWindow` as it makes more sense due to window flashing being exclusive to desktops, and it is exposed in `DesktopGameHost`, which is a class that can be accessed by consumer games through DI and (safe-)casting and that can access internal `IWindow` implementations – in this case, it would be the bridge between the game and the framework's windowing internals.

It could be argued that the implementation in `SDL2DesktopWindow` is redundant and everything could be implemented in `DesktopGameHost` by gathering the window handle via `(Window as SDL2Window)?.SDLWindowHandle` for example – and I'd agree with that, it's just a matter of opinions and what feels best. 
Leaving like that for the time being unless instructed otherwise.

2023-08-19 12:55 UTC, bdach requested changes

2023-08-19 12:55 UTC, bdach commented on osu.Framework/Platform/DesktopGameHost.cs
> +        public void CancelWindowFlashing() => (Window as SDL2DesktopWindow)?.CancelFlash();
Disagree with proxying windowing methods to `DesktopGameHost`. Nothing else does this, even though we already have platform-exclusive windowing things.

Please add to `IWindow` instead, and throw `NotSupportedException` in the `OsuTKWindow` implementation. This doesn't matter for our uses since that's an only-android thing. Consumers can go through `host.Window` instead.

2023-08-19 12:55 UTC, bdach commented on osu.Framework.Tests/Visual/Platform/TestSceneWindowFlash.cs
> +    public partial class TestSceneWindowFlash : FrameworkTestScene
Should be ignored on CI

```csharp
    [Ignore("This test cannot run in headless mode (a window instance is required).")]
```

2023-08-20 02:58 UTC, peppy commented on osu.Framework/Platform/OsuTKWindow.cs
> +        public void Flash(bool _) => throw new NotSupportedException("OsuTK windows can't flash.");
Should probably be `PlatformNotSupportedException`?

Also I question how we implement this as a consumer. Do we have to read the documentation, realise it only works with a desktop game window and do a pre-check for that? If so, the xmldoc should explicitly reference that class. Alternatively, we could make this a no-op instead if that's deemed as easier for usage.

2023-08-20 03:27 UTC, ItsShamed commented on osu.Framework/Platform/OsuTKWindow.cs
> +        public void Flash(bool _) => throw new NotSupportedException("OsuTK windows can't flash.");
> Alternatively, we could make this a no-op instead if that's deemed as easier for usage.

Yes, that's probably better and that was what I initially did (idk why I did all that refactoring 😅)

2023-08-20 03:29 UTC, ItsShamed commented
Also, what should be the default behaviour? Should it flash briefly or until focused? (I'd tend to choose the former personally)

2023-08-21 10:45 UTC, peppy approved these changes

2023-08-21 13:21 UTC, bdach approved these changes

2023-08-21 13:32 UTC, merged