Reduce FFmpeg binary size
ppy/osu-framework pull request #5981
Opened 2023-08-23 19:50 UTC by FreezyLemon

Closes #5974.

Prerequisite:
- [ ] #5980 

macOS (universal dylibs): 37 -> 11 MiB
Windows, Linux: ~20 -> 6 MiB

[Build artifacts](https://github.com/FreezyLemon/osu-framework/actions/runs/5952479124) can be downloaded from my fork for testing.

Significant changes:
- Only enable features as described in #5974
- Enable link-time optimizations (LTO). This slightly increases the binary sizes (<5%), but can increase performance
- Use FFmpeg's built-in `--install-name-dir` option for macOS binaries, no `install_name_tool` necessary
  -> I checked the dylibs with a linux-compatible `otool` implementation, so I'm pretty sure this works correctly. Someone should double-check this on macOS though.
- Specify the "pipe" protocol when setting up the decoder. This is a sort of "optimization hint" for demuxers/decoders, so they can optimize for accessing local resources, and has no other effect since the framework provides custom I/O. The mov/mp4 demuxer will log an info message on every setup without this

The binary size can be reduced further by disabling specific (or all) assembly optimizations, but this is not a great idea unless binary size is more important than performance and/or compatibility.

2023-08-24 01:19 UTC, smoogipoo commented
I like the script changes :+1:

2023-08-24 01:29 UTC, smoogipoo requested changes

2023-08-24 01:29 UTC, smoogipoo commented on .github/workflows/build-ffmpeg.yml
> +    runs-on: ubuntu-22.04
I don't think this is okay, because it targets a different glibc. All of our other libraries (e.g. [sdl2](https://github.com/ppy/SDL2-CS/blame/master/.github/workflows/build.yml)) are compiled against 20.04.

2023-08-24 10:23 UTC, FreezyLemon commented
[New build artifacts](https://github.com/FreezyLemon/osu-framework/actions/runs/5962126733)

2023-08-24 15:20 UTC, peppy approved these changes
Tested to work well on macOS (intel / apple)

2023-08-29 08:45 UTC, bdach commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +            int openInputResult = ffmpeg.avformat_open_input(&fcPtr, "pipe:", null, null);
Out of curiosity mostly, what's this change about?

2023-08-29 08:46 UTC, bdach commented
On linux, vp9 spews a bit in the test scene with hardware decoding enabled:

```
[runtime] 2023-08-29 08:44:30 [debug]: MouseClick handled by "load vp9.webm" SingleStepButton.
[runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid argument (-22)
[runtime] 2023-08-29 08:44:30 [verbose]: Disabling hardware decoding of the current video due to an unexpected error
[runtime] 2023-08-29 08:44:30 [verbose]: Successfully initialized decoder: vp9
[vp9 @ 0x7fac500db500] Not all references are available
[runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid data found when processing input (-1094995529)
[vp9 @ 0x7fac500db500] Not all references are available
[runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid data found when processing input (-1094995529)
[vp9 @ 0x7fac500db500] Not all references are available
[runtime] 2023-08-29 08:44:30 [verbose]: Failed to receive frame from avcodec: Invalid data found when processing input (-1094995529)
[vp9 @ 0x7fac500db500] Not all references are available
[runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid data found when processing input (-1094995529)
[vp9 @ 0x7fac500db500] Not all references are available
```

Doesn't happen on `master` - any ideas?

2023-08-29 09:14 UTC, FreezyLemon commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +            int openInputResult = ffmpeg.avformat_open_input(&fcPtr, "pipe:", null, null);
Some demuxers like to know which protocol is being used when initializing. For example, a networked stream and a local file stream have different default settings.

If no protocol can be found, these demuxers (e.g. mov/mp4) will [print a warning](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/a77521cd5d27e955b16e8097eecefc779ffdcb6d:/libavformat/utils.c#l2114) on every initialization.

Using `pipe` specifically is a bit arbitrary, but it's a protocol that's cheap to compile, and what the framework does is similar to piping input so I figured it makes sense to specify here.

(This is not necessary on master, I think it defaults to another protocol like `file`. Not 100% sure)

2023-08-29 09:18 UTC, FreezyLemon commented
> On linux, vp9 spews a bit in the test scene with hardware decoding enabled:
> 
> ```
> [runtime] 2023-08-29 08:44:30 [debug]: MouseClick handled by "load vp9.webm" SingleStepButton.
> [runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid argument (-22)
> [runtime] 2023-08-29 08:44:30 [verbose]: Disabling hardware decoding of the current video due to an unexpected error
> [runtime] 2023-08-29 08:44:30 [verbose]: Successfully initialized decoder: vp9
> [vp9 @ 0x7fac500db500] Not all references are available
> [runtime] 2023-08-29 08:44:30 [verbose]: Failed to send avcodec packet: Invalid data found when processing input (-1094995529)
> ...
> ```
> 
> Doesn't happen on `master` - any ideas?

Did you manually click through the test scene, or just let it run normally? Errors like these usually appear when enabling or disabling HW acceleration while playback is running. This also happens on master for me.

2023-08-29 09:27 UTC, bdach commented
> Did you manually click through the test scene, or just let it run normally? Errors like these usually appear when enabling or disabling HW acceleration while playback is running. This also happens on master for me.

Nope, also happens when running the test scene start-to-end via either the visual test browser or just via headless runner. Definitely not something that happens on `master`.

2023-08-29 09:40 UTC, FreezyLemon commented
I see. It's probably a genuine error then.

Could you check which hardware device type (`hwDeviceType`) is set when the decoder initializes? And what GPU(s) do you have that could be used for HW acceleration?
Maybe compare if it's the same device type being initialized on master.

Error -22 is `EINVAL` so it's not a true decoding error and more of an initialization error.

2023-08-29 10:04 UTC, bdach commented
> And what GPU(s) do you have that could be used for HW acceleration?

```
$ nvidia-smi -L 
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU (UUID: GPU-d424d500-c6a7-40f8-60de-056b52cf028c)
```

> Could you check which hardware device type (`hwDeviceType`) is set when the decoder initializes?

master:

```
[runtime] 2023-08-29 10:01:31 [verbose]: 🔸 Step #68 load vp9.webm
[runtime] 2023-08-29 10:01:31 [verbose]: Attempting to initalize device type AV_HWDEVICE_TYPE_NONE
[runtime] 2023-08-29 10:01:31 [verbose]: Successfully initialized decoder: vp9
[runtime] 2023-08-29 10:01:31 [verbose]: 🔸 Step #69 Wait for video to load
[runtime] 2023-08-29 10:01:31 [verbose]: 🔸 Step #70 Reset clock
[runtime] 2023-08-29 10:01:31 [verbose]: 🔸 Step #71 Wait for decode start
```

with new binaries:

```
[runtime] 2023-08-29 10:02:19 [verbose]: 🔸 Step #68 load vp9.webm
[runtime] 2023-08-29 10:02:19 [verbose]: Attempting to initalize device type AV_HWDEVICE_TYPE_VDPAU
[runtime] 2023-08-29 10:02:19 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VDPAU for codec vp9
[runtime] 2023-08-29 10:02:19 [verbose]: Successfully initialized decoder: vp9
[runtime] 2023-08-29 10:02:19 [verbose]: Failed to send avcodec packet: Invalid argument (-22)
[runtime] 2023-08-29 10:02:19 [verbose]: Disabling hardware decoding of the current video due to an unexpected error
[runtime] 2023-08-29 10:02:19 [verbose]: Attempting to initalize device type AV_HWDEVICE_TYPE_NONE
[runtime] 2023-08-29 10:02:19 [verbose]: Successfully initialized decoder: vp9
```

Kinda weirded out that master just... didn't try any actual hardware decoding at all? That's not something I was aware of. Joys of silent fallbacks I guess.

Notably it's not a VDPAU-specific thing earlier, because VDPAU played a video just fine earlier:

```
[runtime] 2023-08-29 10:02:17 [verbose]: 🔸 Step #58 load hevc.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4780bfb790] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[runtime] 2023-08-29 10:02:17 [verbose]: Attempting to initalize device type AV_HWDEVICE_TYPE_VDPAU
[runtime] 2023-08-29 10:02:17 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VDPAU for codec hevc
[runtime] 2023-08-29 10:02:17 [verbose]: Successfully initialized decoder: hevc
[runtime] 2023-08-29 10:02:17 [verbose]: 🔸 Step #59 Wait for video to load
```

2023-08-29 11:33 UTC, FreezyLemon commented
> Kinda weirded out that master just... didn't try any actual hardware decoding at all? That's not something I was aware of.

Unlike Video Toolbox on macOS/Media Foundation on Windows, VAAPI and VDPAU are not built-in libraries in Linux. So even with FFmpegs 'autodetect' mode enabled, they'd never get linked into the FFmpeg libraries unless they're explicitly installed on the build host. So I guess they were never included on Linux.

Anyways, regarding the error: Is it possible it's a driver issue or something on your system? Can you check if hardware decoding VP9 works outside of osu, for example in a browser or in a video player like mpv?

The fallback to swdec seems to work, now the question is just whether there's a problem with the VP9 codec, or it's a local problem causing vp9 hwdec to fail.

2023-10-02 16:34 UTC, bdach commented
Sorry for the wait, decided this has waited long enough for its turn on my private todo list.

On checking closer, VLC is also failing to use VDPAU for that vp9-encoded video. I think I'm just gonna look away, the software fallback works pretty well.

I'll run these binaries past windows before approving.

2023-10-02 19:21 UTC, bdach approved these changes

2023-10-03 01:27 UTC, peppy approved these changes

2023-10-03 01:27 UTC, merged