Add new `DecouplingClock` and obsolete `DecoupleableInterpolatingFramedClock`
ppy/osu-framework pull request #6001
Opened 2023-09-22 06:37 UTC by peppy

# Add new `DecouplingClock` and obsolete `DecoupleableInterpolatingFramedClock`

## Clocks, explained

Clocks have been painful, but they were never intended to be. The system should conceptually be simple:

- All clocks have a `CurrentTime`.
- A framed clock (`IFrameBasedClock`) is processed (via `ProcessFrame`) by the consumer every frame and can therefore provide elapsed time.
- An adjustable clock (`IAdjustableClock`) exposes the ability to be `Start`ed, `Stop`ped, `Seek`ed and `Reset`. This is most commonly used to bring audio tracks into the clock system.
- A clock may contain a source clock (via `ISourceChangeableClock`), to allow nesting clocks inside each other. This can be used to add more complex behaviours to existing clocks via composition.

These are the basic governing rules. Let's look at the two main cases for nesting clocks:

- Interpolation via `InterpolatingFramedClock` (aka allowing `CurrentTime` to be more precise than the underlying audio subsystem via interpolation). This one is pretty simple, and has been recently cleaned up via https://github.com/ppy/osu-framework/pull/5992.
- Decoupling (aka allowing a track to play in negative time, or beyond the end of the track, for lead-in / lead-out purposes), historically via `DecoupleableInterpolatingFramedClock`. This is the thorn in the clock system.

## What was wrong with this class?

- It was inheriting `InterpolatingFramedClock`, overriding some pieces but also adding its own complexity on top. It was nigh impossible to follow the cross-interactions between these two implementations. It should have been implemented as its own stand-alone implementation which only decoupled
- It was doing random shit. Like literally, wild west in terms of what behaviours it decided to apply. These were "well tested", but also meant workarounds all over the place osu! side because attempting to fix anything may results in the rest of the house of cards falling down.

So really, the only thing that needs to be fixed (from the framework perspective) when I've said "clocks are fucked" many times over the years is this one implementation. I've rewritten it from scratch with everything I've learned over the years and with the above mistakes in mind. The new class is called 'DecouplingClock'.

## Behaviour differences

## Stand-alone

`DecouplingClock` no longer inherits from `InterpolatingClock`. This reduces about half of the original complexity.

Existing usages of `DecoupleableInterpolatingFramedClock` will need to nest a `DecouplingClock` *inside* of an `InterpolatingClock`. Note the order here – `DecouplingClock` should directly encapsulate the `ITrack` or similar source for best behaviour. Introducing decoupling in the middle of a framed hierarchy will likely not work well.

## Not frame based

`DecouplingClock` is intentionally re-implemented as a non-frame-based clock for simplicity. My main reason for this was to ensure that we are exposing "instantaneous" values to keep complexity to a minimum. ie. we don't need to unnecessarily track and compare time values.

To make this work, time tracking for the case where time is decoupled is done when `CurrentTime` is called. I can understand if this may be seen as a bit weird, but I do think it's better than making it an `IFrameBasedClock` – at least until we can better define how things like `Seek` (should a seek on a framed clock immediately update `CurrentTime` or only after a `ProcessFrame`?) and `IsRunnning` (should running state of the nested clock immediately update or wait for next frame?) work.

In practice, this seems to work quite well. It also hints to consumers to put the `DecoupledClock` *inside* any further adjustments like interpolation.

A potential caveat here is that if a framed clock is provided as the decoupling source (as is done in some osu!-side usages such as tests and spectator), the source will need to be externally processed.

## Less mutations

When `AllowDecoupling` is set to `false`, the new implementation will operate in a completely transparent way. No extra operations will be performed on the `Source`.

When `AllowDecoupling` is set to `true`, there are only two cases where `DecouplingClock` will perform operations on the `Source`:

- If a `DecouplingClock.Seek` is requested by the user and the source returns `false` (aka "cannot seek"), `Stop` will be called on the source to ensure it stops. This is to cover the scenario where calling `Seek(-1000)` on a bass track will seek it to `0` and continue playing.
- After a negative seek which failed on the `Source`, at the boundary of `CurrentTime==0`, the source will be `Start`ed once, hinting that it is likely able to take over.

### Touching on the `CurrentTime==0` special case

To keep things simple, the implementation assumes that if the `Source` could not seek to a negative time value, it will likely be able to again after reaching zero. This is the **only time** a `DecouplingClock` will `Start` the underlying source.

This is a very simplistic approach to handle the main use case of decoupling that we have. If there a new use case where the `Source` can say, only track time from `1000..6000` and we perform a seek to `0`, the `Source` will not be hinted to start when reaching `1000`.

Fixing this would require some extra thought from a performance perspective (we likely don't want to call `Start()` on the `Source` every time `CurrentTime` is retrieved, for instance) without further hinting at what range a clock can actually handle.

A further refinement could be doing precisely this – `DecouplingClock` can only operation on a source which implements a new interface `IRangeLimitedClock { (double, double) ValidRange { get ; } }`.

## Source must be `IAdjustableClock`

This is another arbitrary limitation to keep complexity down. `DecouplingClock` **needs to be** `IAdjustableClock` in order to track operations performed against the source. Without this we would have a very hard time knowing what state we are in.

If necessary in the future, we could allow sources to be non-adjustable, but methods like `Start`/`Stop`/`Seek` would need to `throw` as we rationally cannot make them work.

## All adjustable operations should be performed on `DecouplingClock`

As touched upon, all `IAdjustableClock` operations should be performed directly on the `DecouplingClock`, not the source. Operations performed directly on the source could lead to incorrect behaviour, such as `Seek`s being undone when in a decoupled state and stopped.

# Regarding obsoleting the old implementation

I've searched across github and cannot find any consumers using the old implementation (phew). We could potentially just nuke it from existence once osu! has switched across.

# Current state

I'm publishing this as a draft to get eyes on it and make sure the overall direction is agreeable. I'd estimate there's another day's work to get this ready for prime time, and I'll probably push ahead even if this doesn't get any eyes on it immediately.

## osu! integration

Works against osu! with [some changes](https://github.com/ppy/osu/compare/master...peppy:osu:clock-fix-attempt-2?expand=1). Note that there are a few straggler tests that need fixing, but the hard ones are handled. I've tried to explain changes in commit messages, but will continue to refine things.

One cool thing is that it seems like a few hacks we had in place can be removed. Needs some more rigorous testing, though.

## Test coverage

There's a few tests missing (see inline `TODO`s) which I will add before marking this as non-draft. These came up as I adjusted the implementation to pass osu!-side tests, for what it's worth.

# Breaking changes

## `DecoupleableInterpolatingFramedClock` is obsoleted. Use `DecouplingClock` instead

See #TODO for more details on a migration path.

2023-09-22 08:07 UTC, bdach commented on osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
> +            AddStep("add decoupling(true)", () => AddClock(new DecouplingClock { AllowDecoupling = true }));
Test scene is turbo weird in that `AddClock` takes the last added clock and... nests it into the one being added here? So this is trying to nest a `InterpolatingFramedClock` inside a `DecouplingClock` and failing because `InterpolatingFramedClock` is not adjustable.

2023-09-22 08:07 UTC, bdach commented on osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
> +                    // TODO: confirm.
Confirmed?

2023-09-22 08:07 UTC, bdach commented on osu.Framework.Tests/Clocks/DecouplingClockTest.cs
> +        // TODO: test backwards playback. (over the boundary?)
Some more leftover TODOs

2023-09-22 08:13 UTC, bdach commented
Generally this seems okay aside from the above review, which is mostly minor quibbles, but I'll highlight one point in particular:

> `DecouplingClock` is intentionally re-implemented as a non-frame-based clock for simplicity. My main reason for this was to ensure that we are exposing "instantaneous" values to keep complexity to a minimum. ie. we don't need to unnecessarily track and compare time values.

I'm not sure if it's just me, but in a way, to me, reading this implementation, I have this vague feeling that `DecouplingClock` _seems_ to be essentially a framed clock, without explicitly being one or implementing the interfaces. It's just that the `ProcessFrame()` calls you would normally issue manually, with the current implementation, are sorta-kinda "implicitly" performed _for_ you when observing the decoupling clock's state in any way - because that's when the clock decides to check the source clock and maybe possibly do something on it or update its own internal state to match it. Which means that the timing of when you observe state now begins to matter, and if you observe the state in a "wrong" way, you may potentially get unexpected results.

I'm not necessarily making value judgements on that yet, but it feels like a potential rake one may step on.

2023-09-22 08:21 UTC, peppy commented on osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
> +            AddStep("add decoupling(true)", () => AddClock(new DecouplingClock { AllowDecoupling = true }));
Yeah, it's all intended to be a sandbox for manual testing. Agree it could do with some work.

2023-09-22 08:25 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +                        return currentTime = Source.CurrentTime;
This is a very important implementation detail: when the source is running we *always* want to use the source's current time (and transfer that to our local time to make sure when we do enter a decoupled state we are as in-sync as we can be). Does that make sense?

And if so, should I split this `if` out into two and add inline comments to mention that?

2023-09-22 08:27 UTC, bdach commented on osu.Framework/Timing/DecouplingClock.cs
> +                        return currentTime = Source.CurrentTime;
It does make sense. Reading this conditional, I tunnel-visioned on the `!AllowDecoupling` part, and thought "surely this just ensures that when coupled the time always matches source". I didn't really consider that detail.

Splitting into two and some inline commenting sounds fine to me.

2023-09-22 08:27 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +            isRunning = adjustableSource.IsRunning;
I've added test coverage since you posted this.

For our purposes, `ChangeSource` should reset time and state to match the source (osu! relies on this). I guess we can expand the `ISourceChangeableClock` documentation to mention this?

2023-09-22 08:29 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +            lastSeekFailed = false;
Do you mean decoupled? If so, this does seem like an oversight (which isn't tested yet).

I believe calling `Reset` with `AllowDecoupling = true` while the source is not running will fail currently.

2023-09-22 08:29 UTC, peppy commented on osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
> +                    // TODO: confirm.
I don't think so.

2023-09-22 08:29 UTC, bdach commented on osu.Framework/Timing/DecouplingClock.cs
> +            isRunning = adjustableSource.IsRunning;
I'm not sure it matters for `ISourceChangeableClock`; I'd say it matters for `DecouplingClock` since it is the one which has the notion of... decoupling, and in the case of changing source, it has to choose which of the two time sources two trust. So xmldoc on `DecouplingClock` mentioning this behaviour seems good to me.

2023-09-22 08:30 UTC, peppy commented on osu.Framework.Tests/Clocks/DecouplingClockTest.cs
> +        // TODO: test backwards playback. (over the boundary?)
They are there until I actually add tests. As touched on in the OP I haven't finished writing tests framework side yet as I was waiting to make sure everything slotted in with osu! first.

2023-09-22 08:33 UTC, bdach commented on osu.Framework/Timing/DecouplingClock.cs
> +            lastSeekFailed = false;
Yeah I somehow glossed over the `adjustableSourceClock.Reset()` part, so in coupled mode this _should_ do the right thing.

Dunno about that second part, I don't immediately see why it'd fail, but definitely something to confirm if you think so.

2023-09-22 08:54 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +            lastSeekFailed = false;
If the assumption holds that all source clocks will take over when `Reset` then what I mentioned is a non-issue. It's probably a sane thing to expect. But I think I'd still add a `currentTime=0` in this method.

2023-09-22 08:54 UTC, peppy commented on osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
> +            AddStep("add decoupling(true)", () => AddClock(new DecouplingClock { AllowDecoupling = true }));
I've refactored the tests to make more sense.

2023-09-22 09:08 UTC, peppy commented
> I'm not sure if it's just me, but in a way, to me, reading this implementation, I have this vague feeling that DecouplingClock seems to be essentially a framed clock, without explicitly being one or implementing the interfaces

Making it a framed clock is not a huge change. Give this a shot and see if it reads better to you:

```diff
diff --git a/osu.Framework.Tests/Clocks/DecouplingClockTest.cs b/osu.Framework.Tests/Clocks/DecouplingClockTest.cs
index b183a2523..c0fc4f13e 100644
--- a/osu.Framework.Tests/Clocks/DecouplingClockTest.cs
+++ b/osu.Framework.Tests/Clocks/DecouplingClockTest.cs
@@ -83,6 +83,7 @@ public void TestSeekFromSource(bool allowDecoupling)
             Assert.That(decouplingClock.CurrentTime, Is.EqualTo(0));
 
             source.Seek(1000);
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.CurrentTime, Is.EqualTo(1000));
             Assert.That(decouplingClock.CurrentTime, Is.EqualTo(1000));
@@ -100,10 +101,15 @@ public void TestChangeSourceUpdatesToNewSourceTime(bool allowDecoupling)
             source.Seek(first_source_time);
             source.Start();
 
+            decouplingClock.ProcessFrame();
+
             var secondSource = new TestClock { CurrentTime = second_source_time };
 
             Assert.That(decouplingClock.CurrentTime, Is.EqualTo(first_source_time));
+
             decouplingClock.ChangeSource(secondSource);
+            decouplingClock.ProcessFrame();
+
             Assert.That(secondSource.CurrentTime, Is.EqualTo(second_source_time));
         }
 
@@ -134,10 +140,13 @@ public void TestReset(bool allowDecoupling)
             source.Seek(2000);
             source.Start();
 
+            decouplingClock.ProcessFrame();
+
             Assert.That(decouplingClock.IsRunning, Is.True);
             Assert.That(decouplingClock.CurrentTime, Is.EqualTo(2000));
 
             decouplingClock.Reset();
+            decouplingClock.ProcessFrame();
 
             Assert.That(decouplingClock.IsRunning, Is.False);
             Assert.That(source.IsRunning, Is.False);
diff --git a/osu.Framework/Timing/DecouplingClock.cs b/osu.Framework/Timing/DecouplingClock.cs
index fb449dc36..85150d8e2 100644
--- a/osu.Framework/Timing/DecouplingClock.cs
+++ b/osu.Framework/Timing/DecouplingClock.cs
@@ -20,7 +20,7 @@ namespace osu.Framework.Timing
     /// It is important therefore that if the source clock is set to a framed clock, you will need to call
     /// <see cref="IFrameBasedClock.ProcessFrame"/> externally.
     /// </remarks>
-    public sealed class DecouplingClock : ISourceChangeableClock, IAdjustableClock
+    public sealed class DecouplingClock : ISourceChangeableClock, IAdjustableClock, IFrameBasedClock
     {
         public bool AllowDecoupling = true;
 
@@ -60,40 +60,48 @@ public bool IsRunning
             }
         }
 
-        private double currentTime;
+        public double CurrentTime { get; private set; }
 
-        public double CurrentTime
+        public double ElapsedFrameTime { get; private set; }
+        public double FramesPerSecond => 0;
+
+        public void ProcessFrame()
         {
-            get
+            double lastTime = CurrentTime;
+
+            (Source as IFrameBasedClock)?.ProcessFrame();
+
+            try
             {
-                try
+                if (Source.IsRunning || !AllowDecoupling)
                 {
-                    if (Source.IsRunning || !AllowDecoupling)
-                        return currentTime = Source.CurrentTime;
-
-                    if (!isRunning)
-                        return currentTime;
+                    CurrentTime = Source.CurrentTime;
+                    return;
+                }
 
-                    if (lastReferenceTimeConsumed == null)
-                        return currentTime;
+                if (!isRunning)
+                    return;
 
-                    double elapsedSinceLastCall = (realtimeReferenceClock.CurrentTime - lastReferenceTimeConsumed.Value) * Rate;
+                if (lastReferenceTimeConsumed == null)
+                    return;
 
-                    // Crossing the zero time boundary, we can attempt to start and use the source clock.
-                    // TODO: consider if this is too specific. may need to be mentioned in class xmldoc if we keep it.
-                    if (currentTime < 0 && currentTime + elapsedSinceLastCall >= 0)
-                    {
-                        adjustableSourceClock.Start();
-                        if (Source.IsRunning)
-                            return currentTime = Source.CurrentTime;
-                    }
+                double elapsedSinceLastCall = (realtimeReferenceClock.CurrentTime - lastReferenceTimeConsumed.Value) * Rate;
 
-                    return currentTime += elapsedSinceLastCall;
-                }
-                finally
+                // Crossing the zero time boundary, we can attempt to start and use the source clock.
+                // TODO: consider if this is too specific. may need to be mentioned in class xmldoc if we keep it.
+                if (CurrentTime < 0 && CurrentTime + elapsedSinceLastCall >= 0)
                 {
-                    lastReferenceTimeConsumed = realtimeReferenceClock.CurrentTime;
+                    adjustableSourceClock.Start();
+                    if (Source.IsRunning)
+                        CurrentTime = Source.CurrentTime;
                 }
+
+                CurrentTime += elapsedSinceLastCall;
+            }
+            finally
+            {
+                lastReferenceTimeConsumed = realtimeReferenceClock.CurrentTime;
+                ElapsedFrameTime = CurrentTime - lastTime;
             }
         }
 
@@ -122,7 +130,7 @@ public void Reset()
             adjustableSourceClock.Reset();
             isRunning = false;
             lastSeekFailed = false;
-            currentTime = 0;
+            CurrentTime = 0;
         }
 
         public void Start()
@@ -170,7 +178,7 @@ public bool Seek(double position)
                 adjustableSourceClock.Stop();
             }
 
-            currentTime = position;
+            CurrentTime = position;
             return true;
         }
 
```

Again, my main concern is behaviour around `Reset` / `Seek`  / etc. (see test changes)

2023-09-22 09:22 UTC, bdach commented
Okay, well, that does help elucidate why you originally decided to go for non-framed. That said, I don't necessarily see anything in that patch I'd consider strictly *worse* than the non-framed variant, just potentially more *explicit*.

The kicker here is probably going to be the game-side changes - whether going framed is going to require bringing some of our previous hacks back, and how many (if any) extra manual clock processing we're going to have to do. See how you go I guess.

Would also generally be interested in @smoogipoo's opinion on this if I can get one.

2023-09-22 10:23 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +            lastSeekFailed = false;
(I've added this in https://github.com/ppy/osu-framework/pull/6001/commits/0fe7147f26ca8066410599dfefcc57ae1e715b85)

2023-09-22 10:42 UTC, peppy commented
I've pushed the changes including the framed version as I think it's probably the better direction. I've also tidied up some of the surrounding logic, so please give it another look.

2023-09-22 15:53 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +                adjustableSourceClock.Stop();
Is properly covered now.

2023-09-22 15:56 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +            isRunning = adjustableSource.IsRunning;
Added mention of this in the class' xmldoc.

2023-09-22 15:59 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +                    // TODO: consider if this is too specific. may need to be mentioned in class xmldoc if we keep it.
Added in 57aa7620a1a48fbe31da07b4e139524e4e9923dd.

2023-09-22 15:59 UTC, peppy commented on osu.Framework/Timing/DecouplingClock.cs
> +                        return currentTime = Source.CurrentTime;
I've rewritten all the logic in `ProcessFrame` and documented each condition.

2023-09-22 16:09 UTC, peppy commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +                    adjustableSourceClock.Seek(currentTime);
I'm not 100% on this (ie. how much overhead this has on BASS and whether it's worth it) but I want to roll this out to give it a try. In theory, this should allow a better pass-off from decoupled to track than we previously had. Would be especially noticeable at lower frame rates, and may help with https://github.com/ppy/osu/issues/22488.

2023-09-25 05:01 UTC, smoogipoo requested changes

2023-09-25 05:01 UTC, smoogipoo commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +        }
Maybe just me, but it weirds me out that a getter is mutating the value of `isRunning`.

Is this code particularly important in that it needs to be referenced every frame for the clock to be in a good state? 

For instance, and I'll say ahead of time I haven't tested this, but suppose:
- Decoupling is *not* allowed
- The decoupling clock is `.Start()`ed (at 0)
- The clock moves beyond `trackLength` at which point the source clock stops
- From here I assume `ProcessFrame()` becomes a no-op, but `isRunning` remains `true` in an internally-decoupled state.
- A `.Seek()` to 0 on the decoupling clock would then restart the track. This operation *should* (if my theory is correct) change behaviour based on whether the `IsRunning` property has been referenced.

Is this expected behaviour?

2023-09-25 09:31 UTC, peppy commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +        }
Do we want to change the implementation to match `InterpolatingFramedClock` for consistency?

```diff
diff --git a/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs b/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
index a77817f0c..9025b1cd2 100644
--- a/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
+++ b/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
@@ -35,6 +35,7 @@ public void TestStartFromDecoupling(bool allowDecoupling)
             Assert.That(decouplingClock.IsRunning, Is.False);
 
             decouplingClock.Start();
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.IsRunning, Is.True);
             Assert.That(decouplingClock.IsRunning, Is.True);
@@ -50,6 +51,7 @@ public void TestStartFromSource(bool allowDecoupling)
             Assert.That(decouplingClock.IsRunning, Is.False);
 
             source.Start();
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.IsRunning, Is.True);
             Assert.That(decouplingClock.IsRunning, Is.True);
@@ -126,14 +128,17 @@ public void TestChangeSourceUpdatesToCorrectSourceState(bool allowDecoupling)
             decouplingClock.AllowDecoupling = allowDecoupling;
 
             source.Start();
+            decouplingClock.ProcessFrame();
             Assert.That(decouplingClock.IsRunning, Is.True);
 
             var secondSource = new TestClock();
 
             decouplingClock.ChangeSource(secondSource);
+            decouplingClock.ProcessFrame();
             Assert.That(decouplingClock.IsRunning, Is.False);
 
             decouplingClock.ChangeSource(source);
+            decouplingClock.ProcessFrame();
             Assert.That(decouplingClock.IsRunning, Is.True);
         }
 
@@ -169,11 +174,13 @@ public void TestSourceStoppedWhileNotDecoupling()
         {
             decouplingClock.AllowDecoupling = false;
             decouplingClock.Start();
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.IsRunning, Is.True);
             Assert.That(decouplingClock.IsRunning, Is.True);
 
             source.Stop();
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.IsRunning, Is.False);
             Assert.That(decouplingClock.IsRunning, Is.False);
@@ -210,6 +217,7 @@ public void TestSourceStoppedWhileDecoupling()
         {
             decouplingClock.AllowDecoupling = true;
             decouplingClock.Start();
+            decouplingClock.ProcessFrame();
 
             Assert.That(source.IsRunning, Is.True);
             Assert.That(decouplingClock.IsRunning, Is.True);
diff --git a/osu.Framework/Timing/DecouplingFramedClock.cs b/osu.Framework/Timing/DecouplingFramedClock.cs
index 898866642..5fc61a415 100644
--- a/osu.Framework/Timing/DecouplingFramedClock.cs
+++ b/osu.Framework/Timing/DecouplingFramedClock.cs
@@ -34,23 +34,7 @@ public sealed class DecouplingFramedClock : ISourceChangeableClock, IAdjustableC
         /// </remarks>
         public bool AllowDecoupling { get; set; } = true;
 
-        public bool IsRunning
-        {
-            get
-            {
-                // Always use the source clock's running state if it's running.
-                if (Source.IsRunning)
-                    return isRunning = true;
-
-                // If we're allowed to be decoupled, maintain our internal running state.
-                if (AllowDecoupling)
-                    return isRunning;
-
-                // Otherwise we're definitely not running.
-                Debug.Assert(!Source.IsRunning);
-                return isRunning = false;
-            }
-        }
+        public bool IsRunning { get; private set; }
 
         public double CurrentTime { get; private set; }
 
@@ -107,6 +91,7 @@ public void ProcessFrame()
                 if (Source.IsRunning)
                 {
                     currentTime = Source.CurrentTime;
+                    isRunning = true;
                     return;
                 }
 
@@ -114,6 +99,7 @@ public void ProcessFrame()
                 if (!AllowDecoupling)
                 {
                     currentTime = Source.CurrentTime;
+                    isRunning = false;
                     return;
                 }
 
@@ -141,6 +127,7 @@ public void ProcessFrame()
             }
             finally
             {
+                IsRunning = isRunning;
                 lastReferenceTime = realtimeReferenceClock.CurrentTime;
                 CurrentTime = currentTime;
                 ElapsedFrameTime = CurrentTime - lastTime;

```

2023-09-25 10:12 UTC, bdach commented on osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
> +        }
I'm not sure why I didn't notice nothing ever actually sets `TestClockWithRange.MaxTime` to anything non-default...

2023-09-25 10:26 UTC, bdach commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +        }
Yeah this is sort of a continuation of [my previous point](https://github.com/ppy/osu-framework/pull/6001#issuecomment-1731001344) about "implicit clock processing". Although I will say that it feels a lot more dicey to require `ProcessFrame()` calls for running state to propagate from the source clock to the decoupled, which as far as I can tell the diff above is trying to do.

That said, unless it incurs damage to any other pending adjustments game-side, I'd probably agree with applying the diff above.

2023-09-25 12:39 UTC, peppy commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +        }
I can say that tests do pass osu! side with this change.

2023-09-25 13:35 UTC, peppy commented on osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
> +        public void TestForwardPlaybackOverZeroBoundary()
Whoops, added in 28d159eed38d835c577c85594d08df5875308408.

2023-09-25 13:36 UTC, peppy commented on osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
> +        }
Added in 98f832f7a5fe2a7b596dd9a47e0a8b91706440a3.

2023-09-25 14:53 UTC, peppy commented on osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
> +            Assert.That(secondSource.CurrentTime, Is.EqualTo(second_source_time));
Good catch, this was a typo. Also regressed at some point in my changes, so I've fixed it by transferring the current time value.

2023-09-26 02:43 UTC, smoogipoo commented on osu.Framework/Timing/DecouplingFramedClock.cs
> +        }
Conceptually I'm fine with that change/the ones committed since this comment, and we can see if it ever goes wrong as a future learning lesson.

The other suggestion I had is that I only observed `Seek()` being affected by this, so simply changing its conditional to reference the property would also resolve it.

2023-09-26 02:47 UTC, smoogipoo submitted a review, later dismissed

2023-09-26 04:49 UTC, peppy commented
I've pushed a small fix for an intermittent failure I got after several hundred runs.

2023-09-26 13:27 UTC, bdach commented
Given that we have:

- `TestForwardPlaybackOverZeroBoundary`
- `TestForwardPlaybackOverLengthBoundary`
- `TestBackwardPlaybackOverZeroBoundary`

I wanted to also write `TestBackwardPlaybackOverLengthBoundary`. Came up with something like this:

```diff
diff --git a/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs b/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
index 5eb211377..b9079d3a7 100644
--- a/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
+++ b/osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
@@ -445,6 +445,53 @@ public void TestForwardPlaybackOverLengthBoundary()
             Assert.That(source.IsRunning, Is.False);
         }
 
+        [Test]
+        public void TestBackwardPlaybackOverLengthBoundary()
+        {
+            source = new TestStopwatchClockWithRangeLimit
+            {
+                MaxTime = 10000
+            };
+
+            decouplingClock.ChangeSource(source);
+            decouplingClock.AllowDecoupling = true;
+
+            decouplingClock.Seek(10200);
+            decouplingClock.Rate = -1;
+            decouplingClock.Start();
+
+            decouplingClock.ProcessFrame();
+
+            double time = decouplingClock.CurrentTime;
+
+            while (decouplingClock.CurrentTime > 10000)
+            {
+                Assert.That(source.IsRunning, Is.False);
+                Assert.That(source.CurrentTime, Is.EqualTo(10000));
+                Assert.That(decouplingClock.CurrentTime, Is.LessThanOrEqualTo(time));
+                time = decouplingClock.CurrentTime;
+
+                decouplingClock.ProcessFrame();
+            }
+
+            while (!source.IsRunning)
+                decouplingClock.ProcessFrame();
+
+            Assert.That(source.IsRunning, Is.True);
+            Assert.That(decouplingClock.CurrentTime, Is.LessThan(9900));
+
+            while (decouplingClock.CurrentTime > 9800)
+            {
+                Assert.That(decouplingClock.IsRunning, Is.True);
+                Assert.That(decouplingClock.CurrentTime, Is.LessThanOrEqualTo(time));
+                time = decouplingClock.CurrentTime;
+
+                decouplingClock.ProcessFrame();
+            }
+
+            Assert.That(source.IsRunning, Is.True);
+        }
+
         #endregion
 
         private class TestClockWithRange : TestClock

```

but it fails. Moreover, if I attempt to test manually via the other test scene:

```diff
diff --git a/osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs b/osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
index 32735e014..02460a8d8 100644
--- a/osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
+++ b/osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
@@ -1,6 +1,7 @@
 // Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.
 
+using System.Linq;
 using NUnit.Framework;
 using osu.Framework.Testing;
 using osu.Framework.Tests.Clocks;
@@ -21,7 +22,7 @@ public void TestInterpolationWithLaggyClock()
         [Test]
         public void TestDecouplingWithRangeLimited()
         {
-            AddStep("add non-negative stopwatch", () => AddClock(new TestStopwatchClockWithRangeLimit()));
+            AddStep("add non-negative stopwatch", () => AddClock(new TestStopwatchClockWithRangeLimit { MaxTime = 15000 }));
             AddStep("add decoupling", () => AddClock(new DecouplingFramedClock { AllowDecoupling = true }));
 
             AddStep("seek decoupling to -10000", () =>
@@ -35,6 +36,17 @@ public void TestDecouplingWithRangeLimited()
                 foreach (var c in this.ChildrenOfType<VisualClock>())
                     (c.TrackingClock as DecouplingFramedClock)?.Seek(10000);
             });
+
+            AddStep("seek decoupling to 20000", () =>
+            {
+                foreach (var c in this.ChildrenOfType<VisualClock>())
+                    (c.TrackingClock as DecouplingFramedClock)?.Seek(20000);
+            });
+
+            AddToggleStep("toggle direction", b =>
+            {
+                (this.ChildrenOfType<VisualClock>().Last().TrackingClock as DecouplingFramedClock)!.Rate = b ? -1 : 1;
+            });
         }
     }
 }

```

it also appears that the source clock is not restarted when decoupled clock crosses the length boundary backwards.

Is my testing wrong, or is this a real issue?

2023-09-26 13:30 UTC, peppy commented
Your test is fine I think. There's no logic to support this case because we don't really use it. Moreso, we don't know where the "length" boundary is.

I touch on this in the OP, suggesting we may want to expose the "valid range" of a clock and use that in decoupling.

But without this change, I'd propose documenting this as a caveat and only adding support if we ever require it.

2023-09-26 13:36 UTC, peppy commented
You raise a very good point about using the source time. I'd be okay with considering that if it works.

2023-09-26 13:40 UTC, bdach commented
Yeah sure, I'll run that past both test suites and we'll see how it goes.

2023-09-26 14:20 UTC, bdach commented
Some failures, unfortunately:

![after-mania](https://github.com/ppy/osu-framework/assets/20418176/9de9a2b3-8996-45d5-8ccd-59e326f10756)

The audio track test fails _without_ my change, but the rest is firmly the fault of it. I'll have a look at both, but if I can't get my change to work in like 30 minutes, I'll bail.

2023-09-26 15:04 UTC, bdach commented
For the unrelated failure, see PR link above. For the _related_ failures, yeah, my patch breaks things quite badly.

While it _is_ true that `lastTime > Source.CurrentTime && currentTime <= Source.CurrentTime` _looks_ like the correct condition to apply for the edge case, it is actually _trivially true when rewinding_. So it breaks rewinding past the left-side boundary, among others.

I'll leave a comment and let this be.

2023-09-26 15:12 UTC, bdach approved these changes

2023-09-26 15:51 UTC, merged