Fix keyboard handler getting disabled on window creation failure
ppy/osu-framework pull request #6005
Opened 2023-09-26 06:43 UTC by peppy

Has been reported by multiple users, probably due to a once-off startup failure caused by external factors.

Can be tested with something like:

```diff
diff --git a/osu.Framework/Platform/MacOS/MacOSGameHost.cs b/osu.Framework/Platform/MacOS/MacOSGameHost.cs
index 1600b9af0..2cb5e4432 100644
--- a/osu.Framework/Platform/MacOS/MacOSGameHost.cs
+++ b/osu.Framework/Platform/MacOS/MacOSGameHost.cs
@@ -21,7 +21,7 @@ internal MacOSGameHost(string gameName, HostOptions options)
         {
         }
 
-        protected override IWindow CreateWindow(GraphicsSurfaceType preferredSurface) => new MacOSWindow(preferredSurface);
+        protected override IWindow CreateWindow(GraphicsSurfaceType preferredSurface) => null;
 
         public override IEnumerable<string> UserStoragePaths
         {

```

![JetBrains Rider 2023-09-26 at 06 42 55](https://github.com/ppy/osu-framework/assets/191335/d87d081c-6fd0-46cb-a98d-b01cf6387de4)

---

Closes https://github.com/ppy/osu/issues/24260.

2023-09-26 09:20 UTC, smoogipoo approved these changes

2023-09-26 09:20 UTC, Susko3 requested changes
Needs to consider the failure case of #6007.

2023-09-26 09:20 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
This change doesn't make much sense, because `CreateWindow()` never really returns `null`. The actual failure is `CreateWindow()` throwing, see #6007.

2023-09-26 09:27 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
I think this part needs to be reverted, `RequireWindowExists` seems to actually fix the problem.

If you want to fix #6007 in this pull as well, I think it's best to move `CreateWindow()` to inside the try/catch block.

2023-09-26 09:41 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
I'm quite confused.

This was all intentional, as `CreateWindow` takes a `surfaceType` and could fail for some renderer options and not others. So the try-catch and the `throw` are both intentional here.

I'm not sure how to process #6007. I guess this PR can be marked as closing it?

2023-09-26 09:48 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
> This was all intentional, as `CreateWindow` takes a `surfaceType` and could fail for some renderer options and not others. So the try-catch and the throw are both intentional here.

Correct. But `CreateWindow` can fail by throwing an exception and not by returning `null`.

> I guess this PR can be marked as closing it?

Not in its current state. It may throw an exception, but the original exception is still silenced. I think it's important to have SDL_Init failures be logged.

2023-09-26 09:53 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
Okay, so something like this?

```diff
diff --git a/osu.Framework/Platform/GameHost.cs b/osu.Framework/Platform/GameHost.cs
index 601e0df81..691a3aa17 100644
--- a/osu.Framework/Platform/GameHost.cs
+++ b/osu.Framework/Platform/GameHost.cs
@@ -972,18 +972,18 @@ protected void SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType su
             Renderer = renderer;
             Renderer.CacheStorage = CacheStorage.GetStorageForDirectory("shaders");
 
-            // Prepare window
-            Window = CreateWindow(surfaceType);
-
-            if (RequireWindowExists && Window == null)
-            {
-                // Window creation may fail in the case of a catastrophic failure (ie. graphics driver or SDL2 level).
-                // In such cases, we want to throw here to immediately mark this renderer setup as failed.
-                throw new InvalidOperationException("🖼️ Renderer could not be initialised as window creation failed.");
-            }
-
             try
             {
+                // Prepare window
+                Window = CreateWindow(surfaceType);
+
+                if (RequireWindowExists && Window == null)
+                {
+                    // Window creation may fail in the case of a catastrophic failure (ie. graphics driver or SDL2 level).
+                    // In such cases, we want to throw here to immediately mark this renderer setup as failed.
+                    throw new InvalidOperationException("🖼️ Renderer could not be initialised as window creation failed.");
+                }
+
                 Window.SetupWindow(Config);
                 Window.Create();
                 Window.Title = $@"osu!framework (running ""{Name}"")";

```

2023-09-26 10:09 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
```diff
diff --git a/osu.Framework/Platform/GameHost.cs b/osu.Framework/Platform/GameHost.cs
index 601e0df81..d21829c35 100644
--- a/osu.Framework/Platform/GameHost.cs
+++ b/osu.Framework/Platform/GameHost.cs
@@ -972,18 +972,17 @@ protected void SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType su
             Renderer = renderer;
             Renderer.CacheStorage = CacheStorage.GetStorageForDirectory("shaders");
 
-            // Prepare window
-            Window = CreateWindow(surfaceType);
-
-            if (RequireWindowExists && Window == null)
-            {
-                // Window creation may fail in the case of a catastrophic failure (ie. graphics driver or SDL2 level).
-                // In such cases, we want to throw here to immediately mark this renderer setup as failed.
-                throw new InvalidOperationException("­ƒû╝´©Å Renderer could not be initialised as window creation failed.");
-            }
-
             try
             {
+                // Prepare window
+                Window = CreateWindow(surfaceType);
+
+                if (Window == null)
+                {
+                    // window can be null when running headless
+                    return;
+                }
+
                 Window.SetupWindow(Config);
                 Window.Create();
                 Window.Title = $@"osu!framework (running ""{Name}"")";
```

Something like this.

Maybe `Window == null` meaning 'headless run' is not that great. Time to look into having `DummyWindow`?

2023-09-26 10:11 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
I still think my proposed diff may make more sense if we can expect window creation to potentially fail for a specific `surfaceType`. @smoogipoo do you know if this is possible?

2023-09-26 10:15 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
Your proposed diff and the current state of the PR make the tests not work due to nullref of `Window` in
```cs
Window.SetupWindow(Config);
```

2023-09-26 10:28 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +            if (RequireWindowExists && Window == null)
Right, that failed along the refactoring path. Can you check the latest version?

2023-09-26 10:45 UTC, Susko3 requested changes
Everything else seems fine to me and is more correct.
- Closes #6007 with the new changes

2023-09-26 10:45 UTC, Susko3 commented on osu.Framework/Platform/GameHost.cs
> +                    throw new InvalidOperationException("🖼️ Renderer could not be initialised as window creation failed.");
I think it's impossible that `CreateWindow` returns `null` (except when running headless). So this is dead code with a scary comment.

I'm fine with the exception (it verifies that hosts with `RequireWindowExists == true` don't create `null` windows), but the comment should be moved to where it actually applies: to the `RequireWindowExists` check in `GameHost.Run()`.

2023-09-26 13:33 UTC, peppy commented on osu.Framework/Platform/GameHost.cs
> +                    throw new InvalidOperationException("🖼️ Renderer could not be initialised as window creation failed.");
Sure, I've moved it.

2023-09-26 13:41 UTC, Susko3 approved these changes

2023-09-28 11:20 UTC, smoogipoo approved these changes

2023-09-28 11:39 UTC, merged