Allow enabling computed mipmaps in `LargeTextureStore`
ppy/osu-framework pull request #6048
Opened 2023-11-16 05:09 UTC by EVAST9919

As [per discussion](https://discord.com/channels/188630481301012481/589331078574112768/1174532880408518838).

2023-11-16 05:23 UTC, bdach commented
No testing whatsoever?

2023-11-16 06:45 UTC, EVAST9919 commented
Added 👌

2023-11-16 08:22 UTC, peppy requested changes

2023-11-16 08:22 UTC, peppy commented on osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
> +            dependencies.CacheAs(new LargeTextureStore(renderer, host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(game.Resources, "Textures")), manualMipmaps: false));
Setting `manualMipamaps: true` doesn't change anything in the test.

I'd hope the test shows the difference between the two.

2023-11-16 11:12 UTC, EVAST9919 commented on osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
> +            dependencies.CacheAs(new LargeTextureStore(renderer, host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(game.Resources, "Textures")), manualMipmaps: false));
>Setting manualMipamaps: true doesn't change anything in the test.

That's weird, for me the difference is very clear (I'm on D3D)

2023-11-16 11:42 UTC, peppy commented on osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
> +            dependencies.CacheAs(new LargeTextureStore(renderer, host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(game.Resources, "Textures")), manualMipmaps: false));
May have been hot reload failing. But I'd also hope the test can be run in both modes. I don't want to have to change code each time I want to check a test.

2023-11-16 11:53 UTC, EVAST9919 commented on osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
> +            dependencies.CacheAs(new LargeTextureStore(renderer, host.CreateTextureLoaderStore(new NamespacedResourceStore<byte[]>(game.Resources, "Textures")), manualMipmaps: false));
Will do. Was just trying to ensure it works for you and not a renderer issue or something.

2023-11-17 05:52 UTC, peppy approved these changes

2023-11-17 05:54 UTC, merged