Add a session timestamp prefix to log files (and retain 7 days of logs)
ppy/osu-framework pull request #6063
Opened 2023-11-27 07:44 UTC by peppy

Will be useful for diagnosing user issues where they already restarted the game and as a consequence, nuked previous logs.

2023-11-27 11:33 UTC, Susko3 commented on osu.Framework/Logging/Logger.cs
> -                static_loggers.Clear();
Just noting this: changing the logger storage when the game is running will no longer write the logger header to the new log files.

Changing the logger storage during runtime is dubious, and the old code is incorrect since it wasn't locking `flush_sync_lock` when accessing a thread-shared resource (`static_loggers`).

So I'm not against this change.

2023-11-28 08:28 UTC, peppy commented on osu.Framework/Logging/Logger.cs
> -                static_loggers.Clear();
Unfortunately the setter is used osu! side:

![CleanShot 2023-11-28 at 08 28 22](https://github.com/ppy/osu-framework/assets/191335/14ac6a24-799a-4d12-942a-38ef486cfddc)


I actually removed this because it was writing the headers more than once to the same file location. I guess I'll add it back and fix that part instead..

2023-11-28 08:33 UTC, peppy commented on osu.Framework/Logging/Logger.cs
> -                static_loggers.Clear();
On second thoughts, I guess this depends on what we consider the log header to be. Should it signal the start of a session and therefore *not* be present on a partial log? I could imagine this being one correct way of looking at it.

2023-11-28 09:19 UTC, smoogipoo requested changes

2023-11-28 09:19 UTC, smoogipoo commented on osu.Framework/Logging/Logger.cs
> +                var logFiles = new DirectoryInfo(storage.GetFullPath(string.Empty)).GetFiles();
A bit worried about this, in-case storage is set incorrectly it could nuke unrelated files.

How about doing additional checks against the filename? Something like making sure it matches `*.{Name}.log`?

2023-11-28 09:19 UTC, smoogipoo commented on osu.Framework/Logging/Logger.cs
> -                static_loggers.Clear();
I consider it as the start of a session, but I wouldn't mind it being output every time.

2023-11-28 10:08 UTC, peppy commented on osu.Framework/Logging/Logger.cs
> -                static_loggers.Clear();
I think I'd rather it didn't output every time so we know that some logs might be missing from the start.

2023-12-04 23:41 UTC, smoogipoo approved these changes

2023-12-05 07:07 UTC, merged