Add CultureInfo override for Bindable.Parse
ppy/osu-framework pull request #6065
Opened 2023-11-28 20:03 UTC by Neuheit

Adds a method override for `Bindable.Parse()` to accept different `CultureInfo` values

Fixes #5176

2023-11-29 06:01 UTC, peppy commented
Calls to the new overload for bindables with custom overrides of `Parse(object)` will fail.

![CleanShot 2023-11-29 at 06 00 44](https://github.com/ppy/osu-framework/assets/191335/343a85ac-1511-4ac6-993c-cbc4349df422)

The `virtual` flag should probably be removed from the overload without the `CultureInfo` and those implementation should be moved to the more specific overload.

Alternatively, rather than adding an overload, a nullable `CultureInfo` parameter could be added to the original one, avoiding the silent failures mentioned above (because it was compile-time fail until fixed).

2023-11-29 06:02 UTC, peppy requested changes
As proposed.

2023-11-29 07:09 UTC, Neuheit commented
> Calls to the new overload for bindables with custom overrides of `Parse(object)` will fail.
> 
> ![CleanShot 2023-11-29 at 06 00 44](https://private-user-images.githubusercontent.com/191335/286492280-343a85ac-1511-4ac6-993c-cbc4349df422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDE2MTEsIm5iZiI6MTcwMTI0MTMxMSwicGF0aCI6Ii8xOTEzMzUvMjg2NDkyMjgwLTM0M2E4NWFjLTE1MTEtNGFjNi05OTNjLWNiYzQzNDlkZjQyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNzAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWRhMjY3ZTNiODI3NThhNGNmZjk3M2NkOTE2YTRiZTllNDliNTA0MTRhNzE2ZTc4MTNiMGE3M2UzMTU0ZmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NCCFHXPElPx0_U6hy5K2kKRyzEAvzf8gPojqe6haiPs)
> 
> The `virtual` flag should probably be removed from the overload without the `CultureInfo` and those implementation should be moved to the more specific overload.
> 
> Alternatively, rather than adding an overload, a nullable `CultureInfo` parameter could be added to the original one, avoiding the silent failures mentioned above (because it was compile-time fail until fixed).

I tried that originally, but that would mean we would have to implement it in IParseable, which would make it required for the other bindables that don't have to do with strings, so i didnt think that would make sense. I can still do it that way if you like.

2023-11-29 20:39 UTC, Neuheit commented
I ended up creating a new interface that's used to parse the base bindable types, since having cultureinfo on the list and dictionary types didn't make sense. I also added test cases for doubles and floats.

2023-12-01 08:25 UTC, Susko3 commented
I think there should be only one interface, and it should match [`IFormattable`](https://learn.microsoft.com/en-us/dotnet/api/system.iformattable.tostring?view=net-8.0).

The interface should be applied to `IBindable` and `IBindable<T>` as well.

2023-12-01 08:36 UTC, Susko3 requested changes
Needs to consider and test round-trip ToString + Parse.

2023-12-01 08:36 UTC, Susko3 commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, cultureInfo ?? CultureInfo.InvariantCulture);
```suggestion
                        Value = (T)Convert.ChangeType(input, underlyingType, cultureInfo ?? CultureInfo.CurrentCulture);
```

Using the invariant culture breaks my expectation that `ToString()` and `Parse()` are opposites to each other. 
The following test illustrates that:

```cs
[TestCase(1.4, "en-US", "1.4")]
[TestCase(1.4, "de-DE", "1,4")]
[TestCase(1400.01, "de-DE", "1400,01")]
[TestCase(1234.57, "ru-RU", "1234,57")]
[TestCase(1.094, "fr-FR", "1,094")]
[TestCase(1400.01, "zh-CN", "1400.01")]
public void TestRoundTrip(double value, string locale, string expected)
{
    CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo(locale);

    var bindable = new BindableDouble(value);
    string? asString = bindable.ToString();
    Assert.AreEqual(expected, asString);
    Assert.DoesNotThrow(() => bindable.Parse(asString));
    Assert.AreEqual(value, bindable.Value, Precision.DOUBLE_EPSILON);
}
```

This will fail for French because `"1,094"` will get parsed in as `1094.0` and not `1.094`.

2023-12-01 08:36 UTC, Susko3 commented on osu.Framework/Bindables/Bindable.cs
> +        public virtual void Parse([CanBeNull] object input, [CanBeNull] CultureInfo cultureInfo = null)
```suggestion
        /// <param name="provider">An object that provides culture-specific formatting information about <paramref name="input"/>.</param>
        public virtual void Parse([CanBeNull] object input, [CanBeNull] IFormatProvider provider = null)
```

https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1.parse?view=net-8.0#system-iparsable-1-parse(system-string-system-iformatprovider)

2023-12-01 08:36 UTC, Susko3 commented on osu.Framework.Tests/Bindables/BindableFloatTest.cs
> +        public void TestParsingLocale(string value, string locale, float expected)
I think the tests should also call `bindable.ToString(...)` and check the output. You'll probably need to add a new parameter.

2023-12-01 08:37 UTC, Susko3 commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, cultureInfo ?? CultureInfo.InvariantCulture);
Please note that this is a breaking change.

2023-12-01 08:56 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, cultureInfo ?? CultureInfo.InvariantCulture);
Falling back to current culture - albeit buggy, error-prone, and unfortunate - also matches the rest of the c# ecosystem, so this probably is the more correct way to proceed.

2023-12-04 05:41 UTC, Neuheit commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
My original thought was that we keep it invariant by default and just override it in the game itself where the styling becomes bugged (e.g. in https://github.com/ppy/osu/discussions/18271.

2023-12-04 09:01 UTC, Susko3 commented on osu.Framework/Bindables/BindableList.cs
> +        void IParseable.Parse(object input, IFormatProvider provider) => Parse(input);
```suggestion
```

I think you should just change the signature of `Parse` to match the interface instead of adding this explicit interface implementation.

Same goes for `BindableDictionary`.

2023-12-04 09:03 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
Tend to agree with non-optional, that's how this entire string-printing, parsing, locale, culture stuff should have been designed everywhere to begin with. All of this "default to ambient locale" stuff is just silent footguns.

2023-12-04 09:11 UTC, Susko3 commented on osu.Framework.Tests/Bindables/BindableDoubleTest.cs
> +        public void TestParsingLocale(double numValue, string strValue, string locale, double expected)
Not sure what's up with the tests here. The old ones were fine. With https://github.com/ppy/osu-framework/pull/6065#discussion_r1411770240 I meant to suggest only adding new tests while keeping the existing ones.

Currently, `string strValue` is unused and `double expected` is redundant with `double numValue`.

2023-12-04 23:47 UTC, smoogipoo commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
Agree with making non-optional as long as the changes required to update code to it aren't silly.

2023-12-05 08:17 UTC, peppy commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
osu side changes with non-optional are pretty reasonable:

```diff
diff --git a/osu.Framework/Bindables/Bindable.cs b/osu.Framework/Bindables/Bindable.cs
index 28fc1e75c..a1ce5f5a8 100644
--- a/osu.Framework/Bindables/Bindable.cs
+++ b/osu.Framework/Bindables/Bindable.cs
@@ -249,7 +249,7 @@ private void addWeakReference(WeakReference<Bindable<T>> weakReference)
         /// </summary>
         /// <param name="input">The input which is to be parsed.</param>
         /// <param name="provider">An object that provides culture-specific formatting information about <paramref name="input"/>.</param>
-        public virtual void Parse([CanBeNull] object input, [CanBeNull] IFormatProvider provider = null)
+        public virtual void Parse([CanBeNull] object input, [CanBeNull] IFormatProvider provider)
         {
             switch (input)
             {
diff --git a/osu.Framework/Bindables/IParseable.cs b/osu.Framework/Bindables/IParseable.cs
index c91b00a3f..65970b97c 100644
--- a/osu.Framework/Bindables/IParseable.cs
+++ b/osu.Framework/Bindables/IParseable.cs
@@ -15,6 +15,6 @@ public interface IParseable
         /// </summary>
         /// <param name="input">The input which is to be parsed.</param>
         /// <param name="provider">An object that provides culture-specific formatting information about <paramref name="input"/>.</param>
-        void Parse(object? input, IFormatProvider? provider = null);
+        void Parse(object? input, IFormatProvider? provider);
     }
 }
diff --git a/osu.Framework/Configuration/IniConfigManager.cs b/osu.Framework/Configuration/IniConfigManager.cs
index 0b3470420..5c07aa73b 100644
--- a/osu.Framework/Configuration/IniConfigManager.cs
+++ b/osu.Framework/Configuration/IniConfigManager.cs
@@ -67,7 +67,7 @@ protected override void PerformLoad()
                                 if (!(b is IParseable parseable))
                                     throw new InvalidOperationException($"Bindable type {b.GetType().ReadableName()} is not {nameof(IParseable)}.");
 
-                                parseable.Parse(val);
+                                parseable.Parse(val, CultureInfo.InvariantCulture);
                             }
                             catch (Exception e)
                             {

```

so let's just go with that direction.

2023-12-05 08:28 UTC, peppy submitted a review, later dismissed

2023-12-05 08:28 UTC, peppy commented
Will wait for one more check here.

2023-12-05 17:38 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
https://github.com/ppy/osu-framework/pull/6065/commits/aa508b6bd00584504185406f8a3451489376aced

2023-12-05 17:39 UTC, bdach commented on osu.Framework/Bindables/BindableSize.cs
> +        public override void Parse(object? input, IFormatProvider provider)
https://github.com/ppy/osu-framework/pull/6065/commits/ffb59fb1d39a48676e4c8859a12888bcab4a834a

2023-12-05 17:39 UTC, bdach commented on osu.Framework/Bindables/IBindable.cs
> +    public interface IBindable : ICanBeDisabled, IHasDefaultValue, IUnbindable, IHasDescription, IFormattable, IParseable
https://github.com/ppy/osu-framework/pull/6065/commits/92adaf5ecd2c30d984d131136686404109963d33

2023-12-05 17:39 UTC, bdach commented on osu.Framework/Bindables/BindableDictionary.cs
> +        public void Parse(object? input, IFormatProvider? provider = null)
https://github.com/ppy/osu-framework/pull/6065/commits/63a0f229b7d2cc301235d540cd29c88e11fe51c1

2023-12-05 17:45 UTC, Susko3 commented on osu.Framework/Bindables/IBindable.cs
> +    public interface IBindable : ICanBeDisabled, IHasDefaultValue, IUnbindable, IHasDescription, IFormattable, IParseable
Sorry, I forgot to mention that the interface needs to be added back to bindable implementations.

2023-12-05 17:45 UTC, bdach commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
That doesn't look like a game-side diff. I applied this though:

```diff
diff --git a/osu.Game/Graphics/UserInterfaceV2/SliderWithTextBoxInput.cs b/osu.Game/Graphics/UserInterfaceV2/SliderWithTextBoxInput.cs
index 37ea2a3f96..e5ba7f61bf 100644
--- a/osu.Game/Graphics/UserInterfaceV2/SliderWithTextBoxInput.cs
+++ b/osu.Game/Graphics/UserInterfaceV2/SliderWithTextBoxInput.cs
@@ -121,7 +121,7 @@ private void tryUpdateSliderFromTextBox()
                         break;
 
                     default:
-                        slider.Current.Parse(textBox.Current.Value);
+                        slider.Current.Parse(textBox.Current.Value, CultureInfo.CurrentCulture);
                         break;
                 }
             }
diff --git a/osu.Game/Rulesets/Configuration/RulesetConfigManager.cs b/osu.Game/Rulesets/Configuration/RulesetConfigManager.cs
index 0eea1ff215..418dc3576f 100644
--- a/osu.Game/Rulesets/Configuration/RulesetConfigManager.cs
+++ b/osu.Game/Rulesets/Configuration/RulesetConfigManager.cs
@@ -84,7 +84,7 @@ protected override void AddBindable<TBindable>(TLookup lookup, Bindable<TBindabl
 
             if (setting != null)
             {
-                bindable.Parse(setting.Value);
+                bindable.Parse(setting.Value, CultureInfo.InvariantCulture);
             }
             else
             {
diff --git a/osu.Game/Rulesets/Mods/Mod.cs b/osu.Game/Rulesets/Mods/Mod.cs
index 775f6a0ed4..d635dccab1 100644
--- a/osu.Game/Rulesets/Mods/Mod.cs
+++ b/osu.Game/Rulesets/Mods/Mod.cs
@@ -3,6 +3,7 @@
 
 using System;
 using System.Collections.Generic;
+using System.Globalization;
 using System.Linq;
 using System.Reflection;
 using Newtonsoft.Json;
@@ -284,7 +285,7 @@ internal virtual void CopyAdjustedSetting(IBindable target, object source)
                 if (!(target is IParseable parseable))
                     throw new InvalidOperationException($"Bindable type {target.GetType().ReadableName()} is not {nameof(IParseable)}.");
 
-                parseable.Parse(source);
+                parseable.Parse(source, CultureInfo.InvariantCulture);
             }
         }
 
diff --git a/osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs b/osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs
index eabe9b9f64..151d469415 100644
--- a/osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs
+++ b/osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs
@@ -103,7 +103,7 @@ public IndeterminateSliderWithTextBoxInput(LocalisableString labelText, Bindable
                             break;
 
                         default:
-                            slider.Current.Parse(t.Text);
+                            slider.Current.Parse(t.Text, CultureInfo.CurrentCulture);
                             break;
                     }
                 }
diff --git a/osu.Game/Skinning/ISerialisableDrawable.cs b/osu.Game/Skinning/ISerialisableDrawable.cs
index 503b44c2dd..c9dcaca6d1 100644
--- a/osu.Game/Skinning/ISerialisableDrawable.cs
+++ b/osu.Game/Skinning/ISerialisableDrawable.cs
@@ -2,6 +2,7 @@
 // See the LICENCE file in the repository root for full licence text.
 
 using System;
+using System.Globalization;
 using osu.Framework.Bindables;
 using osu.Framework.Extensions.TypeExtensions;
 using osu.Framework.Graphics;
@@ -46,7 +47,7 @@ void CopyAdjustedSetting(IBindable target, object source)
                 if (!(target is IParseable parseable))
                     throw new InvalidOperationException($"Bindable type {target.GetType().ReadableName()} is not {nameof(IParseable)}.");
 
-                parseable.Parse(source);
+                parseable.Parse(source, CultureInfo.InvariantCulture);
             }
         }
     }
diff --git a/osu.Game/Skinning/LegacySkin.cs b/osu.Game/Skinning/LegacySkin.cs
index 2e91770919..9102231913 100644
--- a/osu.Game/Skinning/LegacySkin.cs
+++ b/osu.Game/Skinning/LegacySkin.cs
@@ -5,6 +5,7 @@
 using System.Collections.Generic;
 using System.Diagnostics;
 using System.Diagnostics.CodeAnalysis;
+using System.Globalization;
 using System.IO;
 using System.Linq;
 using JetBrains.Annotations;
@@ -330,7 +331,7 @@ protected override void ParseConfigurationStream(Stream stream)
 
                     var bindable = new Bindable<TValue>();
                     if (val != null)
-                        bindable.Parse(val);
+                        bindable.Parse(val, CultureInfo.InvariantCulture);
                     return bindable;
                 }
             }

```

and it seems tolerable indeed.

2023-12-05 17:48 UTC, bdach commented on osu.Framework/Bindables/IBindable.cs
> +    public interface IBindable : ICanBeDisabled, IHasDefaultValue, IUnbindable, IHasDescription, IFormattable, IParseable
don't post suggestions then

2023-12-05 18:14 UTC, bdach approved these changes

2023-12-05 18:15 UTC, merged

2023-12-13 05:07 UTC, peppy commented on osu.Framework/Bindables/Bindable.cs
> +                        Value = (T)Convert.ChangeType(input, underlyingType, provider ?? CultureInfo.CurrentCulture);
I'm.. not sure how I attached the wrong diff 😅 .