Fix `InputManager` including non-loaded direct children in input queue
ppy/osu-framework pull request #6101
Opened 2024-01-01 23:04 UTC by frenzibyte

- Closes https://github.com/ppy/osu/issues/23555

`KeyBindingContainer` gets into a weird state when handling input while not in a loaded state. Since it's not loaded, KeyBindings would be null since it only gets populated in LoadComplete, so no press/release events are propagated to children for the first key. However, the key gets stored in pressedInputKeys, and later on, when the next key is pressed, the old key incorrectly becomes processed as a new binding as well, causing the double-press issue.

`KeyBindingContainer` was not supposed to enter the input queue if it's not fully loaded in the first place, but turns out `InputManager` was incorrectly adding it (by bypassing `ShouldBeConsideredForInput`).

2024-01-02 08:11 UTC, bdach requested changes

2024-01-02 08:11 UTC, bdach commented on osu.Framework/Input/InputManager.cs
> +                    children[i].BuildNonPositionalInputQueue(inputQueue);
Two things:

The silent direct implication of this is that:
- [non-loaded drawables](https://github.com/ppy/osu-framework/blob/3eb7a688a5ba9edf0e23d2e3187ccec36266a1c7/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L1407) will not be included here (likely fine)
- [non-current screens](https://github.com/ppy/osu-framework/blob/3eb7a688a5ba9edf0e23d2e3187ccec36266a1c7/osu.Framework/Screens/ScreenStack.cs#L375) will not either (likely fine)

Given that `CompositeDrawable` already respects that method with the aforementioned implications, this seems likely fine, _but_ that doesn't answer the question why this is only applied to `InputManager.buildNonPositionalInputQueue()` but not to

https://github.com/ppy/osu-framework/blob/3eb7a688a5ba9edf0e23d2e3187ccec36266a1c7/osu.Framework/Input/InputManager.cs#L615-L628

I'm pretty sure it should be applied to both.

2024-01-02 08:11 UTC, bdach commented on osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
> +        public void TestPressKeyBeforeKeyBindingContainerAdded_WithPassThroughInputManager()
One thing that I wondered with this test is what happens once <kbd>Enter</kbd> is released after the key binding container is loaded / added. And the answer to that is nothing happens, i.e. the input manager does not receive the release of the <kbd>Enter</kbd> key. Which is probably a good thing, as it's better to send nothing than half a press, but it still has me worried about the implications on game usages.

So this is probably okay, but I'd appreciate assurances that nothing falls over game-side with this change applied, i.e. running game-side tests and making sure nothing fails.

2024-01-12 05:22 UTC, frenzibyte commented on osu.Framework/Input/InputManager.cs
> +                    children[i].BuildNonPositionalInputQueue(inputQueue);
Good catch, totally forgot about that one.

2024-01-12 05:24 UTC, frenzibyte commented on osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
> +        public void TestPressKeyBeforeKeyBindingContainerAdded_WithPassThroughInputManager()
> One thing that I wondered with this test is what happens once Enter is released after the key binding container is loaded / added. And the answer to that is nothing happens, i.e. the input manager does not receive the release of the Enter key. Which is probably a good thing, as it's better to send nothing than half a press, but it still has me worried about the implications on game usages.

If by "input manager" you mean the key binding container, then that is correct. I had run game-side tests beforehand and ensured nothing broke, but I'll check again to confirm.

2024-01-15 20:44 UTC, bdach approved these changes

2024-01-15 21:00 UTC, merged