Reduce allocation overhead for keyboard / binding / button handling
ppy/osu-framework pull request #6126
Opened 2024-01-11 07:44 UTC by peppy

Overall gains are pretty substantial (this is only with 13 keystrokes):

| Before | After |
| :---: | :---: |
| ![CleanShot 2024-01-11 at 07 44 09](https://github.com/ppy/osu-framework/assets/191335/78c1bbb1-97b5-4b4d-8f57-8615200d7c58) | ![CleanShot 2024-01-11 at 07 44 17](https://github.com/ppy/osu-framework/assets/191335/1574e0e3-1c05-490e-b167-db842dca03ed) |

---

94b4b2435aa692d79274fae680b31ceb1dfc8ecb Remove allocation overhead in button propagation flow

| Before | After |
| :---: | :---: |
| ![CleanShot 2024-01-11 at 07 40 36](https://github.com/ppy/osu-framework/assets/191335/3d99afd4-a2aa-408e-87b7-c552205b4cdf) | ![CleanShot 2024-01-11 at 07 41 14](https://github.com/ppy/osu-framework/assets/191335/0fb117e5-cd0c-4563-b654-676c4b721749) |

d16d899a67415dff193f5eb11a272cd99265916a Remove allocation overhead from `KeyBindingContainer` key handling

| Before | After |
| :---: | :---: |
| ![CleanShot 2024-01-11 at 07 35 00](https://github.com/ppy/osu-framework/assets/191335/be3dea65-6a97-4e09-9aac-4d1437662dbc) | ![CleanShot 2024-01-11 at 07 35 54](https://github.com/ppy/osu-framework/assets/191335/fd8bcc18-b608-45fd-83d0-9392bf3eecc9) |

7641f7021ef606f0e68ac28f5078b869648f8edd Reduce allocation overhead of `KeyCombination` constructor

| Before | After |
| :---: | :---: |
| ![CleanShot 2024-01-11 at 07 30 23](https://github.com/ppy/osu-framework/assets/191335/85afc530-0369-42e1-ac2a-8c1b272f7598) | ![CleanShot 2024-01-11 at 07 30 28](https://github.com/ppy/osu-framework/assets/191335/fbc6ad66-5cd5-4015-84d1-bcfc746b0188) |

2024-01-11 11:13 UTC, bdach commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +            keyBuilder.AddRange(keys);
As per inspection `keys` can be enumerated up to three times here. Probably shouldn't be. Maybe ctor argument should be `ICollection`.

2024-01-11 11:13 UTC, bdach commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +            newlyPressed.Sort(static (a, b) => b.KeyCombination.Keys.Length.CompareTo(a.KeyCombination.Keys.Length));
This is technically a change in behaviour as `.Sort()` uses an unstable algorithm while `.OrderByDescending()` uses a stable one. I don't realistically think it matters though.

2024-01-11 11:33 UTC, peppy commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +            keyBuilder.AddRange(keys);
That's what I was looking for.

2024-01-11 12:16 UTC, Susko3 requested changes

2024-01-11 12:16 UTC, Susko3 commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +                Keys = ImmutableArray<InputKey>.Empty;
The previous code would use `KeyCombiantion.none` instead of an empty array.

2024-01-11 12:19 UTC, bdach commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +                Keys = ImmutableArray<InputKey>.Empty;
to spell it out because the above kinda leaves it implied, they're unfortunately not the same thing (empty collection vs collection containing `InputKey.None`)

2024-01-11 12:22 UTC, peppy commented on osu.Framework/Input/Bindings/KeyCombination.cs
> -            Keys = keys?.Any() == true ? keys.Distinct().OrderBy(k => (int)k).ToImmutableArray() : none;
what's the case where it isn't already distinct?

2024-01-11 12:34 UTC, Susko3 commented on osu.Framework/Input/Bindings/KeyCombination.cs
> -            Keys = keys?.Any() == true ? keys.Distinct().OrderBy(k => (int)k).ToImmutableArray() : none;
With #5790, different physical keys might generate the same virtual keycode (eg. number row 0 and numpad 0). But I see that the `FromInputState()` code already does it's own de-duplication for keyboard keys specifically:
 https://github.com/ppy/osu-framework/blob/master/osu.Framework%2FInput%2FBindings%2FKeyCombination.cs#L625-L626

So it's probably fine, but the optimized ctor shouldn't be `public`.

2024-01-11 14:08 UTC, peppy commented on osu.Framework/Input/Bindings/KeyCombination.cs
> +                Keys = ImmutableArray<InputKey>.Empty;
Have fixed.

2024-01-11 17:48 UTC, bdach approved these changes

2024-01-11 18:03 UTC, bdach requested changes

2024-01-11 18:03 UTC, bdach commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                if (binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any)) continue;
There's a behavioural change here that breaks tests...

The previous code had an explicit `pressedInputKeys.Count == 0` check. That would basically "short circuit" the `IsPressed()` checking by just assuming that in such a case all pressed combinations must be released. But now this transformation breaks things because due to the lack of that special check, `IsPressed` is given `KeyCombination.none` as the `pressedCombination` here and dies.

Something like this fixes:

```diff
diff --git a/osu.Framework/Input/Bindings/KeyBindingContainer.cs b/osu.Framework/Input/Bindings/KeyBindingContainer.cs
index 6fcb2ba06..4e7908212 100644
--- a/osu.Framework/Input/Bindings/KeyBindingContainer.cs
+++ b/osu.Framework/Input/Bindings/KeyBindingContainer.cs
@@ -363,11 +363,12 @@ private void handleNewReleased(InputState state, InputKey releasedKey)
             {
                 var binding = pressedBindings[i];
 
-                if (binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any)) continue;
-
-                pressedBindings.RemoveAt(i--);
-                PropagateReleased(getInputQueue(binding).Where(d => d.IsRootedAt(this)), state, binding.GetAction<T>());
-                keyBindingQueues[binding].Clear();
+                if (pressedInputKeys.Count == 0 || !binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any))
+                {
+                    pressedBindings.RemoveAt(i--);
+                    PropagateReleased(getInputQueue(binding).Where(d => d.IsRootedAt(this)), state, binding.GetAction<T>());
+                    keyBindingQueues[binding].Clear();
+                }
             }
         }
 

```

but also feels immensely dodgy... Not sure what *else* to do, though.

2024-01-12 05:03 UTC, peppy commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                if (binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any)) continue;
I don't get it.

My thinking is that if `pressedBindings` is empty, there's nothing to release. What am I missing?

2024-01-12 06:01 UTC, bdach commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                if (binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any)) continue;
The previous code was filtering `pressedInputBindings` _basing on the value of_ `pressedKeys`. Significant difference.

Which then, with the current code, dies at

https://github.com/ppy/osu-framework/blob/master/osu.Framework%2FInput%2FBindings%2FKeyCombination.cs#L75

2024-01-12 15:58 UTC, peppy commented on osu.Framework/Input/Bindings/KeyBindingContainer.cs
> +                if (binding.KeyCombination.IsPressed(pressedCombination, KeyCombinationMatchingMode.Any)) continue;
Right. Got confused with variables to some degree. I think your solution is okay.

2024-01-12 16:08 UTC, bdach approved these changes

2024-01-12 16:24 UTC, merged