Include rounded corner radius in android safe area implementation
ppy/osu-framework pull request #6143
Opened 2024-01-18 11:09 UTC by bdach

Android apparently has a separate API for "window cutouts", i.e. for cameras and the like, and a [separate API for "rounded corners"](https://developer.android.com/develop/ui/views/layout/display-cutout), i.e. devices where the rounded corners of the display will cause some areas of the theoretically-rectangular display to be obscured. Because there is no engineering like overengineering, right? Bonus points for them being usable at different API levels, too.

Disclaimer that this does absolutely nothing on my one test device that has a rounded display and a high enough API level, but honestly it may be a device issue since it's not even returning `true` for `WindowInsets.IsRound`. Maybe it'll help someone, no idea.

2024-01-18 11:57 UTC, LittleEndu commented
Reading the code, I'm guessing that the resulting safe area is less than optimal.

![image](https://github.com/ppy/osu-framework/assets/11320483/a5be4e2e-d664-4682-abe8-e7057c78bdaf)

It would make way more sense if the code only cut away from the longest screen side (resulting in what I colored orange), or if optimizing for most play area only (1-(sqrt(2)/2) of the radius should be cut away (resulting in what I colored green). Hopefully someone can test what the resulting screen actually looks like.

Also there's a TODO still left in.

2024-01-18 12:17 UTC, Susko3 requested changes
I've yet to test this on a real device, but the native android stuff looks correct.

~~You should remove this todo about rounded corners:~~

~~https://github.com/ppy/osu-framework/blob/f67b4bfa910f0d23970a8d6a7d0a9afa262e4706/osu.Framework.Android/AndroidGameView.cs#L276C1-L276C1~~

2024-01-18 12:17 UTC, Susko3 commented on osu.Framework.Android/AndroidGameView.cs
> +                usableScreenArea = usableScreenArea.Intersect(radiusInsetArea);
I think the math here is too conservative. See the illustration (green would be considered the safe area):

![image](https://github.com/ppy/osu-framework/assets/16479013/631bad25-2988-4e55-b7b2-7509e0825b70)

It should either apply top & bottom or left & right padding, not both at the same time.

2024-01-18 12:24 UTC, Susko3 commented
I'm more for the orange solution as it matched what other games do & doesn't complicate things with 4-side padding. The green solution is too simple and not a true optimal area, as it doesn't consider the width and height of the screen (if the screen is really tall, it would be optimal to push the corner point towards the orange solution).

2024-01-18 12:27 UTC, bdach commented
can anyone with an iOS device say what iOS does with rounded corners? @frenzibyte @peppy?

2024-01-18 12:36 UTC, Susko3 commented
I think this is accurate, except the [bottom safe area edge is overriden locally](https://github.com/ppy/osu/blob/2be989b9f570f46bf95a11a162fcab9a3e0adc63/osu.iOS/OsuGameIOS.cs#L22-L25).


![safe_area](https://github.com/ppy/osu-framework/assets/16479013/b17f5092-9cc3-4a55-926c-601828d362ff)

2024-01-18 12:37 UTC, frenzibyte commented
iPhone 12:

![image](https://github.com/ppy/osu-framework/assets/22781491/e1f581cc-7302-4e58-b1d2-6d922e726fd5)

2024-01-18 12:40 UTC, bdach commented
that looks weird because it cuts out mostly at the long edge *but* also appears to cut out a bit on the short edge?

i dunno. think i'm just gonna make it cut at the long edge and hope everyone here can be satisfied with that.

2024-01-18 12:46 UTC, bdach commented on osu.Framework.Android/AndroidGameView.cs
> +                var radiusInsetArea = screenArea.Width >= screenArea.Height
i hope i can be forgiven for probably imperfectly handling square screens

2024-01-18 13:01 UTC, peppy commented
> that looks weird because it cuts out mostly at the long edge *but* also appears to cut out a bit on the short edge?
> 
that's just the bezel

2024-01-18 13:04 UTC, bdach commented on osu.Framework.Android/AndroidGameView.cs
> +                var radiusInsetArea = screenArea.Width >= screenArea.Height
it's not a setting, and i have absolutely no idea, can we skip that question?

2024-01-18 17:20 UTC, Susko3 approved these changes
Tested to work as expected when hard-coding corner radii.

2024-01-20 22:00 UTC, Joehuu approved these changes
LGTM on Pixel 6a.

2024-01-21 01:20 UTC, peppy approved these changes
Looks sane

2024-01-21 01:20 UTC, merged