FFmpeg: Only load versioned libraries on Linux
ppy/osu-framework pull request #6154
Opened 2024-01-28 22:12 UTC by FreezyLemon

Prerequisite:
- [ ]  #6153 (TODO: Update NativeLib in this PR after the the other PR is merged)

macOS and Windows already use versioned files, e.g. `libavutil.56.dylib`, `avutil-56.dll`. Linux uses unversioned binaries at the moment, presumably because the `NativeLibrary.Load` methods don't handle the Linux versioning conventions (`libavutil.so.56`) very well.

This change makes it so only compatible FFmpeg libraries are loaded[^1], which is the first step towards implementing #6025.

[^1]: As determined by the file name, which has some obvious caveats. Properly checking the library version seems like an overkill.

2024-01-29 09:24 UTC, smoogipoo requested changes

2024-01-29 09:24 UTC, smoogipoo commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +                string libraryName = RuntimeInfo.OS switch
Unfortunately, we don't use switch expressions in this project yet :(

2024-02-12 12:58 UTC, sr229 reviewed
Some small nits, I think you may need to make a new CI pipeline to test the switching.

2024-02-12 12:58 UTC, sr229 commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +                        libraryName = $"lib{name}.so.{version}";
You should be able to handle cases where there's a more updated of the library present, otherwise this will just break since system packages tend to update quite fast depending on the distro.

2024-02-12 13:13 UTC, bdach commented
> "you may need to make a new CI pipeline to test the switching"

what switching?

2024-02-12 13:14 UTC, bdach commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +                        libraryName = $"lib{name}.so.{version}";
what? we bundle these binaries in the appimage. they _must_ exist. we have not used the ambient ffmpeg install for a while now.

2024-02-12 14:08 UTC, sr229 commented
> > "you may need to make a new CI pipeline to test the switching"
> 
> @sr229 what switching?

Apologies, it seems this code is also meaning to set the stone for #6025 so I may have misread the intent of the PR as asking for a precise version especially in the context of the aforementioned issue this would break on a minor version upgrade. Please disregard and dismiss.

2024-02-12 15:33 UTC, FreezyLemon commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +                        libraryName = $"lib{name}.so.{version}";
Sorry, but was this a response to the review posted by sr229? I think something got deleted, but am not sure. I can answer this if it is directed at the PR, but I'm not sure

2024-02-12 15:54 UTC, bdach commented on osu.Framework/Graphics/Video/VideoDecoder.cs
> +                        libraryName = $"lib{name}.so.{version}";
Yes my comment was directed at @sr229. Review said something about "should not be hardcoding version because user might have different version installed on system".

2024-03-26 08:50 UTC, smoogipoo approved these changes
Lgtm! Thanks!

2024-03-26 08:50 UTC, merged