Use ThrowHelper methods in more places
ppy/osu-framework pull request #6184
Opened 2024-02-18 18:41 UTC by turbedi

ObjectDisposedException.ThrowIf(), ArgumentException.ThrowIfNullOrEmpty() and the ArgumentOutOfRangeException methods have been introduced in .NET 7/8

2024-02-18 22:39 UTC, smoogipoo commented on osu.Framework/Bindables/BindableNumber.cs
> +                ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value.CompareTo(default));
Can this be `ThrowIfNegativeOrZero(value)`?

2024-02-18 22:56 UTC, turbedi commented on osu.Framework/Bindables/BindableNumber.cs
> +                ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value.CompareTo(default));
Yes should be fine. Will change it.

2024-02-18 23:26 UTC, Susko3 requested changes
Seems ok but some error messages have changed for the worse.

2024-02-18 23:26 UTC, Susko3 commented on osu.Framework/Graphics/Containers/GridContainer.cs
> +            ArgumentOutOfRangeException.ThrowIfGreaterThan(minSize, maxSize);
Just noting that `maxSize` no will longer appear in the error message.

master:
```cs
System.ArgumentOutOfRangeException : Must be less than maxSize. (Parameter 'minSize')
```

This PR:
```cs
System.ArgumentOutOfRangeException : minSize ('20') must be less than or equal to '10'. (Parameter 'minSize')
Actual value was 20.
```

2024-02-18 23:26 UTC, Susko3 commented on osu.Framework/Testing/Drawables/TestGroupButton.cs
> +            ArgumentOutOfRangeException.ThrowIfZero(tests.Length);
Should be reverted, `tests.Length` is not an argument of this method. The error message doesn't make much sense.
```cs
0 ('tests.Length') must be a non-zero value.
```

2024-02-18 23:26 UTC, Susko3 commented on osu.Framework/Utils/IncrementalBSplineBuilder.cs
> +                ArgumentOutOfRangeException.ThrowIfNegative(cornerThreshold);
Wait this is actually wrong on master, it's checking the old `cornerThreshold` and not the newly-set `value`.
Should be changed to

```cs
ArgumentOutOfRangeException.ThrowIfNegative(value);
```

2024-02-18 23:26 UTC, Susko3 commented on osu.Framework/Utils/RNG.cs
> +            ArgumentOutOfRangeException.ThrowIfGreaterThan(minValue, maxValue);
See other comment about `maxValue`/`maxSize` no longer appearing in the error message. Same applies for the other usage of `ThrowIfGreaterThan()` in this file.

2024-02-18 23:26 UTC, Susko3 commented on osu.Framework/Utils/IncrementalBSplineBuilder.cs
> +                ArgumentOutOfRangeException.ThrowIfNegative(tolerance);
Should be:

```cs
ArgumentOutOfRangeException.ThrowIfNegative(value);
```

2024-02-18 23:27 UTC, Susko3 commented on osu.Framework/Bindables/BindableNumber.cs
> +                ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value.CompareTo(default));
Having this done via `CompareTo()` results in the actual value being misrepresented. Eg. setting a `BindableFloat.Precision` to `-5f` will show `-1` as the actual value.

```cs
System.ArgumentOutOfRangeException : value.CompareTo(default) ('-1') must be a non-negative and non-zero value. (Parameter 'value.CompareTo(default)')
Actual value was -1.
```

This is better handled via generic math (could just call `ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value)`). But that is a breaking change and should not be done in this PR, so best to revert for now.

2024-03-01 10:45 UTC, turbedi commented
I've addressed some of the comments. Should I also revert all usages of ThrowIfGreaterThan() to retain the max value in the error message, or is it fine like that?

2024-03-04 02:29 UTC, smoogipoo commented
The other path I can suggest is to make an `ExceptionUtils.ValidateRange()`. Otherwise, I'm _weakly_ okay with the change in messaging but I'd want other reviews.

2024-03-04 07:37 UTC, frenzibyte commented
I personally don't feel the exception message matters that much. Sure it might be a little bit cryptic, but the "must be greater than"/"must be lower than" is already giving it out I think.

2024-03-07 10:43 UTC, bdach commented
My view on the `ThrowIfGreaterThan()` thing is that I'd be fine with the max value not being printed *only* if it's a constant. So in cases where the max value isn't statically known just by looking at the direct call site it should print the max in the exception message.

In favour of revert.

2024-03-07 14:24 UTC, turbedi commented on osu.Framework/Bindables/BindableNumber.cs
> +                ArgumentOutOfRangeException.ThrowIfNegativeOrZero(value.CompareTo(default));
Done

2024-03-07 21:02 UTC, turbedi commented
All comments have been addressed.

2024-03-07 23:21 UTC, peppy approved these changes

2024-03-08 08:44 UTC, bdach approved these changes

2024-03-08 08:44 UTC, merged