Implement a "deferred" renderer
ppy/osu-framework pull request #6190
Opened 2024-02-19 08:50 UTC by smoogipoo

Prereqs:
- [ ] https://github.com/ppy/osu-framework/pull/6189
- [ ] https://github.com/ppy/osu-framework/pull/6187

This is something I've wanted to do for a while now, so I'm glad to finally get this out of the way and hopefully in a release in a somewhat "experimental" state for the time being. It's 100% isolated, so it should be an easy revert/deletion if it doesn't go as planned.

## Introduction

At its core, the idea is to record everything we need to do within a frame - all state changes, all vertices, all UBO data - and run through all of those "events" in a single pass at the end of the frame.  

By doing so we can eliminate some hackery that's employed by `VeldridRenderer` such as different implementations of staging buffers for different scenarios (sometimes causing breakage), and haphazardly using multiple command buffers to split out buffer/texture updates from the main command buffer.  
Furthermore, there's a hope that this can lead to further optimisations down the track, but there's significant work to be done before that's possible.

## Expectations

Before going further, I want to set some expectations:

- You should treat this as doing things correctly first, and improving performance second.
- Generally slightly lower performance across the board, though may be better on D3D11.
- Vulkan is stable on platforms that support it.
- OpenGL doesn't allocate nearly as much as Veldrid-OpenGL.
  - `OpenGL (Legacy)` will continue to be preferred.

## Deep dive

This effectively defines two passes:
- The "draw" pass starts at `Renderer.BeginFrame()` and ends just before `Renderer.FinishFrame()`. It covers the `DrawNode.Draw()` recursion.
- The "paint" pass starts and ends inside `Renderer.FinishFrame()`.

The draw and paint passes are functionally air-gapped via subtypes of `IRenderEvent`.

`ResourceAllocator` is a sort of in-process heap that facilitates marshalling between the two passes. You give it data, it gives you references that can be used later. This is because we can't pass managed objects between the two passes.

`EventList` holds all the draw events emitted by the deferred classes (`DeferredRenderer`, `DeferredShader`, et. al.)

`EventProcessor` is the "paint" pass - it runs through all events in the `EventList` and does the necessary graphics operations.

`UniformBufferManager` and `VertexManager` hold all UBO and vertex data as a contiguous array. There are some specifics as to how each of these work:
- Alignment is of utmost importance for UBOs.
- UBOs have strict size requirements, so they're usually exposed as 65KiB "chunks". If binding incorrectly, D3D11 will silently _ignore_ the bind request (not error or anything - _ignore_).
- Vertices are a little bit more lenient, but we're using the new `vertexIndexOffset` parameter of `GraphicsPipeline.DrawVertices()` which requires them to at least be aligned to their own struct size.

## Testing

- GT 710: D3D11 corruption fixed. Vulkan still dies in gameplay (driver issue).
- GTX 1650: Works.
- ARC A380: System dies on more than just lazer (driver issue).
- 9800 GT: Need to fiddle around with drivers - uses software rendering atm.
- Apple M1: Works.
- RX 5700XT: Works.
- RTX 3070Ti: Works

## Future work

- Improve alignment.
  - The performance of this all is dependent upon the marshalling & structures therein. I've implemented everything (e.g. `EventList`) without considering alignment (hence using `Unsafe.CopyUnaligned()`).
- Reimplement the masking SSBO. This is one thing that couldn't be done efficiently before due to in-line buffer updates.
- Avoid processing of `DrawNode`s that haven't changed during the "draw" pass.

2024-03-02 08:48 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Events/ResizeFrameBufferEvent.cs
> +    internal readonly record struct ResizeFrameBufferEvent(RenderEventType Type, ResourceReference FrameBuffer, Vector2I Size) : IRenderEvent
In recent changes, I've embedded `Type` into the struct rather than as a computed property, like this. This is a micro-optimisation for two reasons:
1. I can avoid a double array access (`array[0] = ...; array[1..] = ...;` / `read(array[0]); read(array[1..]);`).
2. If my understanding of alignment is correct, it should make the aligned versions of `Unsafe` safe to use. I'll leave that for a follow-up PR.

2024-03-04 23:09 UTC, turbedi commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                return buffer.AsSpan().Slice(reference.Offset, reference.Length);
```suggestion
                return buffer.AsSpan(reference.Offset, reference.Length);
```

2024-03-07 09:33 UTC, bdach commented
Hmm this failed to compile... @smoogipoo probably needs "silent" conflict resolution. git let me merge master just fine.

2024-03-07 09:37 UTC, smoogipoo commented
One more thing - if there's any suggestions for naming then I'm all ears. "QueuedRenderer", "BufferedRenderer", dunno.

"Deferred" rendering is a very specific rendering technique, so I can understand the naming being confusing.

2024-03-07 13:25 UTC, TheRealStevie commented on osu.Framework/Graphics/Rendering/Deferred/DeferredContext.cs
> +        /// References an objet.
Typo.
```suggestion
        /// References an object.
```

2024-03-07 13:25 UTC, TheRealStevie commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +        /// References an objet.
Typo.
```suggestion
        /// References an object.
```

2024-03-07 14:05 UTC, bdach reviewed
very initial pass, not tested, alloc parts mostly glossed over

mostly just examining structure and pointing out surprising things

2024-03-07 14:05 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/VertexManager.cs
> +        public void Commit()
I'm not sure what the "commit" here means. Looking at the only usage it seems to be more of a 'free resources' type call, and that's how the implementation looks, too?

2024-03-07 14:05 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/UniformBufferManager.cs
> +        public void Commit()
Same here

2024-03-07 14:09 UTC, smoogipoo commented on osu.Framework/Graphics/Veldrid/Pipelines/GraphicsPipeline.cs
> +                Commands.SetGraphicsResourceSet((uint)layout.Set, buffer.GetResourceSet(layout.Layout), 1, ref bufferOffset);
Yeah so as I found out between the previous branch and this one, this is actually required simply because the shader now uses dynamic binding. It's a bit unfortunate... I can maybe look at casing it out if it's an issue.

2024-03-07 14:11 UTC, bdach commented on osu.Framework/Graphics/Veldrid/Pipelines/GraphicsPipeline.cs
> +                Commands.SetGraphicsResourceSet((uint)layout.Set, buffer.GetResourceSet(layout.Layout), 1, ref bufferOffset);
I saw that flag change and was wondering what *that* was for but figured it was for Something Important so let it be. Probably fine in that case.

2024-03-07 14:16 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/DeferredRenderer.cs
> +            new EventProcessor(Context).ProcessEvents();
This has gone through several implementations, of which your suggestion was one. I ended up with this because storing `EventProcessor` unconsciously encouraged me to store state which I really didn't want to do.

There was a time where `Context` was a triple buffer, so here it would be something like `new EventProcessor(contexts[currentContext])`, which should sound more obvious why I wasn't keen on such "ease of storing states".

I can make it a class if you _really_ want, but it's a `ref struct` so all "allocations" are guaranteed to be on the stack. It's little more than separation of logic right now.

2024-03-07 14:18 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/DeferredRenderer.cs
> +            => ((DeferredFrameBuffer)frameBuffer).DeleteResources();
The base implementation makes sure that this is delayed 3 frames, after which all usages of this must have gone away.

2024-03-07 14:34 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/DeferredRenderer.cs
> +            => Graphics.UpdateTexture(texturePool, texture, x, y, width, height, level, data, rowLengthInBytes);
Fundamentally, this exists because `DeferredRenderer` is still using `VeldridTexture`. There's a weak guarantee that these all occur at the start of the frame via `DrawNode.Draw() -> Renderer.BindTexture() -> NativeTexture.Upload()` and the fact that all other commands are deferred.

I haven't done it yet because textures are a bit complicated due to their queueing mechanism that allows them to be uploaded mid-frame. In the current implementation `DeferredRenderer` doesn't do it during `EventProcessor` (they're only uploaded during `DrawNode.Draw()` as above), _however_ there's still a concern of would we have to make `EventList` threadsafe so that a `new UploadTexture()` event can be enqueued at any time, or how should that be handled?

Questions, I think, for a followup.

2024-03-07 14:34 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/DeferredShaderStorageBufferObject.cs
> +            buffer = renderer.Factory.CreateBuffer(new BufferDescription((uint)(elementSize * Size), BufferUsage.StructuredBufferReadOnly | BufferUsage.Dynamic, (uint)elementSize, true));
SSBOs are super temporary with this renderer. This is the most basic implementation that doesn't crash.

2024-03-07 14:41 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/DeferredVertexBatch.cs
> +                        throw new NotSupportedException();
Line strips and triangle strips reference the last 1 or 2 vertices respectively, so when overflowing a vertex buffer we need to copy those vertices into the new one. I haven't implemented this yet.

I haven't prioritised implementing them because I don't think osu! is going to use these in the near future.

Would `NotImplementedException` fit better?

2024-03-07 14:48 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                memoryBuffers.Add(new MemoryBuffer(memoryBuffers.Count, Math.Max(min_buffer_size * (1 << memoryBuffers.Count), length)));
I don't believe there's much reason for this, and is just something I did because why not. I'll make it `max(2mib, requested)`

2024-03-07 14:50 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/VertexManager.cs
> +        public void Commit()
It calls `Unmap()` which could be thought of as being the function that actually writes the data to GPU. So it's more like "finalise resources for use".

2024-03-07 15:24 UTC, smoogipoo commented
Something broke with this branch causing texture corruption around buffered containers. Looking into it.

2024-03-08 08:26 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/DeferredVertexBatch.cs
> +                        throw new NotSupportedException();
Yeah `NotImplemented` would carry intent better I think.

2024-03-08 14:47 UTC, smoogipoo commented
Texture corruption will be fixed via https://github.com/ppy/osu-framework/pull/6206

2024-03-11 13:18 UTC, bdach requested changes
allocation pass

2024-03-11 13:18 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/MemoryReference.cs
> +            }
I'm not sure this is going to be an actionable comment but an `unsafe` write primitive with no inherent bounds checking makes me _slightly_ nervous...

Both usages seem to be using the correct bounds checking for this, but if it were possible to fold that into here, I'd be much happier.

2024-03-11 13:29 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/MemoryReference.cs
> +            }
The unsafe part is just `target.Data.ToPointer()`, and what makes it safe is the `target.SizeInBytes` that follows it. The rest is safe.

I could rewrite it as:
```csharp
Span<byte> targetSpan;

unsafe
{
    targetSpan = new Span<byte>(target.Data.ToPointer(), (int)target.SizeInBytes);
}

context.GetRegion(this).CopyTo(targetSpan[offsetInTarget..]);
```
If that makes it any better for you?

Otherwise, I don't understand what you indicate to "fold".

2024-03-11 13:39 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/MemoryReference.cs
> +            }
I was mostly fine with the destination part, less so with the source part / values stored in `MemoryReference`. But I suppose

https://github.com/ppy/osu-framework/blob/0a5f3e14213bd157788056eb2b2f67feaa297c67/osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs#L166

is going to do bounds checking underneath so this is probably fine.

2024-03-11 14:01 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +            resources.Add(null!);
Previously, there used to be a special method called `NullReference()` that would give you a resource with `Id: 0`.

Nowadays, this can do `Reference<object?>(null)` directly, but that code path still had a special case that returned the `Id: 0` in such a case.

The reason for the special case is that, previously, the object list used to be de-duplicated. It was somewhat important at the time to maintain a single "null" entry in it, but this is not the case anymore, so I've removed it.

2024-03-11 14:05 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                memoryBuffers.Add(new MemoryBuffer(memoryBuffers.Count, Math.Max(min_buffer_size, length)));
This isn't a recursive method. If `length` is > 2MiB, it will allocate a buffer still from the array pool that is of at least the requested length, and place the object in there.

![image](https://github.com/ppy/osu-framework/assets/1329837/7fbecb31-e372-42d1-a5bb-e2127b42173b)

2024-03-11 14:07 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                memoryBuffers.Add(new MemoryBuffer(memoryBuffers.Count, Math.Max(min_buffer_size, length)));
Not sure how I misread that.

2024-03-11 14:09 UTC, smoogipoo commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                Debug.Assert(length <= Remaining);
This class is private, and this method is used in only one location which guarantees this condition. I'm hesitating to change this to an exception or do unnecessary work when the preconditions are easily verifiable because this is a very hot path.

2024-03-11 14:12 UTC, bdach commented on osu.Framework/Graphics/Rendering/Deferred/Allocation/ResourceAllocator.cs
> +                Debug.Assert(length <= Remaining);
This is gonna be a knock-on thing, I was worried about this because I misread the parent method (see the other review conversation) and was concerned that this was a ticking time bomb that just didn't go off because allocs have been too small for now. Now that I know that's wrong, this doesn't make much sense anymore, the caller ensures that this should be ok.

2024-03-11 15:16 UTC, merged