Don't clear `Logger.NewEntry` when flushing
ppy/osu-framework pull request #6191
Opened 2024-02-19 16:00 UTC by Susko3

Instead, `NewEntry` is cleared only when the `GameHost` is disposing.

This allows using `Logger.Flush()` when [exporting logs from osu!](https://github.com/ppy/osu/blob/d2990170d021f2caee2c6e66368f07792c7ac53c/osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs#L96), the specific use case is to log global statistics:
```cs
GlobalStatistics.OutputToLog();
Logger.Flush();

// create the compressed-logs.zip etc.
```

Clearing `NewEntry` when exporting logs is undesirable.

2024-02-19 22:39 UTC, frenzibyte approved these changes

2024-02-20 03:44 UTC, peppy requested changes

2024-02-20 03:44 UTC, peppy commented on osu.Framework/Logging/Logger.cs
> +        public static void Dispose()
static `Dispose` feels very wrong to me.

```diff
diff --git a/osu.Framework/Logging/Logger.cs b/osu.Framework/Logging/Logger.cs
index 69be3f974..c997ea80b 100644
--- a/osu.Framework/Logging/Logger.cs
+++ b/osu.Framework/Logging/Logger.cs
@@ -479,10 +479,9 @@ public static void Flush()
         }
 
         /// <summary>
-        /// Pause execution until all logger writes have completed and file handles have been closed.
-        /// This will also unbind all handlers bound to <see cref="NewEntry"/>.
+        /// Perform a <see cref="Flush"/> and unbind all events in preparation for game host shutdown.
         /// </summary>
-        public static void Dispose()
+        internal static void FlushForShutdown()
         {
             Flush();
             NewEntry = null;
diff --git a/osu.Framework/Platform/GameHost.cs b/osu.Framework/Platform/GameHost.cs
index e6b4c42ba..09b132787 100644
--- a/osu.Framework/Platform/GameHost.cs
+++ b/osu.Framework/Platform/GameHost.cs
@@ -396,7 +396,7 @@ private void abortExecutionFromException(object sender, Exception exception, boo
             // In the case of an unhandled exception, it's feasible that the disposal flow for `GameHost` doesn't run.
             // This can result in the exception not being logged (or being partially logged) due to the logger running asynchronously.
             // We force flushing the logger here to ensure logging completes (and also unbind in the process since we're aborting execution from here).
-            Logger.Dispose();
+            Logger.FlushForShutdown();
 
             var captured = ExceptionDispatchInfo.Capture(exception);
             var thrownEvent = new ManualResetEventSlim(false);
@@ -1391,7 +1391,7 @@ protected virtual void Dispose(bool disposing)
             Window?.Dispose();
 
             LoadingComponentsLogger.LogAndFlush();
-            Logger.Dispose();
+            Logger.FlushForShutdown();
         }
 
         public void Dispose()

```

2024-02-22 03:28 UTC, peppy approved these changes

2024-02-22 10:08 UTC, merged