Make SDL3Clipboard support images
ppy/osu-framework pull request #6241
Opened 2024-04-13 12:25 UTC by Speykious

This PR supersedes https://github.com/ppy/osu-framework/pull/6151 which aimed at adding support for copying and pasting images from the clipboard on Linux, but had the wrong approach of calling into an external executable (`xclip` for X11).

In the mean time I had actually started a native clipboard library in Rust for applications that would support any mime types and be given arbitrary data, but since osu!framework now uses SDL3, I can just use `SDL_GetClipboardData` and `SDL_SetClipboardData` [as suggested back then by @Susko3](https://github.com/ppy/osu/discussions/16775#discussioncomment-8382238).

This is a first attempt at implementing this, and on my Linux machine, the visual tests for copying images are all green! :D
That said, I really don't know what to think of this code, because this is all pretty unsafe. I had to dig through random GitHub issues to even find a way to have an unmanaged delegate like that... And this static `pngData` is very probably a safety hazard. I'm gonna have to find a way to ensure no memory leak happens.

Maybe I could `SDL_malloc` the `userdata` and then free it myself somewhere like in the cleanup callback or something.

2024-04-13 12:31 UTC, Speykious commented
There's also the caveat that I only implemented a way to copy PNGs. Wouldn't it also need to be able to copy JPGs depending on some setting? I know osu! lets you choose the image format for screenshot savings.

2024-04-13 12:50 UTC, smoogipoo commented
What you have looks pretty standard for the new age of unmanaged->managed callbacks. That being said, this PR now competes with https://github.com/ppy/osu-framework/pull/6223 and we should probably make sure that this implementation is going to easily lend itself to other mime types in the future.

2024-04-13 13:10 UTC, FreezyLemon commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                byte* data = (byte*)SDL3.SDL_GetClipboardData(Encoding.UTF8.GetBytes("image/png"), &size);
Maybe SDL3-CS handles this automagically somehow, but I think you're missing a null terminator here. The `byte[]` returned by `Encoding.GetBytes` does not include a null byte at the end.

2024-04-13 13:17 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                byte* data = (byte*)SDL3.SDL_GetClipboardData(Encoding.UTF8.GetBytes("image/png"), &size);
Would `"image/png\0"u8` work better then?

2024-04-13 13:31 UTC, FreezyLemon commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                byte* data = (byte*)SDL3.SDL_GetClipboardData(Encoding.UTF8.GetBytes("image/png"), &size);
Yeah, that should work

2024-04-13 15:37 UTC, Speykious commented
![image](https://github.com/ppy/osu-framework/assets/13885008/b58b6d4b-1bef-480f-92db-0bfdd1ba8b0f)
I debugged a lot today (both with a debugger and with prints) and concluded that `pngData` was fine as a static due to how the API works. It only calls for a cleanup once if we're requesting for an image again.

2024-04-14 11:17 UTC, Speykious commented
![image](https://github.com/ppy/osu-framework/assets/13885008/accb0aed-b9b3-473c-b973-4aabc02cf69a)
It seems that sometimes the test gives a completely empty screenshot. I was worried that my implementation had some weird undefined behavior thing, but it seems like that bug is happening elsewhere...?

2024-04-14 11:20 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                byte* data = (byte*)SDL3.SDL_GetClipboardData(Encoding.UTF8.GetBytes("image/png"), &size);
done!

2024-04-14 11:28 UTC, Speykious commented
![image](https://github.com/ppy/osu-framework/assets/13885008/2659d6cd-92e4-4465-9eda-d659c76b69d5)
It seems I'm missing something related to the unmanaged call convention

2024-04-15 13:30 UTC, Susko3 commented
I'm testing this on windows (by commenting out the `WindowsClipboard` override) and I can't get images from osu!framework into external programs (and vice versa). The clipboard tests pass fine, but applications complain about there being no image in the clipboard. And trying to paste images into framework doesn't work: either I get the stale image (last one copied from framework) or no image at all (even when copying a sample PNG from the internet).

![image](https://github.com/ppy/osu-framework/assets/16479013/f0dff68b-2c3d-4407-a087-2e44d3eb352c)

Does copying images to/from framework into external programs work on Linux?

2024-04-15 13:33 UTC, Speykious commented
It does work on Linux (at least on my machine on X11), as long as there is a clipboard manager present. If there is no clipboard manager, the selection will disappear once the application closes, which is expected behavior.

I don't know why it doesn't work on Windows though. :/

2024-04-15 14:15 UTC, Susko3 commented
Works perfectly fine on windows if the mime type is changed to `image/bmp` and the image is saved with `.SaveAsBmp()`. Do bitmaps work on Linux too?

I wonder if it works on macOS (which currently uses `MacOSClipboard`) and iOS (which uses `SDL3Clipboard`).

2024-04-15 14:32 UTC, FreezyLemon commented
> Works perfectly fine on windows if the mime type is changed to `image/bmp` and the image is saved with `.SaveAsBmp()`. Do bitmaps work on Linux too?
> 
> I wonder if it works on macOS (which currently uses `MacOSClipboard`) and iOS (which uses `SDL3Clipboard`).

At least on Wayland, the mime type also has to match. If I e.g. copy a PNG from my local storage, the current code works fine. If I use a Paint-like program to scribble around, Ctrl-A and Ctrl-C, then it's also saved as an `image/bmp` and needs that exact mime type to be retrieved from SDL.

The obvious solution would be to just have a list of image mimetypes that are tried one after another. FWIW, [SDL itself also does this](https://github.com/libsdl-org/SDL/blob/d0819bcc5cfe852ad60deab4e1ff7d5598f0b983/src/video/SDL_clipboard.c#L298-L304) for the built-in `GetClipboardText` function.

2024-04-15 15:00 UTC, Speykious commented
I'll try to implement a multi-mime-types solution.

2024-04-15 15:08 UTC, Susko3 commented
We should probably ask ImageSharp about it's supported decoder formats, see https://github.com/SixLabors/ImageSharp/discussions/1353 (but with [`IImageFormat.MimeTypes`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Formats.IImageFormat.html#SixLabors_ImageSharp_Formats_IImageFormat_MimeTypes)).

This is what I get on windows:
```
image/png
image/apng
image/jpeg
image/pjpeg
image/gif
image/bmp
image/x-windows-bmp
image/x-portable-pixmap
image/x-portable-anymap
image/x-tga
image/x-targa
image/tiff
image/tiff-fx
image/webp
image/qoi
image/x-qoi
image/vnd.qoi
```

2024-04-15 15:21 UTC, Susko3 requested changes
I'd rather rewrite this PR then to try and fix it.

2024-04-15 15:21 UTC, Susko3 commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                    buffer[i] = data[i];
This should use [`Marshal.Copy`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.copy?view=net-8.0#system-runtime-interopservices-marshal-copy(system-intptr-system-byte()-system-int32-system-int32)).

2024-04-15 15:21 UTC, Susko3 commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
>          }
Can probably be done much cleaner with a `GCHandleType.Pinned` `ObjectHandle<byte[]>`.

Similar to:
https://github.com/ppy/osu-framework/blob/32e7571aa858c4d055f45cc487c08a11aab64817/osu.Framework/Audio/Sample/SampleBassFactory.cs#L84-L85

2024-04-15 15:21 UTC, Susko3 commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                if (SDL3.SDL_strcmp(mimeType, pngMimetypeStr) == 0)
There is no reason to delegate string comparison to SDL. Better to decode the pointer with `SDL3.PtrToStringUTF8` and use `==` on C# `string`s.

2024-04-15 15:24 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                if (SDL3.SDL_strcmp(mimeType, pngMimetypeStr) == 0)
By using `SDL_strcmp`, I don't need to copy any data over before doing the comparison.

2024-04-15 15:43 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
>          }
Passing around a `byte[]` means the copying will happen in the callback and not before.
But I might end up using an `ObjectHandle` anyways to support multiple mime types. Only this time it'll need to be the `Image` itself.

2024-04-15 16:08 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
>          }
This is trickier than I expected.
In the `SampleBassFactory` code, the handle is created with `using`, so it gets freed immediately after `SampleLoad` gets called. This is fine because `SampleLoad` makes a copy of the data immediately - from its documentation:
> *There is no need to pin the memory buffer for this method, since after loading a sample from memory, the memory can safely be discarded, as a copy is made.*
But I can't just free the `ObjectHandle` immediately after `SDL_SetClipboardData` gets called. Instead I have to free it inside of the `cleanup` callback, which will be called with the old `userdata` before each new call to `SDL_SetClipboardData`.
And unfortunately, I can't just do it manually with `.Dispose()` either, because disposing an object handle obtained from a `nint` won't actually free the object handle, we can only free it on the original one.

I feel like now I need to have two swapping global variables (due to how the cleanup logic works), which would make an object handle unnecessary...

2024-04-18 10:39 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
> +                if (SDL3.SDL_strcmp(mimeType, pngMimetypeStr) == 0)
I ended up doing it anyway to be able to use `ImageFormatManager.TryFindFormatByMimeType` :)

2024-04-18 10:39 UTC, Speykious commented on osu.Framework/Platform/SDL/SDL3Clipboard.cs
>          }
> I feel like now I need to have two swapping global variables

Welp, this is what I have currently

2024-04-18 10:40 UTC, Speykious commented
> Works perfectly fine on windows if the mime type is changed to `image/bmp` and the image is saved with `.SaveAsBmp()`.

@Susko3 Can you tell me if this works on Windows now?

2024-04-18 11:01 UTC, Speykious commented
In any case, I can confirm that it works on MacOS.
![image](https://github.com/ppy/osu-framework/assets/13885008/5aad31cd-d61b-4175-b0a7-4fa9ef3f0735)
![image](https://github.com/ppy/osu-framework/assets/13885008/91956fd1-b0dc-4e2c-9934-0164f193a666)

2024-04-19 19:30 UTC, Susko3 commented
Thanks for the PR,

2024-04-19 19:30 UTC, closed without merging