FFmpeg: Update FFmpeg.AutoGen to 7.0.0
ppy/osu-framework pull request #6256
Opened 2024-04-19 22:42 UTC by FreezyLemon

Closes #5051. There is still a VP9 bug (discussed in that issue), but there hasn't been any movement [upstream](https://trac.ffmpeg.org/ticket/9599) so I assume this is not going to be fixed. I have added a rudimentary (untested) workaround for that issue in this PR.

Prerequisite:
- [ ] #6255 

FFmpeg.AutoGen had a [large API change](https://github.com/Ruslan-B/FFmpeg.AutoGen/pull/227) somewhere around 5.0 or 5.1.

The gist is that `ffmpeg.GetOrLoadLibrary` was removed in favour of the `IFunctionResolver` API. The default resolvers are not usable in o!f[^1], so I added a simple `FFmpegFunctionResolver` class.

Notes:
- Docs are not final. Contents should be correct though
- TODO: Mobile platforms

Open questions:
- Should `FFmpegFunctionResolver` support bringing a different set of libraries? (alternative: framework users have to implement `IFunctionResolver` themselves)
- Is the `OSArchitecture` check correct? We need to differentiate between ARM and x86 architectures for this check, and there's both a [OSArchitecture](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture?view=net-8.0) and a [ProcessArchitecture](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture?view=net-8.0) property to check. I'm not sure how these differ in practice (VMs? Rosetta translation layer? etc.), and they are also both not in o!f's own `RuntimeInfo` class
- Maybe move setting the `FunctionResolver` into a static constructor for `FFmpegFuncs`. Feels like it would reduce the likelihood of problems for framework users.

Feel free to start testing / giving feedback, but this still needs a bit of work, and a lot of testing.

[^1]: The built-in `LibraryDependenciesMap` is wrong for the custom libraries used in o!f. It also requires fiddling with the `RootPath` property and calls system APis (dlopen etc.) directly. Using `NativeLibrary` instead should be more ergonomic.

2024-04-22 07:47 UTC, smoogipoo commented
Enabling HW accel on macOS (x64):
```
[h264 @ 0x7fbc86787680] Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
[h264 @ 0x7fbc86787680] co located POCs unavailable
[h264 @ 0x7fbc86787680] mmco: unref short failure
[h264 @ 0x7fbc86787680] co located POCs unavailable
```
But this is the same as master and the video continues to play, so that's fine.

2024-04-22 08:02 UTC, smoogipoo commented
Enabling HW accel under macOS (rosetta):
```
[h264 @ 0x7ff6b672c1c0] vt decoder cb: output image buffer is null: -12909
[h264 @ 0x7ff6b672c1c0] hardware accelerator failed to decode picture
[h264 @ 0x7ff6d674e740] co located POCs unavailable
[h264 @ 0x7ff6d674e740] mmco: unref short failure
[h264 @ 0x7ff6d674e740] co located POCs unavailable
```
Versus master:
```
[h264 @ 0x13e8be000] Missing reference picture, default is 0
[h264 @ 0x13e8be000] decode_slice_header error
[h264 @ 0x13e8be000] hardware accelerator failed to decode picture
[h264 @ 0x13e8be000] reference picture missing during reorder
[h264 @ 0x13e8be000] reference picture missing during reorder
[h264 @ 0x13e8be000] reference picture missing during reorder
[h264 @ 0x13e8be000] reference picture missing during reorder
[h264 @ 0x13e8be000] Missing reference picture, default is 0
[h264 @ 0x13e8be000] decode_slice_header error
[h264 @ 0x13e8be000] Missing reference picture, default is 65540
[h264 @ 0x13e8be000] Missing reference picture, default is 65540
[h264 @ 0x13e8be000] mmco: unref short failure
[h264 @ 0x13e8be000] mmco: unref short failure
[h264 @ 0x13e8be000] reference picture missing during reorder
[h264 @ 0x13e8be000] Missing reference picture, default is 65536
[h264 @ 0x13e8be000] mmco: unref short failure
```
Can't really tell whether it's working or not, but the video is. Regardless, no one should be running o!f under Rosetta.

2024-04-22 08:41 UTC, smoogipoo commented
👍 macOS (x64):
```
master:
[runtime] 2024-04-22 08:39:04 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:39:05 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc

pr:
[runtime] 2024-04-22 08:40:03 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:40:04 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc
```

👍 macOS (Rosetta):
```
master:
[runtime] 2024-04-22 08:30:59 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:31:00 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc

pr:
[runtime] 2024-04-22 08:33:51 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:33:53 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc
[runtime] 2024-04-22 08:33:55 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec vp9
```

👍 macOS (arm64):
```
master:
[runtime] 2024-04-22 08:36:22 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:36:23 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc

pr:
[runtime] 2024-04-22 08:35:05 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
[runtime] 2024-04-22 08:35:06 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec hevc
[runtime] 2024-04-22 08:35:09 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec vp9
```

Looks about as expected. Looks like `OSArchitecture` is working under Rosetta, though no one should be running o!f under Rosetta.

2024-04-22 08:47 UTC, smoogipoo commented
👍 Windows (x64):
```
master:
[runtime] 2024-04-22 08:43:38 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec h264
[runtime] 2024-04-22 08:43:39 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec hevc
[runtime] 2024-04-22 08:43:41 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec vp9

pr:
[runtime] 2024-04-22 08:46:24 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec h264
[runtime] 2024-04-22 08:46:26 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec hevc
[runtime] 2024-04-22 08:46:28 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_D3D11VA for codec vp9
```

2024-04-22 08:56 UTC, smoogipoo commented
No hardware decoders load for me on Linux (either master or PR) but that's a configuration issue my side.

2024-04-22 09:00 UTC, smoogipoo commented
> Should FFmpegFunctionResolver support bringing a different set of libraries?

Let's not.

> Is the `OSArchitecture` check correct?

Going by my above testing it seems to be fine as is. Haven't tested VM but that's a pretty esoteric use case that we'll cross if it ever comes up. None of our testing considers Rosetta right now, so I'd say it's also irrelevant (even though I tested it).

> Maybe move setting the `FunctionResolver` into a static constructor for `FFmpegFuncs`.

It may be safer, but I also don't expect users to be using FFmpeg directly themselves.

2024-04-22 09:10 UTC, smoogipoo commented
Is this ready to be merged? You mention it needs a bit of work, but it seems to be working alright.

2024-04-22 14:37 UTC, FreezyLemon commented
> No hardware decoders load for me on Linux (either master or PR) but that's likely a configuration issue my side (or ffmpeg compile things™)

This is expected (see #6025).

> Is this ready to be merged? You mention it needs a bit of work, but it seems to be working alright.

That's good, but I have a feeling this will break video playback on mobile platforms (those still bundle old, pre-5.0 FFmpeg libraries which might cause binary incompatibilities).

Otherwise, I feel pretty good about the state of the PR. I'll probably do that one thing with the `FFmpegFuncs` static constructor and then take a look at Android and iOS

2024-04-23 15:57 UTC, FreezyLemon commented
This should be fine now. I thought the mobile platforms might need some changes on the .NET side, but it looks like they'll work just fine as long as the native libraries follow the same conventions.

2024-05-14 23:13 UTC, frenzibyte requested changes

2024-05-14 23:13 UTC, frenzibyte commented on osu.Framework/Graphics/Video/FFmpegFuncs.cs
> +            DynamicallyLoadedBindings.FunctionResolver = new FFmpegFunctionResolver();
`FFmpegFuncs` is shared across all platforms but `FFmpegFunctionResolver` crashes on any platform that's not desktop. Noticed this while testing iOS.

```suggestion
            if (RuntimeInfo.IsDesktop)
                DynamicallyLoadedBindings.FunctionResolver = new FFmpegFunctionResolver();
```

2024-05-14 23:36 UTC, frenzibyte commented
👍 iOS (arm64):
```
master:
2024-05-15 02:28:28.733 osu.Framework.Tests[1894:494188] [runtime] 2024-05-14 23:28:28 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
2024-05-15 02:28:28.734 osu.Framework.Tests[1894:494188] [runtime] 2024-05-14 23:28:28 [verbose]: Successfully initialized decoder: h264

pr:
2024-05-15 02:24:22.766 osu.Framework.Tests[1883:490066] [runtime] 2024-05-14 23:24:22 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
2024-05-15 02:24:22.766 osu.Framework.Tests[1883:490066] [runtime] 2024-05-14 23:24:22 [verbose]: Successfully initialized decoder: h264
```

👍 iOS simulator (x86_64):
```
master:
2024-05-15 02:31:08.698145+0300 osu.Framework.Tests[60243:6304306] [runtime] 2024-05-14 23:31:08 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
2024-05-15 02:31:08.701010+0300 osu.Framework.Tests[60243:6304306] [runtime] 2024-05-14 23:31:08 [verbose]: Successfully initialized decoder: h264
[h264 @ 0x7fa502d35400] Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.

pr:
2024-05-15 02:34:44.993640+0300 osu.Framework.Tests[64562:6328122] [runtime] 2024-05-14 23:34:44 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_VIDEOTOOLBOX for codec h264
2024-05-15 02:34:44.994314+0300 osu.Framework.Tests[64562:6328122] [runtime] 2024-05-14 23:34:44 [verbose]: Successfully initialized decoder: h264
[h264 @ 0x7fd4da7199c0] Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
```
(hardware acceleration never "works" on iOS simulator so ignoring)

2024-05-15 11:37 UTC, FreezyLemon commented
I just noticed that you removed the old iOS libraries from this branch, @frenzibyte. I would've preferred doing that in the auto-generated PR that will be created after #6255 is merged and new binaries are built (example of this PR: #6227).

Do you mind if we remove that change from this PR and include it in the binaries update?

2024-05-15 11:39 UTC, frenzibyte commented
Sure, I pushed it here because I found there's no reason not to, as this PR is already meant to be merged after the FFmpeg libraries update.

2024-05-15 11:44 UTC, FreezyLemon commented
Fair enough. It's just my preference to keep it separated, so that merging only one PR would not result in having double or no library files. Thanks

2026-07-15 09:37 UTC, FreezyLemon commented
Not sure why this wasn't merged, but it's way outdated now. I'm not sure what happened to the related NativeLibs change, looks like other changes have happened since. This would need to be retested before it can get merged, but FFmpeg has released 8.0 and 8.1 in the meantime so it might make more sense to upgrade to that instead.

2026-07-15 09:37 UTC, closed without merging