Refactor child masking bounds handling
ppy/osu-framework pull request #6266
Opened 2024-04-23 04:55 UTC by EVAST9919

Split from https://github.com/ppy/osu-framework/pull/6261

Original pr has too much stuff changed at once, so a bit more lenient approach feels way better.

2024-04-23 05:09 UTC, EVAST9919 commented on osu.Framework/Graphics/Drawable_ProxyDrawable.cs
> +            protected override bool ComputeIsMaskedAway(RectangleF maskingBounds) => false;
Should I be using `UpdateSubTreeMasking() => false` here may be? It's a bit hard to wrap my head around proxies, to be honest.

2024-04-25 20:12 UTC, EVAST9919 commented on osu.Framework/Graphics/Drawable_ProxyDrawable.cs
> +            protected override bool ComputeIsMaskedAway(RectangleF maskingBounds) => false;
Yes, I should.

2024-05-08 08:05 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +                childMaskingBoundsBacking.Invalidate();
Since layout invalidation doesn't propagate, could there be a situation such as:
- Everything is validated.
- Parent has `Masking` set to `true`.
- The parent's masking bounds are invalidated, but the child isn't.
- The child still uses the old masking bounds.

It looks like your test scene asserts against `parent.ChildMaskingBounds`, but does not check an actual child's masking bounds.

2024-05-08 08:06 UTC, smoogipoo commented on osu.Framework/Graphics/Containers/CompositeDrawable.cs
> +                childMaskingBoundsBacking.Invalidate();
If this is the case, then we may want a masking invalidation bit instead.

2024-05-08 08:17 UTC, smoogipoo requested changes

2024-05-08 08:17 UTC, smoogipoo commented on osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
> +            AddStep("Disable masking", () => container.Masking = true);
```suggestion
            AddStep("Enable masking", () => container.Masking = true);
```

2024-05-08 21:12 UTC, EVAST9919 commented
> I believe that this assertion should pass.

The test you've provided failed because as you said children weren't aware of the masking changes in the sub-tree. Invalidating `DrawInfo` did the trick, and it shouldn't affect performance since there are little to no use cases of frequent masking toggling.

2024-05-09 11:20 UTC, smoogipoo approved these changes

2024-05-09 11:21 UTC, smoogipoo commented
Looks okay now, can't think of anything else that'll break. The `DrawNode` invalidation is probably not required but I can understand why you've added it. Not a big deal in any case.

2024-05-09 11:22 UTC, merged