Add targets linux-arm, linux-arm64
ppy/osu-framework pull request #6288
Opened 2024-05-19 10:49 UTC by kvnp

This PR adds the targets linux-arm, linux-arm64 as part of https://github.com/ppy/osu-deploy/pull/170. Will be updated once https://github.com/ppy/osu-framework/pull/6255 is merged.

2024-05-22 13:07 UTC, FreezyLemon requested changes
Some notes:

- Please remove changes not related to the Linux build (macOS bump, merging the Windows build process). These are out of scope and maybe change the resulting binaries which would need testing
- The x86 build [doesn't work](https://github.com/FreezyLemon/osu-framework/actions/runs/9191208432). x86 support is not necessary so you don't need to include it at all, but if you do want to include it, please make sure it works.

I wonder if there's a way to achieve the same builds using cross-compilation similar to the Windows build scripts. That would make it a lot easier to compile these locally (installing QEMU and docker is fairly hefty for these simple builds). That said, it's not a high priority or blocking issue.

2024-06-28 05:25 UTC, smoogipoo commented
This one can be updated now that https://github.com/ppy/osu-framework/pull/6255 has been merged.

2024-07-06 03:38 UTC, kvnp commented
> Some notes:
> 
> * Please remove changes not related to the Linux build (macOS bump, merging the Windows build process). These are out of scope and maybe change the resulting binaries which would need testing
> * The x86 build [doesn't work](https://github.com/FreezyLemon/osu-framework/actions/runs/9191208432). x86 support is not necessary so you don't need to include it at all, but if you do want to include it, please make sure it works.

linux-x86 now builds after disabling asm. I'm not sure about the performance implications, but I'm glad to be one step ahead for now. According to this [issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109137), GCC is having trouble building FFMPEG for x86 32-bit on a 64-bit system. I would open a new PR when this is fixed.

> I wonder if there's a way to achieve the same builds using cross-compilation similar to the Windows build scripts. That would make it a lot easier to compile these locally (installing QEMU and docker is fairly hefty for these simple builds). That said, it's not a high priority or blocking issue.

I find it much easier to set up Docker than to try to piece together a cross-compilation toolchain. If multiplatform images are needed, which is the case here, Docker can install the QEMU binaries [by itself with a single command](https://docs.docker.com/build/building/multi-platform/#qemu-without-docker-desktop). I would leave it as is for now, but would like to revisit this in the future when I have more experience with cross compiling on Linux.

2024-07-07 17:44 UTC, FreezyLemon requested changes
Thanks for addressing my review. I left some feedback, sadly the `dpkg` change breaks the scripts for me (I'm not on a Debian-based distro).

> linux-x86 now builds after disabling asm. I'm not sure about the performance implications, ...

It's cool that you got it to work, but without someone confirming that the binaries are usable in terms of performance, I'm not entirely sure it's a great idea to include them..

> I find it much easier to set up Docker than to try to piece together a cross-compilation toolchain.

FFmpeg really doesn't require much of a toolchain, basically gcc/clang plus the GNU assembler. It shouldn't be more complicated than the Windows script that already exists. To be fair, Docker is still simpler, but it's just not my preference.

2024-07-07 17:44 UTC, FreezyLemon commented on .github/workflows/build-ffmpeg.yml
> +            fi
`--disable-asm` on x86 Linux should mean that this is not needed

2024-07-07 17:44 UTC, FreezyLemon commented on osu.Framework.NativeLibs/scripts/ffmpeg/build-linux.sh
> +fi
Please don't use `dpkg` for this. `uname` is available almost everywhere while `dpkg` is Debian-specific.

2024-07-07 17:44 UTC, FreezyLemon commented on osu.Framework.NativeLibs/scripts/ffmpeg/common.sh
> +    fi
Could be moved to `build-linux.sh` (the other platforms also do arch-specific changes inside their own build scripts, see for example `build-win.sh` lines 23 - 38)

2024-10-29 01:17 UTC, sr229 commented
Looks like [ARM64 runners will be available in the end of the year](https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/) and is available now for GitHub Enterprise Cloud/Team orgs. I suggest holding off this one until this becomes generally available.

2025-06-08 10:35 UTC, closed without merging