Implement `FastCircle` component
ppy/osu-framework pull request #6290
Opened 2024-05-19 11:14 UTC by EVAST9919

Adresses https://github.com/ppy/osu-framework/issues/6067, https://github.com/ppy/osu/issues/21495

Pros:
* No nested `Box` drawable (adds up in demanding scenarios)
* [Correct masking when used inside `CircularContainer`](https://github.com/ppy/osu-framework/assets/22874522/2a484318-582e-46f7-b60b-543fb4cbea45)
* No overhead from masking info and no batch breaking in cases when multiple circles are being drawn consecutively (though I think SSBO supposed to fix that?)

Cons (which are holding me from replacing current `Circle` implementation with this one):
* `Circle` is no longer a container (so is the `Box` which I think is fine)
* No ability to set masking-related effects directly (again `Box` has the same properties)
* Points above might be considered a breaking change, but easily fixeable by using `CircularContainer` instead
* Has a separate shader

Performance comparison in demanding scenarios:
|master|pr|
|---|---|
|![Снимок экрана (524)](https://github.com/ppy/osu-framework/assets/22874522/3533310f-6f22-4606-86a6-a1299e2adc6d)|![Снимок экрана (525)](https://github.com/ppy/osu-framework/assets/22874522/6739bf22-66a5-4ddb-9173-82da1ebf5060)|
|![master-mania](https://github.com/ppy/osu-framework/assets/22874522/d6a19def-f28c-49b2-bbc9-9b4f262f2401)|![pr-mania](https://github.com/ppy/osu-framework/assets/22874522/65e94d45-c0dc-4841-9ef1-08081b0018ea)|
|![master-mania-2](https://github.com/ppy/osu-framework/assets/22874522/fa41504f-3595-4a25-bbcc-7cb5b590c659)|![pr-mania-2](https://github.com/ppy/osu-framework/assets/22874522/6c9910b5-fc03-4adb-9627-6670ee51427a)|
|![master-slider](https://github.com/ppy/osu-framework/assets/22874522/6d5645ce-3ce4-445e-851a-ffa397fab763)|![pr-slider](https://github.com/ppy/osu-framework/assets/22874522/58f1ed68-0769-4e74-9911-8f10aec9b39a)|

2024-05-19 11:26 UTC, bdach commented
Just reading the title of this makes me want to go "no why is this being proposed even". I'd hope we can not resort to cpp style microoptimisations like this. But maybe it's just me 🤷 

I'd be much more okay with this replacing `Circle` as long as there is an actual perf gain and the presumed increase in draw calls from shader rebinding doesn't kill the perf gain. The tradeoffs sound fine to me.

2024-05-19 17:26 UTC, EVAST9919 commented
> I'd be much more okay with this replacing `Circle` as long as there is an actual perf gain and the presumed increase in draw calls from shader rebinding doesn't kill the perf gain. The other tradeoffs mentioned sound fine to me.

My current proposals:
* We probably can do some hackery like providing some specific flag somewhere and use the same texture shader with reroute to the new one and thus shader switch will be eliminated, but I can't think of any sane and good-looking solutions
* We can leave this as a side component (probably with a better name and xmldoc) amd use it only in specific cases, which is what I'm doing in provided screenshots
* Wait for SSBO implementation and see performance difference then

2024-05-19 19:29 UTC, smoogipoo requested changes

2024-05-19 19:29 UTC, smoogipoo commented on osu.Framework/Resources/Shaders/sh_FastCircle.fs
> +    o_Colour = getRoundedColor(vec4(vec3(1.0), alpha), vec2(0.0));
I'm not sure about the use of `v_TexRect` here.
- Have you tested textures at all? It looks like you're not actually sampling the texture.
- What about cropped textures? (`Texture.Crop()`)
- Does this work for rotated ellipses (textured and non-textured)? I assume so but it should be checked.

2024-05-19 20:15 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_FastCircle.fs
> +    o_Colour = getRoundedColor(vec4(vec3(1.0), alpha), vec2(0.0));
That's the thing: I'm abusing texture coordinates to pass screenspace size to the shader without uniforms (to compute antialiasing). This new circle isn't a sprite, so textures can't be set.
Regarding rotation: I'll add test showing it's working.

2024-05-19 20:30 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_FastCircle.fs
> +    o_Colour = getRoundedColor(vec4(vec3(1.0), alpha), vec2(0.0));
To clarify: I'm not trying replicate `CircularContainer`, I'm simplifying one particular usage of it, which is `CircularContainer` with a plane `Box` with no texture inside (`Circle` class) to avoid masking overhead in cases where multiple circes are being drawn consecutively (GPU side) and reducing total drawable count (CPU side)

2024-05-20 20:20 UTC, EVAST9919 commented on osu.Framework/Resources/Shaders/sh_FastCircle.fs
> +    o_Colour = getRoundedColor(vec4(vec3(1.0), alpha), vec2(0.0));
> That's the thing: I'm abusing texture coordinates to pass screenspace size to the shader without uniforms (to compute antialiasing).

As a side note I can apply hacks explored in this pr to the `Triangles` shader since it's being widely used in the game to eliminate uniform buffer. Will pr after checking whether performance gain is worth doing so.

2024-05-21 15:26 UTC, smoogipoo commented
My current position on this is I'm not sure where it fits in right now but I'm not _totally_ opposed to it.

2024-05-21 16:35 UTC, EVAST9919 commented
> I'd be much more okay with this replacing `Circle` as long as there is an actual perf gain and the presumed increase in draw calls from shader rebinding doesn't kill the perf gain. The other tradeoffs mentioned sound fine to me.
If this "fast" circle can't be applied universally then I'm not super interested in this imo.

So I've added the "worst case" performance test scene, in which drawables are alternating between circle and the box since I haven't noticed much difference in game when replacing circle with my implementation.
In this "worst case" scenario draw call count is the same and for my machine specifically my version runs faster. If you are fine with that then I can update this pr to replace original circle instead.
|`Circle`|`FastCircle`|
|---|---|
|![Circle](https://github.com/ppy/osu-framework/assets/22874522/dc4dee1c-e986-4f38-8563-290b4ca33895)|![Fast](https://github.com/ppy/osu-framework/assets/22874522/85e6781d-1d05-4998-b8a7-5cd87b32260e)|

2024-05-22 01:17 UTC, smoogipoo commented
The part that stops me from replacing `Circle` is the lack of a texture. It's the reason I questioned it in my review.

Slight tidbit: draw calls aren't equal. It's very likely your system will handle many draw calls much better than, say, a mobile GPU.

2024-05-22 02:15 UTC, peppy commented
a separate shader is going to interrupt batching, so we need to be sure that's what we want (probably not?)

2024-05-22 02:35 UTC, smoogipoo commented
What you have to understand is that it already interrupts batch as a result of masking. It all depends on whether the gains of SSBO can be realised.

2024-05-22 04:21 UTC, EVAST9919 commented
> The part that stops me from replacing `Circle` is the lack of a texture. It's the reason I questioned it in my review.

Which current `Circle` doesn't have either, so we are not losing anything.

> a separate shader is going to interrupt batching

There's a way to use the same shader, but I'm not sure if it's too ugly or some better approach can be implemented.

> I have a [working implementation](https://github.com/EVAST9919/osu-framework/compare/hacky-circle...EVAST9919:osu-framework:Circle-replace?expand=1#diff-432853374b221479db4515147fe4414d47b8b562813a52cb640f3cf533ae5256) which relies on unused `y` component of `BlendRange` being set to a unique value, however it's probably too ugly.

2024-05-26 06:52 UTC, EVAST9919 commented
Hmm, found discrepancy in behaviour.
While `Circle` changes it's shape on `Scale`, `FastCircle` is always preserving the pill shape and I'm not sure which one is more expected to the end user.
![Снимок экрана (528)](https://github.com/ppy/osu-framework/assets/22874522/dabf8d3f-3e36-45d5-bd8c-0f60e131d8b8)

2024-08-28 01:00 UTC, EVAST9919 commented
> Hmm, found discrepancy in behaviour

Okay, this one is easily fixable.
But also: while I can see how this component is too niche to include with the framework and potentially may cause performance issues upon misuse, I think it will be beneficial to at very least use it locally in osu! in the scenarios shown in OP, where we are sure that multiple circles will be drawn consecutively in a single draw call.
I have branches ready and can proceed further if necessary.

2024-08-28 03:45 UTC, smoogipoo commented
This PR's still in my emails fwiw, just very low priority while working on the many other tasks... I do eventually want to come back and re-read through the above comments + the capabilities offered by the existing `Circle`.

I may be okay blindly merging this in as `FastCircle` with documentation that it behaves slightly differently to `Circle` and is subject to change, for the specific scenarios that warrant it.

2024-08-30 07:58 UTC, smoogipoo approved these changes
I'm going to merge this one as it is for now to see where things go. Thanks!

2024-08-30 08:24 UTC, merged

2024-08-30 08:30 UTC, peppy commented
Hmm, was kinda hoping this would just replace `Circle`. I really don't want to have to go through code and decide when we want to use `FastCircle` vs `Circle`. Would prefer to just fix the few broken cases of `Circle` usage with the new implementation if that's possible.

2024-08-30 08:34 UTC, smoogipoo commented
My point is I don't know if this is the best that can be done. It still breaks the batch after all, and in a way that is much harder to prevent. 99% of cases would be fine with just using `Circle`, there are very specific use-cases that would _currently_ benefit majorly from this.

2024-08-30 08:36 UTC, peppy commented
Fair enough