Bring back SDL2 by default, lock SDL3 behind environment variable
ppy/osu-framework pull request #6292
Opened 2024-05-21 11:06 UTC by smoogipoo

Environment variable: `OSU_SDL3=1`.

The process of making this PR involved:
- Going through every file in https://github.com/ppy/osu-framework/pull/6234
- For every file that's changed, grab the original from https://github.com/ppy/osu-framework/tree/20d55fad04f78f36aafa3036c5540ed3bcd2ddc1

All of which culminates in a 99% 1:1 reimplementation of SDL2. Only supporting logic has been added.

Important changes/things to look out for:
- Namespace `osu.Framework.Platform.SDL` -> `osu.Framework.Platform.SDL3`.
  - `Platform.SDL2` added to hold SDL2 variant classes.
- `SDL3GameHost` -> `SDLGameHost`.
  - It now creates SDL2/SDL3 window variants depending on env variable.
- Inheritance hierarchy inverted: `SDL3GameHost : DesktopGameHost` -> `DesktopGameHost : SDL3GameHost`.
  - I wanted to avoid duplicating every `GameHost` implementation.
- `WindowMouseHandler` contains both SDL2 and SDL3 implementations.
  - Required to not break deserialisation of `input.json` thus losing settings.
- `SDL3ReadableKeyCombinationProvider` does not have an SDL2 variant. 
  - Since the keycodes look identical, I think it's fine to use SDL3's implementation.
- `using static SDL2.SDL` and `using static SDL.SDL3` are used to avoid namespace conflicts.
- Both iOS and Android use SDL3.

Testing:
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] iOS
- [ ] Android

2024-05-21 11:23 UTC, smoogipoo commented
Not sure about the `DesktopGameHost : SDLGameHost` inheritance change. Only just realised `DesktopGameHost` is used in a few other places, like tests. It _looks_ fine and passes the CI tests, but the prospect is a bit scary. Hard to do this otherwise...

2024-05-21 12:58 UTC, Susko3 requested changes
Tested to boot fine on Android, and Windows SDL2 & SDL3.

2024-05-21 12:58 UTC, Susko3 commented on osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
Readable key combinations don't work on SDL2. Can be easily fixed in an ugly way as the SDL3 and SDL2 enums are compatible.

```diff
diff --git a/osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs b/osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
index 126a73e56..9d8d81dab 100644
--- a/osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
+++ b/osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
@@ -11,9 +11,25 @@ namespace osu.Framework.Platform.SDL3
 {
     public class SDL3ReadableKeyCombinationProvider : ReadableKeyCombinationProvider
     {
+        private static SDL_Keycode getKeyFromScancode(SDL_Scancode scancode)
+        {
+            if (FrameworkEnvironment.UseSDL3)
+                return SDL_GetKeyFromScancode(scancode);
+
+            return (SDL_Keycode)global::SDL2.SDL.SDL_GetKeyFromScancode((global::SDL2.SDL.SDL_Scancode)scancode);
+        }
+
+        private static string? getKeyName(SDL_Keycode keycode)
+        {
+            if (FrameworkEnvironment.UseSDL3)
+                return SDL_GetKeyName(keycode);
+
+            return global::SDL2.SDL.SDL_GetKeyName((global::SDL2.SDL.SDL_Keycode)keycode);
+        }
+
         protected override string GetReadableKey(InputKey key)
         {
-            var keycode = SDL_GetKeyFromScancode(key.ToScancode());
+            var keycode = getKeyFromScancode(key.ToScancode());
 
             // early return if unknown. probably because key isn't a keyboard key, or doesn't map to an `SDL_Scancode`.
             if (keycode == SDL_Keycode.SDLK_UNKNOWN)
@@ -25,7 +41,7 @@ protected override string GetReadableKey(InputKey key)
             if (TryGetNameFromKeycode(keycode, out name))
                 return name;
 
-            name = SDL_GetKeyName(keycode);
+            name = getKeyName(keycode);
 
             // fall back if SDL couldn't find a name.
             if (string.IsNullOrEmpty(name))
```

2024-05-21 13:18 UTC, Susko3 commented on osu.Framework/Platform/Windows/WindowsMouseHandler.cs
Could be split into multiple files containing the same partial class. Makes removal easier and better separates the SDL2 and generic implementation. (Plus the future SDL3 impl for https://github.com/ppy/osu-framework/issues/6291.)

2024-05-21 13:27 UTC, Susko3 commented on osu.Framework/Platform/Windows/WindowsMouseHandler.cs
Ditto for `Native.Input`.

2024-05-21 13:37 UTC, smoogipoo commented on osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
Good catch. Although it's a bit messy, I think this is fine for now.

2024-05-21 13:38 UTC, smoogipoo commented on osu.Framework/Platform/Windows/WindowsMouseHandler.cs
I've tried to do this in https://github.com/ppy/osu-framework/pull/6292/commits/6f0702a1200d866470d1413f6efc3576313de7d1, I hope it's what you intended as I'm unsure whether the wndproc handler can truly be shared between the two so I assumed that it can.

2024-05-21 14:20 UTC, peppy commented on osu.Framework/Platform/Linux/SDL3LinuxWindow.cs
> +using static SDL.SDL3;
dunno how i feel about this

2024-05-21 14:21 UTC, Susko3 commented on osu.Framework/Platform/Windows/WindowsMouseHandler.cs
The wndproc handler doesn't work for raw input on windows. I meant to split out the code so that the SDL2 part can just be deleted. Best illustrated by the below diff. With it, the changes of `WindowsMouseHandler.cs` relative to `master` is the smallest. There's no SDL3 code yet so that partial is removed.

Expected final diff to master:

```diff
diff --git a/osu.Framework/Platform/Windows/WindowsMouseHandler.cs b/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
index b74535b78..4abe150a6 100644
--- a/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
+++ b/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
@@ -1,4 +1,4 @@
-﻿// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
+// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.

 using System.Runtime.Versioning;
@@ -12,16 +12,22 @@ namespace osu.Framework.Platform.Windows
     /// This is done to better handle quirks of some devices.
     /// </summary>
     [SupportedOSPlatform("windows")]
-    internal class WindowsMouseHandler : MouseHandler
+    internal partial class WindowsMouseHandler : MouseHandler
     {
-        private WindowsWindow window = null!;
+        private IWindowsWindow window = null!;
+
+        public override bool IsActive => Enabled.Value;

         public override bool Initialize(GameHost host)
         {
-            if (!(host.Window is WindowsWindow desktopWindow))
+            if (host.Window is not IWindowsWindow windowsWindow)
                 return false;

-            window = desktopWindow;
+            window = windowsWindow;
+
+            if (window is SDL2WindowsWindow)
+                initialiseSDL2(host);
+
             return base.Initialize(host);
         }

```

<details><summary>Diff</summary>
<p>

```diff
diff --git a/osu.Framework/Platform/Windows/WindowsMouseHandler.cs b/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
index ef2cdcaad..4abe150a6 100644
--- a/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
+++ b/osu.Framework/Platform/Windows/WindowsMouseHandler.cs
@@ -1,14 +1,8 @@
 // Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.
 
-using System;
-using System.Drawing;
 using System.Runtime.Versioning;
-using osu.Framework.Extensions.EnumExtensions;
 using osu.Framework.Input.Handlers.Mouse;
-using osu.Framework.Input.StateChanges;
-using osu.Framework.Platform.Windows.Native;
-using osu.Framework.Statistics;
 using osuTK;
 
 namespace osu.Framework.Platform.Windows
@@ -20,17 +14,7 @@ namespace osu.Framework.Platform.Windows
     [SupportedOSPlatform("windows")]
     internal partial class WindowsMouseHandler : MouseHandler
     {
-        private static readonly GlobalStatistic<ulong> statistic_relative_events = GlobalStatistics.Get<ulong>(StatisticGroupFor<WindowsMouseHandler>(), "Relative events");
-        private static readonly GlobalStatistic<ulong> statistic_absolute_events = GlobalStatistics.Get<ulong>(StatisticGroupFor<WindowsMouseHandler>(), "Absolute events");
-        private static readonly GlobalStatistic<ulong> statistic_dropped_touch_inputs = GlobalStatistics.Get<ulong>(StatisticGroupFor<WindowsMouseHandler>(), "Dropped native touch inputs");
-
-        private static readonly GlobalStatistic<ulong> statistic_inputs_with_extra_information =
-            GlobalStatistics.Get<ulong>(StatisticGroupFor<WindowsMouseHandler>(), "Native inputs with ExtraInformation");
-
-        private const int raw_input_coordinate_space = 65535;
-
         private IWindowsWindow window = null!;
-        private bool handlerBound;
 
         public override bool IsActive => Enabled.Value;
 
@@ -40,9 +24,9 @@ public override bool Initialize(GameHost host)
                 return false;
 
             window = windowsWindow;
-            handlerBound = window is SDL2WindowsWindow
-                ? bindHandlerSDL2(host)
-                : bindHandlerSDL3(host);
+
+            if (window is SDL2WindowsWindow)
+                initialiseSDL2(host);
 
             return base.Initialize(host);
         }
@@ -52,108 +36,5 @@ public override void FeedbackMousePositionChange(Vector2 position, bool isSelfFe
             window.LastMousePosition = position;
             base.FeedbackMousePositionChange(position, isSelfFeedback);
         }
-
-        protected override void HandleMouseMoveRelative(Vector2 delta)
-        {
-            if (handlerBound)
-            {
-                // When bound, relative movement is reported via the WndProc handler below.
-                return;
-            }
-
-            base.HandleMouseMoveRelative(delta);
-        }
-
-        private unsafe IntPtr onWndProcSDL2(IntPtr userData, IntPtr hWnd, uint message, ulong wParam, long lParam)
-        {
-            if (!Enabled.Value)
-                return IntPtr.Zero;
-
-            if (message != Native.Input.WM_INPUT)
-                return IntPtr.Zero;
-
-            if (Native.Input.IsTouchEvent(Native.Input.GetMessageExtraInfo()))
-            {
-                // sometimes GetMessageExtraInfo returns 0, so additionally, mouse.ExtraInformation is checked below.
-                // touch events are handled by TouchHandler
-                statistic_dropped_touch_inputs.Value++;
-                return IntPtr.Zero;
-            }
-
-            int payloadSize = sizeof(RawInputData);
-
-            Native.Input.GetRawInputData((IntPtr)lParam, RawInputCommand.Input, out var data, ref payloadSize, sizeof(RawInputHeader));
-
-            if (data.Header.Type != RawInputType.Mouse)
-                return IntPtr.Zero;
-
-            var mouse = data.Mouse;
-
-            // `ExtraInformation` doesn't have the MI_WP_SIGNATURE set, so we have to rely solely on the touch flag.
-            if (Native.Input.HasTouchFlag(mouse.ExtraInformation))
-            {
-                statistic_dropped_touch_inputs.Value++;
-                return IntPtr.Zero;
-            }
-
-            //TODO: this isn't correct.
-            if (mouse.ExtraInformation > 0)
-            {
-                statistic_inputs_with_extra_information.Value++;
-
-                // i'm not sure if there is a valid case where we need to handle packets with this present
-                // but the osu!tablet fires noise events with non-zero values, which we want to ignore.
-                // return IntPtr.Zero;
-            }
-
-            var position = new Vector2(mouse.LastX, mouse.LastY);
-            float sensitivity = (float)Sensitivity.Value;
-
-            if (mouse.Flags.HasFlagFast(RawMouseFlags.MoveAbsolute))
-            {
-                var screenRect = mouse.Flags.HasFlagFast(RawMouseFlags.VirtualDesktop) ? Native.Input.VirtualScreenRect : new Rectangle(window.Position, window.ClientSize);
-
-                Vector2 screenSize = new Vector2(screenRect.Width, screenRect.Height);
-
-                if (mouse.LastX == 0 && mouse.LastY == 0)
-                {
-                    // not sure if this is the case for all tablets, but on osu!tablet these can appear and are noise.
-                    return IntPtr.Zero;
-                }
-
-                // i am not sure what this 64 flag is, but it's set on the osu!tablet at very least.
-                // using it here as a method of determining where the coordinate space is incorrect.
-                if (((int)mouse.Flags & 64) == 0)
-                {
-                    position /= raw_input_coordinate_space;
-                    position *= screenSize;
-                }
-
-                if (Sensitivity.Value != 1)
-                {
-                    // apply absolute sensitivity adjustment from the centre of the screen area.
-                    Vector2 halfScreenSize = (screenSize / 2);
-
-                    position -= halfScreenSize;
-                    position *= (float)Sensitiv [...]

2024-05-22 06:18 UTC, peppy commented
I think this looks OK.

@smoogipoo as discussed, can we add an SDL2 / SDL3 string here?

![2024-05-22 14 18 19@2x](https://github.com/ppy/osu-framework/assets/191335/646cfbb6-a836-47dc-8737-b90ae456c7c7)

2024-05-22 06:39 UTC, smoogipoo commented
![image](https://github.com/ppy/osu-framework/assets/1329837/be88e0bf-da31-4177-9f95-7d0ded694d2b)

How does this look? Wanted to keep the line somewhat short...

2024-05-22 07:50 UTC, peppy commented
@bdach not sure if you want to give this a quick run on linux and make sure all is well?

as for iOS i don't really have the energy to test it but i'm sure we'll find out from @frenzibyte if it's failing at some point before next release, worst case.

2024-05-22 08:03 UTC, smoogipoo commented
For linux I've tested (that it runs and supports window modes):
```
SDL_VIDEODRIVER=wayland
SDL_VIDEODRIVER=x11
OSU_SDL3=1;SDL_VIDEO_DRIVER=wayland
OSU_SDL3=1;SDL_VIDEO_DRIVER=x11
```

2024-05-22 08:11 UTC, bdach commented
Linux boots here. Appears to not be more broken than already known on all of the configurations I tested on my box (x11/wayland, sdl2/3).

Not reading source because I presume enough eyes have looked at that already.

2024-05-22 08:12 UTC, bdach approved these changes

2024-05-22 08:12 UTC, merged