Make time move along at the same rate in all threads during headless execution
ppy/osu-framework pull request #6327
Opened 2024-07-10 09:26 UTC by smoogipoo

RFC. This should fix the osu!-side macOS test failures when running under MultiThread execution mode.

## Reproduction:

Local osu!-framework checkout with:
```diff
diff --git a/osu.Framework/Threading/AudioThread.cs b/osu.Framework/Threading/AudioThread.cs
index 171f43280..4debaad82 100644
--- a/osu.Framework/Threading/AudioThread.cs
+++ b/osu.Framework/Threading/AudioThread.cs
@@ -65,6 +65,8 @@ private void onNewFrame()
                     m.Update();
                 }
             }
+
+            System.Threading.Thread.Sleep(200);
         }

         internal void RegisterManager(AudioManager manager)
```

Run test `TestSceneCatchModNoScope.TestVisibleDuringBreak`.

## Investigation

As far as I could deduce, this is caused by the audio thread running much slower than the update thread.

`FastClock` increments `CurrentTime` by 33ms every time it is referenced. In headless execution, this happens once per frame, as mandated by the `FramedClock` wrapping it.

https://github.com/ppy/osu-framework/blob/4f516283dbe9e8b079e1b26783624ecab8a30546/osu.Framework/Platform/HeadlessGameHost.cs#L71-L92

osu! tests use the test scene's clock (which is the framed `FastClock` from above) as the reference clock for the beatmap, allowing gameplay tests to execute at non-realtime speeds:

https://github.com/ppy/osu/blob/95783bd6c2543f15d71f89c6a3469a0d0fcfaba6/osu.Game/Tests/Visual/OsuTestScene.cs#L321-L322

The `TrackVirtualManual` referencing that clock is only updated from the audio thread.

https://github.com/ppy/osu/blob/95783bd6c2543f15d71f89c6a3469a0d0fcfaba6/osu.Game/Tests/Visual/OsuTestScene.cs#L497-L518

So, the failure case seems to be as follows:
- The update thread is running much faster than the audio thread (could be CI runner resource exhaustion/etc - these failures started coming up after the runner was moved to ARM64). I've observed the imbalance up to 2 orders of magnitude.
- This results in the `FastClock` updating very frequently, but the `TrackVirtualManual` updating very _in_frequently.
- When the `TrackVirtualManual` finally updates, it skips forward several seconds in execution, which gameplay also follows.
- Because of the skip, certain test steps aren't executed fast enough (only executed every 200ms) while their expected gameplay state has been skipped.

Using `TestVisibleDuringBreak` as an example, here's a visual simulation. Only the audio thread is being paused here (for 4s):

https://github.com/ppy/osu-framework/assets/1329837/15d2f41e-e8a3-451b-a4e4-a15f2ab4140f

This also makes it intuitive why single-threaded execution is unaffected.

## Fix

I would say that the fix here is a little bit of a workaround. We're preventing the threads from getting too far out-of-sync time-wise without limiting their run rate, matching a little bit closer to reality.

2024-07-10 10:17 UTC, bdach commented
Test fails here look concerning. Framework for one has been 99% green on tests thus far, so I am spooked. Could be a red herring, though.

2024-07-10 11:11 UTC, smoogipoo commented
Yeah, your spook is shared.

2024-07-11 08:11 UTC, peppy requested changes

2024-07-11 08:11 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
`Min` here doesn't sound correct. It means if threads are running at different rates, it will only be checking the slowest (least-run) thread. You'll probably want to be storing an index per thread.

```diff
diff --git a/osu.Framework/Platform/HeadlessGameHost.cs b/osu.Framework/Platform/HeadlessGameHost.cs
index efaf40113..645dbb420 100644
--- a/osu.Framework/Platform/HeadlessGameHost.cs
+++ b/osu.Framework/Platform/HeadlessGameHost.cs
@@ -79,7 +79,7 @@ protected override void SetupForRun()
 
             if (!realtime)
             {
-                customClock = new FramedClock(new FastClock(CLOCK_RATE, new[] { AudioThread, UpdateThread, DrawThread, InputThread }));
+                customClock = new FramedClock(new FastClock(CLOCK_RATE, Threads.ToArray()));
 
                 // time is incremented per frame, rather than based on the real-world time.
                 // therefore our goal is to run frames as fast as possible.
@@ -109,11 +109,13 @@ protected override void UpdateFrame()
         private class FastClock : IClock
         {
             private readonly double increment;
+
             private readonly GameThread[] gameThreads;
+            private readonly ulong[] gameThreadLastFrames;
+
             private readonly Stopwatch stopwatch = new Stopwatch();
 
             private double time;
-            private ulong? lastFrameIndex;
 
             /// <summary>
             /// A clock which increments each time <see cref="CurrentTime"/> is requested.
@@ -121,10 +123,11 @@ private class FastClock : IClock
             /// </summary>
             /// <param name="increment">Milliseconds we should increment the clock by each time the time is requested.</param>
             /// <param name="gameThreads">The game threads.</param>
-            public FastClock(double increment, GameThread?[] gameThreads)
+            public FastClock(double increment, GameThread[] gameThreads)
             {
                 this.increment = increment;
-                this.gameThreads = gameThreads.Where(t => t != null).ToArray()!;
+                this.gameThreads = gameThreads;
+                gameThreadLastFrames = new ulong[gameThreads.Length];
             }
 
             public double CurrentTime
@@ -134,14 +137,20 @@ public double CurrentTime
                     double realElapsedTime = stopwatch.Elapsed.TotalMilliseconds;
                     stopwatch.Restart();
 
-                    ulong frameIndex = gameThreads.Min(t => t.FrameIndex);
+                    for (int i = 0; i < gameThreads.Length; i++)
+                    {
+                        ulong frameIndex = gameThreads[i].FrameIndex;
+
+                        // Don't increment the current time until all threads have advanced at least one frame.
+                        if (frameIndex == gameThreadLastFrames[i])
+                            return time += realElapsedTime;
+                    }
 
-                    // Don't increment the current time until all threads have advanced at least one frame.
-                    if (frameIndex == lastFrameIndex)
-                        return time += realElapsedTime;
+                    // update late thread indices only after we ensure that all threads have progressed.
+                    for (int i = 0; i < gameThreads.Length; i++)
+                        gameThreadLastFrames[i] = gameThreads[i].FrameIndex;
 
                     time += increment;
-                    lastFrameIndex = frameIndex;
 
                     return time;
                 }

```

2024-07-11 08:11 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                customClock = new FramedClock(new FastClock(CLOCK_RATE, new[] { AudioThread, UpdateThread, DrawThread, InputThread }));
```diff
diff --git a/osu.Framework/Platform/HeadlessGameHost.cs b/osu.Framework/Platform/HeadlessGameHost.cs
index efaf40113..b71f10d4b 100644
--- a/osu.Framework/Platform/HeadlessGameHost.cs
+++ b/osu.Framework/Platform/HeadlessGameHost.cs
@@ -79,7 +79,7 @@ protected override void SetupForRun()
 
             if (!realtime)
             {
-                customClock = new FramedClock(new FastClock(CLOCK_RATE, new[] { AudioThread, UpdateThread, DrawThread, InputThread }));
+                customClock = new FramedClock(new FastClock(CLOCK_RATE, Threads.ToArray()));
 
                 // time is incremented per frame, rather than based on the real-world time.
                 // therefore our goal is to run frames as fast as possible.
@@ -121,10 +121,10 @@ private class FastClock : IClock
             /// </summary>
             /// <param name="increment">Milliseconds we should increment the clock by each time the time is requested.</param>
             /// <param name="gameThreads">The game threads.</param>
-            public FastClock(double increment, GameThread?[] gameThreads)
+            public FastClock(double increment, GameThread[] gameThreads)
             {
                 this.increment = increment;
-                this.gameThreads = gameThreads.Where(t => t != null).ToArray()!;
+                this.gameThreads = gameThreads;
             }
 
             public double CurrentTime

```

2024-07-11 08:59 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
I'm very confused as to what's going on here in general?

There's a comment that says

```csharp
// Don't increment the current time until all threads have advanced at least one frame.
```

followed by

```csharp
if (frameIndex == lastFrameIndex)
    return time += realElapsedTime;
```

...isn't that the exact _opposite_ of the comment? If the last frame index is the same as the current index, then why is time... incremented?

Not sure how to review the rest of this even given that this appears to be the core fix but I don't understand what is happening here.

2024-07-11 09:15 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
The idea is to use real time in the case that threads have not run. In the *normal* (`master`) case, the `FastClock` would increment time by a much larger increment, which is causing the drift that we are trying to fix here.

The comment should probably be reworded as I agree it doesn't really make sense.

2024-07-11 09:43 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
Okay I _think_ I get the vague idea now - that said, the `.Min()` makes _more_ sense to me than your patch. The `.Min()` - in principle - should stop all threads except the slowest one, but I'm not sure of the purpose of the per-thread indices? Yes it might ensure that the each thread advances at least once, but isn't it allowing the threads to arbitrarily desync too?

Although I'm still not sure if _any_ of these are correct? Like, if I'm understanding correctly, the idea is that if a thread is rushing, then it should keep receiving the same `CurrentTime` as it has been in the past, _until_ the other threads have caught up.

But here's my primary gripe: _how do we know who's getting `CurrentTime` here_? Why is this just indiscriminately checking `.Min()` or per-thread indices even, _without knowing which thread is going to be throttled or advanced here_?

2024-07-11 09:49 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
> that said, the .Min() makes more sense to me than your patch. The .Min() - in principle - should stop all threads except the slowest one

This only sounds correct if you assume that all threads are running at the same rates (is that somehow the case? does running under tests somehow change that from normal execution where input is running several times faster?).

> But here's my primary gripe: how do we know who's getting CurrentTime here? Why is this just indiscriminately checking .Min() or per-thread indices even, without knowing which thread is going to be throttled or advanced here?

The idea is to not know/care as far as I'm concerned. It shouldn't really matter.

---

If this change isn't easy to swallow then some proposals are

- Removing `FastClock` and either having tests run 30 times slower
- Implementing similar logic in `ThreadRunner` which has similar assurances (but it's basically the same at the end of the day)
- Disabling multithread tests

2024-07-11 09:54 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
> This only sounds correct if you assume that all threads are running at the same rates

If they aren't then why were they all getting the same constant 33ms increment on every query of `CurrentTime` on `master`? Is some of this somehow abstracted/muddled by the framed clock machinery?

> The idea is to not know/care as far as I'm concerned. It shouldn't really matter.

That makes completely no sense to me.

I don't know if it's me being an idiot but I have completely no mental model of what is happening here. Given you're both seemingly more or less on board with this it's probably fine to proceed but I basically still can't tell what is going on.

2024-07-11 10:19 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
Here's a better patch that may help with understanding:

```diff
diff --git a/osu.Framework/Platform/HeadlessGameHost.cs b/osu.Framework/Platform/HeadlessGameHost.cs
index efaf40113..ab379de38 100644
--- a/osu.Framework/Platform/HeadlessGameHost.cs
+++ b/osu.Framework/Platform/HeadlessGameHost.cs
@@ -79,7 +79,7 @@ protected override void SetupForRun()
 
             if (!realtime)
             {
-                customClock = new FramedClock(new FastClock(CLOCK_RATE, new[] { AudioThread, UpdateThread, DrawThread, InputThread }));
+                customClock = new FramedClock(new FastClock(CLOCK_RATE, Threads.ToArray()));
 
                 // time is incremented per frame, rather than based on the real-world time.
                 // therefore our goal is to run frames as fast as possible.
@@ -109,11 +109,13 @@ protected override void UpdateFrame()
         private class FastClock : IClock
         {
             private readonly double increment;
+
             private readonly GameThread[] gameThreads;
+            private readonly ulong[] gameThreadLastFrames;
+
             private readonly Stopwatch stopwatch = new Stopwatch();
 
             private double time;
-            private ulong? lastFrameIndex;
 
             /// <summary>
             /// A clock which increments each time <see cref="CurrentTime"/> is requested.
@@ -121,10 +123,11 @@ private class FastClock : IClock
             /// </summary>
             /// <param name="increment">Milliseconds we should increment the clock by each time the time is requested.</param>
             /// <param name="gameThreads">The game threads.</param>
-            public FastClock(double increment, GameThread?[] gameThreads)
+            public FastClock(double increment, GameThread[] gameThreads)
             {
                 this.increment = increment;
-                this.gameThreads = gameThreads.Where(t => t != null).ToArray()!;
+                this.gameThreads = gameThreads;
+                gameThreadLastFrames = new ulong[gameThreads.Length];
             }
 
             public double CurrentTime
@@ -134,16 +137,31 @@ public double CurrentTime
                     double realElapsedTime = stopwatch.Elapsed.TotalMilliseconds;
                     stopwatch.Restart();
 
-                    ulong frameIndex = gameThreads.Min(t => t.FrameIndex);
+                    if (allThreadRanAtLeastOneFrameSinceLastCall)
+                    {
+                        for (int i = 0; i < gameThreads.Length; i++)
+                            gameThreadLastFrames[i] = gameThreads[i].FrameIndex;
 
-                    // Don't increment the current time until all threads have advanced at least one frame.
-                    if (frameIndex == lastFrameIndex)
-                        return time += realElapsedTime;
+                        // Increment time at the expedited rate.
+                        return time += increment;
+                    }
+
+                    // Fall back to real time to ensure we don't piss off random tests that expect threads to be running.
+                    return time += realElapsedTime;
+                }
+            }
 
-                    time += increment;
-                    lastFrameIndex = frameIndex;
+            public bool allThreadRanAtLeastOneFrameSinceLastCall
+            {
+                get
+                {
+                    for (int i = 0; i < gameThreads.Length; i++)
+                    {
+                        if (gameThreads[i].FrameIndex == gameThreadLastFrames[i])
+                            return false;
+                    }
 
-                    return time;
+                    return true;
                 }
             }
 

```

2024-07-11 10:33 UTC, frenzibyte commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
Comparing between the original fix and the patch directly above me, I find the patch easier to comprehend and explicit in behaviour (it sounds safer to me not to progress forward until all other threads have ran a frame already).

2024-07-11 10:34 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
It helps insofar as it spells out the intention better (which I already was tangentially aware). I'm still not entirely sure how that ties into all other thread clocks, them running at the same or different rates etc but this at least _does_ appear to guarantee forward progress on all of them, just not necessarily by the same amount.

Dunno. Seems like a better option than any of the others presented but I do still want to see @smoogipoo's response to the patch (since it's still a material change from the PR as it was opened).

2024-07-12 06:02 UTC, smoogipoo commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
It sounds like the confusion here is because of the `GameThread` clock, which appears to have been referenced above in the form of "all other thread clocks". This has nothing to do with the `GameThread` clock, in-fact that clock is still running real-time (which could be an issue on its own). Here's a demonstration:

```csharp
public partial class TestSceneScratch : FrameworkTestScene
{
    [Resolved]
    private GameHost host { get; set; } = null!;

    /// <summary>
    /// Schedule to the update thread directly (runs realtime).
    /// </summary>
    [Test]
    public void TestUpdateThread()
    {
        bool complete = false;

        AddStep("schedule to update thread", () =>
        {
            host.UpdateThread.Scheduler.AddDelayed(() => complete = true, 2000);
        });

        AddUntilStep("wait for completion", () => complete);
    }

    /// <summary>
    /// Schedule locally (runs on the FastClock).
    /// </summary>
    [Test]
    public void TestLocal()
    {
        bool complete = false;

        AddStep("schedule to update thread", () =>
        {
            Scheduler.AddDelayed(() => complete = true, 2000);
        });

        AddUntilStep("wait for completion", () => complete);
    }
}
```

A `Track`, likewise, doesn't _really_ have a clock. It can have a real-time clock (`TrackVirtual`), an external real-time clock (`TrackBass`), or a _non_-realtime clock referencing _some other clock_. In osu!, `TrackVirtualManual` does this by referencing the `FastClock` (of the update thread).  
At this point it's important to understand that the "clock" of `Track` is _only_ updated on the audio thread, when `UpdateState()` gets run recursively on audio components.

So let's say that the update thread is running several orders of magnitudes faster than the update thread. In this case, the updates for each thread may see timings like this:
```
< Update > Frame 1   : 0
<  Audio > Frame 1   : 0
< Update > Frame 2   : 33
< Update > Frame 3   : 66
            ...
< Update > Frame 101 : 3300
<  Audio > Frame 2   : 3300
```

What this PR does is make it so that the _time_ doesn't increment until all threads have processed at least once. The ideal scenario is:
```
< Update > Frame 1   : 0
<  Audio > Frame 1   : 0
< Update > Frame 2   : 33
< Update > Frame 3   : 33
            ...
< Update > Frame 101 : 33
<  Audio > Frame 2   : 33
< Update > Frame 102 : 66
            ...
```
However, this doesn't look to work (see: https://github.com/ppy/osu-framework/actions/runs/9871663325/job/27260056579) because it results in NaN values in some components. So instead I've made it use an arbitrary non-zero elapsed time via a real-time stopwatch. This could just as well have been a small value like 0.0001.

---

The `.Min()` vs per-frame index thing doesn't matter at the end of the day because we really only have two threads - update and audio. Draw doesn't exist in headless execution, and input doesn't have any time-based components (though I guess it could in the future).

I'll change it to use per-index threading, but I am not keen on the complexity added by the above "better patch".

---

> Removing FastClock and either having tests run 30 times slower

No.

> Implementing similar logic in ThreadRunner which has similar assurances (but it's basically the same at the end of the day)

Between review and IRL, you've mentioned this several times now, but `ThreadRunner` has a distinctly different purpose. It runs all threads synchronously. Single-threaded tests were added _because_ we noticed differences between MT and ST modes in the real-world and decided it's best to have the threads NOT run in-line with one another as a test scenario.

> Disabling multithread tests

See above.

---

There are a few things I'm considering:
1. Do we want to have `UpdateThread.Clock` separate from the scene's `Drawable.Clock` in headless execution?
2. Related to above, what if we were to give AudioThread a `FastClock` of its own? It's not quite the same as the current scenario - the two threads will run at different rates but each one will only experience 33ms elapses in its own frames.
3. Is 0 elapsed time worth pursuing - figuring out what is resulting in NaN values instead?

2024-07-12 06:23 UTC, smoogipoo commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
The `ThreadRunner` idea could be something like this:
```
public class HeadlessThreadRunner : ThreadRunner
{
    public HeadlessThreadRunner(InputThread mainThread)
        : base(mainThread)
    {
    }

    public override void RunMainLoop()
    {
        ExecutionMode = ExecutionMode.SingleThread;

        for (int i = 0; i < Threads.Count; i++)
        {
            int from = RNG.Next(Threads.Count);
            int to;

            do
            {
                to = RNG.Next(Threads.Count);
            } while (to == from);

            (Threads[from], Threads[to]) = (Threads[to], Threads[from]);
        }

        base.RunMainLoop();
    }
}
```
Basically generating a new combination of threads every time. Though this makes `Threads` an `IList<>` instead of an `IReadOnlyCollection<>`. The implementation of this class w.r.t exposure is kinda weird in general.

2024-07-12 08:21 UTC, bdach commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
Now that I actually learn how tests actually run on CI I'm impressed that they pass as often as they do.....

I would just honestly go with this change (whether the unchanged one, or some variant of above patch) for now and see where we end up. That goes for the "update clock is not scene clock" concern and the zero elapsed time concern.

> The `ThreadRunner` idea could be something like this:

Should probably ensure that `from != to` with that patch. Theoretical chance of that is 12.5% in a single loop which is not insignificant.

2024-07-13 05:39 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                        return time += realElapsedTime;
To keep things moving I've applied a slightly modified version of my last patch in this thread.

2024-07-13 05:39 UTC, peppy approved these changes

2024-07-14 05:01 UTC, peppy commented on osu.Framework/Platform/HeadlessGameHost.cs
> +                customClock = new FramedClock(new FastClock(CLOCK_RATE, new[] { AudioThread, UpdateThread, DrawThread, InputThread }));
Applied in 8a9f261.

2024-07-16 07:28 UTC, smoogipoo commented
The changes look fine to me

2024-07-16 08:06 UTC, merged