Allow `TextBox` to specify type of text being input
ppy/osu-framework pull request #6408
Opened 2024-11-04 09:27 UTC by frenzibyte

Also has the bonus feature of allowing password managers (e.g. 1Password) to be integrated with the game, by specifying the text input type as `Username`/`Password` in the textboxes. Unfortunately it's still quite broken in SDL but should be fixable (see https://github.com/libsdl-org/SDL/pull/11406#discussion_r1827411417).

Since text input types are now identifiable with the new `TextInputType` field, I've applied a refactor on the `TextBox` classes to respect the type at a `TextBox` level w.r.t. certain functionalities such as clipboard exporting, key event logging, character display, etc. This includes removing `BasicPasswordTextBox` entirely as its behaviour can be achieved by simply:
```csharp
new BasicTextBox
{
    InputProperties = new TextInputProperties(TextInputType.Password, allowIme: false)
}
```

I've gone for this refactor as it didn't sit well for me how these implementations still exist while there is now a new field specifying the type of text input.

2024-11-04 09:30 UTC, bdach commented
Compilation failures here

2024-11-04 09:34 UTC, frenzibyte commented
Noticed, fixed.

2024-11-05 06:04 UTC, smoogipoo requested changes
I think this looks okay.

I'm not sure about IME being a property you have to set as opposed to being optional defaulting to `true`, or maybe even `null` and a sane default chosen per type (IME doesn't make sense for numbers/passwords, but maybe this is blocked at and SDL level?).

2024-11-08 11:01 UTC, bdach requested changes

2024-11-08 11:01 UTC, bdach commented on osu.Framework/Input/SDLWindowTextInput.cs
> +            window.StartTextInput(properties);
This doesn't appear to work correctly on android. When switching from a normal textbox to a password textbox immediately, IME remains available. Conversely, when switching from a password textbox to a normal textbox immediately, IME remains unavailable.

https://github.com/user-attachments/assets/d22b53d1-7e5d-440c-a604-571a2ab69779

I wonder what this looks like on iOS. (I own an iOS device now, but no mac, so I still can't check myself.)

Whether this is an SDL bug, or ours, is up for debate I guess. I can say that the naive solution, i.e.

```diff
diff --git a/osu.Framework/Input/SDLWindowTextInput.cs b/osu.Framework/Input/SDLWindowTextInput.cs
index 79fa1d848..c67bf7f77 100644
--- a/osu.Framework/Input/SDLWindowTextInput.cs
+++ b/osu.Framework/Input/SDLWindowTextInput.cs
@@ -10,6 +10,8 @@ internal class SDLWindowTextInput : TextInputSource
     {
         private readonly ISDLWindow window;
 
+        private TextInputProperties? startedInputProperties;
+
         public SDLWindowTextInput(ISDLWindow window)
         {
             this.window = window;
@@ -42,10 +44,14 @@ protected override void ActivateTextInput(TextInputProperties properties)
             window.TextInput += handleTextInput;
             window.TextEditing += handleTextEditing;
             window.StartTextInput(properties);
+            startedInputProperties = properties;
         }
 
         protected override void EnsureTextInputActivated(TextInputProperties properties)
         {
+            if (startedInputProperties != null && startedInputProperties != properties)
+                window.StopTextInput();
+
             window.StartTextInput(properties);
         }
 
@@ -54,6 +60,7 @@ protected override void DeactivateTextInput()
             window.TextInput -= handleTextInput;
             window.TextEditing -= handleTextEditing;
             window.StopTextInput();
+            startedInputProperties = null;
         }
 
         public override void SetImeRectangle(RectangleF rectangle)

```

does not appear to help.

2024-11-09 09:16 UTC, frenzibyte commented on osu.Framework/Input/InputManager.cs
> +                        : e.ToString();
Seems like it did regress since key input used to be logged in this location until it was moved to `KeyEventManager`. I'll correct it in this PR.

2024-11-09 09:56 UTC, frenzibyte commented on osu.Framework/Input/SDLWindowTextInput.cs
> +            window.StartTextInput(properties);
I'm seeing roughly the same issue on iOS, I will have to look into https://github.com/libsdl-org/SDL/pull/11406#discussion_r1827286984 again first to tell whether this is an issue on SDL's side or ours. Not sure about Android though, someone else will have to investigate this (https://github.com/libsdl-org/SDL/pull/11406#discussion_r1827335866 may be relevant).

2024-11-09 09:57 UTC, frenzibyte commented on osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
> +            ScheduleCommand(() => Imm.SetImeAllowed(WindowHandle, properties.AllowIme));
Made `AllowIme` default and added an auxiliary check to disable IME where not supported.

2024-11-11 12:29 UTC, bdach commented on osu.Framework/Input/SDLWindowTextInput.cs
> +            window.StartTextInput(properties);
...so I guess at this point it's either up to me to fix android, or to accept it's broken over there?

~~i feel like my android devices might mysteriously stop working soon.~~

2024-11-11 16:00 UTC, Susko3 requested changes

2024-11-11 16:00 UTC, Susko3 commented on osu.Framework/Input/TextInputType.cs
> +        public static bool SupportsIme(this TextInputType type) => type == TextInputType.Name || type == TextInputType.Text;
`SupportsIme` doesn't match the style of `IsPassword` and `IsNumerical`. Change to a `switch` or change the others to boolean logic.

2024-11-11 16:00 UTC, Susko3 commented on osu.Framework/Platform/SDL3/SDL3Window_Input.cs
`ResetIme()` still calls `SDL_StartTextInput()` without properties.

2024-11-11 16:13 UTC, Susko3 commented on osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
> +            ScheduleCommand(() => Imm.SetImeAllowed(WindowHandle, properties.AllowIme));
@bdach When I first tested the SDL2 implementation of text editing events, it wasn't working as expected on windows. Doing a quick test of the SDL3 impl, it seems to work just fine. I'll do a bit more testing and make a PR changing `SDL3WindowsWindow` to use the SDL impl on windows.

2024-11-11 16:19 UTC, frenzibyte commented on osu.Framework/Input/TextInputType.cs
> +        public static bool SupportsIme(this TextInputType type) => type == TextInputType.Name || type == TextInputType.Text;
I'm not sure that matters.

2024-11-11 17:17 UTC, Susko3 commented on osu.Framework/Input/SDLWindowTextInput.cs
> +            window.StartTextInput(properties);
I can try to take a stab at fixing this in SDL. On first glance, it doesn't seem to be an android-specific issue as [SDL will ignore requests to show the keyboard if it's already active](https://github.com/libsdl-org/SDL/blob/fc12cc6dfd859a4e01376162a58f12208e539ac6/src/video/SDL_video.c#L5300C40-L5300C72).

2024-11-11 18:40 UTC, Susko3 commented on osu.Framework/Input/SDLWindowTextInput.cs
> +            window.StartTextInput(properties);
Created a PR, but I'm not expecting it to go in soon.

- https://github.com/libsdl-org/SDL/pull/11448

2024-12-24 11:49 UTC, frenzibyte commented
@peppy fwiw with this PR in addition to https://github.com/libsdl-org/SDL/pull/11699, users will be able to auto-fill their account passwords from a password manager with ease.

2025-01-10 06:29 UTC, smoogipoo approved these changes
Code-wise this looks fine to me and I've done a basic test (macOS).

2025-01-10 08:40 UTC, bdach approved these changes
see above i guess

2025-01-11 02:15 UTC, Susko3 approved these changes
Let's get this in. Android is bugged, but it's not so bad. The user may end up in the wrong mode, but typing always works. And if they need an IME, they'll probably figure out that closing and opening the keyboard works around the issue. It's the classic turn it off and on again.

2025-01-14 05:35 UTC, peppy approved these changes

2025-01-14 05:35 UTC, merged