Set up-to-date .NET code quality analyzers
ppy/osu-framework pull request #6434
Opened 2024-11-27 16:12 UTC by huoyaoyuan

This is an overhaul from previous FxCop (#3007). Now the rules are shipped in-box with .NET SDK, with concept of mode/level, allowing to set aggressiveness of categories instead of enumerating them.

The analysis rules are grouped by aggressiveness of `None < Default < Minimum < Recommended < All`. I avoided `None` and `All` because they would impact critical/too flaky ones, and didn't involve rules with too much noise/high design impact.

The performance concern for inner loop should be low, since many analyzers are already running at `suggestion` level. If there's evidence of performance impact, we can set `EnableNETAnalyzers` to `false` in projects and pass `true` in CI.

2024-11-27 16:17 UTC, huoyaoyuan commented on osu.Framework.SourceGeneration.Tests/GeneratorTestHelper.cs
> -            if (compilationDiagnostics.Any() || generatorDiagnostics.Any())
I see this rule as controversial. As a non-English speaker, `Any()` or `!Any()` is less readable for me comparing to length tests. I separated all changes with this rule in one commit, in case if you'd like to revert it.

2024-11-27 16:17 UTC, huoyaoyuan commented on CodeAnalysis/BannedSymbols.txt
> -M:System.String.ToUpper();string.ToUpper() changes behaviour depending on CultureInfo.CurrentCulture. Use string.ToUpperInvariant() instead. If wanting culture-sensitive behaviour, explicitly provide
These are covered in CA1304.

2024-11-27 16:17 UTC, huoyaoyuan commented on Directory.Build.props
> +    <AnalysisMode>Default</AnalysisMode>
Actually I tested `Recommended` as baseline for every category, and revert to `Default` if there's too much noise or controversary.

2024-11-27 17:04 UTC, turbedi commented on osu.Framework/Graphics/Containers/SearchContainer.cs
>              string[] terms = (searchTerm ?? string.Empty).Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
To avoid the unnecessary allocation. Not related to this PR, but noticed it while reading through it. Wanna include it in this PR while you are at it?
I'm surprised that there is no analyzer for this 😅

```suggestion
            string[] terms = (searchTerm ?? string.Empty).Split(' ', StringSplitOptions.RemoveEmptyEntries);
```

2024-11-27 17:26 UTC, huoyaoyuan commented on osu.Framework/Graphics/Containers/SearchContainer.cs
>              string[] terms = (searchTerm ?? string.Empty).Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
Yeah surprisingly, there isn't a single rule for switching from collection parameter to singleton. CA1861 is about using collections more efficiently.
I'd like to avoid including unrelated changes for this PR, because the discovered instance numbers can be non-trivial.

2024-11-27 19:37 UTC, Susko3 requested changes
More care needs to be given when changing `ContainsKey()` & item access to `TryGetValue()`. I assume you've just run an automatic fixer?

Due the to currently chosen code structure and variable names, it's harder to understand than the original code.

2024-11-27 19:37 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TabControl.cs
> +                if (!tabVisibility.TryGetValue(child, out bool value) || value != isVisible)
Please don't name it `value`. Maybe `currentVisibility`?

2024-11-27 19:37 UTC, Susko3 commented on osu.Framework/Graphics/UserInterface/TabControl.cs
> +                    tabVisibility[child] = value;
Just revert this change, it doesn't really make sense.

2024-11-27 19:37 UTC, Susko3 commented on osu.Framework/Input/Handlers/Midi/MidiHandler.cs
> +                eventType = value;
```diff
-if (!runningStatus.TryGetValue(senderId, out byte value))
+if (!runningStatus.TryGetValue(senderId, out eventType))
```

2024-11-27 20:04 UTC, huoyaoyuan commented
> I assume you've just run an automatic fixer?

Correct. I didn't even look through the code in detail since the fix is quite mature.

2024-11-27 20:10 UTC, huoyaoyuan commented on osu.Framework/Graphics/UserInterface/TabControl.cs
> +                    tabVisibility[child] = value;
The code fixer was too dumb to include this

2024-11-28 04:36 UTC, peppy approved these changes
No issues from my end 👍

2024-11-28 10:00 UTC, smoogipoo approved these changes
Seems ok

2024-11-28 10:22 UTC, merged