Clean up `IWindow` and remove platform-agnostic code probing `ISDLWindow`
ppy/osu-framework pull request #6438
Opened 2024-11-28 20:06 UTC by Susko3

`Focused`, `PointToClient()` and `PointToScreen()` in `IWindow` are made obsolete as they are not useful. See commits for more details.

Moves some members from `ISDLWindow` to `IWindow`. This makes it so platform-agnostic code no longer needs to cast to `ISDLWindow` (in `UserInputManager` and tests).

2024-11-28 22:23 UTC, frenzibyte requested changes

2024-11-28 22:23 UTC, frenzibyte commented on osu.Framework/Input/UserInputManager.cs
> -            }
I think it's best to do this change in a separate PR and keep this PR as a completely code-quality change. I wouldn't be comfortable to merge this without seeing it being tested on all platforms we have.

2024-11-28 23:53 UTC, frenzibyte approved these changes

2024-11-28 23:59 UTC, frenzibyte commented
If we're obsoleting `PointToScreen` then this usage should probably be inlined with the underlying implementation or something?
https://github.com/ppy/osu-framework/blob/b937b04418290c4bf3d3f079bf9d099d0fafb071/osu.Framework/Platform/Windows/SDL2WindowsWindow.cs#L133

Usually the CIs would've errored out if an obsolete member is being used somewhere, but it looks like applying the attribute to an interface member does not make that happen for some reason. The attribute should be copied to the class implementations as well in order to be effective.

2024-11-28 23:59 UTC, frenzibyte requested changes
^

2024-11-29 00:19 UTC, Susko3 commented
This inner usage is fine, I would like to remove it just from the interface (and the base `SDL{2,3}Window`). No need to copy the obsolete attribute to implementation as they're internal.

2024-11-29 00:25 UTC, frenzibyte commented
Sure, didn't notice the implementations were internal.

2024-11-29 00:25 UTC, frenzibyte approved these changes

2024-11-29 00:25 UTC, merged